package eu.kanade.tachiyomi.extension.vi.truyen18

import eu.kanade.tachiyomi.source.model.Filter
import eu.kanade.tachiyomi.source.model.FilterList

class GenreFilter :
    Filter.Select<String>(
        "Thể loại",
        GENRES.map { it.first }.toTypedArray(),
    ) {
    fun toUriPart(): String? = GENRES[state].second
}

fun getFilters(): FilterList = FilterList(
    Filter.Header("Lọc theo thể loại từ Danh sách thể loại"),
    GenreFilter(),
)

private val GENRES = arrayOf(
    Pair("Tất cả", null),
    Pair("19+", "19"),
    Pair("1X1", "1x1"),
    Pair("21+", "21"),
    Pair("3D Hentai", "3d-hentai"),
    Pair("3P", "3p"),
    Pair("Action", "action"),
    Pair("Adult", "adult"),
    Pair("Adventure", "adventure"),
    Pair("Ahegao", "ahegao"),
    Pair("Ám Ảnh", "am-anh"),
    Pair("Anal", "anal"),
    Pair("Anh Chàng Mưu Mô/ Ranh Mãnh", "anh-chang-muu-mo-ranh-manh"),
    Pair("Anh Chàng Nhỏ Tuổi", "anh-chang-nho-tuoi"),
    Pair("Animal Girl", "animal-girl"),
    Pair("Ảo Tưởng", "ao-tuong"),
    Pair("Art Book", "art-book"),
    Pair("Artist", "artist"),
    Pair("Artist Cg", "artist-cg"),
    Pair("Âu Cổ", "au-co"),
    Pair("Bách Hợp", "bach-hop"),
    Pair("Bạn Bè Thành Người Yêu", "ban-be-thanh-nguoi-yeu"),
    Pair("Bạn Thời Thơ Ấu", "ban-thoi-tho-au"),
    Pair("Bạn Tình", "ban-tinh"),
    Pair("Bạo Dâm", "bao-dam"),
    Pair("Based Game", "based-game"),
    Pair("Bbm", "bbm"),
    Pair("Bdsm", "bdsm"),
    Pair("Beach", "beach"),
    Pair("Beast", "beast"),
    Pair("Bí Ẩn", "bi-an"),
    Pair("Bi Kịch", "bi-kich"),
    Pair("Bị Thuốc", "bi-thuoc"),
    Pair("Big Ass", "big-ass"),
    Pair("Big Boobs", "big-boobs"),
    Pair("Big Breasts", "big-breasts"),
    Pair("Big Dick", "big-dick"),
    Pair("Big Penis", "big-penis"),
    Pair("Big Vagina", "big-vagina"),
    Pair("Black Skin", "black-skin"),
    Pair("Blackmail", "blackmail"),
    Pair("Bloomers", "bloomers"),
    Pair("Blow Job", "blow-job"),
    Pair("Blowjob", "blowjob"),
    Pair("Blowjobs", "blowjobs"),
    Pair("Body Modification", "body-modification"),
    Pair("Body Modifications", "body-modifications"),
    Pair("Body Swap", "body-swap"),
    Pair("Body Writting", "body-writting"),
    Pair("Bodysuit", "bodysuit"),
    Pair("Bondage", "bondage"),
    Pair("Boy Love", "boy-love"),
    Pair("Bối Cảnh Phương Tây", "boi-canh-phuong-tay"),
    Pair("Breast Sucking", "breast-sucking"),
    Pair("Breastjobs", "breastjobs"),
    Pair("Brocon", "brocon"),
    Pair("Brother", "brother"),
    Pair("Bukkake", "bukkake"),
    Pair("Business Suit", "business-suit"),
    Pair("Cáo Già X Thỏ Con", "cao-gia-x-tho-con"),
    Pair("Catgirls", "catgirls"),
    Pair("Cặc Bự", "cac-bu"),
    Pair("Cặp Đôi Chênh Lệch Tuổi Tác", "cap-doi-chenh-lech-tuoi-tac"),
    Pair("Cặp Đôi Thanh Mai Trúc Mã", "cap-doi-thanh-mai-truc-ma"),
    Pair("Cg", "cg"),
    Pair("Chàng Trai Cáu Kỉnh", "chang-trai-cau-kinh"),
    Pair("Chàng Trai Mưu Mô", "chang-trai-muu-mo"),
    Pair("Chàng Trai Yêu Đơn Phương", "chang-trai-yeu-don-phuong"),
    Pair("Che Ít", "che-it"),
    Pair("Che Nhiều", "che-nhieu"),
    Pair("Cheating", "cheating"),
    Pair("Chênh Lệch Thân Phận", "chenh-lech-than-phan"),
    Pair("Chị / Em", "chi-em"),
    Pair("Chị Gái Hơn Tuổi X Em Trai Kém Tuổi", "chi-gai-hon-tuoi-x-em-trai-kem-tuoi"),
    Pair("Chiếm Hữu", "chiem-huu"),
    Pair("Chikan", "chikan"),
    Pair("Chinese Dress", "chinese-dress"),
    Pair("Chơi Hai Lỗ", "choi-hai-lo"),
    Pair("Chữa Lành", "chua-lanh"),
    Pair("Color", "color"),
    Pair("Comedy", "comedy"),
    Pair("Comic", "comic"),
    Pair("Comic 18+", "comic-18"),
    Pair("Comics24H", "comics24h"),
    Pair("Con Gái", "con-gai"),
    Pair("Condom", "condom"),
    Pair("Cosplay", "cosplay"),
    Pair("Cousin", "cousin"),
    Pair("Cô / Dì", "co-di"),
    Pair("Cổ Đại", "co-dai"),
    Pair("Cô Gái Ngây Thơ", "co-gai-ngay-tho"),
    Pair("Cô Gái Từng Bị Tổn Thương", "co-gai-tung-bi-ton-thuong"),
    Pair("Cô Gái Yêu Đơn Phương", "co-gai-yeu-don-phuong"),
    Pair("Cô Nàng Thẳng Thắn", "co-nang-thang-than"),
    Pair("Cô Nàng Từng Bị Tổn Thương", "co-nang-tung-bi-ton-thuong"),
    Pair("Cổ Trang", "co-trang"),
    Pair("Côn Trùng", "con-trung"),
    Pair("Công Sở", "cong-so"),
    Pair("Cốt Truyện", "cot-truyen"),
    Pair("Creampie", "creampie"),
    Pair("Cunnilingus", "cunnilingus"),
    Pair("Cứu Rỗi", "cuu-roi"),
    Pair("Cứu Rỗi Lẫn Nhau", "cuu-roi-lan-nhau"),
    Pair("Dark Skin", "dark-skin"),
    Pair("Deepthroat", "deepthroat"),
    Pair("Defloration", "defloration"),
    Pair("Demon", "demon"),
    Pair("Demon Girl", "demon-girl"),
    Pair("Demongirl", "demongirl"),
    Pair("Devil", "devil"),
    Pair("Devilgirl", "devilgirl"),
    Pair("Dickgirl", "dickgirl"),
    Pair("Dirty", "dirty"),
    Pair("Dirty Old Man", "dirty-old-man"),
    Pair("Dirty Talk", "dirty-talk"),
    Pair("Doctruyen3Q", "doctruyen3q"),
    Pair("Double Penetration", "double-penetration"),
    Pair("Drama", "drama"),
    Pair("Drug", "drug"),
    Pair("Dưa Leo Truyện", "dua-leo-truyen"),
    Pair("Đã Full", "da-full"),
    Pair("Đam Mỹ", "dam-my"),
    Pair("Đeo Kính", "deo-kinh"),
    Pair("Đồ Bơi", "do-boi"),
    Pair("Đồ Chơi Tình Dục", "do-choi-tinh-duc"),
    Pair("Đô Thị", "do-thi"),
    Pair("Ecchi", "ecchi"),
    Pair("Elder Sister", "elder-sister"),
    Pair("Elf", "elf"),
    Pair("Exhibitionism", "exhibitionism"),
    Pair("Family", "family"),
    Pair("Fantasy", "fantasy"),
    Pair("Father", "father"),
    Pair("Femdom", "femdom"),
    Pair("Fendom", "fendom"),
    Pair("Fingering", "fingering"),
    Pair("First Time", "first-time"),
    Pair("Footjob", "footjob"),
    Pair("Foursome", "foursome"),
    Pair("Full Color", "full-color"),
    Pair("Funny", "funny"),
    Pair("Furry", "furry"),
    Pair("Futanari", "futanari"),
    Pair("Game", "game"),
    Pair("Gangbang", "gangbang"),
    Pair("Garter Belts", "garter-belts"),
    Pair("Gender Bender", "gender-bender"),
    Pair("Ghen Tuông", "ghen-tuong"),
    Pair("Gia Đình", "gia-dinh"),
    Pair("Giả Tưởng", "gia-tuong"),
    Pair("Giáo Viên", "giao-vien"),
    Pair("Giật Gân", "giat-gan"),
    Pair("Giới Giải Trí", "gioi-giai-tri"),
    Pair("Girl Love", "girl-love"),
    Pair("Girllove", "girllove"),
    Pair("Glasses", "glasses"),
    Pair("Góa Phụ", "goa-phu"),
    Pair("Gothic Lolita", "gothic-lolita"),
    Pair("Group", "group"),
    Pair("Guideverse", "guideverse"),
    Pair("Guro", "guro"),
    Pair("Gyaru", "gyaru"),
    Pair("Hài Lãng Mạn", "hai-lang-man"),
    Pair("Hairy", "hairy"),
    Pair("Hãm Hiếp", "ham-hiep"),
    Pair("Handjob", "handjob"),
    Pair("Hàng Xóm", "hang-xom"),
    Pair("Hardcode", "hardcode"),
    Pair("Harem", "harem"),
    Pair("Harem Ngược", "harem-nguoc"),
    Pair("Hấp Diêm", "hap-diem"),
    Pair("Hầu Gái", "hau-gai"),
    Pair("Hậu Môn", "hau-mon"),
    Pair("Hentai 3D", "hentai-3d"),
    Pair("Hentai Cube", "hentai-cube"),
    Pair("Hentai Không Che", "hentai-khong-che"),
    Pair("Hentai Lxmanga", "hentai-lxmanga"),
    Pair("Hentai Màu", "hentai-mau"),
    Pair("Hentai18Vn", "hentai18vn"),
    Pair("Hentaiayame", "hentaiayame"),
    Pair("Hentaicb", "hentaicb"),
    Pair("Hentaicube", "hentaicube"),
    Pair("Hentaihvn", "hentaihvn"),
    Pair("Hentaivl", "hentaivl"),
    Pair("Hentaivnx", "hentaivnx"),
    Pair("Hentaiz", "hentaiz"),
    Pair("Hệ Thống", "he-thong"),
    Pair("Hiện Đại", "hien-dai"),
    Pair("Hiện Thực", "hien-thuc"),
    Pair("Hiếp Dâm", "hiep-dam"),
    Pair("Hiểu Lầm", "hieu-lam"),
    Pair("Historical", "historical"),
    Pair("Họ Hàng", "ho-hang"),
    Pair("Hoàng Gia", "hoang-gia"),
    Pair("Horror", "horror"),
    Pair("Housewife", "housewife"),
    Pair("Hôn Nhân Hợp Đồng", "hon-nhan-hop-dong"),
    Pair("Hồng Hài Nhi", "hong-hai-nhi"),
    Pair("Huge Ass", "huge-ass"),
    Pair("Huge Boobs", "huge-boobs"),
    Pair("Humiliation", "humiliation"),
    Pair("Huyền Bí", "huyen-bi"),
    Pair("Idol", "idol"),
    Pair("Ihentai", "ihentai"),
    Pair("Imouto", "imouto"),
    Pair("Incest", "incest"),
    Pair("Incomplete", "incomplete"),
    Pair("Insect", "insect"),
    Pair("Inseki", "inseki"),
    Pair("Josei", "josei"),
    Pair("Joseon", "joseon"),
    Pair("Khoa Học Viễn Tưởng", "khoa-hoc-vien-tuong"),
    Pair("Khoảng Cách Tuổi Tác", "khoang-cach-tuoi-tac"),
    Pair("Khổ Dâm", "kho-dam"),
    Pair("Không Ntr", "khong-ntr"),
    Pair("Kissing", "kissing"),
    Pair("Kogal", "kogal"),
    Pair("Kuudere", "kuudere"),
    Pair("Lãng Mạng", "lang-mang"),
    Pair("Lão Gìa Dâm", "lao-gia-dam"),
    Pair("Lếu Lều", "leu-leu"),
    Pair("Lingerie", "lingerie"),
    Pair("Loạn Luân", "loan-luan"),
    Pair("Loạn Luân Chị Em", "loan-luan-chi-em"),
    Pair("Loli", "loli"),
    Pair("Lolicon", "lolicon"),
    Pair("Lỗ Nhị", "lo-nhi"),
    Pair("Lxnovel", "lxnovel"),
    Pair("Ma Cà Rồng", "ma-ca-rong"),
    Pair("Ma Giới", "ma-gioi"),
    Pair("Magic", "magic"),
    Pair("Maid", "maid"),
    Pair("Maids", "maids"),
    Pair("Mang Thai", "mang-thai"),
    Pair("Manh", "manh"),
    Pair("Masturbation", "masturbation"),
    Pair("Mature", "mature"),
    Pair("Mắt Kính", "mat-kinh"),
    Pair("Mất Trí Nhớ", "mat-tri-nho"),
    Pair("Mẹ Con", "me-con"),
    Pair("Meothamthuy", "meothamthuy"),
    Pair("Mi2Manga", "mi2manga"),
    Pair("Miko", "miko"),
    Pair("Milf", "milf"),
    Pair("Milfs", "milfs"),
    Pair("Mimihentai", "mimihentai"),
    Pair("Mind Break", "mind-break"),
    Pair("Mind Control", "mind-control"),
    Pair("Mizugi", "mizugi"),
    Pair("Monster", "monster"),
    Pair("Monster Girl", "monster-girl"),
    Pair("Monstergirl", "monstergirl"),
    Pair("Mother", "mother"),
    Pair("Mối Quan Hệ Bí Mật", "moi-quan-he-bi-mat"),
    Pair("Mối Quan Hệ Hợp Đồng", "moi-quan-he-hop-dong"),
    Pair("Mối Quan Hệ Tình Cảm Phức Tạp", "moi-quan-he-tinh-cam-phuc-tap"),
    Pair("Mối Tình Đầu", "moi-tinh-dau"),
    Pair("Mối Tình Tay Ba", "moi-tinh-tay-ba"),
    Pair("Mông To", "mong-to"),
    Pair("Mystery", "mystery"),
    Pair("Nakadashi", "nakadashi"),
    Pair("Nam Hối Hận", "nam-hoi-han"),
    Pair("Nam Sinh", "nam-sinh"),
    Pair("Nặng Đô", "nang-do"),
    Pair("Năng Lực Siêu Nhiên", "nang-luc-sieu-nhien"),
    Pair("Net Truyen Hentai", "net-truyen-hentai"),
    Pair("Netori", "netori"),
    Pair("Ngoài Trời", "ngoai-troi"),
    Pair("Ngoài Trời/Công Cộng", "ngoai-troi-cong-cong"),
    Pair("Ngọt", "ngot"),
    Pair("Ngôn Tình", "ngon-tinh"),
    Pair("Ngực Lớn", "nguc-lon"),
    Pair("Ngực Nhỏ", "nguc-nho"),
    Pair("Ngược", "nguoc"),
    Pair("Người Đàn Ông Ám Ảnh", "nguoi-dan-ong-am-anh"),
    Pair("Người Đàn Ông Nhỏ Tuổi", "nguoi-dan-ong-nho-tuoi"),
    Pair("Người Nổi Tiếng", "nguoi-noi-tieng"),
    Pair("Người Phụ Nữ Lớn Tuổi", "nguoi-phu-nu-lon-tuoi"),
    Pair("Nhóm", "nhom"),
    Pair("No Sex", "no-sex"),
    Pair("Nô Lệ", "no-le"),
    Pair("Ntr", "ntr"),
    Pair("Nun", "nun"),
    Pair("Nurse", "nurse"),
    Pair("Nữ Cường", "nu-cuong"),
    Pair("Nữ Đơn Phương", "nu-don-phuong"),
    Pair("Nữ Giả Nam", "nu-gia-nam"),
    Pair("Nữ Sinh", "nu-sinh"),
    Pair("Oan Gia", "oan-gia"),
    Pair("Office Lady", "office-lady"),
    Pair("Old Man", "old-man"),
    Pair("Oral", "oral"),
    Pair("Orgasm Denial", "orgasm-denial"),
    Pair("Osananajimi", "osananajimi"),
    Pair("Paizuri", "paizuri"),
    Pair("Pantyhose", "pantyhose"),
    Pair("Phản Bội", "phan-boi"),
    Pair("Phong Cách Phương Đông", "phong-cach-phuong-dong"),
    Pair("Ponytail", "ponytail"),
    Pair("Pregnant", "pregnant"),
    Pair("Psychological", "psychological"),
    Pair("Quái Vật", "quai-vat"),
    Pair("Quản Giáo", "quan-giao"),
    Pair("Quan Hệ Hôn Nhân Hợp Đồng", "quan-he-hon-nhan-hop-dong"),
    Pair("Ranh Mãnh", "ranh-manh"),
    Pair("Rape", "rape"),
    Pair("Raw", "raw"),
    Pair("Rimjob", "rimjob"),
    Pair("Robot", "robot"),
    Pair("Romanc", "romanc"),
    Pair("Romance", "romance"),
    Pair("Romcom", "romcom"),
    Pair("Rphang", "rphang"),
    Pair("Ryona", "ryona"),
    Pair("Say Xỉn", "say-xin"),
    Pair("Scat", "scat"),
    Pair("School Life", "school-life"),
    Pair("School Uniform", "school-uniform"),
    Pair("Schoolboy Outfit", "schoolboy-outfit"),
    Pair("Schoolgirl", "schoolgirl"),
    Pair("Schoolgirl Outfit", "schoolgirl-outfit"),
    Pair("Schoolgirl Uniform", "schoolgirl-uniform"),
    Pair("Seinen", "seinen"),
    Pair("Sex Bạo", "sex-bao"),
    Pair("Sex Toys", "sex-toys"),
    Pair("Sếch Tàn Bạo", "sech-tan-bao"),
    Pair("Short", "short"),
    Pair("Short Hentai", "short-hentai"),
    Pair("Shota", "shota"),
    Pair("Shotacon", "shotacon"),
    Pair("Siêu Nhiên", "sieu-nhien"),
    Pair("Siscon", "siscon"),
    Pair("Sister", "sister"),
    Pair("Sixty-Nine", "sixty-nine"),
    Pair("Slave", "slave"),
    Pair("Sleeping", "sleeping"),
    Pair("Slice of Life", "slice-of-life"),
    Pair("Small Boobs", "small-boobs"),
    Pair("Small Breasts", "small-breasts"),
    Pair("Small Penis", "small-penis"),
    Pair("Smut", "smut"),
    Pair("Socks", "socks"),
    Pair("Sole Female", "sole-female"),
    Pair("Sole Male", "sole-male"),
    Pair("Sport", "sport"),
    Pair("Sports", "sports"),
    Pair("Squirting", "squirting"),
    Pair("Stocking", "stocking"),
    Pair("Stockings", "stockings"),
    Pair("Story Arc", "story-arc"),
    Pair("Succubus", "succubus"),
    Pair("Supernatural", "supernatural"),
    Pair("Sự Nhỉ Nhục", "su-nhi-nhuc"),
    Pair("Sweating", "sweating"),
    Pair("Swimsuit", "swimsuit"),
    Pair("Swinging", "swinging"),
    Pair("T", "t"),
    Pair("Tài Phiệt", "tai-phiet"),
    Pair("Tall Girl", "tall-girl"),
    Pair("Tam Giác Tình Yêu", "tam-giac-tinh-yeu"),
    Pair("Teacher", "teacher"),
    Pair("Tentacle", "tentacle"),
    Pair("Tentacles", "tentacles"),
    Pair("Thanh Xuân Vườn Trường", "thanh-xuan-vuon-truong"),
    Pair("Thế Giới Abo", "the-gioi-abo"),
    Pair("Three Some", "three-some"),
    Pair("Thủ Dâm", "thu-dam"),
    Pair("Thú Nhân", "thu-nhan"),
    Pair("Thú Vật", "thu-vat"),
    Pair("Tì", "ti"),
    Pair("Time Stop", "time-stop"),
    Pair("Tình C", "tinh-c"),
    Pair("Tình Cảm", "tinh-cam"),
    Pair("Tình Tay Ba", "tinh-tay-ba"),
    Pair("Tình Yêu Bị Cấm Đoán", "tinh-yeu-bi-cam-doan"),
    Pair("Tình Yêu Công Sở", "tinh-yeu-cong-so"),
    Pair("Tình Yêu Hợp Đồng", "tinh-yeu-hop-dong"),
    Pair("Tomboy", "tomboy"),
    Pair("Toys", "toys"),
    Pair("Tổng Tài", "tong-tai"),
    Pair("Tr", "tr"),
    Pair("Trả Thù", "tra-thu"),
    Pair("Tracksuit", "tracksuit"),
    Pair("Transformation", "transformation"),
    Pair("Trap", "trap"),
    Pair("Trâu Già", "trau-gia"),
    Pair("Trinh Thám", "trinh-tham"),
    Pair("Truy", "truy"),
    Pair("Truy Thê", "truy-the"),
    Pair("Truyengihot", "truyengihot"),
    Pair("Truyenmm", "truyenmm"),
    Pair("Truyenvn", "truyenvn"),
    Pair("Truyện", "truyen"),
    Pair("Truyện Dà", "truyen-da"),
    Pair("Truyện Hentai", "truyen-hentai"),
    Pair("Truyện M", "truyen-m"),
    Pair("Truyện Ngọt", "truyen-ngot"),
    Pair("Truyện T", "truyen-t"),
    Pair("Truyện Tranh 1", "truyen-tranh-1"),
    Pair("Truyện Việt", "truyen-viet"),
    Pair("Trường Học", "truong-hoc"),
    Pair("Tsundere", "tsundere"),
    Pair("Tù Nhân", "tu-nhan"),
    Pair("Từ Bạn Thành Yêu", "tu-ban-thanh-yeu"),
    Pair("Tự Sướng", "tu-suong"),
    Pair("Twins", "twins"),
    Pair("Twintails", "twintails"),
    Pair("Ugly Bastard", "ugly-bastard"),
    Pair("Umehentai", "umehentai"),
    Pair("Umetruyen", "umetruyen"),
    Pair("Ungtytruyen", "ungtytruyen"),
    Pair("V", "v"),
    Pair("Vanilla", "vanilla"),
    Pair("Văn Phòng", "van-phong"),
    Pair("Vét Máng", "vet-mang"),
    Pair("Vếu To", "veu-to"),
    Pair("Virgin", "virgin"),
    Pair("Virginity", "virginity"),
    Pair("Virgins", "virgins"),
    Pair("Vợ Của Sư Phụ", "vo-cua-su-phu"),
    Pair("X-Ray", "x-ray"),
    Pair("Xã Hội Đen", "xa-hoi-den"),
    Pair("Xúc Tua", "xuc-tua"),
    Pair("Xuyên Không", "xuyen-khong"),
    Pair("Y Tá", "y-ta"),
    Pair("Yandere", "yandere"),
    Pair("Yaoi", "yaoi"),
    Pair("Yêu Hận Đan Xen", "yeu-han-dan-xen"),
    Pair("Yuri", "yuri"),
)
