package eu.kanade.tachiyomi.extension.vi.mimi

import eu.kanade.tachiyomi.source.model.Filter
import eu.kanade.tachiyomi.source.model.FilterList

fun getFilters(): FilterList = FilterList(
    Filter.Header("Lưu ý: Bộ lọc thể loại chỉ hoạt động khi ô tìm kiếm trống"),
    GenreFilter(),
)

class GenreFilter :
    Filter.Select<String>(
        "Thể loại",
        genres.map { it.first }.toTypedArray(),
    ) {
    fun toUriPart(): String = genres[state].second
}

private val genres = listOf(
    Pair("Tất cả", ""),
    Pair("3D", "416"),
    Pair("Action", "417"),
    Pair("Adult", "406"),
    Pair("Adventure", "457"),
    Pair("Ahegao", "267"),
    Pair("Alien", "343"),
    Pair("Anal", "183"),
    Pair("Angel", "452"),
    Pair("Aphrodisiac", "239"),
    Pair("Apron", "502"),
    Pair("Armpit", "212"),
    Pair("Artist CG", "221"),
    Pair("ArtistCG có thoại", "556"),
    Pair("Assjob", "338"),
    Pair("Aunt", "259"),
    Pair("BBM", "389"),
    Pair("BBW", "311"),
    Pair("BDSM", "182"),
    Pair("Bald", "303"),
    Pair("Band-Aid", "377"),
    Pair("Bestiality", "352"),
    Pair("Big boobs", "261"),
    Pair("Bike shorts", "337"),
    Pair("Bikini", "277"),
    Pair("Bisexual", "315"),
    Pair("Black mail", "265"),
    Pair("Black skin", "187"),
    Pair("Blindfold", "173"),
    Pair("Bloomer", "231"),
    Pair("Blowjob", "314"),
    Pair("Body Writing", "288"),
    Pair("Bodysuit", "339"),
    Pair("Bodyswap", "208"),
    Pair("Bondage", "179"),
    Pair("Breast Sucking", "414"),
    Pair("Breast feeding", "345"),
    Pair("Brother", "275"),
    Pair("Bukkake", "178"),
    Pair("Bunny Girl", "195"),
    Pair("Catgirl", "210"),
    Pair("Chastity belt", "340"),
    Pair("Cheating", "186"),
    Pair("Cheerleader", "168"),
    Pair("Chikan", "176"),
    Pair("Chubby", "193"),
    Pair("Clone", "335"),
    Pair("Clothed M nude F", "324"),
    Pair("Collar", "313"),
    Pair("Color", "245"),
    Pair("Comedy", "411"),
    Pair("Comic", "553"),
    Pair("Condom", "302"),
    Pair("Cosplay", "177"),
    Pair("Cousin", "357"),
    Pair("Crossdressing", "325"),
    Pair("Crotch tattoo", "317"),
    Pair("Cum swap", "334"),
    Pair("Cunnilingus", "220"),
    Pair("Có che", "233"),
    Pair("DILF", "167"),
    Pair("Daughter", "270"),
    Pair("Deepthroat", "174"),
    Pair("Demon", "175"),
    Pair("Dickgirl on dickgirl", "349"),
    Pair("Dickgirl on female", "308"),
    Pair("Dickgirl on male", "381"),
    Pair("Dirty", "418"),
    Pair("Dirty Old Man", "226"),
    Pair("Doggirl", "207"),
    Pair("Double Penetration", "229"),
    Pair("Double blowjob", "304"),
    Pair("Doujinshi", "244"),
    Pair("Drama", "219"),
    Pair("Drug", "293"),
    Pair("Drunk", "344"),
    Pair("Ecchi", "234"),
    Pair("Elf", "181"),
    Pair("Emotionless", "323"),
    Pair("Exhibitionist", "188"),
    Pair("Eye-covering bang", "382"),
    Pair("Eyepatch", "305"),
    Pair("FFF Threesome", "320"),
    Pair("FFM Threesome", "329"),
    Pair("FFT Threesome", "363"),
    Pair("Face Mask", "225"),
    Pair("Facesitting", "307"),
    Pair("Family", "264"),
    Pair("Fang", "222"),
    Pair("Fantasy", "408"),
    Pair("Father", "316"),
    Pair("Females only", "355"),
    Pair("Femdom", "156"),
    Pair("Feminization", "326"),
    Pair("Filming", "289"),
    Pair("Fingering", "169"),
    Pair("Fisting", "159"),
    Pair("Foot licking", "332"),
    Pair("Footjob", "189"),
    Pair("Foxgirl", "217"),
    Pair("Furry", "552"),
    Pair("Futanari", "184"),
    Pair("Gag", "368"),
    Pair("Gangbang", "155"),
    Pair("Gaping", "372"),
    Pair("Garter belt", "356"),
    Pair("GenderBender", "284"),
    Pair("Ghost", "246"),
    Pair("Glasses", "185"),
    Pair("Glory hole", "361"),
    Pair("Godness", "254"),
    Pair("Gothic lolita", "330"),
    Pair("Group", "410"),
    Pair("Guro", "397"),
    Pair("Gyaru", "160"),
    Pair("Gymshorts", "353"),
    Pair("Hairjob", "394"),
    Pair("Hairy", "236"),
    Pair("Handicapped", "306"),
    Pair("Handjob", "203"),
    Pair("Harem", "191"),
    Pair("Heart Pupils", "251"),
    Pair("HentaiVN", "403"),
    Pair("Hidden sex", "386"),
    Pair("Historical", "453"),
    Pair("Horns", "224"),
    Pair("Horror", "253"),
    Pair("Housewife", "232"),
    Pair("Huge Ass", "157"),
    Pair("Huge Boobs", "190"),
    Pair("Huge Dick", "281"),
    Pair("Humiliation", "347"),
    Pair("Idol", "237"),
    Pair("Imouto", "283"),
    Pair("Impregnation", "328"),
    Pair("Incest", "154"),
    Pair("Insect", "348"),
    Pair("Kissing", "299"),
    Pair("Lactation", "342"),
    Pair("Latex", "370"),
    Pair("Leotard", "297"),
    Pair("Lingerie", "268"),
    Pair("Loli", "164"),
    Pair("Maid", "163"),
    Pair("Male on dickgirl", "380"),
    Pair("Males only", "354"),
    Pair("Maledom", "280"),
    Pair("Masturbation", "171"),
    Pair("Miko", "228"),
    Pair("Milf", "162"),
    Pair("Mind Break", "161"),
    Pair("Mind Control", "192"),
    Pair("Monster", "263"),
    Pair("Monster Girl", "170"),
    Pair("Mother", "269"),
    Pair("Multi-work series", "153"),
    Pair("Muscle", "274"),
    Pair("Nakadashi", "216"),
    Pair("Netorare", "158"),
    Pair("Nipple fuck", "391"),
    Pair("Nun", "298"),
    Pair("Nurse", "166"),
    Pair("Office Lady", "180"),
    Pair("Oppai loli", "213"),
    Pair("Oral", "286"),
    Pair("Outdoor Sex", "276"),
    Pair("Paizuri", "172"),
    Pair("Pantyhose", "240"),
    Pair("Piercing", "346"),
    Pair("Ponytail", "230"),
    Pair("Pregnant", "211"),
    Pair("Prostitution", "290"),
    Pair("Pubic stubble", "373"),
    Pair("Rape", "165"),
    Pair("Rimjob", "374"),
    Pair("Robot", "384"),
    Pair("Ryona", "398"),
    Pair("Scat", "400"),
    Pair("School", "235"),
    Pair("Schoolboy", "502"),
    Pair("Schoolgirl", "194"),
    Pair("Selfcest", "336"),
    Pair("Series", "153"),
    Pair("Sex Toys", "196"),
    Pair("Shota", "266"),
    Pair("Sister", "272"),
    Pair("Sleeping", "294"),
    Pair("Slime", "351"),
    Pair("Small boobs", "256"),
    Pair("Spanking", "375"),
    Pair("Squirting", "241"),
    Pair("Stockings", "197"),
    Pair("Story arc", "223"),
    Pair("Stuck in wall", "333"),
    Pair("Succubus", "242"),
    Pair("Sundress", "350"),
    Pair("Sweating", "309"),
    Pair("Swimsuit", "198"),
    Pair("Tanlines", "301"),
    Pair("Teacher", "199"),
    Pair("Tentacles", "200"),
    Pair("Thigh high boots", "358"),
    Pair("Threesome", "252"),
    Pair("Time Stop", "287"),
    Pair("Tomboy", "227"),
    Pair("Torture", "396"),
    Pair("Transformation", "285"),
    Pair("Trap", "209"),
    Pair("Tribadism", "331"),
    Pair("Tsundere", "312"),
    Pair("Twintails", "214"),
    Pair("Uncensored", "201"),
    Pair("Urethra insertion", "390"),
    Pair("Vampire", "249"),
    Pair("Vanilla", "202"),
    Pair("Virginity", "215"),
    Pair("Voyeurism", "291"),
    Pair("Widow", "271"),
    Pair("Wings", "250"),
    Pair("Witch", "247"),
    Pair("X-Ray", "243"),
    Pair("Yandere", "255"),
    Pair("Yaoi", "204"),
    Pair("Yuri", "205"),
    Pair("Zombie", "248"),
)
