package eu.kanade.tachiyomi.extension.id.narasininja

import eu.kanade.tachiyomi.source.model.Filter

class StatusFilter :
    Filter.Select<String>(
        "Status",
        arrayOf("All", "Ongoing", "Completed", "Hiatus"),
    ) {
    private val options = arrayOf("", "ongoing", "completed", "hiatus")
    fun selectedValue() = options[state]
}

class TypeFilter :
    Filter.Select<String>(
        "Type",
        arrayOf("All", "Manga", "Manhwa", "Manhua", "Comic", "Novel"),
    ) {
    private val options = arrayOf("", "manga", "manhwa", "manhua", "comic", "novel")
    fun selectedValue() = options[state]
}

class OrderFilter :
    Filter.Select<String>(
        "Order",
        arrayOf("Default", "A-Z", "Z-A", "Update", "Added"),
    ) {
    private val options = arrayOf("", "title", "titlereverse", "update", "added")
    fun selectedValue() = options[state]
}

class GenreCheckBox(name: String, val value: String) : Filter.CheckBox(name)

class GenreFilter :
    Filter.Group<GenreCheckBox>(
        "Genre",
        listOf(
            GenreCheckBox("4-Koma", "123"),
            GenreCheckBox("Action", "6"),
            GenreCheckBox("Adaptation", "48"),
            GenreCheckBox("Adult", "43"),
            GenreCheckBox("Adventure", "3"),
            GenreCheckBox("Animals", "84"),
            GenreCheckBox("Anthology", "144"),
            GenreCheckBox("Antihero", "90"),
            GenreCheckBox("Apocalypse", "56"),
            GenreCheckBox("Award Winning", "129"),
            GenreCheckBox("Beasts", "68"),
            GenreCheckBox("Bodyswap", "103"),
            GenreCheckBox("Boys' Love", "124"),
            GenreCheckBox("Bully", "135"),
            GenreCheckBox("Cartoon", "104"),
            GenreCheckBox("Childhood Friends", "35"),
            GenreCheckBox("Comedy", "12"),
            GenreCheckBox("Comic", "53"),
            GenreCheckBox("Cooking", "38"),
            GenreCheckBox("Crime", "31"),
            GenreCheckBox("Crossdressing", "125"),
            GenreCheckBox("Dance", "121"),
            GenreCheckBox("Dark Fantasy", "60"),
            GenreCheckBox("Delinquent", "136"),
            GenreCheckBox("Delinquents", "74"),
            GenreCheckBox("Dementia", "105"),
            GenreCheckBox("Demon", "65"),
            GenreCheckBox("Demons", "52"),
            GenreCheckBox("Doujinshi", "70"),
            GenreCheckBox("Drama", "1"),
            GenreCheckBox("Dungeons", "106"),
            GenreCheckBox("Ecchi", "15"),
            GenreCheckBox("Emperor's Daughter", "95"),
            GenreCheckBox("Entertainment", "83"),
            GenreCheckBox("Fan-Colored", "96"),
            GenreCheckBox("Fantasy", "4"),
            GenreCheckBox("Fetish", "107"),
            GenreCheckBox("Full Color", "49"),
            GenreCheckBox("Game", "47"),
            GenreCheckBox("Games", "150"),
            GenreCheckBox("Gang", "87"),
            GenreCheckBox("Gender Bender", "25"),
            GenreCheckBox("Genderswap", "40"),
            GenreCheckBox("Ghosts", "99"),
            GenreCheckBox("Girls", "97"),
            GenreCheckBox("Girls' Love", "122"),
            GenreCheckBox("Gore", "36"),
            GenreCheckBox("Gyaru", "77"),
            GenreCheckBox("Harem", "7"),
            GenreCheckBox("Hero", "75"),
            GenreCheckBox("Historical", "13"),
            GenreCheckBox("Horror", "17"),
            GenreCheckBox("Imageset", "108"),
            GenreCheckBox("Incest", "93"),
            GenreCheckBox("Isekai", "8"),
            GenreCheckBox("Josei", "39"),
            GenreCheckBox("Kids", "101"),
            GenreCheckBox("Leveling", "151"),
            GenreCheckBox("Loli", "131"),
            GenreCheckBox("Long Strip", "50"),
            GenreCheckBox("Mafia", "130"),
            GenreCheckBox("Magic", "30"),
            GenreCheckBox("Magical Girls", "41"),
            GenreCheckBox("Martial Art", "59"),
            GenreCheckBox("Martial Arts", "14"),
            GenreCheckBox("Mature", "9"),
            GenreCheckBox("Mecha", "37"),
            GenreCheckBox("Medical", "32"),
            GenreCheckBox("Military", "73"),
            GenreCheckBox("Monster Girls", "138"),
            GenreCheckBox("Monsters", "63"),
            GenreCheckBox("Murim", "29"),
            GenreCheckBox("Music", "92"),
            GenreCheckBox("Mystery", "22"),
            GenreCheckBox("Necromancer", "147"),
            GenreCheckBox("Ninja", "109"),
            GenreCheckBox("Non-human", "110"),
            GenreCheckBox("Office Workers", "23"),
            GenreCheckBox("Official Colored", "142"),
            GenreCheckBox("One-Shot", "61"),
            GenreCheckBox("Oneshot", "126"),
            GenreCheckBox("Overpowered", "148"),
            GenreCheckBox("Parody", "111"),
            GenreCheckBox("Pets", "149"),
            GenreCheckBox("Philosophical", "133"),
            GenreCheckBox("Police", "24"),
            GenreCheckBox("Post-Apocalyptic", "112"),
            GenreCheckBox("Psychological", "27"),
            GenreCheckBox("Regression", "34"),
            GenreCheckBox("Reincarnation", "33"),
            GenreCheckBox("Revenge", "82"),
            GenreCheckBox("Reverse Harem", "128"),
            GenreCheckBox("Reverse Isekai", "113"),
            GenreCheckBox("Romance", "10"),
            GenreCheckBox("Royal Family", "100"),
            GenreCheckBox("Royalty", "114"),
            GenreCheckBox("School", "81"),
            GenreCheckBox("School Life", "2"),
            GenreCheckBox("Sci-fi", "26"),
            GenreCheckBox("Seinen", "5"),
            GenreCheckBox("Shoujo", "21"),
            GenreCheckBox("Shoujo Ai", "45"),
            GenreCheckBox("Shounen", "11"),
            GenreCheckBox("Shounen Ai", "64"),
            GenreCheckBox("Showbiz", "115"),
            GenreCheckBox("Slice of Life", "16"),
            GenreCheckBox("Smut", "71"),
            GenreCheckBox("Space", "116"),
            GenreCheckBox("Sport", "54"),
            GenreCheckBox("Sports", "19"),
            GenreCheckBox("Super Power", "18"),
            GenreCheckBox("Superhero", "58"),
            GenreCheckBox("Supernatural", "20"),
            GenreCheckBox("Survival", "42"),
            GenreCheckBox("System", "57"),
            GenreCheckBox("Thriller", "62"),
            GenreCheckBox("Time Travel", "98"),
            GenreCheckBox("Traditional Games", "117"),
            GenreCheckBox("Tragedy", "28"),
            GenreCheckBox("Transmigration", "102"),
            GenreCheckBox("Vampire", "67"),
            GenreCheckBox("Vampires", "118"),
            GenreCheckBox("Video Games", "119"),
            GenreCheckBox("Villainess", "79"),
            GenreCheckBox("Violence", "143"),
            GenreCheckBox("Virtual Reality", "120"),
            GenreCheckBox("Web Comic", "51"),
            GenreCheckBox("Webtoon", "86"),
            GenreCheckBox("Webtoons", "94"),
            GenreCheckBox("Wuxia", "55"),
            GenreCheckBox("Xianxia", "89"),
            GenreCheckBox("Xuanhuan", "80"),
            GenreCheckBox("Yaoi", "141"),
            GenreCheckBox("Yuri", "46"),
            GenreCheckBox("Zombies", "140"),
        ),
    )
