package eu.kanade.tachiyomi.extension.ja.nicomanga

import eu.kanade.tachiyomi.source.model.Filter

class SortFilter :
    Filter.Sort(
        "Sort",
        arrayOf("Last Update", "Views", "Post Date", "Name"),
        Selection(0, false),
    )

class MatchingLogic : Filter.Select<String>("Matching Logic", arrayOf("OR", "AND"), 1)

class Genre(name: String, val id: String) : Filter.CheckBox(name)
class GenreList(genres: List<Genre>) : Filter.Group<Genre>("Genres", genres)

fun getGenreList() = listOf(
    Genre("Absurd", "absurd"),
    Genre("Action", "action"),
    Genre("Action (Misunderstanding)", "action-misunderstanding"),
    Genre("Adult", "adult"),
    Genre("Adult Cast", "adult-cast"),
    Genre("Adult Protagonist", "adult-protagonist"),
    Genre("Adult Protagonists", "adult-protagonists"),
    Genre("Adventure", "adventure"),
    Genre("Adventurers", "adventurers"),
    Genre("Age Gap", "age-gap"),
    Genre("Alchemy", "alchemy"),
    Genre("Animal Bond", "animal-bond"),
    Genre("Animals", "animals"),
    Genre("Anthology", "anthology"),
    Genre("Anti-Hero", "anti-hero"),
    Genre("Apocalypse", "apocalypse"),
    Genre("Architecture", "architecture"),
    Genre("Art/Craftsmanship", "art-craftsmanship"),
    Genre("Arts", "arts"),
    Genre("Bad Ending Avoidance", "bad-ending-avoidance"),
    Genre("Baseball", "baseball"),
    Genre("Basketball", "basketball"),
    Genre("Battle", "battle"),
    Genre("Battle Royale", "battle-royale"),
    Genre("Beastman", "beastman"),
    Genre("Biography", "biography"),
    Genre("BL (Boys' Love)", "bl-boys-love"),
    Genre("Boy Meets Girl", "boy-meets-girl"),
    Genre("Boys' Love (BL)", "boys-love-bl"),
    Genre("Brotherly Bond", "brotherly-bond"),
    Genre("Business", "business"),
    Genre("Card Game", "card-game"),
    Genre("Child Protagonist", "child-protagonist"),
    Genre("Childcare", "childcare"),
    Genre("Childhood Friends", "childhood-friends"),
    Genre("Children's Literature", "childrens-literature"),
    Genre("Chinese-style Fantasy", "chinese-style-fantasy"),
    Genre("Cinderella Story", "cinderella-story"),
    Genre("Class Difference", "class-difference"),
    Genre("Clueless Male Lead", "clueless-male-lead"),
    Genre("Comedy", "comedy"),
    Genre("Comic MeDu", "comic-medu"),
    Genre("Coming of Age", "coming-of-age"),
    Genre("Companion Animal", "companion-animal"),
    Genre("Competitive Gaming", "competitive-gaming"),
    Genre("Cooking", "cooking"),
    Genre("Cooking (Gourmet)", "cooking-gourmet"),
    Genre("Crafting", "crafting"),
    Genre("Crime", "crime"),
    Genre("Cyberpunk", "cyberpunk"),
    Genre("Dark Comedy", "dark-comedy"),
    Genre("Dark Fantasy", "dark-fantasy"),
    Genre("Destiny", "destiny"),
    Genre("Disaster", "disaster"),
    Genre("Documentary", "documentary"),
    Genre("Dragons", "dragons"),
    Genre("Drama", "drama"),
    Genre("Dungeon", "dungeon"),
    Genre("Dystopia", "dystopia"),
    Genre("Ecchi", "ecchi"),
    Genre("Ecchi (Light)", "ecchi-light"),
    Genre("Educational", "educational"),
    Genre("Empowerment", "empowerment"),
    Genre("Engineering", "engineering"),
    Genre("Eroge World", "eroge-world"),
    Genre("Erotica", "erotica"),
    Genre("Family", "family"),
    Genre("Fantasy", "fantasy"),
    Genre("Fashion", "fashion"),
    Genre("Fatherhood", "fatherhood"),
    Genre("Female Protagonist", "female-protagonist"),
    Genre("Food/Cooking (Dark)", "food-cooking-dark"),
    Genre("Gag", "gag"),
    Genre("Gambling", "gambling"),
    Genre("Game", "game"),
    Genre("Game Elements", "game-elements"),
    Genre("Game Lit", "game-lit"),
    Genre("Gaming", "gaming"),
    Genre("Gap Moe", "gap-moe"),
    Genre("Gender Bender", "gender-bender"),
    Genre("Gender Bender (Crossdressing)", "gender-bender-crossdressing"),
    Genre("Gender Bender (Tomboy/Crossdressing)", "gender-bender-tomboy-crossdressing"),
    Genre("Gender Bender (TS)", "gender-bender-ts"),
    Genre("Gender Role Reversal", "gender-role-reversal"),
    Genre("Girls Love", "girls-love"),
    Genre("Girls' Love (GL)", "girls-love-gl"),
    Genre("Girls' Love (GL/Yuri)", "girls-love-gl-yuri"),
    Genre("GL (Girls' Love)", "gl-girls-love"),
    Genre("Glow-Up Heroine", "glow-up-heroine"),
    Genre("Gore", "gore"),
    Genre("Gore (Mild)", "gore-mild"),
    Genre("Gothic", "gothic"),
    Genre("Gourmet", "gourmet"),
    Genre("Growth", "growth"),
    Genre("Guardian Spirit", "guardian-spirit"),
    Genre("Gyaru", "gyaru"),
    Genre("Harem", "harem"),
    Genre("Healing", "healing"),
    Genre("Heartwarming", "heartwarming"),
    Genre("Heroic", "heroic"),
    Genre("Heroic Fantasy", "heroic-fantasy"),
    Genre("Historical", "historical"),
    Genre("Historical Japanese Style", "historical-japanese-style"),
    Genre("Horror", "horror"),
    Genre("Horror-Parody", "horror-parody"),
    Genre("Idol", "idol"),
    Genre("Inspirational", "inspirational"),
    Genre("Intellectual Battles", "intellectual-battles"),
    Genre("Investigation", "investigation"),
    Genre("Isekai", "isekai"),
    Genre("Isekai Reincarnation", "isekai-reincarnation"),
    Genre("Isekai/Rebirth", "isekai-rebirth"),
    Genre("Isekai/Tensei", "isekai-tensei"),
    Genre("Iyashikei", "iyashikei"),
    Genre("Iyashikei (Healing)", "iyashikei-healing"),
    Genre("Japanese Folklore", "japanese-folklore"),
    Genre("Josei", "josei"),
    Genre("Kaiju", "kaiju"),
    Genre("Kingdom Building", "kingdom-building"),
    Genre("Lighthearted", "lighthearted"),
    Genre("Lolicon", "lolicon"),
    Genre("Magic", "magic"),
    Genre("Magic School", "magic-school"),
    Genre("Magical Girl", "magical-girl"),
    Genre("Magical Girl (Mahou Shoujo)", "magical-girl-mahou-shoujo"),
    Genre("Martial Art", "martial-art"),
    Genre("Martial Arts", "martial-arts"),
    Genre("Mature", "mature"),
    Genre("Mecha", "mecha"),
    Genre("Medical", "medical"),
    Genre("Mentor–Student", "mentorstudent"),
    Genre("Meta", "meta"),
    Genre("Meta-fiction", "meta-fiction"),
    Genre("Military", "military"),
    Genre("Misunderstandings", "misunderstandings"),
    Genre("Modern Dungeon", "modern-dungeon"),
    Genre("Modern Fantasy", "modern-fantasy"),
    Genre("Modern Setting", "modern-setting"),
    Genre("Modern Society", "modern-society"),
    Genre("Monster Care", "monster-care"),
    Genre("Monster Girl", "monster-girl"),
    Genre("Monster Tamer", "monster-tamer"),
    Genre("Monsters", "monsters"),
    Genre("Music", "music"),
    Genre("Mutual Pining", "mutual-pining"),
    Genre("Mystery", "mystery"),
    Genre("Nariagari (Rising Stars)", "nariagari-rising-stars"),
    Genre("Nobility", "nobility"),
    Genre("Noble Society", "noble-society"),
    Genre("Non-Fiction", "non-fiction"),
    Genre("Nonfiction", "nonfiction"),
    Genre("One Shot", "one-shot"),
    Genre("Otaku Culture", "otaku-culture"),
    Genre("Otherworld Transformation", "otherworld-transformation"),
    Genre("Otome Game", "otome-game"),
    Genre("Otome Isekai", "otome-isekai"),
    Genre("Overpowered", "overpowered"),
    Genre("Overpowered Protagonist", "overpowered-protagonist"),
    Genre("Parenting", "parenting"),
    Genre("Parody", "parody"),
    Genre("Past Life Memories", "past-life-memories"),
    Genre("Performing Arts", "performing-arts"),
    Genre("Persistent Male Lead", "persistent-male-lead"),
    Genre("Police Drama", "police-drama"),
    Genre("Political Drama", "political-drama"),
    Genre("Post-Apocalyptic", "post-apocalyptic"),
    Genre("Power Growth", "power-growth"),
    Genre("Psychological", "psychological"),
    Genre("Psychological Horror", "psychological-horror"),
    Genre("Rebirth", "rebirth"),
    Genre("Rebirth/Regression", "rebirth-regression"),
    Genre("Redemption", "redemption"),
    Genre("Regression", "regression"),
    Genre("Reincarnation", "reincarnation"),
    Genre("Reincarnation Isekai", "reincarnation-isekai"),
    Genre("Reincarnation/Villainess", "reincarnation-villainess"),
    Genre("Revenge", "revenge"),
    Genre("Reverse Harem", "reverse-harem"),
    Genre("Rivalry", "rivalry"),
    Genre("Rom-Com", "rom-com"),
    Genre("Romance", "romance"),
    Genre("Romantic", "romantic"),
    Genre("Romantic Comedy", "romantic-comedy"),
    Genre("Romcom", "romcom"),
    Genre("Royal Life", "royal-life"),
    Genre("Royalty", "royalty"),
    Genre("RPG/System", "rpg-system"),
    Genre("Satire", "satire"),
    Genre("Scenario Reversal", "scenario-reversal"),
    Genre("School Life", "school-life"),
    Genre("Sci-fi", "sci-fi"),
    Genre("Science Fiction", "science-fiction"),
    Genre("Seinen", "seinen"),
    Genre("Seinen (Light)", "seinen-light"),
    Genre("Seinen/Shonen", "seinen-shonen"),
    Genre("Seishun (Youth)", "seishun-youth"),
    Genre("Shojo", "shojo"),
    Genre("Shojo/Seinen", "shojo-seinen"),
    Genre("Shonen", "shonen"),
    Genre("Shonen/Shojo", "shonen-shojo"),
    Genre("Shonen/Shoujo", "shonen-shoujo"),
    Genre("Shotacon", "shotacon"),
    Genre("Shoujo", "shoujo"),
    Genre("Shoujo Ai", "shoujo-ai"),
    Genre("Shoujo/Josei", "shoujo-josei"),
    Genre("Shoujo/Seinen", "shoujo-seinen"),
    Genre("Shoujo/Shonen", "shoujo-shonen"),
    Genre("Shounen", "shounen"),
    Genre("Shounen Ai", "shounen-ai"),
    Genre("Shounen-ai / BL (Soft)", "shounen-ai-bl-soft"),
    Genre("Shounen-ai / BL (Subtle)", "shounen-ai-bl-subtle"),
    Genre("Slapstick", "slapstick"),
    Genre("Slice of Life", "slice-of-life"),
    Genre("Slow Burn", "slow-burn"),
    Genre("Slow Life", "slow-life"),
    Genre("Smut", "smut"),
    Genre("Social Commentary", "social-commentary"),
    Genre("Social Issues", "social-issues"),
    Genre("Sports", "sports"),
    Genre("Sports (Fishing)", "sports-fishing"),
    Genre("Sports (Soccer)", "sports-soccer"),
    Genre("Sports (Table Tennis)", "sports-table-tennis"),
    Genre("Spy", "spy"),
    Genre("Strategy", "strategy"),
    Genre("Streaming", "streaming"),
    Genre("Strong-After-Hardship Protagonist", "strong-after-hardship-protagonist"),
    Genre("Sumo", "sumo"),
    Genre("Supernatural", "supernatural"),
    Genre("Survival", "survival"),
    Genre("Suspense", "suspense"),
    Genre("Suspenser", "suspenser"),
    Genre("Sweet & Fluffy", "sweet-fluffy"),
    Genre("Sweet Comedy", "sweet-comedy"),
    Genre("Teamwork", "teamwork"),
    Genre("Teasing Heroine", "teasing-heroine"),
    Genre("Tech/Cyber", "tech-cyber"),
    Genre("Thriller", "thriller"),
    Genre("Time Loop", "time-loop"),
    Genre("Time Travel", "time-travel"),
    Genre("Tragedy", "tragedy"),
    Genre("Training & Growth", "training-growth"),
    Genre("Transformation", "transformation"),
    Genre("True Crime", "true-crime"),
    Genre("Twin Sisters", "twin-sisters"),
    Genre("Underdog Heroine", "underdog-heroine"),
    Genre("Updating", "updating"),
    Genre("Urban Fantasy", "urban-fantasy"),
    Genre("Vampire", "vampire"),
    Genre("Villain Protagonist", "villain-protagonist"),
    Genre("Villainess", "villainess"),
    Genre("Villainess-style", "villainess-style"),
    Genre("Virtual", "virtual"),
    Genre("Volleyball", "volleyball"),
    Genre("Wafu Fantasy", "wafu-fantasy"),
    Genre("War", "war"),
    Genre("Wish Fulfillment", "wish-fulfillment"),
    Genre("Workplace", "workplace"),
    Genre("Xianxia", "xianxia"),
    Genre("Yandere", "yandere"),
    Genre("Youth", "youth"),
    Genre("Yuri", "yuri"),
    Genre("Zombie", "zombie"),
)
