package eu.kanade.tachiyomi.extension.es.codearc

import eu.kanade.tachiyomi.source.model.Filter
import eu.kanade.tachiyomi.source.model.FilterList

open class UriPartFilter(
    displayName: String,
    val vals: Array<Pair<String, String>>,
) : Filter.Select<String>(displayName, vals.map { it.first }.toTypedArray()) {
    fun toUriPart() = vals[state].second
}

class ContentTypeFilter :
    UriPartFilter(
        "Tipo de contenido",
        arrayOf(
            Pair("Todo tipo de contenido", ""),
            Pair("Doujinshi", "1"),
            Pair("Manga", "2"),
            Pair("Manhwa", "3"),
            Pair("Manhua", "4"),
            Pair("Comic", "5"),
            Pair("Recopilación", "6"),
            Pair("Artista CG", "7"),
        ),
    )

class FormatFilter :
    UriPartFilter(
        "Formato de publicación",
        arrayOf(
            Pair("Serie y One-shot", "both"),
            Pair("Solo Serie", "serie"),
            Pair("Solo One-shot", "oneshot"),
        ),
    )

class SortFilter :
    UriPartFilter(
        "Ordenar por",
        arrayOf(
            Pair("Mas recientes", "latest"),
            Pair("Mas popular del dia", "popular_day"),
            Pair("Mas popular de la semana", "popular_week"),
            Pair("Mas popular del mes", "popular_month"),
            Pair("Mas popular desde siempre", "popular_all"),
        ),
    )

class Genre(name: String, val slug: String) : Filter.CheckBox(name)

class GenreGroup : Filter.Group<Genre>("Géneros", GENRES_LIST)

fun getFilters(): FilterList = FilterList(
    ContentTypeFilter(),
    FormatFilter(),
    SortFilter(),
    GenreGroup(),
)

private val GENRES_LIST = listOf(
    Genre("Acción", "accion"),
    Genre("Adulto", "adulto"),
    Genre("Age Gap", "age-gap"),
    Genre("Ahegao", "ahegao"),
    Genre("Amiga de la Infancia", "amiga-de-la-infancia"),
    Genre("Anal", "anal"),
    Genre("Asfixia", "asfixia"),
    Genre("BDSM", "bdsm"),
    Genre("BL", "bl"),
    Genre("Bbw", "bbw"),
    Genre("Besos", "besos"),
    Genre("Big Breasts", "big-breasts"),
    Genre("Big Penis", "big-penis"),
    Genre("Bikini", "bikini"),
    Genre("Blowjob", "blowjob"),
    Genre("Bronceada", "bronceada"),
    Genre("Bruja", "bruja"),
    Genre("Bukkake", "bukkake"),
    Genre("Cabello claro", "cabello-claro"),
    Genre("Cabello corto", "cabello-corto"),
    Genre("Cheating", "cheating"),
    Genre("Chica alta", "chica-alta"),
    Genre("Coletas", "coletas"),
    Genre("Collar", "collar"),
    Genre("Comedia", "comedia"),
    Genre("Condón", "condon"),
    Genre("Control mental", "control-mental"),
    Genre("Corrupción", "corrupcion"),
    Genre("Cosplay", "cosplay"),
    Genre("Creampie", "creampie"),
    Genre("Culo grande", "culo-grande"),
    Genre("Dark skin", "dark-skin"),
    Genre("Deformación de estomago", "deformacion-de-estomago"),
    Genre("Diferencia de edad", "diferencia-de-edad"),
    Genre("Dilf", "dilf"),
    Genre("Doble penetraciòn", "doble-penetracion"),
    Genre("Dominación", "dominacion"),
    Genre("Drama", "drama"),
    Genre("Drogas", "drogas"),
    Genre("Ecchi", "ecchi"),
    Genre("Elfa", "elfa"),
    Genre("Embarazo", "embarazo"),
    Genre("Enfermera", "enfermera"),
    Genre("Escuela", "escuela"),
    Genre("Exhibicionismo", "exhibicionismo"),
    Genre("Fantasía", "fantasia"),
    Genre("Femboy", "femboy"),
    Genre("Feminization", "feminization"),
    Genre("Filming", "filming"),
    Genre("Full Color", "full-color"),
    Genre("Furry", "furry"),
    Genre("Futanari", "futanari"),
    Genre("Garganta Profunda", "garganta-profunda"),
    Genre("Gender Change", "gender-change"),
    Genre("Gilf", "gilf"),
    Genre("Goblin", "goblin"),
    Genre("Grabación", "grabacion"),
    Genre("Guantes", "guantes"),
    Genre("Gyaru", "gyaru"),
    Genre("Harem", "harem"),
    Genre("Hidden Sex", "hidden-sex"),
    Genre("Hipnosis", "hipnosis"),
    Genre("Idol", "idol"),
    Genre("Incesto", "incesto"),
    Genre("Infidelidad", "infidelidad"),
    Genre("Interracial", "interracial"),
    Genre("Kissing", "kissing"),
    Genre("Lamer Pies", "lamer-pies"),
    Genre("Lenceria", "lenceria"),
    Genre("Lentes", "lentes"),
    Genre("MILF", "milf"),
    Genre("Madre x Hijo", "madre-x-hijo"),
    Genre("Maid", "maid"),
    Genre("Mascara", "mascara"),
    Genre("Masturbacion", "masturbacion"),
    Genre("Matrimonio", "matrimonio"),
    Genre("Mature", "mature"),
    Genre("Mind Break", "mind-break"),
    Genre("Monster Girls", "monster-girls"),
    Genre("Musculos", "musculos"),
    Genre("NTR", "ntr"),
    Genre("Nakadashi", "nakadashi"),
    Genre("Netori", "netori"),
    Genre("Ninfomana", "ninfomana"),
    Genre("Nipple Piercing", "nipple-piercing"),
    Genre("Noona", "noona"),
    Genre("Nurse", "nurse"),
    Genre("Nympho", "nympho"),
    Genre("Oficina", "oficina"),
    Genre("Orgía", "orgia"),
    Genre("Oyakodon", "oyakodon"),
    Genre("Paizuri", "paizuri"),
    Genre("Parodia", "parodia"),
    Genre("Pechos grandes", "pechos-grandes"),
    Genre("Pechos pequeños", "pechos-pequenos"),
    Genre("Personality Excretion", "personality-excretion"),
    Genre("Piel Oscura", "piel-oscura"),
    Genre("Piercing", "piercing"),
    Genre("Possession", "possession"),
    Genre("Profesora", "profesora"),
    Genre("Prostitución", "prostitucion"),
    Genre("Reverse Harem", "reverse-harem"),
    Genre("Romance", "romance"),
    Genre("Roommates", "roommates"),
    Genre("Secretary", "secretary"),
    Genre("Seducción", "seduccion"),
    Genre("Sex Toys", "sex-toys"),
    Genre("Shota", "shota"),
    Genre("Sin Censura", "sin-censura"),
    Genre("Sin Penetración", "sin-penetracion"),
    Genre("Sister", "sister"),
    Genre("SkinSuit", "skinsuit"),
    Genre("Slice of Life", "slice-of-life"),
    Genre("Sobrenatural", "sobrenatural"),
    Genre("Solo Hombres", "solo-hombres"),
    Genre("Squirting", "squirting"),
    Genre("Stockings", "stockings"),
    Genre("Stomach Deformation", "stomach-deformation"),
    Genre("Story Arc", "story-arc"),
    Genre("Succubus", "succubus"),
    Genre("Sucubo", "sucubo"),
    Genre("SuperHéroe", "superheroe"),
    Genre("Swinging", "swinging"),
    Genre("Tankoubon", "tankoubon"),
    Genre("Teacher", "teacher"),
    Genre("Tetas grandes", "tetas-grandes"),
    Genre("Tomboy", "tomboy"),
    Genre("Tomgirl", "tomgirl"),
    Genre("Trio", "trio"),
    Genre("Triángulo Amoroso", "triangulo-amoroso"),
    Genre("Tsundere", "tsundere"),
    Genre("Universidad", "universidad"),
    Genre("Vainilla", "vainilla"),
    Genre("Vecinos", "vecinos"),
    Genre("Venganza", "venganza"),
    Genre("Virgen", "virgen"),
    Genre("Voyeurismo", "voyeurismo"),
    Genre("X-Ray", "x-ray"),
    Genre("Yaoi", "yaoi"),
    Genre("Yuri", "yuri"),
    Genre("assjob", "assjob"),
    Genre("beauty mark", "beauty-mark"),
    Genre("big areolae", "big-areolae"),
    Genre("big ass", "big-ass"),
    Genre("big nipples", "big-nipples"),
    Genre("blowjob face", "blowjob-face"),
    Genre("bondage", "bondage"),
    Genre("cervix penetration", "cervix-penetration"),
    Genre("corset", "corset"),
    Genre("estimilacion de pezones", "estimilacion-de-pezones"),
    Genre("extra", "extra"),
    Genre("femdom", "femdom"),
    Genre("fishnets", "fishnets"),
    Genre("focus anal", "focus-anal"),
    Genre("footjob", "footjob"),
    Genre("fundoshi", "fundoshi"),
    Genre("garter belt", "garter-belt"),
    Genre("glasses", "glasses"),
    Genre("hairy", "hairy"),
    Genre("hairy armpits", "hairy-armpits"),
    Genre("hotpants", "hotpants"),
    Genre("huge breasts", "huge-breasts"),
    Genre("incest", "incest"),
    Genre("inflation", "inflation"),
    Genre("inseki", "inseki"),
    Genre("lactation", "lactation"),
    Genre("lingerie", "lingerie"),
    Genre("medias", "medias"),
    Genre("mother", "mother"),
    Genre("multiple orgasms", "multiple-orgasms"),
    Genre("ncensored", "ncensored"),
    Genre("rape", "rape"),
    Genre("ryona", "ryona"),
    Genre("sleeping", "sleeping"),
    Genre("sweating", "sweating"),
    Genre("swimsuit", "swimsuit"),
    Genre("tall girl", "tall-girl"),
    Genre("traje de baño", "traje-de-bano"),
    Genre("twintails", "twintails"),
    Genre("uncensored", "uncensored"),
    Genre("virginity", "virginity"),
    Genre("vomit", "vomit"),
)
