package eu.kanade.tachiyomi.extension.en.kingcomix

import eu.kanade.tachiyomi.source.model.Filter

open class UriPartFilter(
    displayName: String,
    private val vals: Array<Pair<String, String>>,
) : Filter.Select<String>(displayName, vals.map { it.first }.toTypedArray()) {
    fun toUriPart() = vals[state].second
}

class CategoryFilter : UriPartFilter("Category", CATEGORIES)
class TagFilter : UriPartFilter("Tag", TAGS)

private val CATEGORIES = arrayOf(
    Pair("Any", ""),
    Pair("3D Porn Comics", "3d-porn-comics-xxx"),
    Pair("Adventure Time Porn", "adventure-time"),
    Pair("American Dad Porn", "american-dad-xx-porn-comix"),
    Pair("Attack on Titan Hentai", "attack-on-titan-hentai"),
    Pair("Ben 10 Porn Comics", "ben-10-porn-comics-v1"),
    Pair("Chainsaw Man Porn Comics", "porn-chainsaw-man-porn-comics"),
    Pair("Dragon Ball Porn", "dragon-ball-z-porn-comics-v1"),
    Pair("Exclusive", "exclusive"),
    Pair("Furry Porn Comics", "porn-comic-furry"),
    Pair("Hentai Manga", "xxxx-manga"),
    Pair("Interracial Porn", "interracial-porn-comix2-xxx"),
    Pair("Kim Possible Porn", "kim-possible-porn1"),
    Pair("LoL Hentai", "lol-hentai-xxx-comics1"),
    Pair("My Hero Academia Hentai", "hero-academia-porn-comic-v1"),
    Pair("Naruto Hentai", "naruto-hentai-comic4"),
    Pair("One Piece Hentai", "one-piece-hentai-v2"),
    Pair("Palcomix", "palcomix"),
    Pair("Pokemon Porn", "pokemon-porn-comics-v1"),
    Pair("Porn Comics", "porn-c0mics"),
    Pair("Princess Peach Porn", "princess-peach-porn-xxx"),
    Pair("Rick and Morty Porn Comics", "rick-and-morty-porn-comics"),
    Pair("Simpsons Porn", "simpsons-xxx-porn-comics"),
    Pair("Sonic Porn Comics", "sonic_porn-comics"),
    Pair("Sword Art Online Hentai", "sword-art-online-xxx-hentai1"),
    Pair("Teen Titans Porn", "teen-titans-porn-v1"),
)

private val TAGS = arrayOf(
    Pair("Any", ""),
    Pair("Aarokira", "aarokira"),
    Pair("Accel Art", "accel-art"),
    Pair("Aerith Hentai", "aerith-hentai"),
    Pair("Afrobull", "afrobull"),
    Pair("agent aika", "agent-aika"),
    Pair("Ahri", "ahri"),
    Pair("Ahri Hentai", "ahri-hentai"),
    Pair("Ahsoka", "ahsoka"),
    Pair("Akali Hentai", "akali-hentai1"),
    Pair("Alien Girl", "alien-girl"),
    Pair("American Dragon", "american-dragon"),
    Pair("Amethyst", "amethyst"),
    Pair("Amity Blight", "amity-blight"),
    Pair("Among Us", "among-us"),
    Pair("Amphibia Porn", "amphibia-porn"),
    Pair("Amy", "amy"),
    Pair("Amy Rose Hentai", "amy-rose-hentai"),
    Pair("Amy Wong", "amy-wong"),
    Pair("Anal", "anal"),
    Pair("Anall", "anall"),
    Pair("Android 18 Hentai", "android_18_xxx-hentai"),
    Pair("Android 21 Hentai", "android-21-hentai-xxx"),
    Pair("Animal Crossing", "animal-crossing-hentai-v1"),
    Pair("Animated", "animated"),
    Pair("Ankha", "ankha"),
    Pair("Ann Possible", "ann-possible"),
    Pair("Arabatos", "arabatos"),
    Pair("Area", "area"),
    Pair("Aroma Sensei", "aroma-sensei"),
    Pair("Ashe Hentai", "ashe-hentai"),
    Pair("Asuka Hentai", "asuka-henta1"),
    Pair("Asuna Hentai", "asuna-xxx-hentai"),
    Pair("Atlantis The Lost Empire", "atlantis-the-lost-empire"),
    Pair("Atomic Heart Porn", "atomic-heart-porn"),
    Pair("Avatar Hentai", "avatar-hentai-v1"),
    Pair("Avengers", "avengers"),
    Pair("Batgirl", "batgirl"),
    Pair("Batman Porn Comics", "batman-porn-comics-xxx"),
    Pair("Bayonetta", "bayonetta"),
    Pair("BDSM", "bdsm"),
    Pair("Beast Boy", "beast-boy"),
    Pair("Big As", "big-as"),
    Pair("Big Ass", "big-ass"),
    Pair("Big Black Cock", "big-black-cock"),
    Pair("Big Boobs", "big-boobs-xxx"),
    Pair("Big Breasts", "big-breasts-hentai"),
    Pair("Big Cock", "big-cock"),
    Pair("Big Dick", "big-dick"),
    Pair("Big Hero 6", "big-hero-6-porn"),
    Pair("Big Tits", "big-tit"),
    Pair("Bigdad", "bigdad"),
    Pair("Bioshock Porn", "bioshock-porn"),
    Pair("Black Clover Porn", "black-clover-porn-xxx"),
    Pair("blackfire", "blackfire"),
    Pair("Blacknwhite", "blacknwhite"),
    Pair("Blaze", "blaze"),
    Pair("Bleach Hentai", "bleach-porn-comics-xxx"),
    Pair("Bloodborne", "bloodborne"),
    Pair("Blowjob", "blowjob"),
    Pair("Blue Archive", "blue-archive"),
    Pair("Boa Hancock Hentai", "boa-hancock-hentai-xxx1"),
    Pair("Boruto", "boruto"),
    Pair("Botbot", "botbot"),
    Pair("Bowsette Hentai", "bowsette-hentai1"),
    Pair("Brain Dead 13 Porn", "brain-dead-13-porn"),
    Pair("Brandy and mr Whiskers", "brandy-and-mr-whiskers"),
    Pair("Briar Hentai", "briar-hentai"),
    Pair("Bulma Hentai", "bulma-h3ntaix"),
    Pair("Bunny Girl", "bunny-girl"),
    Pair("Carmelita", "carmelita"),
    Pair("carrot", "carrot"),
    Pair("Catgirl", "catgirl"),
    Pair("Catunder", "catunder"),
    Pair("Caulifla Hentai", "caulifla-hentai"),
    Pair("chainsaw man porn comic", "chainsaw-man-porn-comic"),
    Pair("Chara", "chara"),
    Pair("Cheelai Hentai", "cheelai-hentai"),
    Pair("Cherry Road Porn Comics", "cherry-road-porn-comics"),
    Pair("Chi-Chi Hentai", "chi-chi_hentai"),
    Pair("Chloe", "chloe"),
    Pair("ChoChoX", "chochox"),
    Pair("Chun-Li", "chun-li"),
    Pair("Coco Bandicoot Hentai", "coco-bandicoot-hentai"),
    Pair("Code Lyoko", "code-lyoko"),
    Pair("Connie Maheswaran", "connie-maheswaran"),
    Pair("Cookie Run Porn", "cookie-run-porn"),
    Pair("Cortana Porn", "cortana-porn"),
    Pair("Crash Bandicoot", "crash-bandicoot-porn"),
    Pair("CrazyDad3D", "crazydad3d"),
    Pair("Cream the Rabbit", "cream-the-rabbit"),
    Pair("CrockComix", "crockcomix"),
    Pair("Crossdressing", "crossdressing"),
    Pair("Cumshot", "cumshot"),
    Pair("Cunnilingus", "cunnilingus"),
    Pair("Cuphead Hentai", "cuphead-hentai"),
    Pair("Cyberpunk Edgerunners Porn", "cyberpunk-edgerunners-p0rn-comics"),
    Pair("Daisy Hentai", "daisy-hentai"),
    Pair("Dandadan Hentai", "dandadan-comic2-hentai"),
    Pair("Danganronpa", "danganronpa"),
    Pair("Danny Phantom Porn", "danny-phantom_porn-comics"),
    Pair("Daphne Hentai", "daphne-hentai"),
    Pair("Dark Souls", "dark-souls"),
    Pair("Darkstalkers Porn", "darkstalkers-porn"),
    Pair("Dawn Hentai", "dawn-hentai"),
    Pair("DC Porn", "dc-porn"),
    Pair("Deadpool", "deadpool"),
    Pair("Dee Dee", "dee-dee"),
    Pair("Deepthroat", "deepthroat"),
    Pair("Deku", "deku"),
    Pair("Deltarune Porn", "deltarune-porn"),
    Pair("Demon Girl", "demon-girl"),
    Pair("Demon Slayer Nezuko Porn", "demon-slayer-nezuko-porn1"),
    Pair("Demon Slayer Porn", "demon-slayer-porn-comic1-xxx"),
    Pair("Devil May Cry", "devil-may-cry"),
    Pair("Devvil May Cry Porn", "devvil-may-cry-porn"),
    Pair("Dexter Mom Hentai", "dexter-mom-hentai1"),
    Pair("Dexter Porn Comics", "dexter-porn-comics"),
    Pair("Diane", "diane"),
    Pair("Digimon XXX", "digimon-xxx"),
    Pair("Dipper", "dipper"),
    Pair("Diva Hentai", "diva-hentai"),
    Pair("Doom", "doom"),
    Pair("Dora", "dora"),
    Pair("Double Anal", "double-anal"),
    Pair("Double Penetration", "double-penetration"),
    Pair("Dr. Stone", "dr-stone-x"),
    Pair("Dragon Quest Porn", "dragon-quest-porn"),
    Pair("Drah Navlag", "drah-navlag"),
    Pair("Dsan", "dsan"),
    Pair("dungeon and dragons", "dungeon-and-dragons"),
    Pair("Ed Edd n Eddy Porn", "ed-edd-n-eddy-porn"),
    Pair("Elden Ring", "elden-ring"),
    Pair("Elf", "elf"),
    Pair("Elizabeth Liones porn", "elizabeth-liones-porn"),
    Pair("Elsa", "elsa-hentai"),
    Pair("Emma Frost", "emma-frost"),
    Pair("Epic Seven Hentai", "epic-seven-hentai"),
    Pair("Ero Mantic", "ero-mantic"),
    Pair("Evangelion Hentai", "henta1-evangeli0n"),
    Pair("Evee", "evee"),
    Pair("Evelynn", "evelynn"),
    Pair("Exclusive", "exclusive"),
    Pair("Fairy Tail", "fairy-tail-hentai-v0"),
    Pair("Fallout XXX", "fallout-xxx-hentai"),
    Pair("Family Guy Porn Comics", "family-guy-porn_comix"),
    Pair("Fate Grand Order Hentai", "fate-grand-order-hentai-v0"),
    Pair("Feith Noir", "feith-noir"),
    Pair("Felsala", "felsala"),
    Pair("Final Fantasy Hentai", "final-fantasy-hentai-v2"),
    Pair("Finn", "finn"),
    Pair("Fiona", "fiona"),
    Pair("Fiora", "fiora"),
    Pair("Fire Emblem", "fire-emblem"),
    Pair("five nights at freddy's Porn", "five-nights-at-freddys-porn"),
    Pair("Flame Princess", "flame-princess"),
    Pair("Footjob", "footjob"),
    Pair("Fortnite", "fortnite"),
    Pair("Foster’s Home for Imaginary Friends Porn", "fosters-home-for-imaginary-friends-porn"),
    Pair("Francine Porn Comics", "francine-porn-comics"),
    Pair("Frankie Foster Hentai", "frankie-foster-hentai"),
    Pair("Fred Perry", "fred-perry"),
    Pair("Frieren Porn", "frieren-porn"),
    Pair("Frozen", "frozen"),
    Pair("Fubuki Hentai", "fubuki-hentai"),
    Pair("Full Color", "full-color-comic"),
    Pair("FunsexyDB", "funsexydb"),
    Pair("Furret El Furro", "furret-el-furro"),
    Pair("Futa Comic", "futanari-comic-xxx"),
    Pair("Futurama Porn Comics", "futurama_porn-c0mics1"),
    Pair("Gansoman", "gansoman"),
    Pair("Gardevoir Hentai", "gardevoir-hentaix"),
    Pair("Garnet Hentai", "garnet-hentai"),
    Pair("gay porn comics", "porn-comics-gay"),
    Pair("Gemma Hentai", "gemma-hentai"),
    Pair("Gender Bender", "gender-bender"),
    Pair("Genshin Impact Porn", "genshin-impact-p0rnx"),
    Pair("Gine Hentai", "gine-hentai"),
    Pair("Girls und Panzer Hentai", "girls-und-panzer_hentai"),
    Pair("Girls' Frontline Hentai", "girls-frontline-hentai"),
    Pair("Glitch Techs", "glitch-techs"),
    Pair("Glory Hole", "glory-hole"),
    Pair("Goblin", "goblin"),
    Pair("Goku", "goku"),
    Pair("gold digger", "gold-digger"),
    Pair("Granblue Fantasy", "granblue-fantasy"),
    Pair("Gravity Falls Porn", "gravity-falls-porn-comics"),
    Pair("Great Fairy Hentai", "great-fairy-hentai"),
    Pair("Greendogg", "greendogg"),
    Pair("Guilty Gear", "guilty-gear"),
    Pair("Gumball", "gumball"),
    Pair("Gwen", "gwen"),
    Pair("Gwen Stacy", "gwen-stacy"),
    Pair("GygerBeen", "gygerbeen"),
    Pair("Hagfish", "hagfish"),
    Pair("Haikon Knight", "haikon-knight"),
    Pair("Halo", "halo"),
    Pair("Handjob", "handjob"),
    Pair("Harley Quinn", "harley-quinn"),
    Pair("Harry Potter", "harry-potter"),
    Pair("Hatsune Miku Hentai", "hatsune-miku-hentai"),
    Pair("Hazbin Hotel", "hazbin-hotel-pornx"),
    Pair("Hekapoo", "hekapoo-hentai"),
    Pair("Helluva Boss Porn", "helluva-boss-comics-xxx"),
    Pair("Hermione Granger", "hermione-granger"),
    Pair("Hermit Moth Hentai", "hermit-moth-hentai"),
    Pair("HermitMoth", "hermitmoth"),
    Pair("Hey Arnold", "hey-arnold"),
    Pair("Highschool DxD", "highschool-dxd"),
    Pair("Hilda", "hilda"),
    Pair("Hilda Porn", "hilda-porn"),
    Pair("Himiko Toga Hentai", "himiko-toga-hentai"),
    Pair("Hinata Hentai", "hinata-hentai-xxx2"),
    Pair("Honey Lemon Hentai", "honey-lemon-hentai"),
    Pair("Hornyx", "hornyx"),
    Pair("Hot Step Sister", "hot-step-sister"),
    Pair("Hotel Transylvania Porn Comics", "hotel_transylvania-porn-comics"),
    Pair("Huge Breasts", "huge-breasts"),
    Pair("Ice Queen Hentai", "ice-queen-hentai"),
    Pair("Impa Hentai", "impa-hentai"),
    Pair("Incestibles", "incestibles"),
    Pair("Incognitymous", "incognitymous-comic"),
    Pair("Ino", "ino"),
    Pair("Ino Hentai", "ino-hentai-xxx"),
    Pair("Inside Out", "inside-out"),
    Pair("Inspector Gadget", "inspector-gadget"),
    Pair("Inuyuru", "inuyuru"),
    Pair("Invader Zim Porn", "invader-zim-porn"),
    Pair("INVINCIBLE Porn", "invincible-porn"),
    Pair("Irelia Hentai", "irelia-hentai"),
    Pair("IS Infinite Stratos", "is-infinite-stratos"),
    Pair("Isabelle", "isabelle"),
    Pair("Itsuka Kendo Hentai", "itsuka-kendo-hentai"),
    Pair("Jack and Daxter", "jack-and-daxter"),
    Pair("Jackie Lynn", "jackie-lynn"),
    Pair("Jaguar", "jaguar"),
    Pair("Jaiden XXX", "jaiden-xxx"),
    Pair("Janna", "janna"),
    Pair("Jasmine", "jasmine"),
    Pair("JDseal", "jdseal"),
    Pair("Jenny Hentai", "jenny-hentai"),
    Pair("Jessica Rabbit", "jessica-rabbit"),
    Pair("Jessie Porn", "jessie-porn"),
    Pair("Jill Valentine", "jill-valentine"),
    Pair("Jimmy Neutron", "jimmy-neutron"),
    Pair("Jinx", "jinx"),
    Pair("Jinx Hentai", "jinx-hentai-xxx-v2"),
    Pair("Jirou Hentai", "jirou_hentai"),
    Pair("Jlullaby", "jlullaby"),
    Pair("Johnny Test", "johnny-test"),
    Pair("Jujutsu Kaisen", "jujutsu-kaisen"),
    Pair("Justice League", "justice-league"),
    Pair("JZerosk", "jzerosk"),
    Pair("Kairi", "kairi"),
    Pair("Kale Hentai", "kale-hentai-xxx"),
    Pair("Kantai Collection Hentai", "kantai-collection-hentai"),
    Pair("Katarina Hentai", "katarina-hentai"),
    Pair("Kefla Hentai", "kefla-hentai"),
    Pair("Kid Icarus", "kid-icarus"),
    Pair("Kill la Kill", "kill-la-kill-hentai"),
    Pair("Kim Possible", "kim-possible-porn1"),
    Pair("kingdom hearts", "kingdom-hearts"),
    Pair("Kinkymation", "kinkymation-hentai"),
    Pair("Kirlia Hentai", "kirlia-hentai"),
    Pair("Kiryuin Satsuki Hentai", "kiryuin-satsuki-hentai"),
    Pair("Kogeikun", "kogeikun"),
    Pair("Lady Dimitrescu Porn", "lady_dimitrescu-porn"),
    Pair("Lady Dmittrescu", "lady-dmittrescu"),
    Pair("Lapis Lazuli", "lapis-lazuli"),
    Pair("Lara Croft", "lara-croft"),
    Pair("Leela Porn", "leela-porn"),
    Pair("Leona", "leona"),
    Pair("Lesbians", "lesbians"),
    Pair("Lilo and Stitch", "lilo-and-stitch"),
    Pair("Lina Inverse", "lina-inverse"),
    Pair("Lisa Simpson Porn", "lisa-simpson-porn"),
    Pair("Lissandra", "lissandra"),
    Pair("Little Nightmares", "little-nightmares"),
    Pair("Little Nightmares Porn", "little-nightmares-porn"),
    Pair("Little Witch Academia", "little-witch-academia"),
    Pair("Lola Bunny", "lola-bunny"),
    Pair("Looney Tunes Porn", "looney-tunes-porn"),
    Pair("Lori Loud Porn", "lori-loud-porn"),
    Pair("Luna Loud", "luna-loud"),
    Pair("Lux", "lux"),
    Pair("Luz Noceda", "luz-noceda"),
    Pair("Mabel", "mabel"),
    Pair("Macergo", "macergo"),
    Pair("Madeline Fenton", "madeline-fenton"),
    Pair("Mai Hentai", "mai-hentai"),
    Pair("Malefica", "malefica"),
    Pair("Maleficient", "maleficient"),
    Pair("Mana World", "mana-world"),
    Pair("Manaworld", "manaworld"),
    Pair("Marceline", "marceline"),
    Pair("Marco Diaz", "marco-diaz"),
    Pair("Marge Simpson Porn", "marge-simpson-porn-xxx"),
    Pair("Mario Bros", "mario-bros"),
    Pair("Marvel", "marvel"),
    Pair("Marvel Rivals Porn", "marvel-rivals-porn"),
    Pair("Mass Effect Porn", "mass-effect-porn"),
    Pair("Masturbation", "masturbation"),
    Pair("May Hentai", "may-hentai-xxx"),
    Pair("Meego", "meego"),
    Pair("Meg Griffin", "meg-griffin"),
    Pair("Mega Man", "mega-man"),
    Pair("Mei Hatsume Hentai", "mei-hatsume-hentai"),
    Pair("Mei Hentai", "mei-hentai"),
    Pair("Melkor Mancin", "melkor-mancin"),
    Pair("MelkorMancin", "melkormancin"),
    Pair("Mercy Hentai", "mercy-hentai"),
    Pair("Metroid", "metroid"),
    Pair("Midna Hentai", "midna-hentai"),
    Pair("Mif", "mif"),
    Pair("Mifl", "mifl"),
    Pair("Mikasa Hentai", "mikasa-henta1"),
    Pair("Miko", "miko"),
    Pair("Miles", "miles"),
    Pair("Miles Morales Porn Comics", "miles-morales-porn-comics"),
    Pair("Milf", "milf-xxx"),
    Pair("Milfs", "milfs"),
    Pair("Milk", "milk"),
    Pair("Milky Bunny", "milky-bunny"),
    Pair("Millie", "millie"),
    Pair("Milo Murphy's Law Porn", "milo-murphys-law-porn"),
    Pair("Mina Ashido Hentai", "mina-ashido-hentai1"),
    Pair("Minako Aino", "minako-aino"),
    Pair("Minecraft Porn", "minecraft-porn"),
    Pair("Mineta", "mineta"),
    Pair("Miraculous Ladybug", "miraculous-ladybug"),
    Pair("Misato Katsuragi Hentai", "misato-katsuragi-hentai"),
    Pair("Miss Heed", "miss-heed"),
    Pair("Misty Hentai", "misty-hentai"),
    Pair("Mitsuki Hentai", "mitsuki-hentai"),
    Pair("Mob Psycho 100", "mob-psycho-100"),
    Pair("Mobile Suit Gundam", "mobile-suit-gundam"),
    Pair("Momo Hentai", "momo_hentai"),
    Pair("Mona", "mona"),
    Pair("Monster Girl", "monster-girl"),
    Pair("monster hunter", "monster-hunter"),
    Pair("Morgana Hentai", "morgana-hentai"),
    Pair("Mossy Froot", "mossy-froot"),
    Pair("Mr. Jean Gobax", "mr-jean-gobax"),
    Pair("Mr.E", "mr-e"),
    Pair("My Bad Bunny", "my-bad-bunny"),
    Pair("My LIfe as a Teenage Robot", "my-life-as-a-teenage-robot"),
    Pair("My Little Pony Porn Comics", "porn-comic-xxx-my-little-pony1"),
    Pair("Nami Hentai", "nami-xxx-hentai-1"),
    Pair("Nana Shimura Hentai", "nana-shimura-hentai"),
    Pair("Neeko", "neeko"),
    Pair("Nejire Hado", "nejire-hado"),
    Pair("Nemona Hentai", "nemona-hentai"),
    Pair("Nemuri Kayama Hentai", "nemuri-kayama-hentai"),
    Pair("NGTVisualStudio", "ngtvisualstudio"),
    Pair("Nico Robin Hentai", "nico-robin-xxx-hentai2"),
    Pair("Nicole Watterson", "nicole-watterson"),
    Pair("Nier Automata", "nier-automata"),
    Pair("Nisego", "nisego"),
    Pair("Oban Star Racers", "oban-star-racers"),
    Pair("Ochako Uraraka", "ochako-uraraka"),
    Pair("OK K.O.! Let's Be Heroes Porn", "ok-k-o-lets-be-heroes-porn"),
    Pair("One Punch Man", "comic-hentai-one-punch-man-porn"),
    Pair("OnGoing", "ongoing"),
    Pair("Ousama Ranking", "ousama-ranking"),
    Pair("Overwatch Porn", "overwatch-porn"),
    Pair("Pacifica Porn", "pacifica-porn"),
    Pair("Palutena Hentai", "palutena-hentai"),
    Pair("Panchy", "panchy"),
    Pair("Paya Hentai", "paya-hentai"),
    Pair("Peach Hentai", "peach-hentai"),
    Pair("Pearl", "pearl"),
    Pair("Pedverse", "pedverse"),
    Pair("Peg", "peg"),
    Pair("Persona 2", "persona-2"),
    Pair("Persona 3", "persona-3"),
    Pair("Persona 4", "persona-4-xxx"),
    Pair("persona 5", "persona-5"),
    Pair("Phineas and Ferb", "phineas-and-ferb"),
    Pair("Pink Pawg", "pink-pawg"),
    Pair("Pokemon Scarlet", "pokemon-scarlet"),
    Pair("PokuArts", "pokuarts"),
    Pair("Pony Tsunotori Hentai", "pony-tsunotori-hentai"),
    Pair("Poppy", "poppy"),
    Pair("Porn Parody", "porn-parody"),
    Pair("Princess Bubblegum", "princess-bubblegum"),
    Pair("Princess Daisy", "princess-daisy"),
    Pair("Princess Peach", "princess-peach"),
    Pair("Prison School Hentai", "prison-school-hentai"),
    Pair("Priyanka Hentai", "priyanka-hentai"),
    Pair("Promare", "promare"),
    Pair("Purah Hentai", "purah-hentai"),
    Pair("Rainbow Mika", "rainbow-mika"),
    Pair("Rainbow Six Siege Porn", "rainbow-six-siege-porn"),
    Pair("Ranma Porn", "ranma-porn-comic"),
    Pair("Ratchet and Clank Porn", "ratchet-and-clank-porn"),
    Pair("Raven", "raven"),
    Pair("Raven xxx", "raven-hentaaii"),
    Pair("Razter", "razter"),
    Pair("Rebecca Cyberpunk Porn", "rebecca-cyberpunk-p0rn"),
    Pair("Rei Hentai", "rei-hentai"),
    Pair("RelatedGuy", "relatedguy-porn"),
    Pair("Rem Hentai", "rem-hentai"),
    Pair("Renamon", "renamon"),
    Pair("Resident Evil", "resident-evil-porn"),
    Pair("Rezero Hentai", "rezero-hentai"),
    Pair("Rick and Morty Porn Comics", "rick_and-morty-porn-comics-xxx"),
    Pair("Riukykappa", "riukykappa"),
    Pair("Riven", "riven"),
    Pair("Rivet Hentai", "rivet-hentai"),
    Pair("road to el dorado", "road-to-el-dorado"),
    Pair("Rosalina Hentai", "rosalina-hentai"),
    Pair("Rouge", "rouge"),
    Pair("Roumgu", "roumgu-xxx"),
    Pair("Rudolph", "rudolph"),
    Pair("Rumi Usagiyama Hentai", "rumi-usagiyama-hentai"),
    Pair("Sailor Moon Hentai", "sailor-moon-hentai"),
    Pair("Sakura Hentai", "sakura_h3ntai"),
    Pair("Sally", "sally"),
    Pair("Samantha Manson", "samantha-manson"),
    Pair("Samsung Sam Hentai", "samsung-sam-hentai"),
    Pair("Samus Hentai", "samus-hentai"),
    Pair("Sandy", "sandy"),
    Pair("Sarada Hentai", "sarada-hentai"),
    Pair("Scooby Doo Hentai", "scooby-doo-hentai"),
    Pair("Seiko Hentai", "seiko-hentai"),
    Pair("Seraphine", "seraphine"),
    Pair("Sex Toys", "sex-toys"),
    Pair("Shadbase", "shadbase-comics"),
    Pair("Shantae", "shantae-hentai"),
    Pair("She-Hulk", "she-hulk-porn"),
    Pair("She-Ra and the Princesses of Power Porn", "she-ra-and-the-princesses-of-power-porn"),
    Pair("Shego", "shego"),
    Pair("shin-chan", "shin-chan"),
    Pair("Sidney", "sidney"),
    Pair("Sillygirl", "sillygirl"),
    Pair("Six", "six"),
    Pair("Skullgirls", "skullgirls"),
    Pair("Small Tits", "small-tits"),
    Pair("Smash Bros", "smash-bros"),
    Pair("Sonic", "sonic"),
    Pair("Soraka", "soraka"),
    Pair("Soraka Hentai", "soraka-hentai"),
    Pair("Soul Knight", "soul-knight"),
    Pair("South Park", "south-park"),
    Pair("Spectra", "spectra"),
    Pair("spidergirl", "spidergirl-xxx"),
    Pair("Spiderman Porn Comics", "porn-comics-xxx-spiderman1"),
    Pair("Spinel", "spinel"),
    Pair("Splatoon Porn Comics", "splaton-porn-comic"),
    Pair("Spongebob Porn Comics", "spongebob-porn-comics"),
    Pair("Spy x Family Porn", "p0rn-spy-x-family"),
    Pair("Squirrel Girl Porn", "squirrel-girl-porn"),
    Pair("Star Butterfly Porn", "star-butterfly-porn"),
    Pair("Star Trek", "star-trek"),
    Pair("Star vs The Forces of Evil", "porn-comic-star-vs-the-forces-of-evil"),
    Pair("Star Wars", "star-wars"),
    Pair("Starfire", "starfire"),
    Pair("Steven Universe Porn Comics", "steven-universe-porn_comics1"),
    Pair("StormFedeR", "stormfeder-porn"),
    Pair("Street Fighter Porn", "street-fighter-porn-comix1"),
    Pair("Strong Bana", "strong-bana"),
    Pair("StrongBana", "strongbana-porn"),
    Pair("Suguha Hentai", "suguha-hentai"),
    Pair("Summer Hentai", "summer-hentai"),
    Pair("Super Melons", "super-melons"),
    Pair("Supergirl", "supergirl"),
    Pair("Superman", "superman-x"),
    Pair("Taboolicious", "taboolicious"),
    Pair("Taimanin Asagi", "taimanin-asagi"),
    Pair("Tatsumaki Hentai", "tatsumaki-hentai-one-punch-mam"),
    Pair("Tawna", "tawna"),
    Pair("Teacher", "teacher"),
    Pair("Teen", "teen"),
    Pair("Teenage Mutant Ninja Turtles Porn Comics", "teenage-mutant-ninja-turtles-porn-comics"),
    Pair("Teens", "teens"),
    Pair("Tenn", "tenn"),
    Pair("Tentacles", "tentacles"),
    Pair("Tenten Hentai", "tenten-hentai"),
    Pair("the addams family", "the-addams-family"),
    Pair("The Amazing Digital Circus", "the-amazing-digital-circus"),
    Pair("The Amazing world of Gumball Porn Comics", "amazing-world-of-gumball-porn-comixs"),
    Pair("The Arthman", "tthe-arthman"),
    Pair("the elder scrolls", "the-elder-scrolls"),
    Pair("The Fairly OddParents Porn", "porn-comics-the-fairly-oddparents-xx"),
    Pair("The Grim Adventures of Billy & Mandy Porn", "the-grim-adventures-of-billy-mandy-porn"),
    Pair("The grim adventures of Billy and Mandy", "the-grim-adventures-of-billy-and-mandy"),
    Pair("The Idolmaster", "the-idolmaster"),
    Pair("The Incredibles Porn", "the-incredibles-porn_comics"),
    Pair("The Jetsons", "the-jetsons"),
    Pair("The Last Airbender", "the-last-airbender"),
    Pair("The Last of Us", "the-last-of-us"),
    Pair("The Legend of Zelda Hentai", "the-legend-of-zelda-p"),
    Pair("The Loud House", "porn-comic-the-loud-house-sex"),
    Pair("The Owl House", "porn-comics-the-owl-house"),
    Pair("the powerpuff girls", "the-powerpuff-girls"),
    Pair("The proud family", "the-proud-family"),
    Pair("The Ring", "the-ring"),
    Pair("the seven deadly sins", "the-seven-deadly-sins"),
    Pair("The Summoning Porn", "the-summoning-porn"),
    Pair("The Sword In The Stone Porn Comics", "the-sword-in-the-stone-porn-comics"),
    Pair("The Walking Dead", "the-walking-dead"),
    Pair("The Witcher", "the-witcher"),
    Pair("Thicc", "thicc-xxx"),
    Pair("Three Houses", "three-houses"),
    Pair("Tifa Hentai", "tifa-hentai"),
    Pair("To Love-Ru Hentai", "to-love-ru-hentai"),
    Pair("Tomb Raider", "tomb-raider"),
    Pair("Tomgirl", "tomgirl"),
    Pair("Toph Hentai", "toph-hentai"),
    Pair("Total Drama", "total-drama-porn-comic"),
    Pair("Totally Spies", "porn-comics-totally-spies"),
    Pair("Touhou Project Hentai", "touhou-project-hentaix"),
    Pair("Tracy Scops", "tracy-scops"),
    Pair("Transformers Porn", "transformers-porn"),
    Pair("Tricia Hentai", "tricia-hentai"),
    Pair("Tsunade Hentai", "tsunade_hentai"),
    Pair("Tsuyu Asui Hentai", "tsuyu-asui-hentai"),
    Pair("Umbreon", "umbreon"),
    Pair("Uncensored", "uncensored"),
    Pair("Undertale", "undertale"),
    Pair("Undyne", "undyne"),
    Pair("Uraraka Hentai", "uraraka-hentai-xxx"),
    Pair("Urbosa", "urbosa"),
    Pair("Vados Hentai", "vados-hentai"),
    Pair("Vanilla", "vanilla"),
    Pair("Velma Hentai", "velma-hentai"),
    Pair("VerComicsPorno", "vercomicsporno"),
    Pair("Vicky", "vicky"),
    Pair("Videl Hentai", "videl-hentai1"),
    Pair("violet parr", "violet-parr"),
    Pair("Wakfu Porn", "wakfu-porn"),
    Pair("Wander Over Yonder", "wander-over-yonder"),
    Pair("Warcraft", "warcraft"),
    Pair("Warhammer porn", "warhammer-porn"),
    Pair("Wendy", "wendy"),
    Pair("Widowmaker", "widowmaker"),
    Pair("Willow", "willow"),
    Pair("Wonder Woman", "xxx-wonder-woman"),
    Pair("World of Warcraft", "world-of-warcraft"),
    Pair("WoW", "wow"),
    Pair("x-men", "x-men"),
    Pair("Xayah", "xayah"),
    Pair("Xenoblade Chronicles 2 Hentai", "xenoblade-chronicles-2-hentaix"),
    Pair("Xierra099", "xierra099"),
    Pair("Y3DF", "y3df"),
    Pair("Yamato Hentai", "yamato-hentai"),
    Pair("Yu Takeyama Hentai", "yu-takeyama-hentai"),
    Pair("Yu-Gi-Oh Hentai", "yu-gi-oh-entai"),
    Pair("Yuri", "yuri-hentai"),
    Pair("Zac", "zac"),
    Pair("Zelda Hentai", "zelda-hentai"),
    Pair("Zenless Zone Zero porn", "zenless-zone-zero-porn"),
    Pair("Zoe", "zoe"),
    Pair("Zootopia", "zootopia"),
)
