package eu.kanade.tachiyomi.extension.zh.mh160

import eu.kanade.tachiyomi.source.model.Filter

class CategoryFilter :
    Filter.Select<String>(
        "分类",
        CATEGORY_OPTIONS.map { it.first }.toTypedArray(),
    ) {
    val selectedSlug: String? get() = CATEGORY_OPTIONS[state].second
}

// Browse categories for the mobile site: Pair<label, path slug under /kanmanhua/>.
// The site only supports browsing one category at a time, so they are flattened into one selector.
private val CATEGORY_OPTIONS: List<Pair<String, String?>> = listOf(
    "全部分类" to null,
    "连载中" to "lianzai",
    "完结" to "wanjie",
    "日韩" to "zaixian_rhmh",
    "内地" to "zaixian_dlmh",
    "港台" to "zaixian_gtmh",
    "欧美" to "zaixian_ommh",
    "其他" to "zaixian_qita",
    "少年" to "shaonianqu",
    "少女" to "shaonvqu",
    "青年" to "qingnian",
    "少儿" to "shaoer",
    "热血" to "rexue",
    "格斗" to "gedou",
    "科幻" to "kehuan",
    "竞技" to "jingji",
    "搞笑" to "gaoxiao",
    "推理" to "tuili",
    "恐怖" to "kongbu",
    "耽美" to "danmei",
    "恋爱" to "lianai",
    "生活" to "shenghuo",
    "战争" to "zhanzheng",
    "故事" to "gushi",
    "冒险" to "maoxian",
    "魔幻" to "mohuan",
    "玄幻" to "xuanhuan",
    "校园" to "xiaoyuan",
    "悬疑" to "xuanyi",
    "萌系" to "mengxi",
    "穿越" to "chuanyue",
    "后宫" to "hougong",
    "都市" to "dushi",
    "武侠" to "wuxia",
    "历史" to "lishi",
    "同人" to "tongren",
    "励志" to "lizhi",
    "百合" to "baihe",
    "治愈" to "zhiyu",
    "机甲" to "jijia",
    "纯爱" to "chunai",
    "美食" to "meishi",
    "血腥" to "xuexing",
    "僵尸" to "jiangshi",
    "恶搞" to "egao",
    "虐心" to "nuexin",
    "动作" to "dongzuo",
    "惊险" to "jingxian",
    "唯美" to "weimei",
    "震撼" to "zhenhan",
    "复仇" to "fuchou",
    "侦探" to "zhentan",
    "脑洞" to "naodong",
    "奇幻" to "qihuan",
    "宫斗" to "gongdou",
    "爆笑" to "baoxiao",
    "运动" to "yundong",
    "青春" to "qingchun",
    "灵异" to "lingyi",
    "古风" to "gufeng",
    "权谋" to "quanmou",
    "节操" to "jiecao",
    "明星" to "mingxing",
    "暗黑" to "anhei",
    "社会" to "shehui",
    "浪漫" to "langman",
    "仙侠" to "xianxia",
    "伪娘" to "weiniang",
)
