# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: https://github.com/mihonapp/tachiyomix/blob/9367797/INDEX.md
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'index.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bindex.proto\"\x9d\x01\n\x05Index\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x17\n\nbadgeLabel\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x12\n\nsigningKey\x18\x03 \x01(\t\x12\x1e\n\x07\x63ontact\x18\x04 \x01(\x0b\x32\x08.ContactH\x01\x88\x01\x01\x12\x1e\n\nextensions\x18\x05 \x03(\x0b\x32\n.ExtensionB\r\n\x0b_badgeLabelB\n\n\x08_contact\"M\n\x07\x43ontact\x12\x14\n\x07website\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x14\n\x07\x64iscord\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\n\n\x08_websiteB\n\n\x08_discord\"\xa7\x01\n\tExtension\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0bpackageName\x18\x02 \x01(\t\x12\x1d\n\tresources\x18\x03 \x01(\x0b\x32\n.Resources\x12\x14\n\x0c\x65xtensionLib\x18\x04 \x01(\t\x12\x13\n\x0bversionCode\x18\x05 \x01(\x05\x12\x13\n\x0bversionName\x18\x06 \x01(\t\x12\x18\n\x07sources\x18\x07 \x03(\x0b\x32\x07.Source\",\n\tResources\x12\x0e\n\x06\x61pkUrl\x18\x01 \x01(\t\x12\x0f\n\x07iconUrl\x18\x02 \x01(\t\"\xa2\x01\n\x06Source\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08language\x18\x03 \x01(\t\x12\x0f\n\x07homeUrl\x18\x04 \x01(\t\x12\x12\n\nmirrorUrls\x18\x05 \x03(\t\x12%\n\rcontentRating\x18\x06 \x01(\x0e\x32\x0e.ContentRating\x12\x14\n\x07message\x18\x07 \x01(\tH\x00\x88\x01\x01\x42\n\n\x08_message*\x84\x01\n\rContentRating\x12\x17\n\x13\x43ONTENT_RATING_SAFE\x10\x00\x12\x1d\n\x19\x43ONTENT_RATING_SUGGESTIVE\x10\x01\x12\x1a\n\x16\x43ONTENT_RATING_EROTICA\x10\x02\x12\x1f\n\x1b\x43ONTENT_RATING_PORNOGRAPHIC\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'index_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONTENTRATING']._serialized_start=636
  _globals['_CONTENTRATING']._serialized_end=768
  _globals['_INDEX']._serialized_start=16
  _globals['_INDEX']._serialized_end=173
  _globals['_CONTACT']._serialized_start=175
  _globals['_CONTACT']._serialized_end=252
  _globals['_EXTENSION']._serialized_start=255
  _globals['_EXTENSION']._serialized_end=422
  _globals['_RESOURCES']._serialized_start=424
  _globals['_RESOURCES']._serialized_end=468
  _globals['_SOURCE']._serialized_start=471
  _globals['_SOURCE']._serialized_end=633
# @@protoc_insertion_point(module_scope)
