package eu.kanade.tachiyomi.extension.es.leercapitulo

import eu.kanade.tachiyomi.source.model.Filter

class GenreFilter :
    UriPartFilter(
        "Género",
        arrayOf(
            Pair("<Seleccionar>", ""),
            Pair("Action", "action"),
            Pair("Adventure", "adventure"),
            Pair("Boys' Love", "boys-love"),
            Pair("Comedy", "comedy"),
            Pair("Crime", "crime"),
            Pair("Drama", "drama"),
            Pair("Fantasy", "fantasy"),
            Pair("Girls' Love", "girls-love"),
            Pair("Historical", "historical"),
            Pair("Horror", "horror"),
            Pair("Isekai", "isekai"),
            Pair("Magical Girls", "magical-girls"),
            Pair("Mecha", "mecha"),
            Pair("Medical", "medical"),
            Pair("Mystery", "mystery"),
            Pair("Philosophical", "philosophical"),
            Pair("Psychological", "psychological"),
            Pair("Romance", "romance"),
            Pair("Sci-Fi", "sci-fi"),
            Pair("Slice of Life", "slice-of-life"),
            Pair("Sports", "sports"),
            Pair("Superhero", "superhero"),
            Pair("Thriller", "thriller"),
            Pair("Tragedy", "tragedy"),
            Pair("Wuxia", "wuxia"),
            Pair("Seinen", "seinen"),
            Pair("Shounen", "shounen"),
            Pair("Ecchi", "ecchi"),
            Pair("Shoujo", "shoujo"),
            Pair("Mature", "mature"),
            Pair("Adult", "adult"),
            Pair("Shounen Ai", "shounen-ai"),
            Pair("Gender Bender", "gender-bender"),
            Pair("Shotacon", "shotacon"),
            Pair("Josei", "josei"),
            Pair("Yaoi", "yaoi"),
            Pair("Smut", "smut"),
            Pair("Ciberpunk", "ciberpunk"),
            Pair("Vida Escolar", "vida-escolar"),
            Pair("Realidad Virtual", "realidad-virtual"),
            Pair("Fantasia", "fantasia"),
            Pair("Comedia", "comedia"),
            Pair("Recuentos de la vida", "recuentos-de-la-vida"),
            Pair("Yuri", "yuri"),
            Pair("Sobrenatural", "sobrenatural"),
            Pair("Magia", "magia"),
            Pair("Tragedia", "tragedia"),
            Pair("Historia", "historia"),
            Pair("Guerra", "guerra"),
            Pair("Misterio", "misterio"),
            Pair("Policiaco", "policiaco"),
            Pair("Artes Marciales", "artes-marciales"),
            Pair("Gore", "gore"),
            Pair("Superpoderes", "superpoderes"),
            Pair("Familia", "familia"),
            Pair("Aventura", "aventura"),
            Pair("Supervivencia", "supervivencia"),
            Pair("Demonios", "demonios"),
            Pair("Realidad", "realidad"),
            Pair("Telenovela", "telenovela"),
            Pair("Crimen", "crimen"),
            Pair("Parodia", "parodia"),
            Pair("Deporte", "deporte"),
            Pair("Traps", "traps"),
            Pair("Militar", "militar"),
            Pair("Musica", "musica"),
            Pair("Vampiros", "vampiros"),
            Pair("Extranjero", "extranjero"),
            Pair("Oeste", "oeste"),
            Pair("Shoujo Ai", "shoujo-ai"),
            Pair("Doujinshi", "doujinshi"),
            Pair("Psicológico", "psicologico"),
            Pair("Acción", "accion"),
            Pair("Ciencia Ficción", "ciencia-ficcion"),
            Pair("Género Bender", "genero-bender"),
            Pair("Apocalíptico", "apocaliptico"),
            Pair("Reencarnación", "reencarnacion"),
            Pair("Niños", "ninos"),
            Pair("Lolicon", "lolicon"),
            Pair("Hentai", "hentai"),
            Pair("Animación", "animacion"),
        ),
    )

class ThemeFilter :
    UriPartFilter(
        "Temática",
        arrayOf(
            Pair("<Seleccionar>", ""),
            Pair("Aliens", "aliens"),
            Pair("Animals", "animals"),
            Pair("Cooking", "cooking"),
            Pair("Cross-dressing", "cross-dressing"),
            Pair("Delinquents", "delinquents"),
            Pair("Demons", "demons"),
            Pair("Genderswap", "genderswap"),
            Pair("Ghosts", "ghosts"),
            Pair("Gyaru", "gyaru"),
            Pair("Harem", "harem"),
            Pair("Incest", "incest"),
            Pair("Loli", "loli"),
            Pair("Mafia", "mafia"),
            Pair("Magic", "magic"),
            Pair("Martial Arts", "martial-arts"),
            Pair("Military", "military"),
            Pair("Monster Girls", "monster-girls"),
            Pair("Monsters", "monsters"),
            Pair("Music", "music"),
            Pair("Ninja", "ninja"),
            Pair("Office Workers", "office-workers"),
            Pair("Police", "police"),
            Pair("Post-Apocalyptic", "post-apocalyptic"),
            Pair("Reincarnation", "reincarnation"),
            Pair("Reverse Harem", "reverse-harem"),
            Pair("Samurai", "samurai"),
            Pair("School Life", "school-life"),
            Pair("Shota", "shota"),
            Pair("Supernatural", "supernatural"),
            Pair("Survival", "survival"),
            Pair("Time Travel", "time-travel"),
            Pair("Traditional Games", "traditional-games"),
            Pair("Vampires", "vampires"),
            Pair("Video Games", "video-games"),
            Pair("Villainess", "villainess"),
            Pair("Virtual Reality", "virtual-reality"),
            Pair("Zombies", "zombies"),
        ),
    )

class TypeFilter :
    UriPartFilter(
        "Tipo",
        arrayOf(
            Pair("<Seleccionar>", ""),
            Pair("Manga", "manga"),
            Pair("Manhwa", "manhwa"),
            Pair("Manhua", "manhua"),
            Pair("Comic", "comic"),
        ),
    )

class StatusFilter :
    UriPartFilter(
        "Estado",
        arrayOf(
            Pair("<Seleccionar>", ""),
            Pair("Completed", "completed"),
            Pair("Ongoing", "ongoing"),
            Pair("Paused", "paused"),
            Pair("Cancelled", "cancelled"),
        ),
    )

class SortFilter :
    UriPartFilter(
        "Orden",
        arrayOf(
            Pair("A - Z", "az"),
            Pair("Z - A", "za"),
        ),
    )

open class UriPartFilter(
    displayName: String,
    private val vals: Array<Pair<String, String>>,
) : Filter.Select<String>(
    displayName,
    vals.map { it.first }.toTypedArray(),
) {
    fun toUriPart() = vals[state].second
}
