package eu.kanade.tachiyomi.extension.de.mangatube.util

enum class Genre(val id: Int, val displayName: String) {
    KOMA_4(50, "4-Koma"),
    ABENTEUER(1, "Abenteuer"),
    ACTION(2, "Action"),
    ALLTAGSLEBEN(12, "Alltagsleben"),
    AUTOS(28, "Autos"),
    BOYS_LOVE(46, "Boys Love"),
    DAEMONEN(29, "Dämonen"),
    DELINQUENT(59, "Delinquent"),
    DOUJINSHI(30, "Doujinshi"),
    DRAMA(3, "Drama"),
    ECCHI(7, "Ecchi"),
    EROTIK(44, "Erotik"),
    FANTASY(13, "Fantasy"),
    GEISTER(55, "Geister"),
    GENDER_BENDER(32, "Gender Bender"),
    GIRLS_LOVE(47, "Girls Love"),
    HAREM(23, "Harem"),
    HENTAI(33, "Hentai"),
    HISTORISCH(34, "Historisch"),
    HORROR(35, "Horror"),
    ISEKAI(53, "Isekai"),
    JOSEI(36, "Josei"),
    KAMPFSPORT(25, "Kampfsport"),
    KARTENSPIEL(26, "Kartenspiel"),
    KINDER(37, "Kinder"),
    KOCHEN(51, "Kochen"),
    KOMOEDIE(5, "Komödie"),
    KRIMI(56, "Krimi"),
    MAGICAL_GIRL(54, "Magical Girl"),
    MAGIE(24, "Magie"),
    MECHA(11, "Mecha"),
    MILITAER(38, "Militär"),
    MONSTER(49, "Monster"),
    MUSIK(39, "Musik"),
    MYSTERY(43, "Mystery"),
    ONESHOTS(58, "OneShots"),
    PSYCHODRAMA(52, "Psychodrama"),
    ROMANZE(6, "Romanze"),
    SCHULE(27, "Schule"),
    SCI_FI(10, "Sci-Fi"),
    SEINEN(48, "Seinen"),
    SHOUJO(42, "Shoujo"),
    SHOUNEN(4, "Shounen"),
    SPLATTER(57, "Splatter"),
    SPORT(14, "Sport"),
    SUPERKRAEFTE(16, "Superkräfte"),
    THRILLER(40, "Thriller"),
    VAMPIRE(15, "Vampire"),
    VIDEOSPIEL(9, "Videospiel"),
    WEIBLICHE_PROTAGONISTIN(60, "weibliche Protagonistin"),
    YAOI(41, "Yaoi"),
    YURI(45, "Yuri"),
    ;

    companion object {
        fun fromId(id: Int): Genre? = values().find { it.id == id }
    }
}
