package eu.kanade.tachiyomi.extension.en.plutoscans

import eu.kanade.tachiyomi.multisrc.madara.Madara
import java.text.SimpleDateFormat
import java.util.Locale

class PlutoScans : Madara(
    "Pluto Scans",
    "https://plutoscans.com",
    "en",
    dateFormat = SimpleDateFormat("dd/MM/yyyy", Locale.ROOT),
) {
    override val useLoadMoreRequest = LoadMoreStrategy.Always
    override val useNewChapterEndpoint = true

    override val fetchGenres = false
    override var genresList = listOf(
        Genre("Academy", "academy"),
        Genre("Action", "action"),
        Genre("Adult", "adult"),
        Genre("Adventure", "adventure"),
        Genre("Animals", "animals"),
        Genre("Aventure", "aventure"),
        Genre("Back to the past", "back-to-the-past"),
        Genre("Beasts", "beasts"),
        Genre("Betrayal", "betrayal"),
        Genre("Business", "business"),
        Genre("Cartoon", "cartoon"),
        Genre("Cheat Systems", "cheat-systems"),
        Genre("Chinese", "chinese"),
        Genre("Combat", "combat"),
        Genre("Comedy", "comedy"),
        Genre("Comic", "comic"),
        Genre("Completed", "completed"),
        Genre("Cooking", "cooking"),
        Genre("Crime", "crime"),
        Genre("Cultivation", "cultivation"),
        Genre("Demons", "demons"),
        Genre("Doujinshi", "doujinshi"),
        Genre("Drama", "drama"),
        Genre("Dungeons", "dungeons"),
        Genre("Ecchi", "ecchi"),
        Genre("Fantasy", "fantasy"),
        Genre("Fighting", "fighting"),
        Genre("Full colour", "full-colour"),
        Genre("Funny", "fun"),
        Genre("Game", "game"),
        Genre("Gender Bender", "gender-bender"),
        Genre("Genius MC", "genius-mc"),
        Genre("Girls' Love", "girls-love"),
        Genre("GL", "gl"),
        Genre("Harem", "harem"),
        Genre("Historical", "historical"),
        Genre("Horror", "horror"),
        Genre("Immortality", "immortality"),
        Genre("Immortals", "immortals"),
        Genre("Isekai", "isekai"),
        Genre("Josei", "josei"),
        Genre("Journey", "life"),
        Genre("Long Strip", "long-strip"),
        Genre("Magic", "magic"),
        Genre("Manga", "manga"),
        Genre("Manhua", "manhua"),
        Genre("Manhwa", "manhwa"),
        Genre("Martial Arts", "martial-arts"),
        Genre("Mature", "mature"),
        Genre("Mecha", "mecha"),
        Genre("Medical", "medical"),
        Genre("Money Making", "money-making"),
        Genre("Monsters", "monsters"),
        Genre("Murim", "murim"),
        Genre("Mystery", "mystery"),
        Genre("Myths and Legends", "myths-and-legends"),
        Genre("Overpowered", "overpowered"),
        Genre("Post-Apocalyptic", "post-apocalyptic"),
        Genre("Psychological", "psychological"),
        Genre("Rags To Riches", "rags-to-richess"),
        Genre("Rebirth", "rebirth"),
        Genre("Regression", "regression"),
        Genre("Reincarnation", "reincarnation"),
        Genre("Resurrection", "resurrection"),
        Genre("Revenge", "revenge"),
        Genre("Reverse Harem", "reverse-harem"),
        Genre("Romance", "romance"),
        Genre("School Life", "school-life"),
        Genre("Sci-fi", "sci-fi"),
        Genre("Seinen", "seinen"),
        Genre("Shoujo", "shoujo"),
        Genre("Shounen", "shounen"),
        Genre("Shounen Ai", "shounen-ai"),
        Genre("Slice of Life", "slice-of-life"),
        Genre("Sports", "sports"),
        Genre("Sugary", "sugary"),
        Genre("Summoning", "summoning"),
        Genre("Super Power", "super-power"),
        Genre("Super powers", "super-powers"),
        Genre("Supernatural", "supernatural"),
        Genre("Survival", "survival"),
        Genre("Sword Wives", "sword-wives"),
        Genre("System", "system"),
        Genre("Thriller", "thriller"),
        Genre("Time Travel", "time-travel"),
        Genre("Tragedy", "tragedy"),
        Genre("Transmigration", "transmigration"),
        Genre("Traverse", "traverse"),
        Genre("Urban Cultivation", "urban-cultivation"),
        Genre("Victorian era", "victorian-era"),
        Genre("Video Games", "video-games"),
        Genre("Villainess", "villainess"),
        Genre("Webtoon", "webtoon"),
        Genre("Webtoons", "webtoons"),
        Genre("Wuxia", "wuxia"),
        Genre("Xianxia", "xianxia"),
        Genre("Zombie", "zombie"),
    )
}
