package eu.kanade.tachiyomi.extension.all.batotov4

import eu.kanade.tachiyomi.source.model.Filter
import eu.kanade.tachiyomi.source.model.FilterList

class CheckboxFilterOption(name: String, val value: String) : Filter.CheckBox(name)
class TriStateFilterOption(name: String, val value: String) : Filter.TriState(name)

abstract class SelectFilter(
    name: String,
    private val options: List<Pair<String, String>>,
    default: Int = 0,
) : Filter.Select<String>(name, options.map { it.first }.toTypedArray(), default) {
    val selected: String
        get() = options[state].second
}

abstract class CheckboxGroupFilter(
    name: String,
    options: List<Pair<String, String>>,
) : Filter.Group<CheckboxFilterOption>(name, options.map { CheckboxFilterOption(it.first, it.second) }) {
    val selected: List<String>
        get() = state.filter { it.state }.map { it.value }
}

abstract class TriStateGroupFilter(
    name: String,
    options: List<Pair<String, String>>,
) : Filter.Group<TriStateFilterOption>(name, options.map { TriStateFilterOption(it.first, it.second) }) {
    val included: List<String>
        get() = state.filter { it.isIncluded() }.map { it.value }

    val excluded: List<String>
        get() = state.filter { it.isExcluded() }.map { it.value }
}

class LetterFilter : SelectFilter(
    name = "Letter matching mode (Slow)",
    options = listOf(
        "Disabled" to "disabled",
        "Enabled" to "enabled",
    ),
)

class SortFilter(
    defaultIndex: Int = LATEST_INDEX,
) : SelectFilter(
    name = "Order by",
    options = sortOptions,
    default = defaultIndex,
) {
    companion object {
        const val POPULAR_INDEX = 0 // field_score
        const val LATEST_INDEX = 5 // field_upload
        val POPULAR = FilterList(SortFilter(POPULAR_INDEX))
        val LATEST = FilterList(SortFilter(LATEST_INDEX))
    }
}

private val sortOptions = listOf(
    "Rating Score" to "field_score",
    "Most Follows" to "field_follow",
    "Most Reviews" to "field_review",
    "Most Comments" to "field_comment",
    "Most Chapters" to "field_chapter",
    "Latest Upload" to "field_upload",
    "Recently Created" to "field_public",
    "Name A-Z" to "field_name",
    "Most Views (Total)" to "views_d000",
    "Most Views (360 days)" to "views_d360",
    "Most Views (180 days)" to "views_d180",
    "Most Views (90 days)" to "views_d090",
    "Most Views (30 days)" to "views_d030",
    "Most Views (7 days)" to "views_d007",
    "Most Views (24 hours)" to "views_h024",
    "Most Views (12 hours)" to "views_h012",
    "Most Views (6 hours)" to "views_h006",
    "Most Views (1 hour)" to "views_h001",
    "User Status (Plan to Read)" to "status_wish",
    "User Status (Reading)" to "status_doing",
    "User Status (Completed)" to "status_completed",
    "User Status (On Hold)" to "status_on_hold",
    "User Status (Dropped)" to "status_dropped",
    "User Status (Re-reading)" to "status_repeat",
    "Emotions (Awesome)" to "emotion_upvote",
    "Emotions (Funny)" to "emotion_funny",
    "Emotions (Love)" to "emotion_love",
    "Emotions (Scared)" to "emotion_surprise",
    "Emotions (Angry)" to "emotion_angry",
    "Emotions (Sad)" to "emotion_sad",
)

class PersonalListFilter : SelectFilter(
    name = "Personal list",
    options = listOf(
        "None" to "",
        "My History" to "history",
        "My Updates" to "updates",
    ),
)

class UserComicFilter : SelectFilter(
    name = "User comic list",
    options = listOf(
        "None" to "",
        "Comics: I Uploaded" to "editor=upload",
        "Comics: I Created" to "editor=create",
        "Comics: I Modified" to "editor=modify",
        "Comics: Whitelisted me" to "editor=whitelist",
        "Comics: Blacklisted me" to "editor=blacklist",
        "Comics: Any I participated" to "",
        "Comics: Draft Status" to "dbStatus=draft",
        "Comics: Hidden Status" to "dbStatus=hidden",
        // Below are for "I uploaded + Ongoing + Normal + Not updated in X days" shortcuts
        "Uploaded+Ongoing: Not updated in 7+ days" to "editor=upload&siteStatus=ongoing&dbStatus=normal&mod_lock=n&mod_hide=n&notUpdatedDays=7",
        "Uploaded+Ongoing: Not updated in 30+ days" to "editor=upload&siteStatus=ongoing&dbStatus=normal&mod_lock=n&mod_hide=n&notUpdatedDays=30",
        "Uploaded+Ongoing: Not updated in 60+ days" to "editor=upload&siteStatus=ongoing&dbStatus=normal&mod_lock=n&mod_hide=n&notUpdatedDays=60",
        "Uploaded+Ongoing: Not updated in 90+ days" to "editor=upload&siteStatus=ongoing&dbStatus=normal&mod_lock=n&mod_hide=n&notUpdatedDays=90",
        "Uploaded+Ongoing: Not updated in 180+ days" to "editor=upload&siteStatus=ongoing&dbStatus=normal&mod_lock=n&mod_hide=n&notUpdatedDays=180",
        "Uploaded+Ongoing: Not updated in 360+ days" to "editor=upload&siteStatus=ongoing&dbStatus=normal&mod_lock=n&mod_hide=n&notUpdatedDays=360",
        "Uploaded+Ongoing: Not updated in 1000+ days" to "editor=upload&siteStatus=ongoing&dbStatus=normal&mod_lock=n&mod_hide=n&notUpdatedDays=1000",
    ),
)

class OriginalStatusFilter : SelectFilter(
    name = "Original Work Status",
    options = uploadStatus,
)

class UploadStatusFilter : SelectFilter(
    name = "Bato Upload Status",
    options = uploadStatus,
)

private val uploadStatus = listOf(
    "All" to "",
    "Pending" to "pending",
    "Ongoing" to "ongoing",
    "Completed" to "completed",
    "Hiatus" to "hiatus",
    "Cancelled" to "cancelled",
)

class ChapterCountFilter : SelectFilter(
    name = "Chapter Count",
    options = listOf(
        "Any" to "",
        "0" to "0",
        "1+" to "1",
        "10+" to "10",
        "20+" to "20",
        "30+" to "30",
        "40+" to "40",
        "50+" to "50",
        "60+" to "60",
        "70+" to "70",
        "80+" to "80",
        "90+" to "90",
        "100+" to "100",
        "200+" to "200",
        "300+" to "300",
        "1~9" to "1-9",
        "10~19" to "10-19",
        "20~29" to "20-29",
        "30~39" to "30-39",
        "40~49" to "40-49",
        "50~59" to "50-59",
        "60~69" to "60-69",
        "70~79" to "70-79",
        "80~89" to "80-89",
        "90~99" to "90-99",
        "100~199" to "100-199",
        "200~299" to "200-299",
    ),
)

class OriginalLanguageFilter : CheckboxGroupFilter(
    name = "Original Work Language",
    options = languages,
)

class TranslationLanguageFilter : CheckboxGroupFilter(
    name = "Translated Language",
    options = languages,
)

private val languages = listOf(
    "English" to "en",
    "Chinese" to "zh",
    "Japanese" to "ja",
    "Korean" to "ko",
    "Afrikaans" to "af",
    "Albanian" to "sq",
    "Amharic" to "am",
    "Arabic" to "ar",
    "Armenian" to "hy",
    "Azerbaijani" to "az",
    "Belarusian" to "be",
    "Bengali" to "bn",
    "Bosnian" to "bs",
    "Bulgarian" to "bg",
    "Burmese" to "my",
    "Cambodian" to "km",
    "Catalan" to "ca",
    "Cebuano" to "ceb",
    "Chinese (Cantonese)" to "zh_hk",
    "Chinese (Traditional)" to "zh_tw",
    "Croatian" to "hr",
    "Czech" to "cs",
    "Danish" to "da",
    "Dutch" to "nl",
    "Estonian" to "et",
    "Faroese" to "fo",
    "Filipino" to "fil",
    "Finnish" to "fi",
    "French" to "fr",
    "Georgian" to "ka",
    "German" to "de",
    "Greek" to "el",
    "Guarani" to "gn",
    "Gujarati" to "gu",
    "Haitian Creole" to "ht",
    "Hausa" to "ha",
    "Hebrew" to "he",
    "Hindi" to "hi",
    "Hungarian" to "hu",
    "Icelandic" to "is",
    "Igbo" to "ig",
    "Indonesian" to "id",
    "Irish" to "ga",
    "Italian" to "it",
    "Javanese" to "jv",
    "Kannada" to "kn",
    "Kazakh" to "kk",
    "Kurdish" to "ku",
    "Kyrgyz" to "ky",
    "Laothian" to "lo",
    "Latvian" to "lv",
    "Lithuanian" to "lt",
    "Luxembourgish" to "lb",
    "Macedonian" to "mk",
    "Malagasy" to "mg",
    "Malay" to "ms",
    "Malayalam" to "ml",
    "Maltese" to "mt",
    "Maori" to "mi",
    "Marathi" to "mr",
    "Moldavian" to "mo",
    "Mongolian" to "mn",
    "Nepali" to "ne",
    "Norwegian" to "no",
    "Nyanja" to "ny",
    "Pashto" to "ps",
    "Persian" to "fa",
    "Polish" to "pl",
    "Portuguese" to "pt",
    "Portuguese (Brazil)" to "pt_br",
    "Romanian" to "ro",
    "Romansh" to "rm",
    "Russian" to "ru",
    "Samoan" to "sm",
    "Serbian" to "sr",
    "Serbo-Croatian" to "sh",
    "Sesotho" to "st",
    "Shona" to "sn",
    "Sindhi" to "sd",
    "Sinhalese" to "si",
    "Slovak" to "sk",
    "Slovenian" to "sl",
    "Somali" to "so",
    "Spanish" to "es",
    "Spanish (Latin America)" to "es_419",
    "Swahili" to "sw",
    "Swedish" to "sv",
    "Tajik" to "tg",
    "Tamil" to "ta",
    "Telugu" to "te",
    "Thai" to "th",
    "Tigrinya" to "ti",
    "Tonga" to "to",
    "Turkish" to "tr",
    "Turkmen" to "tk",
    "Ukrainian" to "uk",
    "Urdu" to "ur",
    "Uzbek" to "uz",
    "Vietnamese" to "vi",
    "Yoruba" to "yo",
    "Zulu" to "zu",
    "Other" to "_t",
)

class GenreGroupFilter : TriStateGroupFilter(
    name = "Genres",
    options = genreOptions,
)

val genreOptions = listOf(
    "Artbook" to "artbook",
    "Cartoon" to "cartoon",
    "Comic" to "comic",
    "Doujinshi" to "doujinshi",
    "Imageset" to "imageset",
    "Manga" to "manga",
    "Manhua" to "manhua",
    "Manhwa" to "manhwa",
    "Webtoon" to "webtoon",
    "Western" to "western",
    "4-Koma" to "_4_koma",
    "Oneshot" to "oneshot",
    "Shoujo(G)" to "shoujo",
    "Shounen(B)" to "shounen",
    "Josei(W)" to "josei",
    "Seinen(M)" to "seinen",
    "Yuri(GL)" to "yuri",
    "Yaoi(BL)" to "yaoi",
    "Futa(WL)" to "futa", // May not exist?
    "Bara(ML)" to "bara",
    "Kodomo(Kid)" to "kodomo",
    "Silver & Golden" to "old_people",
    "Shoujo Ai" to "shoujo_ai",
    "Shounen Ai" to "shounen_ai",
    "Non-human" to "non_human",
    "Gore" to "gore",
    "Bloody" to "bloody",
    "Violence" to "violence",
    "Ecchi" to "ecchi",
    "Adult" to "adult",
    "Mature" to "mature",
    "Smut" to "smut",
    "Hentai" to "hentai",
    "Action" to "action",
    "Adaptation" to "adaptation",
    "Adventure" to "adventure",
    "Age Gap" to "age_gap",
    "Aliens" to "aliens",
    "Animals" to "animals",
    "Anthology" to "anthology",
    "Beasts" to "beasts",
    "Bodyswap" to "bodyswap",
    "Boys" to "boys",
    "cars" to "cars",
    "Cheating/Infidelity" to "cheating_infidelity",
    "Childhood Friends" to "childhood_friends",
    "College Life" to "college_life",
    "Comedy" to "comedy",
    "Contest Winning" to "contest_winning",
    "Cooking" to "cooking",
    "crime" to "crime",
    "Crossdressing" to "crossdressing",
    "Delinquents" to "delinquents",
    "Dementia" to "dementia",
    "Demons" to "demons",
    "Drama" to "drama",
    "Dungeons" to "dungeons",
    "Emperor's Daughter" to "emperor_daughte",
    "Fantasy" to "fantasy",
    "Fan-Colored" to "fan_colored",
    "Fetish" to "fetish",
    "Full Color" to "full_color",
    "Game" to "game",
    "Gender Bender" to "gender_bender",
    "Genderswap" to "genderswap",
    "Girls" to "girls",
    "Ghosts" to "ghosts",
    "Gyaru" to "gyaru",
    "Harem" to "harem",
    "Harlequin" to "harlequin",
    "Historical" to "historical",
    "Horror" to "horror",
    "Incest" to "incest",
    "Isekai" to "isekai",
    "Kids" to "kids",
    "Magic" to "magic",
    "Magical Girls" to "magical_girls",
    "Martial Arts" to "martial_arts",
    "Mecha" to "mecha",
    "Medical" to "medical",
    "Military" to "military",
    "Monster Girls" to "monster_girls",
    "Monsters" to "monsters",
    "Music" to "music",
    "Mystery" to "mystery",
    "Netori" to "netori",
    "Netorare/NTR" to "netorare",
    "Ninja" to "ninja",
    "Office Workers" to "office_workers",
    "Omegaverse" to "omegaverse",
    "parody" to "parody",
    "Philosophical" to "philosophical",
    "Police" to "police",
    "Post-Apocalyptic" to "post_apocalyptic",
    "Psychological" to "psychological",
    "Regression" to "regression",
    "Reincarnation" to "reincarnation",
    "Reverse Harem" to "reverse_harem",
    "Revenge" to "revenge",
    "Reverse Isekai" to "reverse_isekai",
    "Romance" to "romance",
    "Royal Family" to "royal_family",
    "Royalty" to "royalty",
    "Samurai" to "samurai",
    "School Life" to "school_life",
    "Sci-Fi" to "sci_fi",
    "Shota" to "shota",
    "Showbiz" to "showbiz",
    "Slice of Life" to "slice_of_life",
    "SM/BDSM/SUB-DOM" to "sm_bdsm",
    "Space" to "space",
    "Sports" to "sports",
    "Super Power" to "super_power",
    "Superhero" to "superhero",
    "Supernatural" to "supernatural",
    "Survival" to "survival",
    "Thriller" to "thriller",
    "Time Travel" to "time_travel",
    "Tower Climbing" to "tower_climbing",
    "Traditional Games" to "traditional_games",
    "Tragedy" to "tragedy",
    "Transmigration" to "transmigration",
    "Vampires" to "vampires",
    "Villainess" to "villainess",
    "Video Games" to "video_games",
    "Virtual Reality" to "virtual_reality",
    "Wuxia" to "wuxia",
    "Xianxia" to "xianxia",
    "Xuanhuan" to "xuanhuan",
    "Yakuzas" to "yakuzas",
    "Zombies" to "zombies",
    // Hidden Genres (Probably don't exist)
    "shotacon" to "shotacon",
    "Loli" to "loli",
    "lolicon" to "lolicon",
    "Award Winning" to "award_winning",
    "Youkai" to "youkai",
    "Uncategorized" to "uncategorized",
)
