package eu.kanade.tachiyomi.extension.vi.cmanga

import eu.kanade.tachiyomi.source.model.Filter
import eu.kanade.tachiyomi.source.model.FilterList

fun getFilters(): FilterList = FilterList(
    GenreFilter(getGenreList()),
    TeamFilter(),
    MinChapterFilter(),
    SortFilter(),
    StatusFilter(),
)

class Genre(name: String, val value: String) : Filter.CheckBox(name)

class GenreFilter(genres: List<Genre>) : Filter.Group<Genre>("Thể loại", genres) {
    fun selectedValues(): List<String> = state.filter { it.state }.map { it.value }
}

class TeamFilter : UriPartFilter("Nhóm dịch", TEAM_OPTIONS)

class MinChapterFilter : UriPartFilter("Số chapter tối thiểu", MIN_CHAPTER_OPTIONS)

class SortFilter : UriPartFilter("Sắp xếp theo", SORT_OPTIONS)

class StatusFilter : UriPartFilter("Tình trạng", STATUS_OPTIONS)

open class UriPartFilter(displayName: String, private val options: Array<Pair<String, String>>) : Filter.Select<String>(displayName, options.map { it.first }.toTypedArray()) {

    fun toUriPart(): String = options[state].second
}

private fun getGenreList() = listOf(
    Genre("romance", "romance"),
    Genre("comedy", "comedy"),
    Genre("action", "action"),
    Genre("manhua", "manhua"),
    Genre("truyện màu", "truyện màu"),
    Genre("fantasy", "fantasy"),
    Genre("drama", "drama"),
    Genre("manhwa", "manhwa"),
    Genre("ngôn tình", "ngôn tình"),
    Genre("slice of life", "slice of life"),
    Genre("school life", "school life"),
    Genre("adventure", "adventure"),
    Genre("supernatural", "supernatural"),
    Genre("manga", "manga"),
    Genre("shounen", "shounen"),
    Genre("xuyên không", "xuyên không"),
    Genre("hiện đại", "hiện đại"),
    Genre("shoujo", "shoujo"),
    Genre("mystery", "mystery"),
    Genre("huyền huyễn", "huyền huyễn"),
    Genre("webtoon", "webtoon"),
    Genre("cổ đại", "cổ đại"),
    Genre("seinen", "seinen"),
    Genre("hành động", "hành động"),
    Genre("psychological", "psychological"),
    Genre("horror", "horror"),
    Genre("harem", "harem"),
    Genre("hài hước", "hài hước"),
    Genre("oneshot", "oneshot"),
    Genre("ecchi", "ecchi"),
    Genre("chuyển sinh", "chuyển sinh"),
    Genre("tragedy", "tragedy"),
    Genre("tu tiên", "tu tiên"),
    Genre("martial arts", "martial arts"),
    Genre("historical", "historical"),
    Genre("web comic", "web comic"),
    Genre("đô thị", "đô thị"),
    Genre("sci-fi", "sci-fi"),
    Genre("hệ thống", "hệ thống"),
    Genre("âu cổ", "âu cổ"),
    Genre("adaptation", "adaptation"),
    Genre("trọng sinh", "trọng sinh"),
    Genre("lãng mạn", "lãng mạn"),
    Genre("nữ cường", "nữ cường"),
    Genre("girls' love", "girls' love"),
    Genre("doujinshi", "doujinshi"),
    Genre("magic", "magic"),
    Genre("isekai", "isekai"),
    Genre("full color", "full color"),
    Genre("cổ trang", "cổ trang"),
    Genre("đam mỹ", "đam mỹ"),
    Genre("phiêu lưu", "phiêu lưu"),
    Genre("tình cảm", "tình cảm"),
    Genre("kinh dị", "kinh dị"),
    Genre("kịch tính", "kịch tính"),
    Genre("tình yêu", "tình yêu"),
    Genre("tổng tài", "tổng tài"),
    Genre("học đường", "học đường"),
    Genre("sports", "sports"),
    Genre("comic", "comic"),
    Genre("mạt thế", "mạt thế"),
    Genre("one shot", "one shot"),
    Genre("monsters", "monsters"),
    Genre("truyện trung", "truyện trung"),
    Genre("gender bender", "gender bender"),
    Genre("boys' love", "boys' love"),
    Genre("josei", "josei"),
    Genre("truyện top", "truyện top"),
    Genre("ngọt sủng", "ngọt sủng"),
    Genre("siêu nhiên", "siêu nhiên"),
    Genre("vip", "vip"),
    Genre("truyện tranh", "truyện tranh"),
    Genre("gore", "gore"),
    Genre("báo thù", "báo thù"),
    Genre("mature", "mature"),
    Genre("anthology", "anthology"),
    Genre("demons", "demons"),
    Genre("girl's love", "girl's love"),
    Genre("yuri", "yuri"),
    Genre("reincarnation", "reincarnation"),
    Genre("sủng ngọt", "sủng ngọt"),
    Genre("long strip", "long strip"),
    Genre("hoàng gia", "hoàng gia"),
    Genre("xuyên sách", "xuyên sách"),
    Genre("monster girls", "monster girls"),
    Genre("animals", "animals"),
    Genre("thriller", "thriller"),
    Genre("đời thường", "đời thường"),
    Genre("trùng sinh", "trùng sinh"),
    Genre("award winning", "award winning"),
    Genre("office workers", "office workers"),
    Genre("xuyên không - hồi sinh", "xuyên không - hồi sinh"),
    Genre("survival", "survival"),
    Genre("bách hợp", "bách hợp"),
    Genre("crime", "crime"),
    Genre("hậu cung", "hậu cung"),
    Genre("bá đạo", "bá đạo"),
    Genre("võ thuật", "võ thuật"),
    Genre("dị giới", "dị giới"),
    Genre("delinquents", "delinquents"),
    Genre("crossdressing", "crossdressing"),
    Genre("truyện nhật (manga)", "truyện nhật (manga)"),
    Genre("bí ẩn", "bí ẩn"),
    Genre("military", "military"),
    Genre("cooking", "cooking"),
    Genre("giả tưởng", "giả tưởng"),
    Genre("huyễn huyền", "huyễn huyền"),
    Genre("shoujo ai", "shoujo ai"),
    Genre("dị năng", "dị năng"),
    Genre("genderswap", "genderswap"),
    Genre("gl", "gl"),
    Genre("chiếm hữu mạnh mẽ", "chiếm hữu mạnh mẽ"),
    Genre("tâm lý", "tâm lý"),
    Genre("ghosts", "ghosts"),
    Genre("viễn tưởng", "viễn tưởng"),
    Genre("cưới trước yêu sau", "cưới trước yêu sau"),
    Genre("video games", "video games"),
    Genre("4-koma", "4-koma"),
    Genre("15+", "15+"),
    Genre("truyện siêu hay", "truyện siêu hay"),
    Genre("philosophical", "philosophical"),
    Genre("thanh xuân vườn trường", "thanh xuân vườn trường"),
    Genre("girls love", "girls love"),
    Genre("time travel", "time travel"),
    Genre("shounen ai", "shounen ai"),
    Genre("gyaru", "gyaru"),
    Genre("trinh thám", "trinh thám"),
    Genre("sủng", "sủng"),
    Genre("chiếm hữu", "chiếm hữu"),
    Genre("hành động - action", "hành động - action"),
    Genre("showbiz", "showbiz"),
    Genre("bi kịch", "bi kịch"),
    Genre("linh dị", "linh dị"),
    Genre("music", "music"),
    Genre("police", "police"),
    Genre("vườn trường", "vườn trường"),
    Genre("lgbt+", "lgbt+"),
    Genre("aliens", "aliens"),
    Genre("smut", "smut"),
    Genre("post-apocalyptic", "post-apocalyptic"),
    Genre("vampires", "vampires"),
    Genre("mafia", "mafia"),
    Genre("võng du", "võng du"),
    Genre("mecha", "mecha"),
    Genre("16+", "16+"),
    Genre("phản diện", "phản diện"),
    Genre("loli", "loli"),
    Genre("ngược", "ngược"),
    Genre("tình cảm", "tình cảm"),
    Genre("mạo hiểm", "mạo hiểm"),
    Genre("trả thù", "trả thù"),
    Genre("võ lâm", "võ lâm"),
    Genre("game", "game"),
    Genre("sinh tồn", "sinh tồn"),
    Genre("villainess", "villainess"),
    Genre("xuyên nhanh", "xuyên nhanh"),
    Genre("giới giải trí", "giới giải trí"),
    Genre("hào môn thế gia", "hào môn thế gia"),
    Genre("anime", "anime"),
    Genre("baby", "baby"),
    Genre("ngược tâm", "ngược tâm"),
    Genre("phép thuật", "phép thuật"),
    Genre("detective", "detective"),
    Genre("khoa học viễn tưởng", "khoa học viễn tưởng"),
    Genre("kịch tính.", "kịch tính."),
    Genre("hoàng cung", "hoàng cung"),
    Genre("cung đấu", "cung đấu"),
    Genre("đại lão", "đại lão"),
    Genre("võ hiệp", "võ hiệp"),
    Genre("ngọt", "ngọt"),
    Genre("tận thế", "tận thế"),
    Genre("truyện âu mỹ", "truyện âu mỹ"),
    Genre("lãng mạng", "lãng mạng"),
    Genre("dị tộc", "dị tộc"),
    Genre("tái sinh", "tái sinh"),
    Genre("đấu trí", "đấu trí"),
    Genre("đang cập nhật", "đang cập nhật"),
    Genre("hồi quy", "hồi quy"),
    Genre("boy love", "boy love"),
    Genre("huyền bí", "huyền bí"),
    Genre("isekai/dị giới/trọng sinh", "isekai/dị giới/trọng sinh"),
    Genre("manhwa ngôn tình", "manhwa ngôn tình"),
    Genre("martial art", "martial art"),
    Genre("lịch sử", "lịch sử"),
    Genre("magical girls", "magical girls"),
    Genre("shota", "shota"),
    Genre("1x1", "1x1"),
    Genre("medical", "medical"),
    Genre("superhero", "superhero"),
    Genre("truyện nam", "truyện nam"),
    Genre("zombies", "zombies"),
    Genre("official colored", "official colored"),
    Genre("thiên tài", "thiên tài"),
    Genre("novel", "novel"),
    Genre("self-published", "self-published"),
    Genre("soft yaoi", "soft yaoi"),
    Genre("bạn thời thơ ấu", "bạn thời thơ ấu"),
    Genre("bắt nạt", "bắt nạt"),
    Genre("full m&224;u", "full m&224;u"),
    Genre("lãng mạn,", "lãng mạn,"),
    Genre("...", "..."),
    Genre("bl", "bl"),
    Genre("boylove", "boylove"),
    Genre("hài hước - comedy", "hài hước - comedy"),
    Genre("lạc miêu team", "lạc miêu team"),
    Genre("nhân thú", "nhân thú"),
    Genre("soft yuri", "soft yuri"),
    Genre("người lớn", "người lớn"),
    Genre("samurai", "samurai"),
    Genre("thể thao", "thể thao"),
    Genre("lãng mạn kỳ ảo", "lãng mạn kỳ ảo"),
    Genre("pheromone", "pheromone"),
    Genre("truy thê", "truy thê"),
    Genre("công sở", "công sở"),
    Genre("cục cưng", "cục cưng"),
    Genre("girllove", "girllove"),
    Genre("hài lãng mạn", "hài lãng mạn"),
    Genre("không gian", "không gian"),
    Genre("romance comedy", "romance comedy"),
    Genre("thú nhân", "thú nhân"),
    Genre("tiểu thuyết", "tiểu thuyết"),
    Genre("webtoons", "webtoons"),
    Genre("ngược tra", "ngược tra"),
    Genre("ninja", "ninja"),
    Genre("quái vật", "quái vật"),
    Genre("sủng nịch", "sủng nịch"),
    Genre("theo đuổi", "theo đuổi"),
    Genre("tình yêu công sở", "tình yêu công sở"),
    Genre("truyện tranh hot", "truyện tranh hot"),
    Genre("virtual reality", "virtual reality"),
    Genre("ngự thú", "ngự thú"),
    Genre("trâu già gặm cỏ non", "trâu già gặm cỏ non"),
    Genre("truyện ma", "truyện ma"),
    Genre("trưởng thành", "trưởng thành"),
    Genre("ép hôn", "ép hôn"),
    Genre("hoạt hình", "hoạt hình"),
    Genre("nấu nướng", "nấu nướng"),
    Genre("reverse harem", "reverse harem"),
    Genre("thanh mai trúc mã", "thanh mai trúc mã"),
    Genre("thiếu nhi", "thiếu nhi"),
    Genre("traditional games", "traditional games"),
    Genre("trở thành", "trở thành"),
    Genre("con gái nô", "con gái nô"),
    Genre("công chúa", "công chúa"),
    Genre("giật gân", "giật gân"),
    Genre("ma cà rồng", "ma cà rồng"),
    Genre("manh bảo", "manh bảo"),
    Genre("ác nữ", "ác nữ"),
    Genre("ảo tưởng", "ảo tưởng"),
    Genre("bệnh kiều", "bệnh kiều"),
    Genre("girl love", "girl love"),
    Genre("idol", "idol"),
    Genre("ma pháp", "ma pháp"),
    Genre("yaoi", "yaoi"),
)

private val TEAM_OPTIONS = arrayOf(
    "Tất cả" to "0",
    "Thánh Leech" to "1",
    "Quần Què Comic" to "2",
    "Nie Li" to "3",
    "Kitanda" to "4",
    "Mèo Sữa" to "5",
    "Munn House" to "6",
    "Pheromone" to "7",
    "SubTeam SpeedMax" to "8",
    "Miêu Dạ Tử" to "9",
    "Bơ Tập Tành Dịch Truyện Tranh" to "10",
    "Doluno Hotel" to "11",
    "Bơ Dịch Truyện" to "12",
    "Gấu Nâu Di Hành" to "13",
    "CEN" to "14",
    "Test" to "15",
    "Shiriaki Team" to "16",
    "meomansion" to "17",
    "Truyện Tranh Hot" to "18",
    "Vua Meow" to "19",
    "Truyện nhà Tanh" to "20",
    "Lian truyện" to "21",
    "Aimee Celine Team" to "22",
    "BLACKCARD" to "23",
    "U Lan Cốc Team" to "24",
    "LattesTeam" to "25",
    "Nhà của Hine" to "26",
    "Lạc Thủy Cung" to "27",
    "Trứng Bắp Thảo" to "28",
    "Venetus" to "29",
    "Mông" to "30",
    "Naive Team" to "31",
    "Quán Nước Mùa Hè Comic" to "32",
    "Rina" to "33",
    "Truyện Cuối Tuần" to "34",
    "khongtenteam" to "35",
    "RestartComics" to "36",
    "Team vilnius" to "37",
    "Thanh Phong Trai" to "38",
    "Bạc hà đường" to "39",
    "Mộng Nguyệt" to "40",
    "Thỏ Ham Ăn" to "41",
    "Kaii" to "42",
    "Đông Chi Thanh Hạ" to "43",
    "Xí Xẹo" to "44",
    "Bạch Cửu Hoa" to "45",
    "Bồng Chanh Teams" to "46",
    "Đứng Đường Team" to "47",
    "Meowdoujinshi" to "48",
    "Lazy Cloud" to "49",
    "Mỡ Mỡ" to "50",
    "Mèo Ma Kết" to "51",
    "Thiên Hải Comic" to "52",
    "khư đại bản" to "53",
    "M.M.T" to "54",
    "Monluvnovel" to "55",
    "SSGroup" to "56",
    "Thư Sinh Lười" to "57",
    "Thở Oxygen Team" to "58",
    "Lười Tem Truyện" to "59",
    "Hạ Hạ" to "60",
    "Foxie Team" to "61",
    "Mộng Tiên Giới" to "62",
    "Alice Comic" to "63",
    "Miu Ngủ Gật" to "64",
    "Gió Thổi Mây Bay" to "65",
    "Mê Truyện Hàn" to "66",
    "Mochi Đậu Đỏ" to "67",
    "Động nhà Moi" to "68",
    "Bubble team" to "69",
    "Nhóm cẩu đạo" to "70",
    "BL Bàn Cuối" to "71",
    "Nguyên Cateline" to "72",
    "Hanabi" to "73",
    "Ari Here" to "74",
    "GTEAM" to "75",
    "Thỏ Tu Tiên" to "76",
    "Tiểu Mã" to "77",
    "Aurora GL" to "78",
    "Starlit Team" to "79",
    "Kho Gió" to "80",
    "Bún Đậu Comics" to "81",
    "Sữa đậu nành" to "82",
    "Kẻ Nhổn Comic" to "83",
    "Cá Muối" to "84",
    "SHEEP Team" to "85",
    "Lost Planet Scanlation Team" to "86",
    "Lucifer" to "87",
    "Chân Đèo" to "88",
    "Tiệm Nhà Hươu" to "89",
    "Truyện Nhà Sa" to "90",
    "Phiêu Nguyệt Team" to "91",
    "Aimee Celine Team" to "92",
    "Cái Mồm Xinh" to "93",
    "Ổ lười của monkey" to "94",
    "Thạch Thỏ" to "95",
    "SunShine" to "96",
    "Là Muse Translating Team" to "97",
    "Thỏ Ngọc Comics" to "98",
    "QQTruyen" to "99",
    "Fuyumanga" to "100",
    "sweetyy" to "101",
    "Meoluoidichtruyen" to "102",
    "Xì Gà Dâu Team" to "103",
    "Romcom Chữa Lành" to "104",
    "Hội Truyện Dạo" to "105",
    "Meomeo" to "106",
    "Nguyệt Ly" to "107",
    "RevengLove Team" to "108",
    "Siêu Phẩm Comic" to "109",
    "TheNeverRated" to "110",
    "Bánh Bèo Hội Quán" to "111",
    "Thothotho" to "112",
    "Bắp Dịch Quán" to "113",
    "Mèo Thư Các" to "114",
    "Tisi thích dịch truyện" to "115",
    "Tiểu Hắc Miêu" to "116",
    "Vô năng tử" to "117",
    "Tàng Kính" to "118",
    "Snow Bunny Team" to "119",
    "Capy Comics" to "120",
    "Trần Uyên Nhi" to "121",
    "Athox" to "122",
    "Thiên Y" to "123",
    "Vườn Mèo" to "124",
    "YAOI team" to "125",
    "Ajisai Translation" to "126",
    "Ocean of Memories" to "127",
)

private val MIN_CHAPTER_OPTIONS = arrayOf(
    "0 chapter" to "0",
    "20 chapter" to "20",
    "40 chapter" to "40",
    "60 chapter" to "60",
    "80 chapter" to "80",
    "100 chapter" to "100",
    "120 chapter" to "120",
    "140 chapter" to "140",
    "160 chapter" to "160",
    "180 chapter" to "180",
    "200 chapter" to "200",
    "220 chapter" to "220",
    "240 chapter" to "240",
    "260 chapter" to "260",
    "280 chapter" to "280",
    "300 chapter" to "300",
    "320 chapter" to "320",
    "340 chapter" to "340",
    "360 chapter" to "360",
    "380 chapter" to "380",
    "400 chapter" to "400",
    "420 chapter" to "420",
    "440 chapter" to "440",
    "460 chapter" to "460",
    "480 chapter" to "480",
    "500 chapter" to "500",
    "520 chapter" to "520",
    "540 chapter" to "540",
    "560 chapter" to "560",
    "580 chapter" to "580",
    "600 chapter" to "600",
    "620 chapter" to "620",
    "640 chapter" to "640",
    "660 chapter" to "660",
    "680 chapter" to "680",
    "700 chapter" to "700",
    "720 chapter" to "720",
    "740 chapter" to "740",
    "760 chapter" to "760",
    "780 chapter" to "780",
    "800 chapter" to "800",
    "820 chapter" to "820",
    "840 chapter" to "840",
    "860 chapter" to "860",
    "880 chapter" to "880",
    "900 chapter" to "900",
    "920 chapter" to "920",
    "940 chapter" to "940",
    "960 chapter" to "960",
    "980 chapter" to "980",
    "1000 chapter" to "1000",
)

private val SORT_OPTIONS = arrayOf(
    "Thời gian đăng" to "update",
    "Lượt xem trong ngày" to "view_day",
    "Lượt xem trong tuần" to "view_week",
    "Lượt xem trong tháng" to "view_month",
    "Lượt xem tổng" to "view_total",
    "Lượt follow" to "follow",
)

private val STATUS_OPTIONS = arrayOf(
    "Tất cả" to "all",
    "Đang ra" to "doing",
    "Đã dừng" to "drop",
    "Đã hoàn thành" to "done",
)
