package eu.kanade.tachiyomi.extension.en.nineanime

import eu.kanade.tachiyomi.source.model.Filter

class GenreFilter :
    UriPartFilter(
        "Genres",
        arrayOf(
            Pair("All", "All"),
            Pair("4-Koma", "4-Koma"),
            Pair("Action", "Action"),
            Pair("Adaptation", "Adaptation"),
            Pair("Adult", "Adult"),
            Pair("Adventure", "Adventure"),
            Pair("Aliens", "Aliens"),
            Pair("All", "category"),
            Pair("Animals", "Animals"),
            Pair("Anthology", "Anthology"),
            Pair("Award Winning", "Award+Winning"),
            Pair("Comedy", "Comedy"),
            Pair("Cooking", "Cooking"),
            Pair("Crime", "Crime"),
            Pair("Crossdressing", "Crossdressing"),
            Pair("Delinquents", "Delinquents"),
            Pair("Demons", "Demons"),
            Pair("Doujinshi", "Doujinshi"),
            Pair("Drama", "Drama"),
            Pair("Ecchi", "Ecchi"),
            Pair("Fantasy", "Fantasy"),
            Pair("Food", "Food"),
            Pair("Full Color", "Full+color"),
            Pair("Game", "Game"),
            Pair("Gender Bender", "Gender+Bender"),
            Pair("Genderswap", "Genderswap"),
            Pair("Ghosts", "Ghosts"),
            Pair("Gossip", "Gossip"),
            Pair("Gyaru", "Gyaru"),
            Pair("Harem", "Harem"),
            Pair("Hentai", "Hentai"),
            Pair("Historical", "Historical"),
            Pair("Horror", "Horror"),
            Pair("Incest", "Incest"),
            Pair("Isekai", "Isekai"),
            Pair("Josei", "Josei"),
            Pair("Kids", "Kids"),
            Pair("Loli", "Loli"),
            Pair("Long Strip", "Long+strip"),
            Pair("Mafia", "Mafia"),
            Pair("Magic", "Magic"),
            Pair("Magical Girls", "Magical+Girls"),
            Pair("Manga", "Manga"),
            Pair("Manhua", "Manhua"),
            Pair("Manhwa", "Manhwa"),
            Pair("Martial Arts", "Martial+Arts"),
            Pair("Mature", "Mature"),
            Pair("Mecha", "Mecha"),
            Pair("Medical", "Medical"),
            Pair("Military", "Military"),
            Pair("Monster Girls", "Monster+girls"),
            Pair("Monsters", "Monsters"),
            Pair("Music", "Music"),
            Pair("Mystery", "Mystery"),
            Pair("N/A", "N%2Fa"),
            Pair("Ninja", "Ninja"),
            Pair("None", "None"),
            Pair("Office Workers", "Office+workers"),
            Pair("Official Colored", "Official+colored"),
            Pair("One Shot", "One+Shot"),
            Pair("Oneshot", "Oneshot"),
            Pair("Parody", "Parody"),
            Pair("Philosophical", "Philosophical"),
            Pair("Police", "Police"),
            Pair("Post Apocalyptic", "Post+apocalyptic"),
            Pair("Psychological", "Psychological"),
            Pair("Reincarnation", "Reincarnation"),
            Pair("Reverse Harem", "Reverse+harem"),
            Pair("Romance", "Romance"),
            Pair("Samurai", "Samurai"),
            Pair("School Life", "School+Life"),
            Pair("Sci Fi", "sci+fi"),
            Pair("Sci-Fi", "Sci-fi"),
            Pair("Seinen", "Seinen"),
            Pair("Shota", "Shota"),
            Pair("Shotacon", "Shotacon"),
            Pair("Shoujo", "Shoujo"),
            Pair("Shoujo Ai", "Shoujo+Ai"),
            Pair("Shounen", "Shounen"),
            Pair("Shounen Ai", "Shounen+Ai"),
            Pair("Slice Of Life", "Slice+Of+Life"),
            Pair("Smut", "Smut"),
            Pair("Sports", "Sports"),
            Pair("Super Power", "Super+power"),
            Pair("Superhero", "Superhero"),
            Pair("Supernatural", "Supernatural"),
            Pair("Survival", "Survival"),
            Pair("Thriller", "Thriller"),
            Pair("Time Travel", "Time+travel"),
            Pair("Toomics", "Toomics"),
            Pair("Tragedy", "Tragedy"),
            Pair("Uncategorized", "Uncategorized"),
            Pair("User Created", "User+created"),
            Pair("Vampire", "Vampire"),
            Pair("Vampires", "Vampires"),
            Pair("Video Games", "Video+games"),
            Pair("Virtual Reality", "Virtual+reality"),
            Pair("Web Comic", "Web+comic"),
            Pair("Webtoon", "Webtoon"),
            Pair("Webtoons", "Webtoons"),
            Pair("Wuxia", "Wuxia"),
            Pair("Yaoi", "Yaoi"),
            Pair("Yuri", "Yuri"),
            Pair("Zombies", "Zombies"),
            Pair("[No Chapters]", "%5Bno+chapters%5D"),
        ),
    )

open class UriPartFilter(displayName: String, val vals: Array<Pair<String, String>>) : Filter.Select<String>(displayName, vals.map { it.first }.toTypedArray()) {
    fun toUriPart() = vals[state].second
}
