package eu.kanade.tachiyomi.extension.vi.mimihentai

import eu.kanade.tachiyomi.source.model.Filter
import eu.kanade.tachiyomi.source.model.FilterList

fun getFilters(): FilterList = FilterList(
    SortFilter(),
    StatusFilter(),
    GenreFilter(getGenreList()),
)

class SortFilter : UriPartFilter(
    "Sắp xếp",
    arrayOf(
        Pair("Mới cập nhật", "-updated_at"),
        Pair("Xem nhiều", "-views"),
        Pair("A-Z", "name"),
    ),
)

class StatusFilter : UriPartFilter(
    "Trạng thái",
    arrayOf(
        Pair("Tất cả", ""),
        Pair("Đang tiến hành", "1"),
        Pair("Đã hoàn thành", "2"),
    ),
)

class Genre(name: String, val id: String) : Filter.CheckBox(name)

class GenreFilter(genres: List<Genre>) : Filter.Group<Genre>("Thể loại", genres)

open class UriPartFilter(
    displayName: String,
    private val vals: Array<Pair<String, String>>,
) : Filter.Select<String>(displayName, vals.map { it.first }.toTypedArray()) {
    fun toUriPart() = vals[state].second
}

private fun getGenreList(): List<Genre> = listOf(
    Genre("3D Hentai", "1"),
    Genre("Action", "2"),
    Genre("Adult", "3"),
    Genre("Adventure", "4"),
    Genre("Ahegao", "5"),
    Genre("Anal", "6"),
    Genre("Angel", "7"),
    Genre("Animal", "9"),
    Genre("Animal girl", "10"),
    Genre("Apron", "12"),
    Genre("Artist CG", "13"),
    Genre("Based Game", "14"),
    Genre("BBM", "15"),
    Genre("BBW", "16"),
    Genre("BDSM", "17"),
    Genre("Bestiality", "18"),
    Genre("Big Ass", "19"),
    Genre("Big Boobs", "20"),
    Genre("Big Penis", "21"),
    Genre("Bikini", "174"),
    Genre("Bisexual", "175"),
    Genre("Black skin", "176"),
    Genre("Blackmail", "22"),
    Genre("Blindfold", "177"),
    Genre("Bloomers", "23"),
    Genre("BlowJobs", "24"),
    Genre("Body Swap", "25"),
    Genre("Bodysuit", "26"),
    Genre("Bondage", "27"),
    Genre("Breast Sucking", "28"),
    Genre("BreastJobs", "29"),
    Genre("Brocon", "30"),
    Genre("Brother", "31"),
    Genre("Bunny Girl", "32"),
    Genre("Cat Girl", "33"),
    Genre("Chastity Belt", "34"),
    Genre("Cheating", "35"),
    Genre("Cheerleader", "36"),
    Genre("Childhood", "37"),
    Genre("Chinese Dress", "38"),
    Genre("Classmate", "39"),
    Genre("Collar", "40"),
    Genre("Comedy", "41"),
    Genre("Cosplay", "42"),
    Genre("Cousin", "43"),
    Genre("CowGirl", "44"),
    Genre("Crossdressing", "45"),
    Genre("Cumflation", "46"),
    Genre("Cunnilingus", "47"),
    Genre("Dark Skin", "48"),
    Genre("DeepThroat", "49"),
    Genre("Demon", "50"),
    Genre("Demon Girl", "51"),
    Genre("Dog Girl", "52"),
    Genre("Doujinshi", "53"),
    Genre("Double Penetration", "54"),
    Genre("Drama", "55"),
    Genre("Drunk", "56"),
    Genre("Ecchi", "57"),
    Genre("Elf", "58"),
    Genre("Exhibitionism", "59"),
    Genre("Fantasy", "60"),
    Genre("Father", "61"),
    Genre("Femdom", "62"),
    Genre("Fingering", "63"),
    Genre("Footjob", "64"),
    Genre("Fox Girl", "65"),
    Genre("Full Color", "66"),
    Genre("Furry", "67"),
    Genre("Futanari", "68"),
    Genre("Gangbang", "69"),
    Genre("Garter Belt", "70"),
    Genre("Gender Bender", "71"),
    Genre("Ghost", "72"),
    Genre("Glasses", "73"),
    Genre("Goth Loli", "74"),
    Genre("Gyaru", "75"),
    Genre("Handjob", "76"),
    Genre("Harem", "77"),
    Genre("Historical", "78"),
    Genre("Horror", "79"),
    Genre("Hot Pants", "80"),
    Genre("Human Pet", "81"),
    Genre("Humiliation", "82"),
    Genre("Hypnosis", "83"),
    Genre("Idol", "84"),
    Genre("Isekai", "85"),
    Genre("Josei", "86"),
    Genre("Kemonomimi", "87"),
    Genre("Kimono", "88"),
    Genre("Lactation", "89"),
    Genre("Leotard", "90"),
    Genre("Loli", "91"),
    Genre("Magical Girl", "92"),
    Genre("Maid", "93"),
    Genre("Manhua", "100"),
    Genre("Manhwa", "101"),
    Genre("Mature", "102"),
    Genre("Mecha", "103"),
    Genre("Megane", "104"),
    Genre("Miko", "105"),
    Genre("MILF", "106"),
    Genre("Mind Break", "107"),
    Genre("Mind Control", "108"),
    Genre("Monster", "109"),
    Genre("Monster Girl", "110"),
    Genre("Mother", "111"),
    Genre("Nakadashi", "112"),
    Genre("Netorare", "113"),
    Genre("Netori", "114"),
    Genre("NTR", "115"),
    Genre("Nurse", "116"),
    Genre("Office Lady", "117"),
    Genre("One Shot", "118"),
    Genre("Oneshot", "119"),
    Genre("Oppai Loli", "120"),
    Genre("Oral", "121"),
    Genre("Osananajimi", "122"),
    Genre("Paizuri", "123"),
    Genre("Pantyhose", "124"),
    Genre("Petite", "125"),
    Genre("Pregnancy", "126"),
    Genre("Prostitution", "127"),
    Genre("Psychological", "128"),
    Genre("Public Sex", "129"),
    Genre("Rape", "130"),
    Genre("Reverse Harem", "131"),
    Genre("Reverse Rape", "132"),
    Genre("Romance", "133"),
    Genre("Ryona", "134"),
    Genre("School Girl", "135"),
    Genre("School Life", "136"),
    Genre("Sci-Fi", "137"),
    Genre("Seinen", "138"),
    Genre("Sequel", "139"),
    Genre("Shemale", "140"),
    Genre("Shotacon", "141"),
    Genre("Shoujo", "142"),
    Genre("Shoujo Ai", "143"),
    Genre("Shounen", "144"),
    Genre("Shounen Ai", "145"),
    Genre("Sister", "146"),
    Genre("Siscon", "147"),
    Genre("Slave", "148"),
    Genre("Slice of Life", "149"),
    Genre("Small Breasts", "150"),
    Genre("Smut", "151"),
    Genre("Sports", "152"),
    Genre("Stockings", "153"),
    Genre("Supernatural", "154"),
    Genre("Sweating", "155"),
    Genre("Swimsuit", "156"),
    Genre("Teacher", "157"),
    Genre("Tentacles", "158"),
    Genre("Threesome", "159"),
    Genre("Tomboy", "160"),
    Genre("Tragedy", "161"),
    Genre("Trap", "162"),
    Genre("Tsundere", "163"),
    Genre("Twins", "164"),
    Genre("Ugly Bastard", "165"),
    Genre("Uncensored", "166"),
    Genre("Vanilla", "167"),
    Genre("Vampire", "168"),
    Genre("Virgin", "169"),
    Genre("Webtoon", "170"),
    Genre("Widow", "171"),
    Genre("Witch", "172"),
    Genre("Yaoi", "94"),
    Genre("Yandere", "95"),
    Genre("Yuri", "96"),
)
