package eu.kanade.tachiyomi.extension.ru.nudemoon

import eu.kanade.tachiyomi.source.model.Filter
import eu.kanade.tachiyomi.source.model.FilterList

internal class Genre(name: String, val id: String = name.replace(' ', '_')) : Filter.CheckBox(name.replaceFirstChar { it.uppercaseChar() })
internal class GenreList(genres: List<Genre>) : Filter.Group<Genre>("Тэги", genres)
internal class OrderBy :
    Filter.Sort(
        "Сортировка",
        order.map { it.first }.toTypedArray(),
        Selection(1, false),
    ) {
    val selected: String get() = order[state?.index ?: 1].second
    companion object {
        val order = listOf(
            "Дата" to "date",
            "Просмотры" to "views",
            "Лайки" to "like",
            "Отзывы" to "com",
            "Количество страниц" to "pages",
        )
    }
}

fun getFilters(): FilterList = FilterList(
    OrderBy(),
    GenreList(getGenreList()),
)

private fun getGenreList() = listOf(
    Genre("анал"),
    Genre("анимация"),
    Genre("без цензуры"),
    Genre("беременные"),
    Genre("близняшки"),
    Genre("большие груди"),
    Genre("в бассейне"),
    Genre("в больнице"),
    Genre("в ванной"),
    Genre("в общественном месте"),
    Genre("в первый раз"),
    Genre("в транспорте"),
    Genre("в туалете"),
    Genre("гарем"),
    Genre("гипноз"),
    Genre("горничные"),
    Genre("горячий источник"),
    Genre("групповой секс"),
    Genre("гуро"),
    Genre("драма"),
    Genre("запредельное"),
    Genre("золотой дождь"),
    Genre("зоо"),
    Genre("зрелые женщины"),
    Genre("идолы"),
    Genre("извращение"),
    Genre("измена"),
    Genre("имеют парня"),
    Genre("инцест"),
    Genre("клизма"),
    Genre("колготки"),
    Genre("комиксы"),
    Genre("косплей"),
    Genre("лоликон"),
    Genre("манхва"),
    Genre("мастурбация"),
    Genre("мерзкий мужик"),
    Genre("много спермы"),
    Genre("молоко"),
    Genre("монашки"),
    Genre("монстры"),
    Genre("на камеру"),
    Genre("на природе"),
    Genre("насекомые"),
    Genre("небритые подмышки"),
    Genre("нейросеть"),
    Genre("обычный секс"),
    Genre("огромный член"),
    Genre("пляж"),
    Genre("подглядывание"),
    Genre("пояс верности"),
    Genre("принуждение"),
    Genre("продажность"),
    Genre("пьяные"),
    Genre("рабыни"),
    Genre("романтика"),
    Genre("с ушками"),
    Genre("секс игрушки"),
    Genre("сетакон"),
    Genre("спящие"),
    Genre("страпон"),
    Genre("студенты"),
    Genre("суккуб"),
    Genre("тентакли"),
    Genre("толстушки"),
    Genre("трапы"),
    Genre("ужасы"),
    Genre("униформа"),
    Genre("учитель и ученик"),
    Genre("фемдом"),
    Genre("фетиш"),
    Genre("фурри"),
    Genre("футанари"),
    Genre("футджоб"),
    Genre("фэнтези"),
    Genre("цветная"),
    Genre("чикан"),
    Genre("чулки"),
    Genre("шимейл"),
    Genre("эксгибиционизм"),
    Genre("эльфы"),
    Genre("юмор"),
    Genre("юные"),
    Genre("юри"),
    Genre("яой"),
    Genre("3D арт"),
    Genre("ahegao"),
    Genre("bdsm"),
    Genre("ganguro"),
    Genre("gender bender"),
    Genre("glory hole"),
    Genre("inseki"),
    Genre("megane"),
    Genre("mind break"),
    Genre("monstergirl"),
    Genre("netorare"),
    Genre("nipple penetration"),
    Genre("oyakodon"),
    Genre("skinsuit"),
    Genre("titsfuck"),
    Genre("vore"),
    Genre("x-ray"),
)
