name: Build ScanManga Extension

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execute permission to gradlew
        run: chmod +x gradlew

      - name: Build ScanManga APK
        run: ./gradlew :src:fr:scanmanga:assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ScanManga-APK
          path: src/fr/scanmanga/build/outputs/apk/debug/*.apk
