package eu.kanade.tachiyomi.extension.en.mangamirai

import eu.kanade.tachiyomi.source.model.Filter
import okhttp3.HttpUrl.Builder

class SortFilter :
    SelectFilter(
        "Sort by",
        arrayOf(
            Pair("Newest", "new"),
            Pair("Ranking", "ranking"),
        ),
    )

class GenreFilter :
    SelectFilter(
        "Genres",
        arrayOf(
            Pair("All", ""),
            Pair("Action", "Action"),
            Pair("Fantasy", "Fantasy"),
            Pair("Romance", "Romance"),
            Pair("Drama", "Drama"),
            Pair("Horror", "Horror"),
            Pair("Suspense", "Suspense"),
            Pair("Mystery", "Mystery"),
            Pair("Sports", "Sports"),
            Pair("Slice of Life", "Slice of Life"),
            Pair("Boys Love", "Boys Love"),
            Pair("Girls Love", "Girls Love"),
            Pair("Sci-Fi", "Sci-Fi"),
            Pair("Gourmet", "Gourmet"),
            Pair("Historical", "Historical"),
            Pair("Comedy", "Comedy"),
            Pair("Other", "Other"),
        ),
    )

class TagFilter :
    Filter.Group<CheckFilter>(
        "Tags",
        listOf(
            CheckFilter("Free"),
            CheckFilter("On Sale"),
            CheckFilter("New"),
            CheckFilter("Completed"),
            CheckFilter("Manga"),
            CheckFilter("V-scroll Manga"),
            CheckFilter("Chapter"),
        ),
    )

class AuthorFilter :
    Filter.Group<CheckFilter>(
        "Authors",
        listOf(
            CheckFilter("Abigail Blackman"),
            CheckFilter("Lys Blakeslee"),
            CheckFilter("Phil Christie"),
            CheckFilter("Alexis Eckerman"),
            CheckFilter("Rochelle Gancio"),
            CheckFilter("Bianca Pistillo"),
            CheckFilter("Chiho Christie"),
            CheckFilter("Stephen Paul"),
            CheckFilter("Rachel Pierce"),
            CheckFilter("Taylor Engel"),
            CheckFilter("Alethea Nibley"),
            CheckFilter("Athena Nibley"),
            CheckFilter("Katie Blakeslee"),
            CheckFilter("Amanda Haley"),
            CheckFilter("Caleb Cook"),
            CheckFilter("Kevin Gifford"),
            CheckFilter("Ryukishi07"),
            CheckFilter("Junji Ito"),
            CheckFilter("Leighann Harvey"),
            CheckFilter("Reki Kawahara"),
            CheckFilter("CLAMP"),
            CheckFilter("Rachel J. Pierce"),
            CheckFilter("Carolina Hdz"),
            CheckFilter("Eleanor Summers"),
            CheckFilter("Sheldon Drzka"),
            CheckFilter("Dayeun kim"),
            CheckFilter("Elena Pizarro Lanzas"),
            CheckFilter("Shigeru Tsuchiyama"),
            CheckFilter("Hiro Mashima"),
            CheckFilter("Adnazeer Macalangcom"),
            CheckFilter("Andrew Cunningham"),
            CheckFilter("Ko Ransom"),
            CheckFilter("Brandon Bovia"),
            CheckFilter("John Neal"),
            CheckFilter("Magica Magica Quartet"),
            CheckFilter("Akira Toriyama"),
            CheckFilter("Arbash Mughal"),
            CheckFilter("Jan Cash"),
            CheckFilter("William Flanagan"),
            CheckFilter("Erin Hickman"),
            CheckFilter("Ivo Marques"),
            CheckFilter("Madeleine Jose"),
            CheckFilter("Ajani Oloye"),
            CheckFilter("Akane Shimizu"),
            CheckFilter("Alexandra McCullough-Garcia"),
            CheckFilter("Alice Prowse"),
            CheckFilter("Rumiko Takahashi"),
            CheckFilter("abec"),
            CheckFilter("Arina Tanemura"),
            CheckFilter("Christine Dashiell"),
            CheckFilter("Hajime Isayama"),
            CheckFilter("AndWorld AndWorld Design"),
            CheckFilter("Anthony Quintessenza"),
            CheckFilter("Ema Toyama"),
            CheckFilter("Emma Schumacker"),
            CheckFilter("Fujino Omori"),
            CheckFilter("Giuseppe di Martino"),
            CheckFilter("Jenny McKeon McKeon"),
            CheckFilter("Julie Goniwich"),
            CheckFilter("Masashi Kishimoto"),
            CheckFilter("Tsutomu Nihei"),
            CheckFilter("Amber Tamosaitis"),
            CheckFilter("Amethyst Xuan"),
            CheckFilter("Andria McKnight"),
            CheckFilter("Arata Shiraishi"),
            CheckFilter("Hirohiko Araki"),
            CheckFilter("Hiroyuki Takei"),
            CheckFilter("Kafka Asagiri"),
            CheckFilter("Kaori Yuki"),
            CheckFilter("Kazuki Takahashi"),
            CheckFilter("Kei Coffman"),
            CheckFilter("Natsume Ono"),
            CheckFilter("Sango Harukawa"),
            CheckFilter("Shuzo Oshimi"),
            CheckFilter("Suzuhito Yasuda"),
            CheckFilter("Takeshi Obata"),
            CheckFilter("Aila Nagamine"),
            CheckFilter("Hitoshi Iwaaki"),
            CheckFilter("Homura Kawamoto"),
            CheckFilter("Keji Mizoguchi"),
            CheckFilter("Ken Akamatsu"),
            CheckFilter("Noboru Akimoto"),
            CheckFilter("Paul Starr"),
            CheckFilter("Ryohgo Narita"),
            CheckFilter("Shinkoshoto"),
            CheckFilter("Tomo Kimura"),
            CheckFilter("Yuu Watase"),
            CheckFilter("Aki"),
            CheckFilter("Akiko Higashimura"),
            CheckFilter("Akira Kanbe"),
            CheckFilter("Andrew Gaippe"),
            CheckFilter("Boichi"),
            CheckFilter("Chana Conley"),
            CheckFilter("Christina Rose"),
            CheckFilter("Eiichiro Oda"),
            CheckFilter("Fuse"),
            CheckFilter("Inio Asano"),
            CheckFilter("Jasmine Bernhardt"),
            CheckFilter("Jocelyne Allen"),
            CheckFilter("Kaoru Mori"),
        ),
    )

class PublisherFilter :
    SelectFilter(
        "Publishers",
        arrayOf(
            Pair("All", ""),
            Pair("Yen Press", "Yen Press"),
            Pair("Kodansha USA Publishing LLC", "Kodansha USA Publishing LLC"),
            Pair("VIZ Media LLC", "VIZ Media LLC"),
            Pair("Manga UP!", "Manga UP!"),
            Pair("One Peace Books, Inc.", "One Peace Books, Inc."),
            Pair("J-Novel Club", "J-Novel Club"),
            Pair("NIHONBUNGEISHA Co.,Ltd.", "NIHONBUNGEISHA Co.,Ltd."),
            Pair("Shusuisha inc.", "Shusuisha inc."),
            Pair("Coamix Inc.", "Coamix Inc."),
            Pair("TORICO Co., Ltd.", "TORICO Co., Ltd."),
            Pair("Animate International Co., Ltd.", "Animate International Co., Ltd."),
            Pair("AKITASHOTEN Co., Ltd.", "AKITASHOTEN Co., Ltd."),
            Pair("Futabasha Publishers LTD.", "Futabasha Publishers LTD."),
            Pair("YUZU comics", "YUZU comics"),
            Pair("weavin", "weavin"),
            Pair("Cork", "Cork"),
            Pair("Jitsugyo no Nihon Sha, Ltd.", "Jitsugyo no Nihon Sha, Ltd."),
            Pair("No.9 Inc.", "No.9 Inc."),
            Pair("TO BOOKS, Inc", "TO BOOKS, Inc"),
            Pair("EARTH STAR Entertainment", "EARTH STAR Entertainment"),
            Pair("HykeComic", "HykeComic"),
            Pair("SHUFU TO SEIKATSU SHA CO.,LTD.", "SHUFU TO SEIKATSU SHA CO.,LTD."),
            Pair("HERO’S INC", "HERO’S INC"),
            Pair("Kaoru Tada/minato-pro,M'z-plan", "Kaoru Tada/minato-pro,M'z-plan"),
            Pair("COMPASS Inc.", "COMPASS Inc."),
            Pair("Manga Box Co., Ltd.", "Manga Box Co., Ltd."),
        ),
    )

class CheckFilter(name: String) : Filter.CheckBox(name)

open class SelectFilter(displayName: String, private val vals: Array<Pair<String, String>>) : Filter.Select<String>(displayName, vals.map { it.first }.toTypedArray()) {
    val value: String
        get() = vals[state].second
}

fun Builder.addFilter(param: String, filter: Filter.CheckBox) = filter.state.takeIf { it }?.let { addQueryParameter(param, filter.name) }
