package eu.kanade.tachiyomi.extension.en.manhwalike

import eu.kanade.tachiyomi.source.model.Filter

open class UriPartFilter(displayName: String, private val vals: Array<Pair<String, String>>) : Filter.Select<String>(displayName, vals.map { it.first }.toTypedArray()) {
    fun toUriPart() = vals[state].second
}

class GenreFilter :
    UriPartFilter(
        "Genre",
        arrayOf(
            Pair("Action", "manga-genre-action"),
            Pair("Adaptation", "manga-genre-adaptation"),
            Pair("Adult", "manga-genre-adult"),
            Pair("Adventure", "manga-genre-adventure"),
            Pair("Boy love", "manga-genre-boy-love"),
            Pair("Comedy", "manga-genre-comedy"),
            Pair("Comic", "manga-genre-comic"),
            Pair("Cooking", "manga-genre-cooking"),
            Pair("Crime", "manga-genre-crime"),
            Pair("Doujinshi", "manga-genre-doujinshi"),
            Pair("Drama", "manga-genre-drama"),
            Pair("Ecchi", "manga-genre-ecchi"),
            Pair("Fantasy", "manga-genre-fantasy"),
            Pair("Full Color", "manga-genre-full-color"),
            Pair("Game", "manga-genre-game"),
            Pair("Gender Bender", "manga-genre-gender-bender"),
            Pair("Harem", "manga-genre-harem"),
            Pair("Historical", "manga-genre-historical"),
            Pair("Horror", "manga-genre-horror"),
            Pair("Isekai", "manga-genre-isekai"),
            Pair("Josei", "manga-genre-josei"),
            Pair("Magic", "manga-genre-magic"),
            Pair("Manga", "manga-genre-manga"),
            Pair("Manhua", "manga-genre-manhua"),
            Pair("Manhwa", "manga-genre-manhwa"),
            Pair("Martial Arts", "manga-genre-martial-arts"),
            Pair("Mature", "manga-genre-mature"),
            Pair("Mecha", "manga-genre-mecha"),
            Pair("Medical", "manga-genre-medical"),
            Pair("Mystery", "manga-genre-mystery"),
            Pair("NTR", "manga-genre-ntr"),
            Pair("Oneshot", "manga-genre-oneshot"),
            Pair("Psychological", "manga-genre-psychological"),
            Pair("Reincarnation", "manga-genre-reincarnation"),
            Pair("Romance", "manga-genre-romance"),
            Pair("School life", "manga-genre-school-life"),
            Pair("Sci-fi", "manga-genre-sci-fi"),
            Pair("Seinen", "manga-genre-seinen"),
            Pair("Shoujo", "manga-genre-shoujo"),
            Pair("Shoujo ai", "manga-genre-shoujo-ai"),
            Pair("Shounen", "manga-genre-shounen"),
            Pair("Shounen ai", "manga-genre-shounen-ai"),
            Pair("Slice Of Life", "manga-genre-slice-of-life"),
            Pair("Smut", "manga-genre-smut"),
            Pair("Soft Yaoi", "manga-genre-soft-yaoi"),
            Pair("Soft Yuri", "manga-genre-soft-yuri"),
            Pair("Sports", "manga-genre-sports"),
            Pair("Super Power", "manga-genre-super-power"),
            Pair("Supernatural", "manga-genre-supernatural"),
            Pair("SURVIVAL", "manga-genre-survival"),
            Pair("Time travel", "manga-genre-time-travel"),
            Pair("Tragedy", "manga-genre-tragedy"),
            Pair("Villainess", "manga-genre-villainess"),
            Pair("Webtoon", "manga-genre-webtoon"),
            Pair("Webtoons", "manga-genre-webtoons"),
            Pair("Yaoi", "manga-genre-yaoi"),
        ),
    )
