package eu.kanade.tachiyomi.extension.pt.bladetoons

import eu.kanade.tachiyomi.multisrc.mangotheme.MangoThemeTagFilterOption

internal typealias BladeToonsTagFilterOption = MangoThemeTagFilterOption

internal object BladeToonsFilters {

    val statusOptions = arrayOf(
        "Todos" to "",
        "Ativo" to "6",
        "Cancelado" to "4",
        "Conclu\u00eddo" to "3",
        "Em Andamento" to "1",
        "Hiato" to "5",
        "Pausado" to "2",
    )

    val formatOptions = arrayOf(
        "Todos" to "",
        "Comic" to "20",
        "Hentai" to "23",
        "Manga" to "24",
        "Manhua" to "17",
        "Manhwa" to "25",
        "Novel" to "18",
        "Shoujo" to "19",
        "Webtoon" to "26",
        "Yaoi" to "21",
        "Yuri" to "22",
    )

    val tagOptions = listOf(
        BladeToonsTagFilterOption("+18", "48"),
        BladeToonsTagFilterOption("A\u00e7\u00e3o", "2"),
        BladeToonsTagFilterOption("Adulto", "64"),
        BladeToonsTagFilterOption("Apocalipse", "33"),
        BladeToonsTagFilterOption("Apocal\u00edptico", "58"),
        BladeToonsTagFilterOption("Artes Marciais", "24"),
        BladeToonsTagFilterOption("Aventura", "3"),
        BladeToonsTagFilterOption("Bullying", "60"),
        BladeToonsTagFilterOption("Com\u00e9dia", "6"),
        BladeToonsTagFilterOption("Crime", "51"),
        BladeToonsTagFilterOption("Culinaria", "28"),
        BladeToonsTagFilterOption("Cultivo", "23"),
        BladeToonsTagFilterOption("Dem\u00f4nios", "39"),
        BladeToonsTagFilterOption("Drama", "7"),
        BladeToonsTagFilterOption("Dungeon", "25"),
        BladeToonsTagFilterOption("Ecchi", "42"),
        BladeToonsTagFilterOption("Escolar", "56"),
        BladeToonsTagFilterOption("Esportes", "38"),
        BladeToonsTagFilterOption("Fantasia", "4"),
        BladeToonsTagFilterOption("Fatia da Vida/Slice of Life", "41"),
        BladeToonsTagFilterOption("Fic\u00e7\u00e3o Cient\u00edfica", "40"),
        BladeToonsTagFilterOption("Finalizado", "55"),
        BladeToonsTagFilterOption("Gore", "59"),
        BladeToonsTagFilterOption("Har\u00e9m", "44"),
        BladeToonsTagFilterOption("Hist\u00f3rico", "11"),
        BladeToonsTagFilterOption("Horror", "9"),
        BladeToonsTagFilterOption("Isekai", "19"),
        BladeToonsTagFilterOption("Jogos", "66"),
        BladeToonsTagFilterOption("Luta", "35"),
        BladeToonsTagFilterOption("Magia", "29"),
        BladeToonsTagFilterOption("manhua", "45"),
        BladeToonsTagFilterOption("Manhwa", "67"),
        BladeToonsTagFilterOption("Militar", "14"),
        BladeToonsTagFilterOption("Mist\u00e9rio", "43"),
        BladeToonsTagFilterOption("Moderno", "54"),
        BladeToonsTagFilterOption("Monstros", "37"),
        BladeToonsTagFilterOption("Murim", "31"),
        BladeToonsTagFilterOption("Necromante", "32"),
        BladeToonsTagFilterOption("Policial", "52"),
        BladeToonsTagFilterOption("Psicol\u00f3gico", "27"),
        BladeToonsTagFilterOption("Reencarna\u00e7\u00e3o", "21"),
        BladeToonsTagFilterOption("Regress\u00e3o", "47"),
        BladeToonsTagFilterOption("Retorno", "20"),
        BladeToonsTagFilterOption("Romance", "5"),
        BladeToonsTagFilterOption("Sci-Fi", "62"),
        BladeToonsTagFilterOption("Seinen", "34"),
        BladeToonsTagFilterOption("Shoujo", "16"),
        BladeToonsTagFilterOption("Shounen", "15"),
        BladeToonsTagFilterOption("Sistema", "22"),
        BladeToonsTagFilterOption("Slice of Life", "61"),
        BladeToonsTagFilterOption("Sobrenatural", "13"),
        BladeToonsTagFilterOption("SuperPoder", "30"),
        BladeToonsTagFilterOption("Super Poderes", "57"),
        BladeToonsTagFilterOption("Suspense", "10"),
        BladeToonsTagFilterOption("Terror", "8"),
        BladeToonsTagFilterOption("teste", "1"),
        BladeToonsTagFilterOption("Trag\u00e9dia", "26"),
        BladeToonsTagFilterOption("Vida escolar", "12"),
        BladeToonsTagFilterOption("Yuri", "50"),
    )
}
