package eu.kanade.tachiyomi.extension.pt.hipercool

import eu.kanade.tachiyomi.multisrc.hiper.Hiper
import keiyoushi.annotation.Source
import keiyoushi.network.rateLimit
import okhttp3.Headers
import okhttp3.OkHttpClient

@Source
abstract class Hipercool : Hiper() {

    override fun Headers.Builder.configureHeaders(): Headers.Builder = this
        .set("x-flux-node", "G2ZsDdWhUwdU82Vw")

    override fun OkHttpClient.Builder.configureClient(): OkHttpClient.Builder = addHiperAuthInterceptor()
        .rateLimit(3)

    override val genresList = listOf(
        "Academia",
        "Ação",
        "Adult",
        "Adulto",
        "Adventure",
        "Ahega",
        "Ahegao",
        "Akio takami",
        "Amiga de infância",
        "Amputado",
        "Anal",
        "Angelical",
        "Animal",
        "Anjo",
        "Anjos",
        "anorexic",
        "Aprisionada",
        "Ar livre",
        "Aréola Grande",
        "Arte Marcial",
        "Artes Marciais",
        "Artist CG",
        "Ashikoki",
        "Avental",
        "Aventura",
        "Bakuman",
        "Bakunyuu",
        "Bakuynuu",
        "Banheiro",
        "Banho",
        "Banner",
        "BBM",
        "BBW",
        "BDSM",
        "Beatmania",
        "Beauty Mark",
        "Bêbada",
        "Bêbado",
        "Bêbado(a)",
        "Bebida",
        "Beijo grego",
        "Bestial",
        "bi",
        "Big breasts",
        "big penis",
        "Bikini",
        "Biquíni",
        "bisexual",
        "Bishoujo Senshi Sailor Moon",
        "Bissexual",
        "Bkaunyuu",
        "Bleach",
        "Bloomers",
        "Blooomers",
        "Blowjob",
        "Bodysuit",
        "Bonage",
        "Bondage",
        "Bongade",
        "Brinquedos",
        "Brinquedos Sexuais",
        "Bronzeada",
        "Bronzeado",
        "Bronzeado(a)",
        "Bronzeamento",
        "Bruxa",
        "BSDM",
        "Bukakke",
        "Bukkake",
        "Bunda Grande",
        "Bundão",
        "Bunduda",
        "BWC",
        "Cabeluda",
        "Calcinha",
        "Camisinha",
        "Camisola",
        "Campione!",
        "Campus",
        "cannabis",
        "Casada",
        "Centauro",
        "Centauro(a)",
        "CEO",
        "Chantagem",
        "Chobits",
        "Clannad",
        "Clorofórmio",
        "Clorofórmo",
        "Club",
        "Code Geass",
        "Coelgial",
        "Coelhinha",
        "Coelhinho",
        "Colã",
        "Colegial",
        "Colegual",
        "Coleigal",
        "Coleira",
        "Colorida",
        "Colorido",
        "Comédia",
        "Condage",
        "Consolo",
        "Controle da Mente",
        "Controle Mental",
        "Coprofilia",
        "Corrupção",
        "Cosplay",
        "cosplaying",
        "Creampie",
        "Crosdressing",
        "Cross-Dressing",
        "Crossdresing",
        "Crossdressing",
        "Crossdressinh",
        "Cunhada",
        "Cuntboy",
        "Dakr Skin",
        "Dança",
        "Dance In The Vampire Bund",
        "Dark Skin",
        "Darki Skin",
        "Darkstalkers",
        "Defloração",
        "Demônio",
        "Demônios",
        "Dildo",
        "DILF",
        "Dokidoki! PreCure",
        "Dormindo",
        "Dragonaut",
        "Drama",
        "Dream C Club",
        "Drogas",
        "Drunk",
        "Dupla Penetração",
        "Ecchi",
        "Elf",
        "Elfa",
        "Elfas",
        "Elfo(a)",
        "Elfos",
        "Embriaguez",
        "Empregada",
        "Enema",
        "Enfemeira",
        "Enfermeira",
        "Engravidando",
        "Esapnhola",
        "Escolar",
        "Escrava",
        "Escravidão",
        "Escravo(a)",
        "Espanhol",
        "Espanhola",
        "Esporte",
        "Esportes",
        "Esposa",
        "Espsanhola",
        "Esspanhola",
        "Estrangeira",
        "Exibicionismo",
        "eye-covering bang",
        "Facial",
        "Familia",
        "Fantasia",
        "Fantasma",
        "Fantasy",
        "Fate/hollow ataraxia",
        "Fate/stay night",
        "Fecundação",
        "Femdom",
        "Femdom.Espanhola",
        "feminization",
        "Fetiche por Axila",
        "Fetiches",
        "Fezes",
        "ffm threesome",
        "Ficção",
        "Ficcção",
        "Filha",
        "Filho",
        "Filho(a)",
        "Filho(a)Dupla Penetração",
        "Filmagem",
        "Filmando",
        "Final Fantasy X-2",
        "Final Fantasy XII",
        "Final Fantasy XIII​",
        "Fisting",
        "Footjob",
        "Freira",
        "Fresh PreCure!",
        "Full color",
        "Furry",
        "Futanari",
        "Futanari com Futanari",
        "Futanari on Futanari",
        "Futanari on Futanarin",
        "Futanari on Male",
        "Gaping",
        "Garçonete",
        "Garganta Profunda",
        "Gargantilha",
        "Gargantilho",
        "Garota Demônio",
        "Garota Mágica",
        "Garota Monstro",
        "Garoto de sorte",
        "Gêmeas",
        "Gêmeos",
        "Gêmeos(as)",
        "Gender bender",
        "Genderbend",
        "Genshiken",
        "Gigante",
        "Gintama",
        "Glasses",
        "Goblin",
        "Gordinha",
        "Gordinho(a)",
        "Gordinhoi(a)",
        "Gozando Junto",
        "Grávida",
        "Gravidez",
        "Gruapl",
        "Grupal",
        "Grupal.Incesto",
        "GrupalIncesto",
        "Grupla",
        "Grupo",
        "Gundam Build Fighters",
        "Gundam Unicorn",
        "Guri",
        "Guro",
        "Gyaru",
        "H-Mangá",
        "Happy Sex",
        "Hardcore",
        "Harém",
        "Harry Potter",
        "Hase Yuu",
        "Hentai",
        "Hikawa Yuuki",
        "Hipnose",
        "Historical",
        "Histórico",
        "Horror",
        "Humilhação",
        "Humor",
        "Idols",
        "Impregnação",
        "Incesot",
        "Incest",
        "Incesto",
        "Incesto.Crossdressing",
        "inconsciente",
        "Inseki",
        "Inseto",
        "Invisível",
        "Irmã",
        "Irmã mais velha",
        "Irmã(ã)",
        "Irmão",
        "Irmão(ã)",
        "Irmãos",
        "Irmãs",
        "Isekai",
        "Jaleco",
        "Jogos",
        "Josei",
        "Kemonomimi",
        "Kimono",
        "King of Fighters",
        "kissing",
        "Kogal",
        "Kunoichi",
        "Lactação",
        "Lâmia",
        "Latex",
        "Lesbica",
        "Líder de Torcida",
        "Lingeire",
        "Lingeri",
        "Lingeria",
        "Lingerie",
        "Loja",
        "Madrasta",
        "Maduro",
        "Mãe",
        "Magia",
        "Maid",
        "Maiô",
        "Maiô.Sumata",
        "Mais",
        "Mamilo Invertido",
        "Marquinha",
        "Masoquismo",
        "Massagem",
        "Masturabação",
        "Masturbação",
        "Mature",
        "Meia",
        "Meia Calça",
        "Meia Creampie",
        "Meia Longa",
        "Meledom",
        "Menage",
        "Metrô",
        "Miko",
        "MILF",
        "Militar",
        "Mind Break",
        "Mind Breka",
        "Mind Creampie",
        "Mistério",
        "Mobile Suit Gundam Unicorn",
        "Monstro",
        "Monstros",
        "Mordaça",
        "Morena",
        "Mosntro",
        "Murim",
        "Musculos",
        "Mystery",
        "Nakadashi",
        "namorada",
        "Necrofilia",
        "Negras",
        "Neko",
        "Neotrare",
        "Neto(a)",
        "Netorare",
        "Netorarea",
        "Netori",
        "Ninja",
        "Noiva",
        "Noivo(a)",
        "NTR",
        "Óculos",
        "Onahole",
        "Oni",
        "Onsen",
        "Oral",
        "Orc",
        "Orgasmo",
        "Overlord",
        "Oyakodon",
        "Pai",
        "Paizuri",
        "Palmada",
        "Paradise",
        "Parto",
        "Pau Grande",
        "Peiõtes",
        "Peitihnos",
        "Peitinho",
        "Peitinhos",
        "PeitinhosTsundere",
        "Peitõe",
        "Peitões",
        "Peitões.Primo(a)",
        "Peitos Enormes",
        "Peitos Grande",
        "Peitos Grandes",
        "Peittões",
        "Pelos Pubianos",
        "Penetração Dupla",
        "Petiões",
        "Piercing",
        "Pintura Corporal",
        "Po-ju",
        "Policial",
        "Ponytail",
        "Possessão",
        "Praia",
        "Preservativo",
        "Prima",
        "Prima(o)",
        "Primeira Vez",
        "Primo",
        "Primo(a)",
        "Prisioneiro(a)",
        "Profeesor(a)",
        "Professor",
        "Professor(a)",
        "Professor(a)Oral",
        "Prostitui;'ao",
        "Prostituição",
        "Prostituilção",
        "prostitution",
        "Psicológico",
        "Raio-X",
        "rape",
        "Reencarnação",
        "regressão de idade",
        "Relacionamento secreto",
        "Revenge",
        "Robô Sexual",
        "Romance",
        "Ruiva",
        "Sailor Suit",
        "Scat",
        "School girl",
        "School Life",
        "school uniform",
        "Schoolboy uniform",
        "Schoolgirl uniform",
        "Sci-fi",
        "Sedução",
        "Seinen",
        "Seios Grandes",
        "Seios Pequenos",
        "Sem Censura",
        "Sensei",
        "Sereia",
        "sex stoy",
        "Sex Toy",
        "Sex Toys",
        "Sexo em Público",
        "Shimapan",
        "Shota",
        "Shoujo",
        "Shoujo Ai",
        "Shounen",
        "Shounen Ai",
        "Sinen",
        "sissy",
        "Slice of Life",
        "Smut",
        "Sobrenatural",
        "Sobrevivência",
        "Sobrinha",
        "Sobrinho",
        "Sobrinho(a)",
        "Sobrinho(a)mFilha",
        "sole female",
        "sole male",
        "Solo Female",
        "Solo Male",
        "sonho",
        "Squirt",
        "Squirting",
        "Squrting",
        "Stocking",
        "Stockings",
        "Strap-on",
        "Strpa-on",
        "Suamata",
        "Succubus",
        "Súcubo",
        "Sumata",
        "Supernatural",
        "Swimsuit",
        "Takese Yuu",
        "Tamboy",
        "tankoubon",
        "Tapa-olho",
        "Tatuagem na Virilha",
        "Tentáculos",
        "Terror",
        "Tia",
        "Tio",
        "Tio(a)",
        "Toddler",
        "Toddlercon",
        "tomboy",
        "Tomgimrl",
        "Tomgirl",
        "Tomgirl (Gay)",
        "Tomgirl Femdom",
        "Tomrgirl",
        "Tomrigl",
        "Tortura",
        "Tragédia",
        "Traição",
        "Transformação",
        "Transformação de Sexo",
        "Transsexual",
        "Trap",
        "Travesit",
        "Travesti",
        "Treinadora",
        "Triação",
        "Tribadism",
        "Tribadismo",
        "Troca de Corpos",
        "Tsundere",
        "Uniforme Escolar",
        "Urina",
        "Vampiro",
        "Vanila",
        "Vanilla",
        "Velho",
        "Velhote",
        "Vellhote",
        "Venda",
        "Vida Cotidiana",
        "Vida Escolar",
        "Vingança",
        "virgem",
        "Viúva",
        "Vore",
        "Voyerismo",
        "Voyeur",
        "Voyeurismo",
        "Voyeurismoão(ã)",
        "Webtoon",
        "Wolf Girl",
        "Wuxia",
        "X-Ray",
        "Yamamoto Ryuusuke",
        "Yandere",
        "Yaoi",
        "Yukata",
        "Yuri",
        "Zombie",
        "Zoofilia",
        "Zumbi",
    )
}
