package eu.kanade.tachiyomi.extension.fr.astralmanga

import eu.kanade.tachiyomi.source.model.Filter
import eu.kanade.tachiyomi.source.model.FilterList

class SortFilter(displayName: String, vals: Array<Pair<String, String>>) : UriPartFilter(displayName, vals)
class StatusFilter(displayName: String, vals: Array<Pair<String, String>>) : UriPartFilter(displayName, vals)
class TypeFilter(displayName: String, vals: Array<Pair<String, String>>) : UriPartFilter(displayName, vals)

class Genre(name: String) : Filter.CheckBox(name)
class GenreFilter(displayName: String, genres: List<Genre>) : Filter.Group<Genre>(displayName, genres)

open class UriPartFilter(displayName: String, val vals: Array<Pair<String, String>>) : Filter.Select<String>(displayName, vals.map { it.first }.toTypedArray()) {
    fun toUriPart() = vals[state].second
}

fun getFilters() = FilterList(
    SortFilter("Trier par", getSortList()),
    Filter.Separator(),
    StatusFilter("Statut", getStatusList()),
    Filter.Separator(),
    TypeFilter("Type", getTypeList()),
    Filter.Separator(),
    GenreFilter("Genres", getGenreList()),
)

private fun getSortList() = arrayOf(
    Pair("Popularité", "popularity"),
    Pair("Titre", "title"),
    Pair("Note", "note"),
    Pair("Date de création", "createdAt"),
    Pair("Date de publication", "publishDate"),
)

private fun getStatusList() = arrayOf(
    Pair("Tout", ""),
    Pair("En cours", "ON_GOING"),
    Pair("Terminé", "COMPLETED"),
    Pair("En pause", "HIATUS"),
    Pair("Annulé", "CANCELLED"),
)

private fun getTypeList() = arrayOf(
    Pair("Tout", ""),
    Pair("Manga", "MANGA"),
    Pair("Manhwa", "MANHWA"),
    Pair("Manhua", "MANHUA"),
    Pair("Novel", "NOVEL"),
)

private fun getGenreList() = listOf(
    Genre("Action"),
    Genre("Adolescence"),
    Genre("Agriculture"),
    Genre("Alchimie"),
    Genre("Alcool"),
    Genre("Aliens / Extra-terrestres"),
    Genre("Alpinisme"),
    Genre("Amitié"),
    Genre("Amnésie"),
    Genre("Amour"),
    Genre("Anges"),
    Genre("Animaux"),
    Genre("Antiquité"),
    Genre("Antropomorphisme"),
    Genre("Apocalypse"),
    Genre("Apprentissage"),
    Genre("Archéologie"),
    Genre("Art"),
    Genre("Artisanat"),
    Genre("Arts martiaux"),
    Genre("Assassinat"),
    Genre("Astronomie"),
    Genre("Athlétisme"),
    Genre("Autre monde"),
    Genre("Aventure"),
    Genre("Aviation"),
    Genre("Avocat"),
    Genre("Bara"),
    Genre("Baseball"),
    Genre("Basketball"),
    Genre("Boxe"),
    Genre("Calligraphie"),
    Genre("Campagne"),
    Genre("Camping"),
    Genre("Cannibalisme"),
    Genre("Catch"),
    Genre("Chant"),
    Genre("Chantage"),
    Genre("Chasseur de prime"),
    Genre("Chevalerie"),
    Genre("Cinéma"),
    Genre("Cirque"),
    Genre("Clonage"),
    Genre("Club"),
    Genre("Colocation"),
    Genre("Combats"),
    Genre("Comédie"),
    Genre("Cosplay"),
    Genre("Couture"),
    Genre("Crime"),
    Genre("Crossdressing"),
    Genre("Crossover"),
    Genre("Culture"),
    Genre("Cybernétique"),
    Genre("Cyberpunk"),
    Genre("Cyborgs"),
    Genre("Cyclisme"),
    Genre("Célibat"),
    Genre("Danse"),
    Genre("Dieux / Déesses"),
    Genre("Dinosaures"),
    Genre("Discrimination"),
    Genre("Divorce"),
    Genre("Dragons"),
    Genre("Drame"),
    Genre("Drogue"),
    Genre("Dystopie"),
    Genre("Délinquance"),
    Genre("Démons"),
    Genre("Détective"),
    Genre("E-sport"),
    Genre("Ecchi"),
    Genre("Elfe"),
    Genre("Enlèvement"),
    Genre("Enquête"),
    Genre("Erotique"),
    Genre("Escalade"),
    Genre("Esclavage"),
    Genre("Espace"),
    Genre("Espionnage"),
    Genre("Famille"),
    Genre("Fantastique"),
    Genre("Fantasy"),
    Genre("Fantômes"),
    Genre("Folklore"),
    Genre("Football"),
    Genre("Furyo"),
    Genre("Futur"),
    Genre("Fée"),
    Genre("Fétichisme"),
    Genre("Gastronomie"),
    Genre("Geisha"),
    Genre("Gender Bender"),
    Genre("Golf"),
    Genre("Gore"),
    Genre("Guerre"),
    Genre("Gyaru"),
    Genre("Gymnastique"),
    Genre("Hacking"),
    Genre("Handicap"),
    Genre("Handisport"),
    Genre("Harcèlement"),
    Genre("Harem"),
    Genre("Harem inversé"),
    Genre("Histoire"),
    Genre("Historique"),
    Genre("Homme-Bête"),
    Genre("Homosexualité"),
    Genre("Horreur"),
    Genre("Héritage"),
    Genre("Idols"),
    Genre("Ijime"),
    Genre("Immortalité"),
    Genre("Inceste"),
    Genre("Isekai"),
    Genre("Jardinage"),
    Genre("Jazz"),
    Genre("Jeu d'argent"),
    Genre("Jeunesse"),
    Genre("Jeux"),
    Genre("Jeux vidéo"),
    Genre("Josei"),
    Genre("Journalisme"),
    Genre("Judo"),
    Genre("Justice"),
    Genre("Kabuki"),
    Genre("Karaté"),
    Genre("Kemonomimi"),
    Genre("Kendo"),
    Genre("Kodomo"),
    Genre("Littérature"),
    Genre("Lutte"),
    Genre("Lycanthropes"),
    Genre("Mafia"),
    Genre("Magical girl"),
    Genre("Magie"),
    Genre("Mahjong"),
    Genre("Maids"),
    Genre("Majordome"),
    Genre("Maladie"),
    Genre("Maltraitance"),
    Genre("Malédiction"),
    Genre("Maquillage"),
    Genre("Mariage"),
    Genre("Maritime"),
    Genre("Maternité"),
    Genre("Mature"),
    Genre("Mechas"),
    Genre("Mensonges"),
    Genre("Militaire"),
    Genre("Mode"),
    Genre("Monde virtuel"),
    Genre("Monster Girl"),
    Genre("Monstres"),
    Genre("Montagne"),
    Genre("Mort"),
    Genre("Musique"),
    Genre("Mystère"),
    Genre("Mythologie"),
    Genre("Médecine"),
    Genre("Médiéval"),
    Genre("Natation"),
    Genre("Nature"),
    Genre("Nekketsu"),
    Genre("Ninjas"),
    Genre("Noblesse"),
    Genre("Nostalgie"),
    Genre("Nucléaire"),
    Genre("One Shot"),
    Genre("Organisations secrètes"),
    Genre("Otaku"),
    Genre("Paranormal"),
    Genre("Parodie"),
    Genre("Patinage artistique"),
    Genre("Pauvreté"),
    Genre("Peinture / dessin"),
    Genre("Perversité"),
    Genre("Philosophie"),
    Genre("Photographie"),
    Genre("Ping-pong"),
    Genre("Pirates"),
    Genre("Police"),
    Genre("Politique"),
    Genre("Pompier"),
    Genre("Post-apocalyptique"),
    Genre("Poupées"),
    Genre("Pouvoirs psychiques"),
    Genre("Poésie"),
    Genre("Prison"),
    Genre("Prostitution"),
    Genre("Préhistoire"),
    Genre("Psychologique"),
    Genre("Pêche"),
    Genre("Quotidien"),
    Genre("Racisme"),
    Genre("Radio"),
    Genre("Rap"),
    Genre("Religion"),
    Genre("Requins"),
    Genre("Robots"),
    Genre("Rock"),
    Genre("Romance"),
    Genre("Royauté"),
    Genre("Rugby"),
    Genre("Réincarnation / Transmigration"),
    Genre("Réseaux sociaux"),
    Genre("Rêves"),
    Genre("Samouraïs"),
    Genre("School Life"),
    Genre("Science-Fantasy"),
    Genre("Science-Fiction"),
    Genre("Scientifique"),
    Genre("Secrets"),
    Genre("Secte"),
    Genre("Seinen"),
    Genre("Sentai"),
    Genre("Sexe"),
    Genre("Sexisme"),
    Genre("Shinigami"),
    Genre("Shojo"),
    Genre("Shonen"),
    Genre("Shôjo-aï"),
    Genre("Shônen-aï"),
    Genre("Sirène"),
    Genre("Slice of Life"),
    Genre("Société"),
    Genre("Solitude"),
    Genre("Sorcellerie"),
    Genre("Sport"),
    Genre("Sports mécaniques"),
    Genre("Steampunk"),
    Genre("Suicide"),
    Genre("Super pouvoirs"),
    Genre("Super-héros"),
    Genre("Surnaturel"),
    Genre("Survie"),
    Genre("Survival game"),
    Genre("Séisme"),
    Genre("Technologies"),
    Genre("Teens' Love"),
    Genre("Tennis"),
    Genre("Terrorisme"),
    Genre("Thriller"),
    Genre("Théâtre"),
    Genre("Tir à l'arc"),
    Genre("Tokusatsu"),
    Genre("Torture"),
    Genre("Tournois"),
    Genre("Traditions"),
    Genre("Tragique"),
    Genre("Train"),
    Genre("Transidentité"),
    Genre("Traumatisme"),
    Genre("Travail"),
    Genre("Triangle amoureux"),
    Genre("Tsunami"),
    Genre("Téléréalité"),
    Genre("Univers alternatif"),
    Genre("Université"),
    Genre("Vampires"),
    Genre("Vengeance"),
    Genre("Viking"),
    Genre("Viol"),
    Genre("Virginité"),
    Genre("Volley-ball"),
    Genre("Voyage"),
    Genre("Voyage temporel"),
    Genre("WTF"),
    Genre("Western"),
    Genre("Yakuza"),
    Genre("Yaoi"),
    Genre("Yonkoma"),
    Genre("Yuri"),
    Genre("Yōkai"),
    Genre("Zombies"),
    Genre("École"),
    Genre("Écologie"),
    Genre("Économie"),
    Genre("Écriture"),
    Genre("Équitation"),
)
