package eu.kanade.tachiyomi.extension.pt.manhastro

import eu.kanade.tachiyomi.source.model.Filter
import eu.kanade.tachiyomi.source.model.FilterList

fun getFilters() = FilterList(
    SortFilter(),
    Filter.Separator(),
    Filter.Header("Tipo"),
    TypeFilter(getTypeList()),
    Filter.Separator(),
    Filter.Header("Gêneros"),
    GenreFilter(getGenreList()),
)

class SortFilter : Filter.Select<String>(
    "Ordenar por",
    SORT_OPTIONS.map { it.first }.toTypedArray(),
) {
    val selected get() = SORT_OPTIONS[state].second

    companion object {
        private val SORT_OPTIONS = listOf(
            "Mais Popular" to "popular",
            "Mais Recente" to "recent",
            "Título (A-Z)" to "alphabetical",
            "Mais Capítulos" to "chapters",
        )
    }
}

class TypeFilter(types: List<Pair<String, String>>) : Filter.Group<TypeCheckBox>(
    "Tipos",
    types.map { TypeCheckBox(it.first, it.second) },
)

class TypeCheckBox(name: String, val value: String) : Filter.CheckBox(name, false)

private fun getTypeList() = listOf(
    "Manhwa" to "Manhwa",
    "Manhua" to "Manhua",
    "Manga" to "Manga",
    "Webtoon" to "Webtoon",
    "Novel" to "Novel",
)

class GenreFilter(genres: List<Pair<String, String>>) : Filter.Group<GenreCheckBox>(
    "Gêneros",
    genres.map { GenreCheckBox(it.first, it.second) },
)

class GenreCheckBox(name: String, val value: String) : Filter.CheckBox(name, false)

private fun getGenreList() = listOf(
    "4-koma" to "4-koma",
    "Ação" to "ação",
    "Adaptação" to "adaptação",
    "Adaptation" to "adaptation",
    "Adulto" to "adulto",
    "Aliens" to "aliens",
    "Animais" to "animais",
    "Animals" to "animals",
    "Anthology" to "anthology",
    "Apocalipse" to "apocalipse",
    "Argos" to "argos",
    "Artes Marciais" to "artes marciais",
    "Ativo" to "ativo",
    "Atualização" to "atualização",
    "Auto-publicado" to "auto-publicado",
    "Aventura" to "aventura",
    "Award Winning" to "award winning",
    "BL" to "bl",
    "Bizarro" to "bizarro",
    "Comédia" to "comédia",
    "Completo" to "completo",
    "Cooking" to "cooking",
    "Crime" to "crime",
    "Crossdressing" to "crossdressing",
    "Culinária" to "culinária",
    "Cultivo" to "cultivo",
    "Delinquents" to "delinquents",
    "Demônios" to "demônios",
    "Deuses" to "deuses",
    "Doujinshi" to "doujinshi",
    "Drama" to "drama",
    "Ecchi" to "ecchi",
    "Escola" to "escola",
    "Esporte" to "esporte",
    "Esportes" to "esportes",
    "FKscan" to "fkscan",
    "Familia" to "familia",
    "Fantasia" to "fantasia",
    "Ficção Científica" to "ficção científica",
    "Filosófico" to "filosófico",
    "Full Color" to "full color",
    "Genérico" to "genérico",
    "Gender Bender" to "gender bender",
    "Ghosts" to "ghosts",
    "Gore" to "gore",
    "Guerra" to "guerra",
    "Gyaru" to "gyaru",
    "Harém" to "harém",
    "Histórico" to "histórico",
    "Horror" to "horror",
    "Incest" to "incest",
    "Isekai" to "isekai",
    "Josei" to "josei",
    "Kamen Rider" to "kamen rider",
    "Linha do Tempo" to "linha do tempo",
    "Loli" to "loli",
    "Long Strip" to "long strip",
    "Luta" to "luta",
    "Médico" to "médico",
    "Música" to "música",
    "Mafia" to "mafia",
    "Magia" to "magia",
    "Mecha" to "mecha",
    "Mechas" to "mechas",
    "Militar" to "militar",
    "Mistério" to "mistério",
    "Moderno" to "moderno",
    "Monster Girls" to "monster girls",
    "Monstros" to "monstros",
    "Murim" to "murim",
    "Music" to "music",
    "NextSakura Scan" to "nextsakura scan",
    "Ninja" to "ninja",
    "Nitury Scan" to "nitury scan",
    "Office Workers" to "office workers",
    "Official Colored" to "official colored",
    "One Shot" to "one shot",
    "Oneshot" to "oneshot",
    "Police" to "police",
    "Policial" to "policial",
    "Post-Apocalyptic" to "post-apocalyptic",
    "Psicológico" to "psicológico",
    "Reencarnação" to "reencarnação",
    "Regressão" to "regressão",
    "Reincarnation" to "reincarnation",
    "Reverse Harem" to "reverse harem",
    "Romance" to "romance",
    "Sagrado Império da Britannia" to "sagrado império da britannia",
    "Saint Seiya" to "saint seiya",
    "Samurai" to "samurai",
    "School Life" to "school life",
    "Seinen" to "seinen",
    "Sempre ao seu lado Scan" to "sempre ao seu lado scan",
    "Shota" to "shota",
    "Shoujo" to "shoujo",
    "Shoujo Ai" to "shoujo ai",
    "Shounen" to "shounen",
    "Shounen Ai" to "shounen ai",
    "Sistema" to "sistema",
    "Slice of Life" to "slice of life",
    "Sobrenatural" to "sobrenatural",
    "Sobrevivência" to "sobrevivência",
    "Super Poderes" to "super poderes",
    "Super-herói" to "super-herói",
    "Supernatural" to "supernatural",
    "Survival" to "survival",
    "Suspense" to "suspense",
    "Terror" to "terror",
    "Thriller" to "thriller",
    "Time Travel" to "time travel",
    "Tokusatsu" to "tokusatsu",
    "Tragédia" to "tragédia",
    "Vampires" to "vampires",
    "Vampiros" to "vampiros",
    "Vida Escolar" to "vida escolar",
    "Video Games" to "video games",
    "Villainess" to "villainess",
    "Vingança" to "vingança",
    "Volta no Tempo" to "volta no tempo",
    "Wuxia" to "wuxia",
    "Yaoi" to "yaoi",
    "Yuri" to "yuri",
    "Zombies" to "zombies",
    "jogos" to "jogos",
    "shonen ai" to "shonen ai",
)
