package eu.kanade.tachiyomi.extension.it.hentaifantasy

import eu.kanade.tachiyomi.source.model.Filter

internal class Tag(name: String, val id: Int) : Filter.CheckBox(name)
internal class TagList(title: String, tags: List<Tag>) : Filter.Group<Tag>(title, tags)

internal fun getTagList() = listOf(
    Tag("Ahegao", 56),
    Tag("Anal", 28),
    Tag("Ashikoki", 12),
    Tag("Bestiality", 24),
    Tag("Bizzare", 44),
    Tag("Bondage", 30),
    Tag("Cheating", 33),
    Tag("Chubby", 57),
    Tag("Dark Skin", 39),
    Tag("Demon Girl", 43),
    Tag("Femdom", 38),
    Tag("Forced", 46),
    Tag("Full color", 52),
    Tag("Furry", 36),
    Tag("Futanari", 18),
    Tag("Group", 34),
    Tag("Guro", 8),
    Tag("Harem", 41),
    Tag("Housewife", 51),
    Tag("Incest", 11),
    Tag("Lolicon", 20),
    Tag("Maid", 55),
    Tag("Milf", 31),
    Tag("Monster Girl", 15),
    Tag("Nurse", 49),
    Tag("Oppai", 25),
    Tag("Paizuri", 42),
    Tag("Pettanko", 35),
    Tag("Pissing", 32),
    Tag("Public", 53),
    Tag("Rape", 21),
    Tag("Schoolgirl", 27),
    Tag("Shotacon", 26),
    Tag("Stockings", 40),
    Tag("Swimsuit", 47),
    Tag("Tanlines", 48),
    Tag("Teacher", 50),
    Tag("Tentacle", 23),
    Tag("Toys", 45),
    Tag("Trap", 29),
    Tag("Tsundere", 54),
    Tag("Uncensored", 59),
    Tag("Vanilla", 19),
    Tag("Yandere", 58),
    Tag("Yaoi", 22),
    Tag("Yuri", 14),
)
