package eu.kanade.tachiyomi.extension.pt.pointzerotoons

import eu.kanade.tachiyomi.source.model.Filter

val sortFilterList = listOf(
    Pair("popular", "Popular"),
    Pair("updated", "Atualizados"),
    Pair("title", "Título (A-Z)"),
)

val statusFilterList = listOf(
    Pair("", "Todos"),
    Pair("Ongoing", "Ongoing"),
    Pair("Completed", "Completed"),
    Pair("Hiatus", "Hiatus"),
    Pair("Dropped", "Dropped"),
    Pair("on-going", "on-going"),
    Pair("Canceled", "Canceled"),
)

val typeFilterList = listOf(
    Pair("", "Todos"),
    Pair("Manga", "Manga"),
    Pair("Manhwa", "Manhwa"),
    Pair("Manhua", "Manhua"),
    Pair("One Shot", "One Shot"),
    Pair("Comic", "Comic"),
)

val genreFilterList = listOf(
    Pair("", "Todos"),
    Pair("4-koma", "4-koma"),
    Pair("acao", "Ação"),
    Pair("acao-social", "Ação Social"),
    Pair("action", "Action"),
    Pair("adaptacao", "Adaptação"),
    Pair("adulto", "Adulto"),
    Pair("adventure", "Adventure"),
    Pair("alienigenas", "Alienígenas"),
    Pair("aliens", "Aliens"),
    Pair("amnesia", "Amnésia"),
    Pair("amor-entre-garotas", "Amor Entre Garotas"),
    Pair("animais", "Animais"),
    Pair("animal", "Animal"),
    Pair("anti-heroi", "Antí-Herói"),
    Pair("antologia", "Antologia"),
    Pair("apocalipse", "Apocalipse"),
    Pair("apocaliptico", "Apocalíptico"),
    Pair("argos", "Argos"),
    Pair("armas", "Armas"),
    Pair("artes-marciais", "Artes Marciais"),
    Pair("aventura", "Aventura"),
    Pair("basquete", "Basquete"),
    Pair("carros", "Carros"),
    Pair("casamento", "casamento"),
    Pair("colegial", "colegial"),
    Pair("colorido", "colorido"),
    Pair("comedia", "Comédia"),
    Pair("comedy", "Comedy"),
    Pair("conspiracao", "Conspiração"),
    Pair("cooking", "Cooking"),
    Pair("corrida", "corrida"),
    Pair("cotidiano", "Cotidiano"),
    Pair("cowboys", "Cowboys"),
    Pair("cozinha", "Cozinha"),
    Pair("crime", "Crime"),
    Pair("culinaria", "Culinária"),
    Pair("cultivo", "Cultivo"),
    Pair("danca", "Dança"),
    Pair("delinquentes", "Delinquentes"),
    Pair("delinquents", "Delinquents"),
    Pair("deliquentes", "Deliquentes"),
    Pair("demonio", "Demônio"),
    Pair("demonios", "Demônios"),
    Pair("doujinshi", "Doujinshi"),
    Pair("dragoes", "Dragões"),
    Pair("drama", "Drama"),
    Pair("dungeon", "Dungeon"),
    Pair("ecchi", "Ecchi"),
    Pair("erotico", "erotico"),
    Pair("escolar", "Escolar"),
    Pair("escritorio", "Escritório"),
    Pair("esporte", "Esporte"),
    Pair("esportes", "Esportes"),
    Pair("exploracao", "Exploração"),
    Pair("familia", "Família"),
    Pair("fantasia", "Fantasia"),
    Pair("fantasia-sombria", "Fantasia Sombria"),
    Pair("fantasma", "Fantasma"),
    Pair("fantasy", "Fantasy"),
    Pair("ficcao", "Ficção"),
    Pair("ficcao-cientifica", "Ficção Científica"),
    Pair("filme-de-acao", "Filme de ação"),
    Pair("filosofico", "Filosófico"),
    Pair("full-color", "Full color"),
    Pair("gamelit", "GameLit"),
    Pair("games-tradicionais", "Games tradicionais"),
    Pair("gangues", "Gangues"),
    Pair("garotas-magicas", "Garotas Mágicas"),
    Pair("garotas-monstro", "Garotas Monstro"),
    Pair("gender-bender", "Gender Bender"),
    Pair("girlslove", "Girls'Love"),
    Pair("gore", "Gore"),
    Pair("gyaru", "Gyaru"),
    Pair("habilidades", "Habilidades"),
    Pair("harem", "Harém"),
    Pair("harem-reverso", "Harém Reverso"),
    Pair("historica", "Histórica"),
    Pair("historico", "Histórico"),
    Pair("horro", "horro"),
    Pair("horror", "Horror"),
    Pair("isek", "isek"),
    Pair("isekai", "Isekai"),
    Pair("jogo", "Jogo"),
    Pair("jogos", "Jogos"),
    Pair("jogos-de-video", "Jogos de vídeo"),
    Pair("josei", "Josei"),
    Pair("loli", "Loli"),
    Pair("long-strip", "Long Strip"),
    Pair("luta", "Luta"),
    Pair("maduro", "Maduro"),
    Pair("mafia", "Máfia"),
    Pair("magia", "Magia"),
    Pair("manhua", "Manhua"),
    Pair("manhwa", "Manhwa"),
    Pair("martial-arts", "Martial Arts"),
    Pair("mecha", "Mecha"),
    Pair("medicina", "Medicina"),
    Pair("medico", "Médico"),
    Pair("medieval", "Medieval"),
    Pair("militar", "Militar"),
    Pair("misterio", "Mistério"),
    Pair("mitologia", "Mitologia"),
    Pair("monstros", "Monstros"),
    Pair("mundo-virtual", "Mundo Virtual"),
    Pair("murim", "Murim"),
    Pair("musica", "Música"),
    Pair("mystery", "Mystery"),
    Pair("necromancia", "Necromancia"),
    Pair("ninja", "Ninja"),
    Pair("office-workers", "Office Workers"),
    Pair("one", "One"),
    Pair("oneshot", "Oneshot"),
    Pair("pets", "Pets"),
    Pair("policial", "Policial"),
    Pair("pos-apocaliptico", "Pós-Apocalíptico"),
    Pair("premiado", "Premiado"),
    Pair("protagonista-feminina", "protagonista Feminina"),
    Pair("protagonista-genio", "Protagonista gênio"),
    Pair("protagonista-masculino", "Protagonista Masculino"),
    Pair("psicologico", "Psicológico"),
    Pair("psychological", "Psychological"),
    Pair("rakugo", "Rakugo"),
    Pair("realidade-virtual", "Realidade Virtual"),
    Pair("reencarnacao", "Reencarnação"),
    Pair("regressao", "Regressão"),
    Pair("regressao-deslizamento-temporal", "Regressão/Deslizamento Temporal"),
    Pair("reincarnation", "Reincarnation"),
    Pair("retorno", "Retorno"),
    Pair("romance", "Romance"),
    Pair("samurai", "Samurai"),
    Pair("sangue", "Sangue"),
    Pair("sci-fi", "SCI-FI"),
    Pair("seinen", "Seinen"),
    Pair("shonen", "shonen"),
    Pair("shota", "Shota"),
    Pair("shoujo", "Shoujo"),
    Pair("shounen", "Shounen"),
    Pair("shounen-tipo", "Shounen Tipo"),
    Pair("sistema", "Sistema"),
    Pair("sistema-de-jogo", "Sistema de Jogo"),
    Pair("slice-of-life", "Slice of Life"),
    Pair("smut", "Smut"),
    Pair("sobrenatural", "Sobrenatural"),
    Pair("sobrevivencia", "Sobrevivência"),
    Pair("steampunk", "Steampunk"),
    Pair("sugestivo", "Sugestivo"),
    Pair("super-poderes", "Super Poderes"),
    Pair("super-heroi", "Super-Herói"),
    Pair("supernatural", "Supernatural"),
    Pair("survival", "Survival"),
    Pair("suspense", "Suspense"),
    Pair("terror", "Terror"),
    Pair("thriller", "Thriller"),
    Pair("tira-longa", "Tira Longa"),
    Pair("tiro", "Tiro"),
    Pair("trabalhadores-de-escritorio", "Trabalhadores de Escritório"),
    Pair("tragedia", "Tragédia"),
    Pair("tragedias", "Tragédias"),
    Pair("transmigracao", "Transmigração"),
    Pair("tregedia", "Tregédia"),
    Pair("triangulo-amoroso", "Triângulo Amoroso"),
    Pair("troca-de-genero", "Troca de Gênero"),
    Pair("um-recorte-da-vida", "Um recorte da vida"),
    Pair("vampiros", "Vampiros"),
    Pair("viagem-dimensional", "Viagem Dimensional"),
    Pair("viagem-no-tempo", "Viagem no Tempo"),
    Pair("vida", "Vida"),
    Pair("vida-escolar", "Vida Escolar"),
    Pair("video-games", "Video Games"),
    Pair("viking", "Viking"),
    Pair("vila", "Vilã"),
    Pair("vinganca", "Vingança"),
    Pair("violencia", "violencia"),
    Pair("web-comic", "Web Comic"),
    Pair("webcomic", "Webcomic"),
    Pair("webtoon", "Webtoon"),
    Pair("wuxia", "Wuxia"),
    Pair("xianxia", "Xianxia"),
    Pair("xuanhuan", "Xuanhuan"),
    Pair("yaoi", "Yaoi"),
    Pair("yuri", "Yuri"),
    Pair("zombie", "Zombie"),
    Pair("zumbi", "Zumbi"),
)

class SortFilter(sortables: Array<String>) : Filter.Select<String>("Ordenar por", sortables)

class StatusFilter(statuses: Array<String>) : Filter.Select<String>("Status", statuses)

class TypeFilter(types: Array<String>) : Filter.Select<String>("Tipo", types)

class GenreFilter(genres: Array<String>) : Filter.Select<String>("Gênero", genres)
