package eu.kanade.tachiyomi.extension.id.lumoskomik

import eu.kanade.tachiyomi.source.model.Filter
import eu.kanade.tachiyomi.source.model.FilterList

abstract class SelectFilter(
    name: String,
    private val options: Array<Pair<String, String>>,
    state: Int = 0,
) : Filter.Select<String>(name, options.map { it.first }.toTypedArray(), state) {
    val selected get() = options[state].second
}

class StatusFilter :
    SelectFilter(
        "Status",
        arrayOf(
            Pair("Semua", ""),
            Pair("Ongoing", "ongoing"),
            Pair("Tamat", "completed"),
            Pair("Hiatus", "hiatus"),
        ),
    )

class TypeFilter :
    SelectFilter(
        "Type",
        arrayOf(
            Pair("Semua", ""),
            Pair("Manga", "manga"),
            Pair("Manhua", "manhua"),
            Pair("Manhwa", "manhwa"),
        ),
    )

class SortFilter :
    SelectFilter(
        "Sort By",
        arrayOf(
            Pair("Terbaru", "latest"),
            Pair("Populer", "popular"),
            Pair("Rating", "rating"),
            Pair("A-Z", "az"),
        ),
    )

class MinChapterFilter : Filter.Text("Minimal Chapter")

class GenreOption(val name: String, val valName: String)

class GenreCheckBox(name: String, val value: String) : Filter.CheckBox(name)

class GenreFilter(val genres: List<GenreOption>) :
    Filter.Group<Filter.CheckBox>(
        "Genre",
        genres.map { GenreCheckBox(it.name, it.valName) },
    ) {
    val selected: String
        get() = state.mapIndexedNotNull { index, checkbox ->
            if (checkbox.state) (checkbox as GenreCheckBox).value else null
        }.joinToString(",")
}

val genreList = listOf(
    GenreOption("Action", "action"),
    GenreOption("Adaptation", "adaptation"),
    GenreOption("Adult", "adult"),
    GenreOption("Adventure", "adventure"),
    GenreOption("Age Gap", "age-gap"),
    GenreOption("Ahegao", "ahegao"),
    GenreOption("Aliens", "aliens"),
    GenreOption("Animals", "animals"),
    GenreOption("Anthology", "anthology"),
    GenreOption("Apocalypse", "apocalypse"),
    GenreOption("Bald", "bald"),
    GenreOption("Bara(ML)", "baraml"),
    GenreOption("Bbw", "bbw"),
    GenreOption("BDSM", "bdsm"),
    GenreOption("Beasts", "beasts"),
    GenreOption("Big Areolae", "big-areolae"),
    GenreOption("Big Ass", "big-ass"),
    GenreOption("Big Breasts", "big-breasts"),
    GenreOption("Blackmail", "blackmail"),
    GenreOption("Bloody", "bloody"),
    GenreOption("Blowjob", "blowjob"),
    GenreOption("Bodyswap", "bodyswap"),
    GenreOption("Boys", "boys"),
    GenreOption("Boys' Love", "boys-love"),
    GenreOption("Bunny girl", "bunny-girl"),
    GenreOption("Cars", "cars"),
    GenreOption("Cheating", "cheating"),
    GenreOption("Cheating/Infidelity", "cheatinginfidelity"),
    GenreOption("Childhood Friends", "childhood-friends"),
    GenreOption("College life", "college-life"),
    GenreOption("Comedy", "comedy"),
    GenreOption("Comic", "comic"),
    GenreOption("Contest winning", "contest-winning"),
    GenreOption("Cooking", "cooking"),
    GenreOption("Crime", "crime"),
    GenreOption("Crossdressing", "crossdressing"),
    GenreOption("Delinquents", "delinquents"),
    GenreOption("Dementia", "dementia"),
    GenreOption("Demon", "demon"),
    GenreOption("Demons", "demons"),
    GenreOption("Dilf", "dilf"),
    GenreOption("Drama", "drama"),
    GenreOption("Dungeons", "dungeons"),
    GenreOption("Ecchi", "ecchi"),
    GenreOption("Emperor's daughter", "emperors-daughter"),
    GenreOption("Entertainment", "entertainment"),
    GenreOption("Fan-Colored", "fan-colored"),
    GenreOption("Fantasy", "fantasy"),
    GenreOption("Femdom", "femdom"),
    GenreOption("Fetish", "fetish"),
    GenreOption("Fight", "fight"),
    GenreOption("Full Color", "full-color"),
    GenreOption("Furry", "furry"),
    GenreOption("Game", "game"),
    GenreOption("Gender Bender", "gender-bender"),
    GenreOption("Genderswap", "genderswap"),
    GenreOption("Ghosts", "ghosts"),
    GenreOption("Girls", "girls"),
    GenreOption("Girls' Love", "girls-love"),
    GenreOption("Glasses", "glasses"),
    GenreOption("Gore", "gore"),
    GenreOption("Group", "group"),
    GenreOption("Gyaru", "gyaru"),
    GenreOption("Hairy", "hairy"),
    GenreOption("Harem", "harem"),
    GenreOption("Harlequin", "harlequin"),
    GenreOption("Hentai", "hentai"),
    GenreOption("Hero", "hero"),
    GenreOption("Historical", "historical"),
    GenreOption("Horror", "horror"),
    GenreOption("Hotpants", "hotpants"),
    GenreOption("Huge breasts", "huge-breasts"),
    GenreOption("Impregnant", "impregnant"),
    GenreOption("Incest", "incest"),
    GenreOption("Isekai", "isekai"),
    GenreOption("Josei", "josei"),
    GenreOption("Josei(W)", "joseiw"),
    GenreOption("Kids", "kids"),
    GenreOption("Knight", "knight"),
    GenreOption("Kodomo(Kid)", "kodomokid"),
    GenreOption("Latest", "latest"),
    GenreOption("Lolicon", "lolicon"),
    GenreOption("Long Strip", "long-strip"),
    GenreOption("Magic", "magic"),
    GenreOption("Magical Girls", "magical-girls"),
    GenreOption("Manga", "manga"),
    GenreOption("Manhua", "manhua"),
    GenreOption("Manhwa", "manhwa"),
    GenreOption("Martial Arts", "martial-arts"),
    GenreOption("Mature", "mature"),
    GenreOption("Mecha", "mecha"),
    GenreOption("Medical", "medical"),
    GenreOption("MILF", "milf"),
    GenreOption("Military", "military"),
    GenreOption("Monster Girls", "monster-girls"),
    GenreOption("Monsters", "monsters"),
    GenreOption("Murim", "murim"),
    GenreOption("Music", "music"),
    GenreOption("Mystery", "mystery"),
    GenreOption("Mythology", "mythology"),
    GenreOption("Nakadashi", "nakadashi"),
    GenreOption("Netorare", "netorare"),
    GenreOption("Netorare/NTR", "netorarentr"),
    GenreOption("Ninja", "ninja"),
    GenreOption("Non-human", "non-human"),
    GenreOption("Office Workers", "office-workers"),
    GenreOption("Omegaverse", "omegaverse"),
    GenreOption("One-Shot", "one-shot"),
    GenreOption("Oneshot", "oneshot"),
    GenreOption("Parody", "parody"),
    GenreOption("Philosophical", "philosophical"),
    GenreOption("Police", "police"),
    GenreOption("Post-Apocalyptic", "post-apocalyptic"),
    GenreOption("Pregnant", "pregnant"),
    GenreOption("Psychological", "psychological"),
    GenreOption("Regression", "regression"),
    GenreOption("Reincarnation", "reincarnation"),
    GenreOption("Return", "return"),
    GenreOption("Revenge", "revenge"),
    GenreOption("Reverse Harem", "reverse-harem"),
    GenreOption("Reverse Isekai", "reverse-isekai"),
    GenreOption("Rofan", "rofan"),
    GenreOption("Romance", "romance"),
    GenreOption("Royal family", "royal-family"),
    GenreOption("Royalty", "royalty"),
    GenreOption("Samurai", "samurai"),
    GenreOption("School", "school"),
    GenreOption("School girl uniform", "school-girl-uniform"),
    GenreOption("School Life", "school-life"),
    GenreOption("Sci-Fi", "sci-fi"),
    GenreOption("Seinen", "seinen"),
    GenreOption("Seinen(M)", "seinenm"),
    GenreOption("Shotacon", "shotacon"),
    GenreOption("Shoujo", "shoujo"),
    GenreOption("Shoujo ai", "shoujo-ai"),
    GenreOption("Shoujo(G)", "shoujog"),
    GenreOption("Shounen", "shounen"),
    GenreOption("Shounen ai", "shounen-ai"),
    GenreOption("Shounen(B)", "shounenb"),
    GenreOption("Showbiz", "showbiz"),
    GenreOption("Silver & Golden", "silver--golden"),
    GenreOption("Slice of Life", "slice-of-life"),
    GenreOption("SM/BDSM/SUB-DOM", "smbdsmsub-dom"),
    GenreOption("Smut", "smut"),
    GenreOption("Sole Female", "sole-female"),
    GenreOption("Sole Male", "sole-male"),
    GenreOption("Space", "space"),
    GenreOption("Sport", "sport"),
    GenreOption("Sports", "sports"),
    GenreOption("Super Power", "super-power"),
    GenreOption("Superhero", "superhero"),
    GenreOption("Supernatural", "supernatural"),
    GenreOption("Supranatural", "supranatural"),
    GenreOption("Survival", "survival"),
    GenreOption("System", "system"),
    GenreOption("Thick eyebrows", "thick-eyebrows"),
    GenreOption("Thriller", "thriller"),
    GenreOption("Time Travel", "time-travel"),
    GenreOption("Tower", "tower"),
    GenreOption("Tower Climbing", "tower-climbing"),
    GenreOption("Toys", "toys"),
    GenreOption("Traditional Games", "traditional-games"),
    GenreOption("Tragedy", "tragedy"),
    GenreOption("Transmigration", "transmigration"),
    GenreOption("Ugly Bastard", "ugly-bastard"),
    GenreOption("Vampires", "vampires"),
    GenreOption("Video Games", "video-games"),
    GenreOption("Villainess", "villainess"),
    GenreOption("Violence", "violence"),
    GenreOption("Virgin", "virgin"),
    GenreOption("Virtual Reality", "virtual-reality"),
    GenreOption("Web Comic", "web-comic"),
    GenreOption("Webtoon", "webtoon"),
    GenreOption("Webtoons", "webtoons"),
    GenreOption("Wuxia", "wuxia"),
    GenreOption("Xianxia", "xianxia"),
    GenreOption("Xuanhuan", "xuanhuan"),
    GenreOption("Yakuzas", "yakuzas"),
    GenreOption("Yaoi(BL)", "yaoibl"),
    GenreOption("Yuri", "yuri"),
    GenreOption("Yuri(GL)", "yurigl"),
    GenreOption("Zombies", "zombies"),
)

fun getFilters() = FilterList(
    Filter.Header("Semua filter dapat digabungkan, termasuk dengan pencarian teks"),
    Filter.Separator(),
    SortFilter(),
    StatusFilter(),
    TypeFilter(),
    GenreFilter(genreList),
    MinChapterFilter(),
)
