package eu.kanade.tachiyomi.extension.pt.yomumangas

import eu.kanade.tachiyomi.source.model.Filter

open class UriPartFilter(
    displayName: String,
    private val vals: Array<Pair<String, String>>,
) : Filter.Select<String>(displayName, vals.map { it.first }.toTypedArray()) {
    fun toUriPart() = vals[state].second
}

class TypeFilter :
    UriPartFilter(
        "Tipo",
        arrayOf(
            Pair("Qualquer", ""),
            Pair("Mangá", "MANGA"),
            Pair("Manhwa", "MANHWA"),
            Pair("Manhua", "MANHUA"),
            Pair("Novel", "NOVEL"),
        ),
    )

class StatusFilter :
    UriPartFilter(
        "Status",
        arrayOf(
            Pair("Qualquer", ""),
            Pair("Em andamento", "ONGOING"),
            Pair("Completo", "COMPLETE"),
            Pair("Hiato", "HIATUS"),
            Pair("Cancelado", "CANCELLED"),
        ),
    )

class NsfwFilter :
    UriPartFilter(
        "NSFW",
        arrayOf(
            Pair("Qualquer", ""),
            Pair("Ocultar", "false"),
            Pair("Mostrar", "true"),
        ),
    )

class Genre(name: String, val id: String) : Filter.CheckBox(name)
class GenreFilter(genres: List<Genre>) : Filter.Group<Genre>("Gêneros", genres)

class Tag(name: String, val id: String) : Filter.CheckBox(name)
class TagFilter(tags: List<Tag>) : Filter.Group<Tag>("Tags", tags)

fun getGenresList() = listOf(
    Genre("Romance", "13"),
    Genre("Ação", "1"),
    Genre("Aventura", "2"),
    Genre("Drama", "3"),
    Genre("Sobrenatural", "4"),
    Genre("Comédia", "5"),
    Genre("Terror", "6"),
    Genre("Fantasia", "7"),
    Genre("Psicológico", "8"),
    Genre("Mistério", "9"),
    Genre("Suspense", "10"),
    Genre("Esportes", "11"),
    Genre("Cotidiano", "12"),
    Genre("Ecchi", "16"),
    Genre("Hentai", "17"),
    Genre("Mecha", "15"),
    Genre("Ficção Científica", "14"),
    Genre("Horror", "20"),
    Genre("Action", "23"),
    Genre("Adventure", "24"),
    Genre("Fantasy", "25"),
    Genre("Slice of Life", "26"),
    Genre("Comedy", "27"),
    Genre("Supernatural", "28"),
    Genre("Sci-Fi", "29"),
    Genre("Sports", "30"),
    Genre("Thriller", "31"),
    Genre("Cultivo", "32"),
    Genre("Artes Marciais", "33"),
    Genre("Regressão", "34"),
    Genre("Reencarnação", "35"),
    Genre("Gênio", "36"),
    Genre("Murim", "37"),
    Genre("Magia", "38"),
    Genre("Isekai", "40"),
    Genre("Yuri", "41"),
    Genre("Escolar", "42"),
    Genre("Mahou Shoujo", "43"),
    Genre("Music", "44"),
    Genre("Adult", "45"),
    Genre("Josei", "46"),
    Genre("School Life", "47"),
    Genre("Smut", "48"),
    Genre("School", "49"),
    Genre("Seinen", "50"),
    Genre("Shoujo", "51"),
    Genre("Mature", "52"),
    Genre("Shounen", "53"),
    Genre("Erotica", "54"),
    Genre("Time Travel", "55"),
    Genre("Reverse Harem", "56"),
    Genre("Office Workers", "57"),
    Genre("Adaptation", "58"),
    Genre("Award Winning", "59"),
    Genre("Official Colored", "60"),
    Genre("Gore", "61"),
    Genre("Web Comic", "62"),
    Genre("Long Strip", "63"),
    Genre("Mafia", "64"),
    Genre("Historical", "66"),
    Genre("Military", "67"),
    Genre("Survival", "68"),
    Genre("Philosophical", "69"),
    Genre("Tragedy", "70"),
    Genre("Reincarnation", "71"),
    Genre("Sexual Violence", "72"),
    Genre("Monsters", "73"),
    Genre("Demons", "74"),
)

fun getTagsList() = listOf(
    Tag("Destaques", "1"),
    Tag("Temporada", "2"),
    Tag("Viagem", "4"),
    Tag("Busca Familiar", "5"),
    Tag("Shounen", "6"),
    Tag("Elenco Coletivo", "7"),
    Tag("Super Poderes", "8"),
    Tag("Protagonista Masculino", "9"),
    Tag("Tragédia", "10"),
    Tag("Navios", "11"),
    Tag("Militar", "12"),
    Tag("Crime", "13"),
    Tag("Conspiração", "14"),
    Tag("Deuses", "15"),
    Tag("Fugitivo", "16"),
    Tag("Politica", "17"),
    Tag("Terrorismo", "18"),
    Tag("Pós Apocaliptico", "19"),
    Tag("Guerra", "20"),
    Tag("Pastelão", "21"),
    Tag("Distopia", "22"),
    Tag("Elenco Adulto", "23"),
    Tag("Prisão", "24"),
    Tag("Cultivo", "25"),
    Tag("Time Skip", "26"),
    Tag("Protagonista Feminina", "27"),
    Tag("Lost Civilization", "28"),
    Tag("Anachronism", "29"),
    Tag("Anthropomorphism", "30"),
    Tag("Religion", "31"),
    Tag("Slavery", "32"),
    Tag("Large Breasts", "33"),
    Tag("Environmental", "34"),
    Tag("Swordplay", "35"),
    Tag("Kemonomimi", "36"),
    Tag("Mythology", "37"),
    Tag("Gangs", "38"),
    Tag("Assassins", "39"),
    Tag("Animals", "40"),
    Tag("Anti-Hero", "41"),
    Tag("Espionage", "42"),
    Tag("Drugs", "43"),
    Tag("Cyborg", "44"),
    Tag("Coming of Age", "45"),
    Tag("Adoption", "46"),
    Tag("Battle Royale", "47"),
    Tag("Henshin", "48"),
    Tag("Skeleton", "49"),
    Tag("Amnesia", "50"),
    Tag("Medicine", "51"),
    Tag("Samurai", "52"),
    Tag("Robots", "53"),
    Tag("Desert", "54"),
    Tag("Food", "55"),
    Tag("Female Harem", "56"),
    Tag("Revenge", "57"),
    Tag("Meta", "58"),
    Tag("Angels", "59"),
    Tag("Ninja", "60"),
    Tag("Guns", "61"),
    Tag("Mermaid", "62"),
    Tag("Dragons", "63"),
    Tag("Centaur", "64"),
    Tag("LGBTQ+ Themes", "65"),
    Tag("Time Manipulation", "66"),
    Tag("Monster Girl", "67"),
    Tag("Oiran", "68"),
    Tag("Trains", "69"),
    Tag("Memory Manipulation", "70"),
    Tag("Zombie", "71"),
    Tag("Dinosaurs", "72"),
    Tag("Aliens", "73"),
    Tag("Gender Bending", "74"),
    Tag("Transgender", "75"),
    Tag("Clone", "76"),
    Tag("Body Swapping", "77"),
    Tag("Demons", "78"),
    Tag("Gore", "79"),
    Tag("Historical", "80"),
    Tag("Body Horror", "81"),
    Tag("Rural", "82"),
    Tag("Shapeshifting", "83"),
    Tag("Disability", "84"),
    Tag("Orphan", "85"),
    Tag("Family Life", "86"),
    Tag("Afterlife", "87"),
    Tag("Age Regression", "88"),
    Tag("Reincarnation", "89"),
    Tag("Youkai", "90"),
    Tag("Crossdressing", "91"),
    Tag("Polyamorous", "92"),
    Tag("Bisexual", "93"),
    Tag("Urban Fantasy", "94"),
    Tag("Dissociative Identities", "95"),
    Tag("Cosmic Horror", "96"),
    Tag("Urban", "97"),
    Tag("Survival", "98"),
    Tag("Work", "99"),
    Tag("Monster Boy", "100"),
    Tag("Cult", "101"),
    Tag("Heterosexual", "102"),
    Tag("Human Pet", "103"),
    Tag("Psychosexual", "104"),
    Tag("Yandere", "105"),
    Tag("Philosophy", "106"),
    Tag("Primarily Teen Cast", "107"),
    Tag("Nudity", "108"),
    Tag("Necromancy", "109"),
    Tag("Cannibalism", "110"),
    Tag("Delinquents", "111"),
    Tag("Mafia", "112"),
    Tag("School", "113"),
    Tag("Yakuza", "114"),
    Tag("Tsundere", "115"),
    Tag("Chimera", "116"),
    Tag("Motorcycles", "117"),
    Tag("Yuri", "118"),
    Tag("Surreal Comedy", "119"),
    Tag("Pandemic", "120"),
    Tag("Seinen", "121"),
    Tag("Space", "122"),
    Tag("Foreign", "123"),
    Tag("Rape", "124"),
    Tag("Magic", "125"),
    Tag("Rehabilitation", "126"),
    Tag("Torture", "127"),
    Tag("Fairy", "128"),
    Tag("Sadism", "129"),
    Tag("Witch", "130"),
    Tag("Elf", "131"),
    Tag("Group Sex", "132"),
    Tag("Prostitution", "133"),
    Tag("Kaiju", "134"),
    Tag("Achronological Order", "135"),
    Tag("Pregnant", "136"),
    Tag("Tomboy", "137"),
    Tag("Incest", "138"),
    Tag("Dungeon", "139"),
    Tag("Vore", "140"),
    Tag("Masturbation", "141"),
    Tag("Kingdom Management", "142"),
    Tag("Fellatio", "143"),
    Tag("Martial Arts", "144"),
    Tag("Biographical", "145"),
    Tag("Ghost", "146"),
    Tag("Outdoor", "147"),
    Tag("Agriculture", "148"),
    Tag("Language Barrier", "149"),
    Tag("Twins", "150"),
)
