name: 🐞 Relatório de problema
description: Relatar um problema de fonte
labels: [Bug]
body:

  - type: input
    id: source
    attributes:
      label: Informações da fonte
      description: |
        Você pode encontrar o nome da extensão e versão em **Navegar → Extensões**.
      placeholder: |
        Exemplo: "Not Real Scans 1.4.1"
    validations:
      required: true

  - type: input
    id: language
    attributes:
      label: Idioma da fonte
      placeholder: |
        Exemplo: "Português"
    validations:
      required: true

  - type: textarea
    id: reproduce-steps
    attributes:
      label: Passos para reproduzir
      description: Forneça um exemplo do problema.
      placeholder: |
        Exemplo:
          1. Primeiro passo
          2. Segundo passo
          3. Problema aqui
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Comportamento esperado
      placeholder: |
        Exemplo:
          "Isso deveria acontecer..."
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Comportamento atual
      placeholder: |
        Exemplo:
          "Isso aconteceu em vez disso..."
    validations:
      required: true

  - type: input
    id: tachiyomi-version
    attributes:
      label: Versão do Mihon/Tachiyomi
      description: |
        Você pode encontrar sua versão do Mihon/Tachiyomi em **Mais → Sobre**.
      placeholder: |
        Exemplo: "0.18.0"
    validations:
      required: true

  - type: input
    id: android-version
    attributes:
      label: Versão do Android
      description: |
        Você pode encontrar isso em algum lugar nas configurações do Android.
      placeholder: |
        Exemplo: "Android 11"
    validations:
      required: true

  - type: textarea
    id: other-details
    attributes:
      label: Outros detalhes
      placeholder: |
        Detalhes adicionais e anexos.

  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Reconhecimentos
      description: Seu problema será fechado se você não tiver feito essas etapas.
      options:
        - label: Eu pesquisei os problemas existentes e este é um novo ticket, **NÃO** um duplicado ou relacionado a outro problema aberto ou fechado.
          required: true
        - label: Eu escrevi um título curto, mas informativo.
          required: true
        - label: Eu atualizei o aplicativo para a versão **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
          required: true
        - label: Eu atualizei todas as extensões instaladas.
          required: true
        - label: Eu tentei o [guia de solução de problemas](https://mihon.app/docs/guides/troubleshooting/).
          required: true
        - label: Se este é um problema com o próprio aplicativo, eu deveria estar abrindo um problema no repositório do aplicativo.
          required: true
        - label: Eu preencherei todas as informações solicitadas neste formulário.
          required: true

  - type: textarea
    attributes:
      label: <!-- footer -->
      description: Não modifique. Este é um lembrete para outros usuários votarem.
      value: |
        ---

        Adicione uma reação :+1: aos [problemas que você acha importantes].

        [reação]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
        [problemas que você acha importantes]: https://github.com/FelipeGFA/fonte-extensoes/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc
