name: 🐞 Issue report
description: Report a source issue in Tachiyomi
labels: [Bug]
body:

  - type: input
    id: source
    attributes:
      label: Source information
      description: |
        You can find the extension name and version in **Browse → Extensions**.
      placeholder: |
        Example: "Not Real Scans 1.4.1"
    validations:
      required: true

  - type: input
    id: language
    attributes:
      label: Source language
      placeholder: |
        Example: "English"
    validations:
      required: true

  - type: textarea
    id: reproduce-steps
    attributes:
      label: Steps to reproduce
      description: Provide an example of the issue.
      placeholder: |
        Example:
          1. First step
          2. Second step
          3. Issue here
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      placeholder: |
        Example:
          "This should happen..."
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      placeholder: |
        Example:
          "This happened instead..."
    validations:
      required: true

  - type: input
    id: tachiyomi-version
    attributes:
      label: Mihon/Tachiyomi version
      description: |
        You can find your Mihon/Tachiyomi version in **More → About**.
      placeholder: |
        Example: "0.16.3"
    validations:
      required: true

  - type: input
    id: android-version
    attributes:
      label: Android version
      description: |
        You can find this somewhere in your Android settings.
      placeholder: |
        Example: "Android 11"
    validations:
      required: true

  - type: textarea
    id: other-details
    attributes:
      label: Other details
      placeholder: |
        Additional details and attachments.

  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: Your issue will be closed if you haven't done these steps.
      options:
        - label: I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
          required: true
        - label: I have written a short but informative title.
          required: true
        - label: I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
          required: true
        - label: I have updated all installed extensions.
          required: true
        - label: I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
          required: true
        - label: I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
        - label: If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
          required: true
        - label: I will fill out all of the requested information in this form.
          required: true
