name: ❌ Relatório de fonte morta
description: A fonte está fora do ar e o site está fechado
labels: [Source is down]
body:

  - type: markdown
    attributes:
      value: |
        ### Aviso
        Se você tiver muitas fontes mortas para relatar, volte e envie uma única solicitação meta.

  - type: input
    id: source
    attributes:
      label: Nome da fonte
      description: |
        Você pode encontrar o nome da extensão em **Navegar → Extensões**.
      placeholder: |
        Exemplo: "Not Real Scans"
    validations:
      required: true

  - type: input
    id: language
    attributes:
      label: Idioma da fonte
      placeholder: |
        Exemplo: "Português"
    validations:
      required: true

  - type: input
    id: link
    attributes:
      label: Link da fonte
      placeholder: |
        Exemplo: "https://notrealscans.org"
    validations:
      required: true

  - type: textarea
    id: other-details
    attributes:
      label: Outros detalhes
      placeholder: |
        Detalhes adicionais e anexos.

  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Reconhecimentos
      description: Seu problema será fechado se você não tiver feito essas etapas.
      options:
        - label: Eu atualizei todas as extensões instaladas.
          required: true
        - label: Eu abri o WebView e verifiquei que o site da fonte está fora do ar.
          required: true
        - label: Eu pesquisei os problemas existentes e este é um novo ticket, **NÃO** um duplicado ou relacionado a outro problema aberto ou fechado.
          required: true
        - label: Eu escrevi um título significativo com o nome da fonte.
          required: true
        - label: Eu preencherei todas as informações solicitadas neste formulário.
          required: true

  - type: textarea
    attributes:
      label: <!-- footer -->
      description: Não modifique. Este é um lembrete para outros usuários votarem.
      value: |
        ---

        Adicione uma reação :+1: aos [problemas que você acha importantes].

        [reação]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
        [problemas que você acha importantes]: https://github.com/FelipeGFA/fonte-extensoes/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc