name: 🧠 Solicitação meta
description: Sugerir melhorias para o projeto
labels: [Meta request]
body:

  - type: textarea
    id: feature-description
    attributes:
      label: Descreva por que isso deve ser adicionado
      description: Como o projeto pode ser melhorado?
      placeholder: |
        Exemplo:
          "Deve funcionar assim..."
    validations:
      required: true

  - type: textarea
    id: other-details
    attributes:
      label: Outros detalhes
      placeholder: |
        Detalhes adicionais e anexos.

  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Reconhecimentos
      description: Seu problema será fechado se você não tiver feito essas etapas.
      options:
        - label: Eu pesquisei os problemas existentes e este é um novo ticket, **NÃO** um duplicado ou relacionado a outro problema aberto ou fechado.
          required: true
        - label: Eu escrevi um título curto, mas informativo.
          required: true
        - label: Se este é um problema com o próprio aplicativo, eu deveria estar abrindo um problema no [repositório do aplicativo](https://github.com/mihonapp/mihon/issues/new/choose).
          required: true
        - label: Eu atualizei o aplicativo para a versão **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
          required: true
        - label: Eu atualizei todas as extensões instaladas.
          required: true
        - label: Eu preencherei todas as informações solicitadas neste formulário.
          required: true

  - type: textarea
    attributes:
      label: <!-- footer -->
      description: Não modifique. Este é um lembrete para outros usuários votarem.
      value: |
        ---

        Adicione uma reação :+1: aos [problemas que você acha importantes].

        [reação]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
        [problemas que você acha importantes]: https://github.com/FelipeGFA/fonte-extensoes/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc
