package eu.kanade.tachiyomi.extension.vi.soaicacomic

import eu.kanade.tachiyomi.source.model.Filter
import eu.kanade.tachiyomi.source.model.FilterList

fun getFilters(): FilterList = FilterList(
    Filter.Header("Bộ lọc sẽ bị bỏ qua khi tìm kiếm"),
    TheLoaiFilter(),
    NhomFilter(),
    LoatTruyenFilter(),
    TuKhoaFilter(),
)

class TheLoaiFilter :
    UriPartFilter(
        "Thể Loại",
        arrayOf(
            Pair("Tất cả", ""),
            Pair("Ác Ma", "the-loai/ac-ma"),
            Pair("Áo choàng", "the-loai/ao-choang"),
            Pair("Áo giáp", "the-loai/ao-giap"),
            Pair("Âu Cổ", "the-loai/au-co"),
            Pair("Bách Hợp", "the-loai/bach-hop"),
            Pair("Báo Thù", "the-loai/bao-thu"),
            Pair("Bệnh Kiều", "the-loai/benh-kieu"),
            Pair("Bí Ẩn", "the-loai/bi-an"),
            Pair("Bí ẩn gia tộc", "the-loai/bi-an-gia-toc"),
            Pair("Cậu ấm nhà giàu", "the-loai/cau-am-nha-giau"),
            Pair("Cẩu Huyết", "the-loai/cau-huyet"),
            Pair("Chiếm Hữu", "the-loai/chiem-huu"),
            Pair("Chữa Lành", "the-loai/chua-lanh"),
            Pair("Chuyển sinh", "the-loai/chuyen-sinh"),
            Pair("Cổ Đại", "the-loai/co-dai"),
            Pair("Cổ trang", "the-loai/co-trang"),
            Pair("Cổ Xuyên", "the-loai/co-xuyen"),
            Pair("Công lược", "the-loai/cong-luoc"),
            Pair("Công Tước", "the-loai/cong-tuoc"),
            Pair("Cưng chiều", "the-loai/cung-chieu"),
            Pair("Cung đấu", "the-loai/cung-dau"),
            Pair("Cưới trước yêu sau", "the-loai/cuoi-truoc-yeu-sau"),
            Pair("Đại Lão", "the-loai/dai-lao"),
            Pair("Đam Mỹ", "the-loai/dam-my"),
            Pair("dễ thương", "the-loai/de-thuong"),
            Pair("Dị giới", "the-loai/di-gioi"),
            Pair("Diệt tiểu tam", "the-loai/diet-tieu-tam"),
            Pair("Diệt tra nam", "the-loai/diet-tra-nam"),
            Pair("Định mệnh", "the-loai/dinh-menh"),
            Pair("Đô Thị", "the-loai/do-thi"),
            Pair("Độc Chiếm", "the-loai/doc-chiem"),
            Pair("đời sống", "the-loai/doi-song"),
            Pair("Drama", "the-loai/drama"),
            Pair("Dưỡng phu", "the-loai/duong-phu"),
            Pair("Dưỡng Phu từ bé", "the-loai/duong-phu-tu-be"),
            Pair("Fantasy", "the-loai/fantasy"),
            Pair("Game", "the-loai/game"),
            Pair("Game Thủ", "the-loai/game-thu"),
            Pair("Gender Bender", "the-loai/gender-bender"),
            Pair("Gia đấu", "the-loai/gia-dau"),
            Pair("Gia đình", "the-loai/gia-dinh"),
            Pair("Giả Tưởng", "the-loai/gia-tuong"),
            Pair("Giới giải trí", "the-loai/gioi-giai-tri"),
            Pair("Hắc Bang", "the-loai/hac-bang"),
            Pair("Hài Hước", "the-loai/hai-huoc"),
            Pair("Hành Động", "the-loai/hanh-dong"),
            Pair("Hành Tinh", "the-loai/hanh-tinh"),
            Pair("Hào Môn", "the-loai/hao-mon"),
            Pair("Harem", "the-loai/harem"),
            Pair("Hậu Cung", "the-loai/hau-cung"),
            Pair("HE", "the-loai/he"),
            Pair("Hệ thống", "the-loai/he-thong"),
            Pair("Healing", "the-loai/healing"),
            Pair("Hiện đại", "the-loai/hien-dai"),
            Pair("Hoán Đổi Thân Phận", "the-loai/hoan-doi-than-phan"),
            Pair("Hoàng Cung", "the-loai/hoang-cung"),
            Pair("Hoàng Gia", "the-loai/hoang-gia"),
            Pair("Học Đường", "the-loai/hoc-duong"),
            Pair("Hồi Hộp", "the-loai/hoi-hop"),
            Pair("hợp đồng hôn nhân", "the-loai/hop-dong-hon-nhan"),
            Pair("Huyền Huyễn", "the-loai/huyen-huyen"),
            Pair("Huyết Tộc", "the-loai/huyet-toc"),
            Pair("Kịch Tính", "the-loai/kich-tinh"),
            Pair("Kinh dị", "the-loai/kinh-di"),
            Pair("Lãng Mạn", "the-loai/lang-man"),
            Pair("Lịch Sử", "the-loai/lich-su"),
            Pair("Liên Hôn", "the-loai/lien-hon"),
            Pair("Long Tộc", "the-loai/long-toc"),
            Pair("Ly Hôn - Tái Ngộ", "the-loai/ly-hon-tai-ngo"),
            Pair("Ma ca rồng", "the-loai/ma-ca-rong"),
            Pair("Manga Yuri", "the-loai/manga-yuri"),
            Pair("Manh bảo", "the-loai/manh-bao"),
            Pair("Manhua", "the-loai/manhua"),
            Pair("Manhwa", "the-loai/manhwa"),
            Pair("Mẫu tử", "the-loai/mau-tu"),
            Pair("Nam chính giả nghèo", "the-loai/nam-chinh-gia-ngheo"),
            Pair("Nghèo Giả Giàu", "the-loai/ngheo-gia-giau"),
            Pair("Nghịch Tập", "the-loai/nghich-tap"),
            Pair("Ngôn Tình", "the-loai/ngon-tinh"),
            Pair("Ngọt sủng", "the-loai/ngot-sung"),
            Pair("Ngược", "the-loai/nguoc"),
            Pair("Ngược Tâm", "the-loai/nguoc-tam"),
            Pair("Ngược Trước Sủng Sau", "the-loai/nguoc-truoc-sung-sau"),
            Pair("Người Cá", "the-loai/nguoi-ca"),
            Pair("Người tình hợp đồng", "the-loai/nguoi-tinh-hop-dong"),
            Pair("Nhân Quả Luân Hồi", "the-loai/nhan-qua-luan-hoi"),
            Pair("Nhân Thú", "the-loai/nhan-thu"),
            Pair("Nhân - Yêu", "the-loai/nhan-yeu"),
            Pair("Nhiều thân phận", "the-loai/nhieu-than-phan"),
            Pair("Nhiều vị diện", "the-loai/nhieu-vi-dien"),
            Pair("Nữ Cường", "the-loai/nu-cuong"),
            Pair("Nữ theo đuổi nam", "the-loai/nu-theo-duoi-nam"),
            Pair("Nữ tôn", "the-loai/nu-ton"),
            Pair("Ở Rể", "the-loai/o-re"),
            Pair("Oan gia", "the-loai/oan-gia"),
            Pair("Oneshot", "the-loai/oneshot"),
            Pair("Phản Diện", "the-loai/phan-dien"),
            Pair("Phép Thuật", "the-loai/phep-thuat"),
            Pair("Phiêu Lưu", "the-loai/phieu-luu"),
            Pair("Phó Bản", "the-loai/pho-ban"),
            Pair("Quyền Lực", "the-loai/quyen-luc"),
            Pair("Romance", "the-loai/romance"),
            Pair("SE", "the-loai/se"),
            Pair("Sếp - Cấp Dưới", "the-loai/sep-cap-duoi"),
            Pair("Sếp - Thư Ký", "the-loai/sep-thu-ky"),
            Pair("Showbiz", "the-loai/showbiz"),
            Pair("Si Mê Cực Đoan", "the-loai/si-me-cuc-doan"),
            Pair("Si Tình", "the-loai/si-tinh"),
            Pair("siêu nhiều mèo", "the-loai/sieu-nhieu-meo"),
            Pair("Song sinh tráo thân", "the-loai/song-sinh-trao-than"),
            Pair("Sư Tôn", "the-loai/su-ton"),
            Pair("Sủng nịch", "the-loai/sung-nich"),
            Pair("Sủng vợ", "the-loai/sung-vo"),
            Pair("Thầm Yêu", "the-loai/tham-yeu"),
            Pair("Thần Tiên", "the-loai/than-tien"),
            Pair("Thanh Mai Trúc Mã", "the-loai/thanh-mai-truc-ma"),
            Pair("Thanh Xuân Vườn Trường", "the-loai/thanh-xuan-vuon-truong"),
            Pair("Thế thân", "the-loai/the-than"),
            Pair("Theo đuổi", "the-loai/theo-duoi"),
            Pair("Thiên kim giả", "the-loai/thien-kim-gia"),
            Pair("Thiên Kim Thật", "the-loai/thien-kim-that"),
            Pair("Thú nhân", "the-loai/thu-nhan"),
            Pair("Thú Thế", "the-loai/thu-the"),
            Pair("Thừa kế gia sản", "the-loai/thua-ke-gia-san"),
            Pair("Thuần hóa", "the-loai/thuan-hoa"),
            Pair("Tình cảm", "the-loai/tinh-cam"),
            Pair("Toàn Năng", "the-loai/toan-nang"),
            Pair("Tổng Tài", "the-loai/tong-tai"),
            Pair("Trả thù", "the-loai/tra-thu"),
            Pair("Tranh sủng", "the-loai/tranh-sung"),
            Pair("Trinh Thám", "the-loai/trinh-tham"),
            Pair("Trinh thám giả tưởng", "the-loai/trinh-tham-gia-tuong"),
            Pair("Trọng Sinh", "the-loai/trong-sinh"),
            Pair("Truy phu", "the-loai/truy-phu"),
            Pair("Truy thê", "the-loai/truy-the"),
            Pair("TRUYỆN CHỮ", "the-loai/truyen-chu"),
            Pair("Truyện ngắn", "the-loai/truyen-ngan"),
            Pair("Tu Tiên", "the-loai/tu-tien"),
            Pair("Tương Lai", "the-loai/tuong-lai"),
            Pair("Tỷ Phú", "the-loai/ty-phu"),
            Pair("Vả Mặt", "the-loai/va-mat"),
            Pair("Vai ác", "the-loai/vai-ac"),
            Pair("Vai Ác", "the-loai/vai-ac-2"),
            Pair("Viễn Tưởng", "the-loai/vien-tuong"),
            Pair("Viễn Tưởng Phương Tây", "the-loai/vien-tuong-phuong-tay"),
            Pair("Vô Hạn Lưu", "the-loai/vo-han-luu"),
            Pair("Võ Thuật", "the-loai/vo-thuat"),
            Pair("Vườn trường", "the-loai/vuon-truong"),
            Pair("Vương Gia Chiều Vợ", "the-loai/vuong-gia"),
            Pair("Xung hỉ", "the-loai/xung-hi"),
            Pair("Xuyên Không", "the-loai/xuyen-khong"),
            Pair("Xuyên nhanh", "the-loai/xuyen-nhanh"),
            Pair("Xuyên Sách", "the-loai/xuyen-sach"),
            Pair("Yêu Đương", "the-loai/yeu-duong"),
        ),
    )

class NhomFilter :
    UriPartFilter(
        "Nhóm",
        arrayOf(
            Pair("Tất cả", ""),
            Pair("2M Translation Group", "nhom/2m-translation-group"),
            Pair("A Little Corner Of Myfanh", "nhom/a-little-corner-of-myfanh"),
            Pair("An Nhiên’s Group", "nhom/an-nhiens-group"),
            Pair("Anna Dao", "nhom/anna-dao"),
            Pair("Bạch Nguyệt Quang", "nhom/bach-nguyet-quang"),
            Pair("Bầu Trời Sao", "nhom/bau-troi-sao"),
            Pair("BÍ NGÔ COMIC", "nhom/bi-ngo-comic"),
            Pair("Black Cat", "nhom/black-cat"),
            Pair("Cái Mồm Xinh", "nhom/cai-mom-xinh"),
            Pair("Cơm nắm Phi Hành Gia", "nhom/com-nam-phi-hanh-gia"),
            Pair("Đông Chi Thanh Hạ", "nhom/dong-chi-thanh-ha"),
            Pair("404 ERROR TEAM", "nhom/error-team-404"),
            Pair("Haruna’s relics", "nhom/harunas-relics"),
            Pair("Hồ Ly Comic", "nhom/ho-ly-comic"),
            Pair("Hoa Ban Nhỏ – 小花花", "nhom/hoa-ban-nho-%E5%B0%8F%E8%8A%B1%E8%8A%B1"),
            Pair("J-TEAM", "nhom/j-team"),
            Pair("Josia’s Fairy Tale", "nhom/josias-fairy-tale"),
            Pair("Kho Gió", "nhom/kho-gio"),
            Pair("Lầu Mộng Nguyệt", "nhom/lau-mong-nguyet"),
            Pair("Leksibus", "nhom/leksibus"),
            Pair("Lost Planet Scanlation Team", "nhom/lost-planet-scanlation-team"),
            Pair("Mật Ong Tươi", "nhom/mat-ong-tuoi"),
            Pair("Mèo Làm Biếng", "nhom/meo-lam-bieng"),
            Pair("Miêu Dạ Tử", "nhom/mieu-da-tu"),
            Pair("Nghèo Nàn Team", "nhom/ngheo-nan-team"),
            Pair("Nguyên Cateline", "nhom/nguyen-cateline"),
            Pair("Nguyệt Hạ Team", "nhom/nguyet-ha-team"),
            Pair("Nhà Ngôn Tình Wxynz", "nhom/nha-ngon-tinh-wxynz"),
            Pair("Nhật Hạ", "nhom/nhat-ha"),
            Pair("Ổ Nhà Gấu", "nhom/o-nha-gau"),
            Pair("RBH", "nhom/rbh"),
            Pair("Truyện Nhà Mêy", "nhom/sau-khi-bi-chong-cu-giet-toi-tro-thanh-chi-dau-cua-han"),
            Pair("Seraphim Adalicia", "nhom/seraphim-adalicia"),
            Pair("Smuty Team", "nhom/smuty-team"),
            Pair("SOÁI CA COMIC", "nhom/soai-ca-comic"),
            Pair("Sữa Chuối Sicula", "nhom/sua-chuoi-sicula"),
            Pair("Hờ Hửng Team", "nhom/team-ho-hung"),
            Pair("The Mafia Team", "nhom/the-mafia-team"),
            Pair("Tiểu Hắc", "nhom/tieu-hac"),
            Pair("Tiểu Hồ Điệp", "nhom/tieu-ho-diep"),
            Pair("Tiểu Lộc Mạn", "nhom/tieu-loc-man"),
            Pair("Tiểu Yêu Đỏng Đảnh", "nhom/tieu-yeu-dong-danh"),
            Pair("Truyện Nhà Mêy", "nhom/truyen-nha-mey"),
            Pair("vlogmanhua", "nhom/vlogmanhua"),
            Pair("Vườn Bông Bê Đê", "nhom/vuon-bong-be-de"),
            Pair("Vườn Trẻ Hề", "nhom/vuon-tre-he"),
            Pair("Whitneyteam", "nhom/whitneyteam"),
        ),
    )

class LoatTruyenFilter :
    UriPartFilter(
        "Loạt Truyện",
        arrayOf(
            Pair("Tất cả", ""),
            Pair("Gặp Nhau Ở Trung Gian", "series/gap-nhau-o-trung-gian"),
            Pair("Ngày Nào Đó Bỗng Trở Thành Tế Phẩm Công Chúa", "series/ngay-nao-do-bong-tro-thanh-te-pham-cong-chua"),
            Pair("Trọn Bộ", "tron-bo"),
            Pair("Hót Nhất", "truyen-hot-nhat"),
            Pair("Xem Nhiều", "xem-nhieu-nhat"),
        ),
    )

class TuKhoaFilter :
    UriPartFilter(
        "Từ Khóa",
        arrayOf(
            Pair("Tất cả", ""),
            Pair("#Ác Ma", "ac-ma"),
            Pair("#Manh Bảo", "manh-bao"),
            Pair("#Tổng Tài", "tong-tai"),
            Pair("#Vương Gia", "vuong-gia"),
            Pair("#Vương Phi", "vuong-phi"),
        ),
    )

open class UriPartFilter(
    displayName: String,
    private val vals: Array<Pair<String, String>>,
) : Filter.Select<String>(displayName, vals.map { it.first }.toTypedArray()) {
    fun toUriPart(): String = vals[state].second
}
