package eu.kanade.tachiyomi.extension.es.onfmangas

import eu.kanade.tachiyomi.source.model.Filter

class TabFilter : Filter.Select<String>("Categoría principal", tabs.map { it.first }.toTypedArray()) {
    val selected get() = tabs[state].second

    companion object {
        private val tabs = arrayOf(
            Pair("General", "general"),
            Pair("GL / Yuri", "yuri"),
            Pair("BL / Yaoi", "yaoi"),
            Pair("Doujinshis", "doujinshi"),
        )
    }
}

class GenreFilter : Filter.Select<String>("Género", genres.map { it.first }.toTypedArray()) {
    val selected get() = genres[state].second

    companion object {
        private val genres = arrayOf(
            Pair("Todas las categorías", "0"),
            Pair("4-venida", "44"),
            Pair("A todo color", "38"),
            Pair("Acción", "14"),
            Pair("Adaptación", "13"),
            Pair("Adulto", "87"),
            Pair("Amor de chicas", "43"),
            Pair("Amor de chicos", "61"),
            Pair("Animales", "66"),
            Pair("Antología", "71"),
            Pair("Apocalipsis", "83"),
            Pair("Arreglarlo", "42"),
            Pair("Artes marciales", "7"),
            Pair("Autoeditado", "54"),
            Pair("Aventura", "15"),
            Pair("Cambio de sexo", "33"),
            Pair("Chicas magicas", "64"),
            Pair("Chicas monstruo", "22"),
            Pair("Ciencia ficción", "52"),
            Pair("Cocinando", "70"),
            Pair("Color del abanico", "80"),
            Pair("Color oficial", "69"),
            Pair("Comedia", "1"),
            Pair("Cómic web", "18"),
            Pair("Crimen", "97"),
            Pair("Culinario", "90"),
            Pair("Cultivación", "92"),
            Pair("Cyberpunk", "84"),
            Pair("Delincuentes", "12"),
            Pair("Delito", "76"),
            Pair("Demonios", "25"),
            Pair("Deportes", "68"),
            Pair("Dominó chino", "73"),
            Pair("Doujinshi", "65"),
            Pair("Drama", "2"),
            Pair("Ecchi", "3"),
            Pair("Extraterrestres", "75"),
            Pair("Fantasía", "16"),
            Pair("Fantasmas", "29"),
            Pair("Filosófico", "49"),
            Pair("Gore", "85"),
            Pair("Harem", "8"),
            Pair("Harem inverso", "81"),
            Pair("Hentai", "82"),
            Pair("Histórico", "28"),
            Pair("Horror", "51"),
            Pair("Incesto", "40"),
            Pair("Intercambio de género", "55"),
            Pair("Isekai", "11"),
            Pair("Jefe/Empleado", "88"),
            Pair("Juegos de vídeo", "58"),
            Pair("Juegos tradicionales", "72"),
            Pair("Loli", "35"),
            Pair("Mafia", "46"),
            Pair("Magia", "17"),
            Pair("Meca", "63"),
            Pair("Mecha", "53"),
            Pair("Médico", "50"),
            Pair("Militar", "36"),
            Pair("Misterio", "31"),
            Pair("Monstruos", "24"),
            Pair("Música", "78"),
            Pair("Ninja", "79"),
            Pair("Niños", "95"),
            Pair("Policía", "62"),
            Pair("Post-apocalíptico", "59"),
            Pair("Premiado", "21"),
            Pair("Psicológico", "26"),
            Pair("Realeza", "98"),
            Pair("Realidad virtual", "57"),
            Pair("Recuentos de la vida", "6"),
            Pair("Reencarnación", "9"),
            Pair("Romance", "4"),
            Pair("Samurai", "56"),
            Pair("Sangre", "27"),
            Pair("Shota", "32"),
            Pair("Shoujo Ai", "94"),
            Pair("Smut", "96"),
            Pair("Sobrenatural", "23"),
            Pair("Superhéroe", "74"),
            Pair("Supervivencia", "30"),
            Pair("Suspense", "48"),
            Pair("Suspenso", "67"),
            Pair("Tira larga", "37"),
            Pair("Trabajadores de oficina", "20"),
            Pair("Tragedia", "47"),
            Pair("Travestismo", "34"),
            Pair("Un trago", "39"),
            Pair("Vampiros", "41"),
            Pair("Venganza", "93"),
            Pair("Viaje en el tiempo", "19"),
            Pair("Vida escolar", "5"),
            Pair("Vida Laboral", "91"),
            Pair("Videojuegos", "86"),
            Pair("Villana", "45"),
            Pair("Violencia sexual", "10"),
            Pair("Wuxia", "77"),
            Pair("Yaoi", "89"),
            Pair("Zombis", "60"),
        )
    }
}
