package eu.kanade.tachiyomi.extension.en.mangaowlto

import eu.kanade.tachiyomi.source.Source
import eu.kanade.tachiyomi.source.SourceFactory

class MangaOwlToFactory : SourceFactory {
    override fun createSources(): List<Source> = listOf(
        MangaOwlTo(
            collection = "manga",
            extraName = "Manga",
            genresList = listOf(
                Genre("Action", "13"),
                Genre("Adult", "29"),
                Genre("Adventure", "31"),
                Genre("Comedy", "14"),
                Genre("Cooking", "37"),
                Genre("Doujinshi", "39"),
                Genre("Drama", "17"),
                Genre("Ecchi", "15"),
                Genre("Fantasy", "16"),
                Genre("Gender bender", "35"),
                Genre("Harem", "27"),
                Genre("Historical", "18"),
                Genre("Horror", "28"),
                Genre("Isekai", "40"),
                Genre("Josei", "23"),
                Genre("Manhua", "38"),
                Genre("Manhwa", "36"),
                Genre("Martial arts", "30"),
                Genre("Mature", "20"),
                Genre("Mecha", "33"),
                Genre("Medical", "41"),
                Genre("Mystery", "7"),
                Genre("One shot", "1"),
                Genre("Psychological", "8"),
                Genre("Romance", "10"),
                Genre("School life", "3"),
                Genre("Sci fi", "19"),
                Genre("Seinen", "25"),
                Genre("Shoujo ai", "5"),
                Genre("Shoujo", "12"),
                Genre("Shounen ai", "4"),
                Genre("Shounen", "9"),
                Genre("Slice of life", "26"),
                Genre("Smut", "32"),
                Genre("Sports", "21"),
                Genre("Supernatural", "24"),
                Genre("Tragedy", "22"),
                Genre("Webtoons", "34"),
                Genre("Yaoi", "2"),
                Genre("Yuri", "6"),
            ),
        ),
        MangaOwlTo(
            collection = "comic",
            extraName = "Comic",
            genresList = listOf(
                Genre("215 Ink", "189"),
                Genre("Ablaze", "98"),
                Genre("Action Lab", "204"),
                Genre("Aftershock Comics", "68"),
                Genre("American Mythology", "130"),
                Genre("Antartic Press", "261"),
                Genre("Archie", "178"),
                Genre("Aspen", "487"),
                Genre("Avatar Press", "177"),
                Genre("Black Mask", "107"),
                Genre("Boom Studios", "65"),
                Genre("Comics Experience", "159"),
                Genre("Dark Horse", "92"),
                Genre("DC Comics", "133"),
                Genre("Devils Due", "290"),
                Genre("Dynamite", "173"),
                Genre("Europe Comics", "67"),
                Genre("Heavy Metal", "55"),
                Genre("Humanoids", "85"),
                Genre("IDW", "110"),
                Genre("Image Comics", "60"),
                Genre("Inverse", "384"),
                Genre("Lion Forge", "162"),
                Genre("Mad Cave", "96"),
                Genre("MAD", "485"),
                Genre("Magnetic Press", "114"),
                Genre("Marvel Comics", "45"),
                Genre("One Shots &amp; TPBs", "136"),
                Genre("Oni Press", "338"),
                Genre("Rebellion", "50"),
                Genre("Red 5", "88"),
                Genre("SAF Comics", "378"),
                Genre("Soleil", "156"),
                Genre("Source Point Press", "57"),
                Genre("Space Goat Productions", "421"),
                Genre("Top Cow", "138"),
                Genre("Top Shelf", "101"),
                Genre("Upshot", "396"),
                Genre("Valiant", "87"),
                Genre("Vault", "360"),
                Genre("Vertigo", "457"),
                Genre("Zenescope", "119"),
            ),
        ),
    )
}
