package eu.kanade.tachiyomi.extension.vi.truyenhentaivn

import eu.kanade.tachiyomi.source.model.Filter
import eu.kanade.tachiyomi.source.model.FilterList

fun getFilters(): FilterList = FilterList(
    GenreFilter(),
)

class GenreFilter : UriPartFilter("Thể loại Hentai", getGenreList())

open class UriPartFilter(
    displayName: String,
    private val genres: Array<Genre>,
) : Filter.Select<String>(displayName, genres.map { it.name }.toTypedArray()) {
    fun toUriPart(): String? = genres[state].uriPart
}

class Genre(val name: String, val uriPart: String?)

private fun getGenreList(): Array<Genre> = arrayOf(
    Genre("Tất cả", null),
    Genre("3D Hentai", "/the-loai-161-3d-hentai"),
    Genre("Action", "/the-loai-142-action"),
    Genre("Adult", "/the-loai-105-adult"),
    Genre("Adventure", "/the-loai-149-adventure"),
    Genre("Ahegao", "/the-loai-1-ahegao"),
    Genre("Anal", "/the-loai-20-anal"),
    Genre("Angel", "/the-loai-94-angel"),
    Genre("Ảnh động", "/the-loai-156-anh-dong"),
    Genre("Animal", "/the-loai-2-animal"),
    Genre("Animal girl", "/the-loai-109-animal-girl"),
    Genre("Áo Dài", "/the-loai-170-ao-dai"),
    Genre("Apron", "/the-loai-168-apron"),
    Genre("Armpit", "/the-loai-174-armpit"),
    Genre("Artist CG", "/the-loai-118-artist-cg"),
    Genre("Based Game", "/the-loai-150-based-game"),
    Genre("BBM", "/the-loai-85-bbm"),
    Genre("BBW", "/the-loai-117-bbw"),
    Genre("BDSM", "/the-loai-43-bdsm"),
    Genre("Bestiality", "/the-loai-3-bestiality"),
    Genre("Big Ass", "/the-loai-89-big-ass"),
    Genre("Big Boobs", "/the-loai-13-big-boobs"),
    Genre("Big Penis", "/the-loai-48-big-penis"),
    Genre("Blackmail", "/the-loai-80-blackmail"),
    Genre("Bloomers", "/the-loai-66-bloomers"),
    Genre("BlowJobs", "/the-loai-14-blowjobs"),
    Genre("Body Swap", "/the-loai-76-body-swap"),
    Genre("Bodysuit", "/the-loai-27-bodysuit"),
    Genre("Bondage", "/the-loai-49-bondage"),
    Genre("Breast Sucking", "/the-loai-31-breast-sucking"),
    Genre("BreastJobs", "/the-loai-158-breastjobs"),
    Genre("Brocon", "/the-loai-110-brocon"),
    Genre("Brother", "/the-loai-154-brother"),
    Genre("Business Suit", "/the-loai-70-business-suit"),
    Genre("Catgirls", "/the-loai-90-catgirls"),
    Genre("Che ít", "/the-loai-4-che-it"),
    Genre("Che nhiều", "/the-loai-123-che-nhieu"),
    Genre("Cheating", "/the-loai-32-cheating"),
    Genre("Chikan", "/the-loai-81-chikan"),
    Genre("Chinese Dress", "/the-loai-140-chinese-dress"),
    Genre("Có che", "/the-loai-26-co-che"),
    Genre("Comedy", "/the-loai-40-comedy"),
    Genre("Comic", "/the-loai-133-comic"),
    Genre("Condom", "/the-loai-138-condom"),
    Genre("Cosplay", "/the-loai-61-cosplay"),
    Genre("Cousin", "/the-loai-71-cousin"),
    Genre("Crotch Tattoo", "/the-loai-163-crotch-tattoo"),
    Genre("Cunnilingus", "/the-loai-126-cunnilingus"),
    Genre("Dark Skin", "/the-loai-5-dark-skin"),
    Genre("Daughter", "/the-loai-86-daughter"),
    Genre("Deepthroat", "/the-loai-88-deepthroat"),
    Genre("Demon", "/the-loai-157-demon"),
    Genre("DemonGirl", "/the-loai-145-demongirl"),
    Genre("Devil", "/the-loai-127-devil"),
    Genre("DevilGirl", "/the-loai-108-devilgirl"),
    Genre("Dirty", "/the-loai-164-dirty"),
    Genre("Dirty Old Man", "/the-loai-62-dirty-old-man"),
    Genre("DogGirl", "/the-loai-155-doggirl"),
    Genre("Double Penetration", "/the-loai-33-double-penetration"),
    Genre("Doujinshi", "/the-loai-9-doujinshi"),
    Genre("Drama", "/the-loai-101-drama"),
    Genre("Drug", "/the-loai-50-drug"),
    Genre("Ecchi", "/the-loai-106-ecchi"),
    Genre("Elder Sister", "/the-loai-151-elder-sister"),
    Genre("Elf", "/the-loai-95-elf"),
    Genre("Exhibitionism", "/the-loai-29-exhibitionism"),
    Genre("Fantasy", "/the-loai-143-fantasy"),
    Genre("Father", "/the-loai-165-father"),
    Genre("Femdom", "/the-loai-15-femdom"),
    Genre("Fingering", "/the-loai-28-fingering"),
    Genre("Footjob", "/the-loai-121-footjob"),
    Genre("Foxgirls", "/the-loai-166-foxgirls"),
    Genre("Full Color", "/the-loai-16-full-color"),
    Genre("Furry", "/the-loai-147-furry"),
    Genre("Futanari", "/the-loai-51-futanari"),
    Genre("GangBang", "/the-loai-34-gangbang"),
    Genre("Garter Belts", "/the-loai-52-garter-belts"),
    Genre("Gender Bender", "/the-loai-96-gender-bender"),
    Genre("Ghost", "/the-loai-100-ghost"),
    Genre("Glasses", "/the-loai-35-glasses"),
    Genre("Gothic Lolita", "/the-loai-136-gothic-lolita"),
    Genre("Group", "/the-loai-17-group"),
    Genre("Guro", "/the-loai-131-guro"),
    Genre("Hairy", "/the-loai-83-hairy"),
    Genre("Handjob", "/the-loai-77-handjob"),
    Genre("Harem", "/the-loai-41-harem"),
    Genre("HentaiVN", "/the-loai-102-hentaivn"),
    Genre("Historical", "/the-loai-139-historical"),
    Genre("Horror", "/the-loai-114-horror"),
    Genre("Housewife", "/the-loai-63-housewife"),
    Genre("Humiliation", "/the-loai-87-humiliation"),
    Genre("Idol", "/the-loai-10-idol"),
    Genre("Imouto", "/the-loai-125-imouto"),
    Genre("Incest", "/the-loai-44-incest"),
    Genre("Insect (Côn Trùng)", "/the-loai-112-insect-con-trung"),
    Genre("Invisible", "/the-loai-175-invisible"),
    Genre("Isekai", "/the-loai-169-isekai"),
    Genre("Không che", "/the-loai-18-khong-che"),
    Genre("Kimono", "/the-loai-82-kimono"),
    Genre("Kissing", "/the-loai-172-kissing"),
    Genre("Kuudere", "/the-loai-159-kuudere"),
    Genre("Lolicon", "/the-loai-6-lolicon"),
    Genre("Maids", "/the-loai-21-maids"),
    Genre("Manhua", "/the-loai-162-manhua"),
    Genre("Manhwa", "/the-loai-115-manhwa"),
    Genre("Masturbation", "/the-loai-30-masturbation"),
    Genre("Mature", "/the-loai-128-mature"),
    Genre("Miko", "/the-loai-97-miko"),
    Genre("Milf", "/the-loai-53-milf"),
    Genre("Mind Break", "/the-loai-54-mind-break"),
    Genre("Mind Control", "/the-loai-91-mind-control"),
    Genre("Mizugi", "/the-loai-144-mizugi"),
    Genre("Monster", "/the-loai-122-monster"),
    Genre("Monstergirl", "/the-loai-72-monstergirl"),
    Genre("Mother", "/the-loai-55-mother"),
    Genre("Nakadashi", "/the-loai-56-nakadashi"),
    Genre("Netori", "/the-loai-129-netori"),
    Genre("Non-hen", "/the-loai-141-non-hen"),
    Genre("NTR", "/the-loai-36-ntr"),
    Genre("Nun", "/the-loai-135-nun"),
    Genre("Nurse", "/the-loai-42-nurse"),
    Genre("Old Man", "/the-loai-67-old-man"),
    Genre("Oneshot", "/the-loai-7-oneshot"),
    Genre("Oral", "/the-loai-65-oral"),
    Genre("Osananajimi", "/the-loai-134-osananajimi"),
    Genre("Paizuri", "/the-loai-19-paizuri"),
    Genre("Pantyhose", "/the-loai-103-pantyhose"),
    Genre("Ponytail", "/the-loai-99-ponytail"),
    Genre("Pregnant", "/the-loai-57-pregnant"),
    Genre("Prostitution", "/the-loai-173-prostitution"),
    Genre("Rape", "/the-loai-22-rape"),
    Genre("Rimjob", "/the-loai-84-rimjob"),
    Genre("Romance", "/the-loai-120-romance"),
    Genre("Ryona", "/the-loai-119-ryona"),
    Genre("Scat", "/the-loai-68-scat"),
    Genre("School Uniform", "/the-loai-11-school-uniform"),
    Genre("SchoolGirl", "/the-loai-12-schoolgirl"),
    Genre("Series", "/the-loai-37-series"),
    Genre("Sex Toys", "/the-loai-23-sex-toys"),
    Genre("Shimapan", "/the-loai-73-shimapan"),
    Genre("Short Hentai", "/the-loai-78-short-hentai"),
    Genre("Shota", "/the-loai-45-shota"),
    Genre("Shoujo", "/the-loai-148-shoujo"),
    Genre("Siscon", "/the-loai-111-siscon"),
    Genre("Sister", "/the-loai-58-sister"),
    Genre("Slave", "/the-loai-46-slave"),
    Genre("Sleeping", "/the-loai-92-sleeping"),
    Genre("Small Boobs", "/the-loai-8-small-boobs"),
    Genre("Son", "/the-loai-160-son"),
    Genre("Sports", "/the-loai-64-sports"),
    Genre("Stockings", "/the-loai-24-stockings"),
    Genre("Supernatural", "/the-loai-107-supernatural"),
    Genre("Sweating", "/the-loai-59-sweating"),
    Genre("Swimsuit", "/the-loai-47-swimsuit"),
    Genre("Tall Girl", "/the-loai-146-tall-girl"),
    Genre("Teacher", "/the-loai-38-teacher"),
    Genre("Tentacles", "/the-loai-39-tentacles"),
    Genre("Time Stop", "/the-loai-124-time-stop"),
    Genre("Tomboy", "/the-loai-98-tomboy"),
    Genre("Tracksuit", "/the-loai-152-tracksuit"),
    Genre("Transformation", "/the-loai-153-transformation"),
    Genre("Trap", "/the-loai-132-trap"),
    Genre("Truyện Việt", "/the-loai-167-truyen-viet"),
    Genre("Tsundere", "/the-loai-104-tsundere"),
    Genre("Twins", "/the-loai-79-twins"),
    Genre("Twintails", "/the-loai-74-twintails"),
    Genre("Vampire", "/the-loai-137-vampire"),
    Genre("Vanilla", "/the-loai-113-vanilla"),
    Genre("Virgin", "/the-loai-25-virgin"),
    Genre("Webtoon", "/the-loai-116-webtoon"),
    Genre("X-ray", "/the-loai-75-x-ray"),
    Genre("Yandere", "/the-loai-93-yandere"),
    Genre("Yaoi", "/the-loai-60-yaoi"),
    Genre("Yuri", "/the-loai-69-yuri"),
    Genre("Zombie", "/the-loai-130-zombie"),
)
