package eu.kanade.tachiyomi.extension.all.beauty3600000

import eu.kanade.tachiyomi.source.model.Filter

open class UriPartFilter(
    displayName: String,
    private val valuePair: Array<Pair<String, String>>,
) : Filter.Select<String>(displayName, valuePair.map { it.first }.toTypedArray()) {
    fun toUriPart() = valuePair[state].second
}

class CategoryFilter :
    UriPartFilter(
        "Category",
        arrayOf(
            Pair("Any", ""),
            Pair("Aidol", "6"),
            Pair("China", "3293"),
            Pair("Chinese", "5"),
            Pair("Cosplay", "4"),
            Pair("Gravure", "7"),
            Pair("Japan", "3291"),
            Pair("Korea", "2128"),
            Pair("Magazine", "9"),
            Pair("Photobook", "10"),
            Pair("Thailand", "8"),
            Pair("Uncategorized", "1"),
            Pair("Western", "11"),
        ),
    )

// NOTE: Source has way more tags (~6000)
class TagFilter :
    UriPartFilter(
        "Tag",
        arrayOf(
            Pair("<Select tag>", ""),
            Pair("[☆JVID]", "1036"),
            Pair("[4K-STAR]", "1293"),
            Pair("[AISS爱丝钻石版]", "791"),
            Pair("[Akisoso秋楚楚]", "2578"),
            Pair("[AllGravure]", "1608"),
            Pair("[ArtGravia]", "2130"),
            Pair("[Arty亞緹]", "2207"),
            Pair("[Ayase_绮滨酱]", "2526"),
            Pair("[Azami]", "2164"),
            Pair("[Baijin Jiang]", "2225"),
            Pair("[BBUTTERMILK]", "3219"),
            Pair("[Bejean On Line]", "711"),
            Pair("[Bimilstory]", "3033"),
            Pair("[BLUECAKE]", "2454"),
            Pair("[BOMB.tv]", "102"),
            Pair("[BUNNY]", "4255"),
            Pair("[Byoru ビヨル]", "2275"),
            Pair("[CANDY糖果画报]", "590"),
            Pair("[CherryS]", "2658"),
            Pair("[chi.yun]", "2199"),
            Pair("[Chihiro]", "2645"),
            Pair("[CHOKmoson作品]", "729"),
            Pair("[Chono Black ちょうの]", "2337"),
            Pair("[coli厨 水無月みり]", "2237"),
            Pair("[Conboy]", "4649"),
            Pair("[Cosdoki]", "1822"),
            Pair("[Cosplay]", "458"),
            Pair("[CREAM PIE]", "4471"),
            Pair("[CreamSoda]", "2497"),
            Pair("[Crepe]", "1026"),
            Pair("[DCP-snaps]", "4655"),
            Pair("[Deepblue]", "4710"),
            Pair("[Deepmore Office]", "4435"),
            Pair("[DGC] (Desktop Gal Collection)", "172"),
            Pair("[Digi-Gra]", "634"),
            Pair("[Digital Photobook]", "1632"),
            Pair("[Dishwasher1910]", "2457"),
            Pair("[DJAWA]", "2131"),
            Pair("[DKGirl御女郎]", "208"),
            Pair("[DPB] デジタル写真集", "753"),
            Pair("[ED MOSAIC]", "1609"),
            Pair("[Eliza喵喵 Elizamiaomiao]", "2264"),
            Pair("[Ely]", "2316"),
            Pair("[EROONICHAN]", "1067"),
            Pair("[EroticBeauty]", "902"),
            Pair("[Espacia Korea]", "4881"),
            Pair("[Espasia Korea]", "3194"),
            Pair("[EternalDesire]", "904"),
            Pair("[Eugene Snap]", "4082"),
            Pair("[FAIRY CLUB 妖精社]", "3115"),
            Pair("[FANDING]", "3651"),
            Pair("[Fantasy Story]", "4381"),
            Pair("[FEILIN嗲囡囡]", "341"),
            Pair("[FemJoy]", "915"),
            Pair("[Fetibox]", "657"),
            Pair("[G44不会受伤]", "2600"),
            Pair("[G44不會受傷]", "2352"),
            Pair("[Ghost私房]", "1100"),
            Pair("[GirlFriendEnd]", "3439"),
            Pair("[Girlz-High]", "43"),
            Pair("[Glamarchive]", "4306"),
            Pair("[Graphis]", "15"),
            Pair("[H.J.Chamber作品集]", "2478"),
            Pair("[Hachi小芭]", "2255"),
            Pair("[Hana Bunny]", "2109"),
            Pair("[HaneAme 雨波]", "2444"),
            Pair("[Hegre-Art]", "903"),
            Pair("[Hidori Rose]", "2330"),
            Pair("[HIGH FANTASY]", "4279"),
            Pair("[Hokunaimeko]", "1700"),
            Pair("[HONGDAN]", "4760"),
            Pair("[HUAFOX系列]", "1811"),
            Pair("[HuaYang花漾]", "24"),
            Pair("[HuaYan花の颜]", "170"),
            Pair("[iAsian4u]", "1383"),
            Pair("[Idol Line]", "788"),
            Pair("[IKOF-6]", "4963"),
            Pair("[Ilogos アイロゴス]", "386"),
            Pair("[Image.tv]", "939"),
            Pair("[IMISS爱蜜社]", "160"),
            Pair("[IShow愛秀]", "2160"),
            Pair("[IVITAMIN系列]", "932"),
            Pair("[JOApictures]", "2872"),
            Pair("[Jooa]", "2283"),
            Pair("[JVID美模]", "1028"),
            Pair("[KaYa萱]", "2099"),
            Pair("[Kettoe]", "2375"),
            Pair("[KIMLEMON]", "3843"),
            Pair("[KIREI]", "4709"),
            Pair("[KiSiA]", "4421"),
            Pair("[KIYO キヨ]", "2431"),
            Pair("[KONELA]", "3213"),
            Pair("[Korean Realgraphic]", "3110"),
            Pair("[KuukoW クー子]", "2090"),
            Pair("[LEEHEE EXPRESS]", "2443"),
        ),
    )
