package eu.kanade.tachiyomi.extension.vi.tusachxinhxinh

import eu.kanade.tachiyomi.source.model.Filter
import eu.kanade.tachiyomi.source.model.FilterList

fun getFilters(): FilterList = FilterList(
    Filter.Header("Bộ lọc sẽ bị bỏ qua khi tìm kiếm"),
    GenreFilter(),
    GroupFilter(),
    SeriesTypeFilter(),
    KeywordFilter(),
)

class GenreFilter :
    UriPartFilter(
        "Thể loại",
        arrayOf(
            Pair("Tất cả", ""),
            Pair("15+", "the-loai/15"),
            Pair("18+", "the-loai/18"),
            Pair("1x1", "the-loai/1x1"),
            Pair("ABO", "the-loai/abo"),
            Pair("Action", "the-loai/action"),
            Pair("Adaptation", "the-loai/adaptation"),
            Pair("Adult", "the-loai/adult"),
            Pair("Adventure", "the-loai/adventure"),
            Pair("Anh chàng lắm mưu", "the-loai/anh-chang-lam-muu"),
            Pair("Animal", "the-loai/animal"),
            Pair("Âu cổ", "the-loai/au-co"),
            Pair("Baby", "the-loai/baby"),
            Pair("Bách Hợp", "the-loai/bach-hop"),
            Pair("BE", "the-loai/be"),
            Pair("Bender", "the-loai/bender"),
            Pair("Betrayal", "the-loai/betrayal"),
            Pair("Bí ẩn", "the-loai/bi-an"),
            Pair("Bi Kịch", "the-loai/bi-kich"),
            Pair("BL", "the-loai/bl"),
            Pair("BLHĐ", "the-loai/blhd"),
            Pair("Boy Tâm Cơ", "the-loai/boy-tam-co"),
            Pair("Childcare", "the-loai/childcare"),
            Pair("Chủ Thụ", "the-loai/chu-thu"),
            Pair("Chữa Lành", "the-loai/chua-lanh"),
            Pair("Chuyển Sinh", "the-loai/chuyen-sinh"),
            Pair("Cổ Đại", "the-loai/co-dai"),
            Pair("Cô nàng nhút nhát", "the-loai/co-nang-nhut-nhat"),
            Pair("Cổ Trang", "the-loai/co-trang"),
            Pair("Comedy", "the-loai/comedy"),
            Pair("Comic", "the-loai/comic"),
            Pair("Cooking", "the-loai/cooking"),
            Pair("Crime", "the-loai/crime"),
            Pair("Cưới trước yêu sau", "the-loai/cuoi-truoc-yeu-sau"),
            Pair("Dark", "the-loai/dark"),
            Pair("Drama", "the-loai/drama"),
            Pair("Đam Mỹ", "the-loai/dam-my"),
            Pair("Đô Thị", "the-loai/do-thi"),
            Pair("Đơn Phương", "the-loai/don-phuong"),
            Pair("Ecchi", "the-loai/ecchi"),
            Pair("Esper and Guide", "the-loai/esper-and-guide"),
            Pair("Fantasy", "the-loai/fantasy"),
            Pair("First Love", "the-loai/first-love"),
            Pair("Full Color", "the-loai/full-color"),
            Pair("Game", "the-loai/game"),
            Pair("Gender", "the-loai/gender"),
            Pair("Gender Bender", "the-loai/gender-bender"),
            Pair("Gender Blender", "the-loai/gender-blender"),
            Pair("Ghosts", "the-loai/ghosts"),
            Pair("Giật gân", "the-loai/giat-gan"),
            Pair("Giới Giải Trí", "the-loai/gioi-giai-tri"),
            Pair("Girl Crush", "the-loai/girl-crush"),
            Pair("GL", "the-loai/gl"),
            Pair("Hài Hước", "the-loai/hai-huoc"),
            Pair("Hầm Ngục", "the-loai/ham-nguc"),
            Pair("Harem", "the-loai/harem"),
            Pair("Hệ Thống", "the-loai/he-thong"),
            Pair("Hiện Đại", "the-loai/hien-dai"),
            Pair("Historical", "the-loai/historical"),
            Pair("Hoán đổi thân xác", "the-loai/hoan-doi-than-xac"),
            Pair("Hoàng Gia", "the-loai/hoang-gia"),
            Pair("Học Đường", "the-loai/hoc-duong"),
            Pair("Horror", "the-loai/horror"),
            Pair("Huyền Huyễn", "the-loai/huyen-huyen"),
            Pair("Idol", "the-loai/idol"),
            Pair("Isekai", "the-loai/isekai"),
            Pair("Josei", "the-loai/josei"),
            Pair("Josei(W)", "the-loai/joseiw"),
            Pair("Kingdom", "the-loai/kingdom"),
            Pair("Kinh Dị", "the-loai/kinh-di"),
            Pair("Lãng Mạn", "the-loai/lang-man"),
            Pair("Light Novel", "the-loai/light-novel"),
            Pair("Love Triangle", "the-loai/love-triangle"),
            Pair("Ma Cà Rồng", "the-loai/ma-ca-rong"),
            Pair("Magic", "the-loai/magic"),
            Pair("Mahou", "the-loai/mahou"),
            Pair("Manga", "the-loai/manga"),
            Pair("Manhua", "the-loai/manhua"),
            Pair("Manhwa", "the-loai/manhwa"),
            Pair("Martial Arts", "the-loai/martial-arts"),
            Pair("Mất Trí Nhớ", "the-loai/mat-tri-nho"),
            Pair("Mature", "the-loai/mature"),
            Pair("Mindgame", "the-loai/mindgame"),
            Pair("Murim", "the-loai/murim"),
            Pair("Mỹ Thực", "the-loai/my-thuc"),
            Pair("Mystery", "the-loai/mystery"),
            Pair("N9 giả nữ", "the-loai/n9-gia-nu"),
            Pair("NamNu9 Cùng Xuyên", "the-loai/namnu9-cung-xuyen"),
            Pair("Ngôn Tình", "the-loai/ngon-tinh"),
            Pair("Ngọt Sủng", "the-loai/ngot-sung"),
            Pair("Ngược", "the-loai/nguoc"),
            Pair("Nhân Thú", "the-loai/nhan-thu"),
            Pair("Novel", "the-loai/novel"),
            Pair("Nữ chủ", "the-loai/nu-chu"),
            Pair("Nữ Cường", "the-loai/nu-cuong"),
            Pair("Nu9 giả nam", "the-loai/nu9-gia-nam"),
            Pair("Oneshot", "the-loai/oneshot"),
            Pair("Phép Thuật", "the-loai/phep-thuat"),
            Pair("Prologue", "the-loai/prologue"),
            Pair("Psychological", "the-loai/psychological"),
            Pair("Reincarnation", "the-loai/reincarnation"),
            Pair("Revenge", "the-loai/revenge"),
            Pair("Reverse Harem", "the-loai/reverse-harem"),
            Pair("Romance", "the-loai/romance"),
            Pair("Romance Comedy", "the-loai/romance-comedy"),
            Pair("Sắc", "the-loai/sac"),
            Pair("School Life", "the-loai/school-life"),
            Pair("Second Chance", "the-loai/second-chance"),
            Pair("Shoujo", "the-loai/shoujo"),
            Pair("Shoujo Ai", "the-loai/shoujo-ai"),
            Pair("Shounen", "the-loai/shounen"),
            Pair("Shounen Ai", "the-loai/shounen-ai"),
            Pair("Showbiz", "the-loai/showbiz"),
            Pair("Siêu Năng Lực", "the-loai/sieu-nang-luc"),
            Pair("Slice of Life", "the-loai/slice-of-life"),
            Pair("Spiritualism", "the-loai/spiritualism"),
            Pair("Super Power", "the-loai/super-power"),
            Pair("Supernatural", "the-loai/supernatural"),
            Pair("Suspense", "the-loai/suspense"),
            Pair("Sweet", "the-loai/sweet"),
            Pair("Tâm lí", "the-loai/tam-li"),
            Pair("Thần tượng", "the-loai/than-tuong"),
            Pair("Thanh mai trúc mã", "the-loai/thanh-mai-truc-ma"),
            Pair("Thanh Xuân Vườn Trường", "the-loai/thanh-xuan-vuon-truong"),
            Pair("Thriller", "the-loai/thriller"),
            Pair("Thương Trường", "the-loai/thuong-truong"),
            Pair("Tiểu Thuyết", "the-loai/tieu-thuyet"),
            Pair("Tim", "the-loai/tim"),
            Pair("Time Travel", "the-loai/time-travel"),
            Pair("Tình Cảm", "the-loai/tinh-cam"),
            Pair("Tình Yêu Công Sở", "the-loai/tinh-yeu-cong-so"),
            Pair("Tình Yêu Kém Tuổi", "the-loai/tinh-yeu-kem-tuoi"),
            Pair("Tổng Tài", "the-loai/tong-tai"),
            Pair("Trả Thù", "the-loai/tra-thu"),
            Pair("Tragedy", "the-loai/tragedy"),
            Pair("Tragic Past", "the-loai/tragic-past"),
            Pair("Trang điểm", "the-loai/trang-diem"),
            Pair("Trinh Thám", "the-loai/trinh-tham"),
            Pair("Trọng Sinh", "the-loai/trong-sinh"),
            Pair("Trùng Sinh", "the-loai/trung-sinh"),
            Pair("Truyện 4 khung", "the-loai/truyen-4-khung"),
            Pair("Truyện Ngắn", "the-loai/truyen-ngan"),
            Pair("Tu Tiên", "the-loai/tu-tien"),
            Pair("Võ Lâm", "the-loai/vo-lam"),
            Pair("Webtoon", "the-loai/webtoon"),
            Pair("Xuyên Không", "the-loai/xuyen-khong"),
            Pair("Xuyên Nhanh", "the-loai/xuyen-nhanh"),
            Pair("Xuyên Sách", "the-loai/xuyen-sach"),
            Pair("Yandere", "the-loai/yandere"),
            Pair("Yaoi", "the-loai/yaoi"),
            Pair("Yuri", "the-loai/yuri"),
        ),
    )

class GroupFilter :
    UriPartFilter(
        "Nhóm",
        arrayOf(
            Pair("Tất cả", ""),
            Pair("Bông-er", "nhom/bong-er"),
            Pair("Calliandra Tuor", "nhom/calliandra-tuor"),
            Pair("Cinder's Tea Time Team", "nhom/cinders-tea-time-team"),
            Pair("Closed Heart", "nhom/closed-heart"),
            Pair("Củ Cải Nhỏ", "nhom/cu-cai-nho"),
            Pair("Diệp Tư Mục", "nhom/diep-tu-muc-%e5%8f%b6%e6%80%9d%e7%bc%aa"),
            Pair("Falena Team", "nhom/falena-team"),
            Pair("HeliumTG", "nhom/heliumtg"),
            Pair("Hoa Viên Mèo Lười", "nhom/hoa-vien-meo-luoi"),
            Pair("Hồng Trà Mật Ong – Truyện Nhà Dịch", "nhom/hong-tra-mat-ong-truyen-nha-dich"),
            Pair("Ivy Comic", "nhom/ivy-comic"),
            Pair("Like An Espresso", "nhom/like-an-espresso"),
            Pair("Little Bunny", "nhom/little-bunny"),
            Pair("Little Cat Team", "nhom/little-cat-team"),
            Pair("MIKE DID IT", "nhom/mike-did-it"),
            Pair("Miyuki Comics", "nhom/miyuki-comics"),
            Pair("Mồn Lèo Biết Bay", "nhom/mon-leo-biet-bay"),
            Pair("Munn's House", "nhom/munns-house"),
            Pair("Nàng Bạch Thỏ", "nhom/nang-bach-tho"),
            Pair("Nhiều chút dopamine", "nhom/nhieu-chut-dopamine"),
            Pair("Nova's Zone Team", "nhom/novas-zone-team"),
            Pair("Ổ Truyện Dịch Nhà Chowder", "nhom/o-truyen-dich-nha-chowder"),
            Pair("Panda Team", "nhom/panda-team"),
            Pair("Râu Mơ Ry", "nhom/rosemary-team"),
            Pair("Sứa Biển", "nhom/sua-bien"),
            Pair("Tart Trứng Vị Hỗn Hợp", "nhom/tart-trung-vi-hon-hop"),
            Pair("The Wolf Team", "nhom/the-wolf-team"),
            Pair("Tiệm Nhỏ Nhà Mây", "nhom/tiem-nho-nha-may"),
            Pair("Vì Tinh Tú Hình Củ Chuối", "nhom/vi-tinh-tu-hinh-cu-chuoi"),
            Pair("Yurei Fansub", "nhom/yurei-fansub"),
        ),
    )

class SeriesTypeFilter :
    UriPartFilter(
        "Loại Truyện",
        arrayOf(
            Pair("Tất cả", ""),
            Pair("Hot Nhất", "truyen-hot-nhat"),
            Pair("Xem Nhiều", "nhieu-xem-nhat"),
            Pair("Trọn Bộ", "tron-bo"),
        ),
    )

class KeywordFilter :
    UriPartFilter(
        "Từ khóa",
        arrayOf(
            Pair("Tất cả", ""),
            Pair("#Ác Nữ", "ac-nu"),
            Pair("#Bạo Chúa", "bao-chua"),
            Pair("#Bệ Hạ", "be-ha"),
            Pair("#Con Gái", "con-gai"),
            Pair("#Hẹn Hò", "hen-ho"),
            Pair("#Nam Chính", "nam-chinh"),
            Pair("#Nhân Vật", "nhan-vat"),
            Pair("#Phản Diện", "phan-dien"),
            Pair("#Phương Pháp", "phuong-phap"),
            Pair("#Tiểu Thư", "tieu-thu"),
            Pair("#Tình Yêu", "tinh-yeu"),
            Pair("#Trở Thành", "tro-thanh"),
            Pair("#Yêu Tôi", "yeu-toi"),
        ),
    )

open class UriPartFilter(
    displayName: String,
    private val vals: Array<Pair<String, String>>,
) : Filter.Select<String>(displayName, vals.map { it.first }.toTypedArray()) {
    fun toUriPart() = vals[state].second
}
