package eu.kanade.tachiyomi.extension.pt.spectralscan

import eu.kanade.tachiyomi.source.model.Filter
import kotlinx.serialization.Serializable

class SelectFilter(
    displayName: String = "",
    val parameter: String = "",
    private val vals: Array<Pair<String, String>>,
    state: Int = 0,
) : Filter.Select<String>(displayName, vals.map { it.first }.toTypedArray(), state) {
    fun selected() = vals[state].second
}

val sortList = arrayOf(
    "Mais Recentes" to "latest",
    "Mais Populares" to "popular",
    "Melhor Avaliação" to "rating",
    "Nome (A-Z)" to "name_asc",
    "Nome (Z-A)" to "name_desc",
)

val genreList = arrayOf(
    "Todos os Gêneros" to "",
    "Academia de Magia" to "academia-de-magia",
    "Acadêmica" to "academica",
    "Ação" to "acao",
    "Adaptação" to "adaptacao",
    "Adaptação de Novel" to "adaptacao-de-novel",
    "Adultério" to "adulterio",
    "Adulto" to "adulto",
    "Ahegao" to "ahegao",
    "Apocalipse" to "apocalipse",
    "App" to "app",
    "Artes Marciais" to "artes-marciais",
    "Aventura" to "aventura",
    "BDSM" to "bdsm",
    "Bondage" to "bondage",
    "Bullying" to "bullying",
    "Bunda Grande" to "bunda-grande",
    "Campus" to "campus",
    "Cartoon" to "cartoon",
    "Casada" to "casada",
    "Casamento" to "casamento",
    "Club" to "club",
    "Comédia" to "comedia",
    "Comédia Romântica" to "comedia-romantica",
    "Comida" to "comida",
    "Cotidiano" to "cotidiano",
    "Crime" to "crime",
    "Culinária" to "culinaria",
    "Cultivo" to "cultivo",
    "Curta" to "curta",
    "Cyberpunk" to "cyberpunk",
    "Dark Romance" to "dark-romance",
    "Demônio" to "demonio",
    "Demônios" to "demonios",
    "Dominação" to "dominacao",
    "Doujinshi" to "doujinshi",
    "Dragões" to "dragoes",
    "Drama" to "drama",
    "Ecchi" to "ecchi",
    "Escolar" to "escolar",
    "Escritório" to "escritorio",
    "Esporte" to "esporte",
    "Esportes" to "Esportes",
    "Estratégia" to "estrategia",
    "Estudante" to "estudante",
    "Exibicionismo" to "exibicionismo",
    "Família" to "familia",
    "Família Real" to "familia-real",
    "Fantasia" to "fantasia",
    "Fantasmas" to "fantasmas",
    "Fetiche" to "fetiche",
    "Ficção Científica" to "ficcao-cientifica",
    "Futanari" to "futanari",
    "Game" to "game",
    "Game System" to "game-system",
    "Gangster" to "gangster",
    "Gender Bender" to "gender-bender",
    "Gênio" to "genio",
    "Gore" to "gore",
    "Guerra" to "guerra",
    "Hardcore" to "hardcore",
    "Harem" to "harem",
    "Harém Reverso" to "harem-reverso",
    "Hentai" to "hentai",
    "Híbrido" to "hibrido",
    "História" to "historia",
    "Histórico" to "historico",
    "Horror" to "horror",
    "Idols" to "idols",
    "Incesto" to "incesto",
    "Isekai" to "isekai",
    "Jogo" to "jogo",
    "Jogos" to "jogos",
    "Josei" to "josei",
    "Luta" to "luta",
    "Máfia" to "mafia",
    "Magia" to "magia",
    "Magia Escolar" to "magia-escolar",
    "Mature" to "mature",
    "Mecha" to "mecha",
    "Médico" to "medico",
    "Metaverso" to "metaverso",
    "Milf" to "milf",
    "Militar" to "militar",
    "Mistério" to "misterio",
    "Mitologia" to "mitologia",
    "MMORPG" to "mmorpg",
    "Monstros" to "monstros",
    "Murim" to "murim",
    "Música" to "musica",
    "Musical" to "musical",
    "Nerd" to "nerd",
    "Netori" to "netori",
    "Obsessão" to "obsessao",
    "One Shot" to "one-shot",
    "Oneshot" to "oneshot",
    "Peitões" to "peitoes",
    "Perda de Memória" to "perda-de-memoria",
    "Polícia" to "policia",
    "Policial" to "policial",
    "Portais" to "portais",
    "Pós-apocalíptico" to "pos-apocaliptico",
    "Profecias" to "profecias",
    "Prostituição" to "prostituicao",
    "Psicológico" to "psicologico",
    "Psicopata" to "psicopata",
    "Realidade Virtual" to "realidade-virtual",
    "Realismo" to "realismo",
    "Reencarnação" to "reencarnacao",
    "Reencontro" to "reencontro",
    "Regressão" to "regressao",
    "Retornado" to "retornado",
    "Retorno" to "retorno",
    "Revenge" to "revenge",
    "Romance" to "romance",
    "RPG" to "rpg",
    "Sangue" to "sangue",
    "School Life" to "school-life",
    "Sci-Fi" to "sci-fi",
    "Seinen" to "seinen",
    "Sem Censura" to "sem-censura",
    "Shoujo" to "shoujo",
    "Shounen" to "shounen",
    "Sistema" to "sistema",
    "Sistema de Níveis" to "sistema-de-niveis",
    "Slice of Life" to "slice-of-life",
    "Smut" to "smut",
    "Sobrenatural" to "sobrenatural",
    "Sobrevivência" to "sobrevivencia",
    "Sombrio" to "sombrio",
    "Sports" to "sports",
    "Submissão" to "submissao",
    "Sugestivo" to "sugestivo",
    "Super Poderes" to "super-poderes",
    "Supernatural" to "supernatural",
    "Superpoderes" to "superpoderes",
    "Suspense" to "suspense",
    "Tecnológico" to "tecnologico",
    "Tela de Sistema" to "tela-de-sistema",
    "Terror" to "terror",
    "Thriller" to "thriller",
    "Tomboy" to "tomboy",
    "Torre" to "torre",
    "Tóxico" to "toxico",
    "Tragédia" to "tragedia",
    "Traição" to "traicao",
    "Triângulo" to "triangulo",
    "Tsundere" to "tsundere",
    "Universitários" to "universitarios",
    "Vampiro" to "vampiro",
    "Vampiros" to "vampiros",
    "Viagem no Tempo" to "viagem-no-tempo",
    "Vida Adulta" to "vida-adulta",
    "Vida Cotidiana" to "vida-cotidiana",
    "Vida Escolar" to "vida-escolar",
    "Video Game" to "video-game",
    "Video Games" to "video-games",
    "Vídeo Game" to "video-game-1",
    "Vingança" to "vinganca",
    "Violência" to "violencia",
    "Volta no Tempo" to "volta-no-tempo",
    "VRMMO" to "vrmmo",
    "Web Comic" to "web-comic",
    "Webcomic" to "webcomic",
    "Wuxia" to "wuxia",
    "Xianxia" to "xianxia",
    "Xuanhuan" to "xuanhuan",
    "Yuri" to "yuri",
    "Zumbis" to "zumbis",
)

val typeList = arrayOf(
    "Todos os Tipos" to "",
    "Manga" to "manga",
    "Manhwa" to "manhwa",
    "Manhua" to "manhua",
    "Webtoon" to "webtoon",
    "Comic" to "comic",
    "HQ" to "hq",
    "Pornhwa" to "pornhwa",
)

@Serializable
class MangaListResponse(
    val html: String = "",
    val has_next: Boolean = false,
)

@Serializable
class ChapterListResponse(
    val chapters_html: String = "",
    val has_next: Boolean = false,
)

@Serializable
class PageData(
    val page_number: Int = 0,
    val image_url: String = "",
)
