@file:Suppress("SpellCheckingInspection")

package eu.kanade.tachiyomi.extension.es.heavenmanga

import eu.kanade.tachiyomi.source.model.Filter

open class UriPartFilter(displayName: String, val vals: Array<Pair<String, String>>) : Filter.Select<String>(displayName, vals.map { it.first }.toTypedArray()) {
    fun toUriPart() = vals[state].second
}

class GenreFilter :
    UriPartFilter(
        "Géneros",
        arrayOf(
            Pair("<Seleccionar>", ""),
            Pair("Accion", "accion"),
            Pair("Adulto", "adulto"),
            Pair("Artes Marciales", "artes-marciales"),
            Pair("Acontesimientos de la Vida", "acontesimientos-de-la-vida"),
            Pair("Bakunyuu", "bakunyuu"),
            Pair("Gore", "gore"),
            Pair("Gender Bender", "gender-bender"),
            Pair("Humor", "humor"),
            Pair("Harem", "harem"),
            Pair("Hentai", "hentai"),
            Pair("Horror", "horror"),
            Pair("Historico", "historico"),
            Pair("Josei", "josei"),
            Pair("Loli", "loli"),
            Pair("Light", "light"),
            Pair("Lucha Libre", "lucha-libre"),
            Pair("Manga", "manga"),
            Pair("Mecha", "mecha"),
            Pair("Magia", "magia"),
            Pair("Manhwa", "manhwa"),
            Pair("Manhua", "manhua"),
            Pair("Mature", "mature"),
            Pair("Misterio", "misterio"),
            Pair("Mutantes", "mutantes"),
            Pair("Novela", "novela"),
            Pair("OneShot", "oneshot"),
            Pair("Psicologico", "psicologico"),
            Pair("Romance", "romance"),
            Pair("Recuentos de la vida", "recuentos-de-la-vida"),
            Pair("Smut", "smut"),
            Pair("Shojo", "shojo"),
            Pair("Shonen", "shonen"),
            Pair("Seinen", "seinen"),
            Pair("Shoujo", "shoujo"),
            Pair("Shounen", "shounen"),
            Pair("Suspenso", "suspenso"),
            Pair("School Life", "school-life"),
            Pair("SuperHeroes", "superheroes"),
            Pair("Supernatural", "supernatural"),
            Pair("Slice of Life", "slice-of-life"),
            Pair("Super Poderes", "super-poderes"),
            Pair("Torneo", "torneo"),
            Pair("Tragedia", "tragedia"),
            Pair("Transexual", "transexual"),
            Pair("Vampiros", "vampiros"),
            Pair("Violencia", "violencia"),
            Pair("Vida Pasadas", "vida-pasadas"),
            Pair("Vida Cotidiana", "vida-cotidiana"),
            Pair("Vida de Escuela", "vida-de-escuela"),
            Pair("Webtoon", "webtoon"),
            Pair("Yaoi", "yaoi"),
            Pair("Yuri", "yuri"),
            Pair("Sobrenatural", "sobrenatural"),
            Pair("Drama", "drama"),
            Pair("Ecchi", "ecchi"),
            Pair("Comedia", "comedia"),
            Pair("Aventura", "aventura"),
            Pair("Fantasia", "fantasia"),
            Pair("Demonios", "demonios"),
            Pair("Superpoderes", "superpoderes"),
            Pair("Deporte", "deporte"),
            Pair("Ciencia Ficcion", "ciencia-ficcion"),
            Pair("Supervivencia", "supervivencia"),
            Pair("Crimen", "crimen"),
            Pair("Reencarnación", "reencarnacion"),
            Pair("Género Bender", "genero-bender"),
            Pair("Apocaliptico", "apocaliptico"),
            Pair("Familia", "familia"),
            Pair("Militar", "militar"),
            Pair("Guerra", "guerra"),
            Pair("Realidad", "realidad"),
            Pair("Animación", "animacion"),
            Pair("Musica", "musica"),
            Pair("Samurái", "samurai"),
            Pair("Historia", "historia"),
            Pair("Thriller", "thriller"),
            Pair("Girls Love", "girls-love"),
            Pair("Zombies", "zombies"),
            Pair("Netorare", "netorare"),
            Pair("Boys Love", "boys-love"),
            Pair("Transmigración", "transmigracion"),
            Pair("Regresion", "regresion"),
            Pair("Harem Inverso", "harem-inverso"),
            Pair("Moderno", "moderno"),
            Pair("Sistema", "sistema"),
            Pair("Venganza", "venganza"),
            Pair("Amateur", "amateur"),
            Pair("Parodia", "parodia"),
            Pair("Matrimonio", "matrimonio"),
        ),
    )

class AlphabeticoFilter :
    UriPartFilter(
        "Alfabético",
        arrayOf(
            Pair("<Seleccionar>", ""),
            Pair("Other", "Other"),
            Pair("A", "a"),
            Pair("B", "b"),
            Pair("C", "c"),
            Pair("D", "d"),
            Pair("E", "e"),
            Pair("F", "f"),
            Pair("G", "g"),
            Pair("H", "h"),
            Pair("I", "i"),
            Pair("J", "j"),
            Pair("K", "k"),
            Pair("L", "l"),
            Pair("M", "m"),
            Pair("N", "n"),
            Pair("O", "o"),
            Pair("P", "p"),
            Pair("Q", "q"),
            Pair("R", "r"),
            Pair("S", "s"),
            Pair("T", "t"),
            Pair("U", "u"),
            Pair("V", "v"),
            Pair("W", "w"),
            Pair("X", "x"),
            Pair("Y", "y"),
            Pair("Z", "z"),
            Pair("0-9", "0-9"),
        ),
    )

class ListaCompletasFilter :
    UriPartFilter(
        "Lista Completa",
        arrayOf(
            Pair("<Seleccionar>", ""),
            Pair("Lista Comis", "comic"),
            Pair("Lista Novelas", "novela"),
            Pair("Lista Adulto", "adulto"),
        ),
    )
