package eu.kanade.tachiyomi.extension.pt.mangotoons

import eu.kanade.tachiyomi.multisrc.mangotheme.MangoThemeTagFilterOption

internal typealias MangoToonsTagFilterOption = MangoThemeTagFilterOption

internal object MangoToonsFilters {

    val statusOptions = arrayOf(
        "Todos" to "",
        "Ativo" to "6",
        "Cancelado" to "4",
        "Conclu\u00eddo" to "3",
        "Em Andamento" to "1",
        "Hiato" to "5",
        "Pausado" to "2",
    )

    val formatOptions = arrayOf(
        "Todos" to "",
        "Comic" to "20",
        "Hentai" to "23",
        "Manga" to "24",
        "Manhua" to "17",
        "Manhwa" to "25",
        "Novel" to "18",
        "Shoujo" to "19",
        "Webtoon" to "26",
        "Yaoi" to "21",
        "Yuri" to "22",
    )

    val tagOptions = listOf(
        MangoToonsTagFilterOption("+18", "48"),
        MangoToonsTagFilterOption("A\u00e7\u00e3o", "2"),
        MangoToonsTagFilterOption("Adulto", "64"),
        MangoToonsTagFilterOption("Alien\u00edgenas", "65"),
        MangoToonsTagFilterOption("Apocalipse", "33"),
        MangoToonsTagFilterOption("Apocal\u00edptico", "58"),
        MangoToonsTagFilterOption("Artes Marciais", "24"),
        MangoToonsTagFilterOption("Aventura", "3"),
        MangoToonsTagFilterOption("Bullying", "60"),
        MangoToonsTagFilterOption("Com\u00e9dia", "6"),
        MangoToonsTagFilterOption("Crime", "51"),
        MangoToonsTagFilterOption("Culinaria", "28"),
        MangoToonsTagFilterOption("Cultivo", "23"),
        MangoToonsTagFilterOption("Dem\u00f4nios", "39"),
        MangoToonsTagFilterOption("Drama", "7"),
        MangoToonsTagFilterOption("Dungeon", "25"),
        MangoToonsTagFilterOption("Ecchi", "42"),
        MangoToonsTagFilterOption("Escolar", "56"),
        MangoToonsTagFilterOption("Esportes", "38"),
        MangoToonsTagFilterOption("Fantasia", "4"),
        MangoToonsTagFilterOption("Fatia da Vida/Slice of Life", "41"),
        MangoToonsTagFilterOption("Fic\u00e7\u00e3o Cient\u00edfica", "40"),
        MangoToonsTagFilterOption("Finalizado", "55"),
        MangoToonsTagFilterOption("Gore", "59"),
        MangoToonsTagFilterOption("Har\u00e9m", "44"),
        MangoToonsTagFilterOption("Hist\u00f3rico", "11"),
        MangoToonsTagFilterOption("Horror", "9"),
        MangoToonsTagFilterOption("Isekai", "19"),
        MangoToonsTagFilterOption("Jogo", "46"),
        MangoToonsTagFilterOption("Jogos", "66"),
        MangoToonsTagFilterOption("Josei", "17"),
        MangoToonsTagFilterOption("Luta", "35"),
        MangoToonsTagFilterOption("m\u00e1fia", "36"),
        MangoToonsTagFilterOption("Magia", "29"),
        MangoToonsTagFilterOption("manhua", "45"),
        MangoToonsTagFilterOption("Manhwa", "67"),
        MangoToonsTagFilterOption("Militar", "14"),
        MangoToonsTagFilterOption("Mist\u00e9rio", "43"),
        MangoToonsTagFilterOption("Moderno", "54"),
        MangoToonsTagFilterOption("Monstros", "37"),
        MangoToonsTagFilterOption("Murim", "31"),
        MangoToonsTagFilterOption("Necromante", "32"),
        MangoToonsTagFilterOption("One-shot", "18"),
        MangoToonsTagFilterOption("Oneshot", "49"),
        MangoToonsTagFilterOption("Policial", "52"),
        MangoToonsTagFilterOption("P\u00f3s Apocal\u00edptico", "68"),
        MangoToonsTagFilterOption("Psicol\u00f3gico", "27"),
        MangoToonsTagFilterOption("Reencarna\u00e7\u00e3o", "21"),
        MangoToonsTagFilterOption("Regress\u00e3o", "47"),
        MangoToonsTagFilterOption("Retorno", "20"),
        MangoToonsTagFilterOption("Romance", "5"),
        MangoToonsTagFilterOption("Sci-Fi", "62"),
        MangoToonsTagFilterOption("Seinen", "34"),
        MangoToonsTagFilterOption("Shoujo", "16"),
        MangoToonsTagFilterOption("Shounen", "15"),
        MangoToonsTagFilterOption("Shounen Ai", "63"),
        MangoToonsTagFilterOption("Sistema", "22"),
        MangoToonsTagFilterOption("Slice of Life", "61"),
        MangoToonsTagFilterOption("Sobrenatural", "13"),
        MangoToonsTagFilterOption("SuperPoder", "30"),
        MangoToonsTagFilterOption("Super Poderes", "57"),
        MangoToonsTagFilterOption("Suspense", "10"),
        MangoToonsTagFilterOption("Terror", "8"),
        MangoToonsTagFilterOption("teste", "1"),
        MangoToonsTagFilterOption("Trag\u00e9dia", "26"),
        MangoToonsTagFilterOption("Viagem no Tempo", "53"),
        MangoToonsTagFilterOption("Vida escolar", "12"),
        MangoToonsTagFilterOption("Yuri", "50"),
    )
}
