package eu.kanade.tachiyomi.extension.all.xasiatalbums

import eu.kanade.tachiyomi.source.model.Filter

open class UriPartFilter(displayName: String, val vals: Array<Pair<String, String>>) : Filter.Select<String>(displayName, vals.map { it.first }.toTypedArray()) {
    fun toUriPart() = vals[state].second
}

val initialCategories = mapOf(
    "None" to "",
    "China & Taiwan" to "albums/categories/china-taiwan",
    "South Korea" to "albums/categories/korea",
    "JAV & AV Models" to "albums/categories/jav",
    "Gravure Idols" to "albums/categories/gravure-idols",
    "Amateur" to "albums/categories/amateur3",
    "Western Girls" to "albums/categories/western-girls",
    "Southeast Asia" to "albums/categories/southeast-asia",
    "JAV Amateur" to "albums/categories/jav-amateur",
    "Cosplay" to "albums/tags/cosplay",
    "Japanese" to "albums/tags/japanese",
    "Japan" to "albums/tags/japan",
    "Photobook" to "albums/tags/photobook",
    "Friday" to "albums/tags/friday",
    "Korean" to "albums/tags/korean",
    "Friday Digital Photobook" to "albums/tags/friday-digital-photobook",
    "Graphis" to "albums/tags/graphis",
    "Lovepop" to "albums/tags/lovepop",
    "Fantia" to "albums/tags/fantia",
    "Gals" to "albums/tags/gals",
    "Friday Gold" to "albums/tags/friday-gold",
    "Girlz-High" to "albums/tags/girlz-high",
    "Xiuren" to "albums/tags/xiuren",
    "Weekly Playboy" to "albums/tags/weekly-playboy",
    "Leehee Express" to "albums/tags/leehee-express",
    "Flash" to "albums/tags/flash",
    "Young Magazine" to "albums/tags/young-magazine",
    "Bunny" to "albums/tags/bunny",
    "Nude" to "albums/tags/nude",
    "JVID" to "albums/tags/jvid",
    "Maid" to "albums/tags/maid",
    "Artgravia" to "albums/tags/artgravia",
    "Onlyfans" to "albums/tags/onlyfans",
    "Young Jump" to "albums/tags/young-jump",
    "Young Champion" to "albums/tags/young-champion",
    "Big Comic Spirits" to "albums/tags/big-comic-spirits",
    "Uniform" to "albums/tags/uniform",
    "Shonen Magazine" to "albums/tags/shonen-magazine",
    "Xiaoyu" to "albums/tags/xiaoyu",
    "Summertime" to "albums/tags/summertime",
    "Patreon" to "albums/tags/patreon",
    "Swimsuit" to "albums/tags/swimsuit",
    "Tiny Body" to "albums/tags/tiny-body",
    "Yuuhui" to "albums/tags/yuuhui",
    "Yanmaga Web" to "albums/tags/yanmaga-web",
    "Shonen Sunday" to "albums/tags/shonen-sunday",
    "Bejean On Line" to "albums/tags/bejean-on-line",
    "Djawa" to "albums/tags/djawa",
    "Pure Media" to "albums/tags/pure-media",
    "School" to "albums/tags/school",
    "Night" to "albums/tags/night",
    "Espacia Korea" to "albums/tags/espacia-korea",
    "Bikini" to "albums/tags/bikini",
    "Black" to "albums/tags/black",
    "Bluecake" to "albums/tags/bluecake",
    "Teen" to "albums/tags/teen",
    "Loozy" to "albums/tags/loozy",
    "Allgravure" to "albums/tags/allgravure",
    "Girls" to "albums/tags/girls",
)
