package eu.kanade.tachiyomi.extension.pt.imperiodabritannia

import eu.kanade.tachiyomi.multisrc.mangotheme.MangoThemeTagFilterOption

internal typealias ImperioTagFilterOption = MangoThemeTagFilterOption

internal object ImperioDaBritanniaFilters {

    val statusOptions = arrayOf(
        "Todos" to "",
        "Ativo" to "6",
        "Cancelado" to "4",
        "Conclu\u00eddo" to "3",
        "Em Andamento" to "1",
        "Hiato" to "5",
        "Pausado" to "2",
    )

    val formatOptions = arrayOf(
        "Todos" to "",
        "Comic" to "20",
        "Hentai" to "23",
        "Manga" to "24",
        "Manhua" to "17",
        "Manhwa" to "25",
        "Novel" to "18",
        "Shoujo" to "19",
        "Webtoon" to "26",
        "Yaoi" to "21",
        "Yuri" to "22",
    )

    val tagOptions = listOf(
        ImperioTagFilterOption("+18", "48"),
        ImperioTagFilterOption("A\u00e7\u00e3o", "2"),
        ImperioTagFilterOption("Adapta\u00e7\u00e3o", "108"),
        ImperioTagFilterOption("Adulto", "64"),
        ImperioTagFilterOption("Alien\u00edgenas", "96"),
        ImperioTagFilterOption("Apocalipse", "33"),
        ImperioTagFilterOption("Apocal\u00edptico", "58"),
        ImperioTagFilterOption("Artes Marciais", "24"),
        ImperioTagFilterOption("Aventura", "3"),
        ImperioTagFilterOption("Bullying", "60"),
        ImperioTagFilterOption("c", "65"),
        ImperioTagFilterOption("Com\u00e9dia", "6"),
        ImperioTagFilterOption("Crime", "51"),
        ImperioTagFilterOption("Culinaria", "28"),
        ImperioTagFilterOption("Culin\u00e1ria", "112"),
        ImperioTagFilterOption("Cultivo", "23"),
        ImperioTagFilterOption("Delinquente", "91"),
        ImperioTagFilterOption("Dem\u00f4nios", "114"),
        ImperioTagFilterOption("Dem\u00f4nios", "39"),
        ImperioTagFilterOption("Doujin", "9"),
        ImperioTagFilterOption("Dragon lan scan", "101"),
        ImperioTagFilterOption("Drama", "92"),
        ImperioTagFilterOption("Dungeon", "25"),
        ImperioTagFilterOption("Ecchi", "42"),
        ImperioTagFilterOption("Escolar", "56"),
        ImperioTagFilterOption("Esportes", "38"),
        ImperioTagFilterOption("Fantasia", "4"),
        ImperioTagFilterOption("Fatia da Vida/Slice of Life", "41"),
        ImperioTagFilterOption("Fic\u00e7\u00e3o Cient\u00edfica", "40"),
        ImperioTagFilterOption("Finalizado", "55"),
        ImperioTagFilterOption("Full Collor", "97"),
        ImperioTagFilterOption("Full Color", "93"),
        ImperioTagFilterOption("Garota Monstro", "68"),
        ImperioTagFilterOption("Garota Monstro.", "98"),
        ImperioTagFilterOption("Garotas M\u00e1gicas", "69"),
        ImperioTagFilterOption("Gender Bender", "70"),
        ImperioTagFilterOption("Genderswap", "71"),
        ImperioTagFilterOption("Girl Love", "72"),
        ImperioTagFilterOption("Gore", "59"),
        ImperioTagFilterOption("Gore scan", "111"),
        ImperioTagFilterOption("Har\u00e9m", "44"),
        ImperioTagFilterOption("Hentai", "73"),
        ImperioTagFilterOption("Her\u00f3i", "74"),
        ImperioTagFilterOption("Hist\u00f3rico", "11"),
        ImperioTagFilterOption("Horror", "75"),
        ImperioTagFilterOption("Isekai", "19"),
        ImperioTagFilterOption("Jogo", "46"),
        ImperioTagFilterOption("Jogos", "95"),
        ImperioTagFilterOption("Josei", "17"),
        ImperioTagFilterOption("Loli", "5"),
        ImperioTagFilterOption("Luta", "35"),
        ImperioTagFilterOption("m\u00e1fia", "36"),
        ImperioTagFilterOption("Magia", "29"),
        ImperioTagFilterOption("Manga", "8"),
        ImperioTagFilterOption("Mang\u00e1", "99"),
        ImperioTagFilterOption("manhua", "45"),
        ImperioTagFilterOption("Manhua", "7"),
        ImperioTagFilterOption("Manhwa", "76"),
        ImperioTagFilterOption("Mecha", "77"),
        ImperioTagFilterOption("Med\u00edocre", "105"),
        ImperioTagFilterOption("Mediocre scan", "107"),
        ImperioTagFilterOption("Med\u00edocre scan", "103"),
        ImperioTagFilterOption("Militar", "14"),
        ImperioTagFilterOption("Mist\u00e9rio", "43"),
        ImperioTagFilterOption("Moderno", "54"),
        ImperioTagFilterOption("Monstro", "100"),
        ImperioTagFilterOption("Monstros", "37"),
        ImperioTagFilterOption("Murim", "31"),
        ImperioTagFilterOption("M\u00fasica", "78"),
        ImperioTagFilterOption("Necromante", "32"),
        ImperioTagFilterOption("Norte scan", "113"),
        ImperioTagFilterOption("One-shot", "18"),
        ImperioTagFilterOption("Oneshot", "49"),
        ImperioTagFilterOption("One Shot", "110"),
        ImperioTagFilterOption("Policial", "52"),
        ImperioTagFilterOption("P\u00f3s Apocal\u00edptico", "94"),
        ImperioTagFilterOption("Psicol\u00f3gico", "27"),
        ImperioTagFilterOption("Realidade Virtua", "67"),
        ImperioTagFilterOption("Realidade Virtual", "106"),
        ImperioTagFilterOption("Reencarna\u00e7\u00e3o", "21"),
        ImperioTagFilterOption("Regress\u00e3o", "47"),
        ImperioTagFilterOption("Retorno", "20"),
        ImperioTagFilterOption("Romance", "79"),
        ImperioTagFilterOption("Sagrado imp\u00e9rio da britannia", "117"),
        ImperioTagFilterOption("Samurai", "80"),
        ImperioTagFilterOption("Sci-Fi", "62"),
        ImperioTagFilterOption("Seinen", "34"),
        ImperioTagFilterOption("Sempre ao seu lado scan", "109"),
        ImperioTagFilterOption("Shoujo", "16"),
        ImperioTagFilterOption("Shoujo Ai", "81"),
        ImperioTagFilterOption("Shounen", "15"),
        ImperioTagFilterOption("Shounen Ai", "63"),
        ImperioTagFilterOption("Sistema", "22"),
        ImperioTagFilterOption("Skarla scan", "116"),
        ImperioTagFilterOption("Slice of Life", "61"),
        ImperioTagFilterOption("Sobrenatural", "13"),
        ImperioTagFilterOption("Sobreviv\u00eancia", "82"),
        ImperioTagFilterOption("SuperPoder", "30"),
        ImperioTagFilterOption("Super Poderes", "57"),
        ImperioTagFilterOption("Suspense", "10"),
        ImperioTagFilterOption("Terror", "83"),
        ImperioTagFilterOption("teste", "1"),
        ImperioTagFilterOption("Teste99", "66"),
        ImperioTagFilterOption("Thriller", "84"),
        ImperioTagFilterOption("Trag\u00e9dia", "26"),
        ImperioTagFilterOption("Updating", "102"),
        ImperioTagFilterOption("Verdinha", "104"),
        ImperioTagFilterOption("Viagem no Tempo", "53"),
        ImperioTagFilterOption("Vida escolar", "12"),
        ImperioTagFilterOption("Video Game", "85"),
        ImperioTagFilterOption("Vingan\u00e7a", "86"),
        ImperioTagFilterOption("Web Comic", "87"),
        ImperioTagFilterOption("Webtoon", "88"),
        ImperioTagFilterOption("Wuxia", "89"),
        ImperioTagFilterOption("Xianxia", "90"),
        ImperioTagFilterOption("Yuri", "50"),
        ImperioTagFilterOption("Zero scan", "115"),
    )
}
