package eu.kanade.tachiyomi.extension.vi.vihentai

import eu.kanade.tachiyomi.source.model.Filter
import eu.kanade.tachiyomi.source.model.FilterList

fun getFilters(): FilterList = FilterList(
    SortFilter(),
    StatusFilter(),
    GenreFilter(getGenreList()),
)

class SortFilter :
    UriPartFilter(
        "Sắp xếp",
        arrayOf(
            Pair("Mới cập nhật", "-updated_at"),
            Pair("Mới nhất", "-created_at"),
            Pair("Cũ nhất", "created_at"),
            Pair("Xem nhiều", "-views"),
            Pair("A-Z", "name"),
            Pair("Z-A", "-name"),
        ),
    )

class StatusFilter :
    UriPartFilter(
        "Trạng thái",
        arrayOf(
            Pair("Tất cả", ""),
            Pair("Đang tiến hành", "2"),
            Pair("Đã hoàn thành", "1"),
        ),
    )

class Genre(name: String, val id: String) : Filter.CheckBox(name)

class GenreFilter(genres: List<Genre>) : Filter.Group<Genre>("Thể loại", genres)

open class UriPartFilter(
    displayName: String,
    private val vals: Array<Pair<String, String>>,
) : Filter.Select<String>(displayName, vals.map { it.first }.toTypedArray()) {
    fun toUriPart() = vals[state].second
}

private fun getGenreList(): List<Genre> = listOf(
    Genre("3D Hentai", "1"),
    Genre("Action", "2"),
    Genre("Adult", "3"),
    Genre("Adventure", "4"),
    Genre("Ahegao", "5"),
    Genre("AI Generated", "213"),
    Genre("Anal", "6"),
    Genre("Angel", "7"),
    Genre("Ảnh động", "8"),
    Genre("Animal", "9"),
    Genre("Animal girl", "10"),
    Genre("Áo Dài", "11"),
    Genre("Apron", "12"),
    Genre("Artist CG", "13"),
    Genre("Based Game", "14"),
    Genre("BBM", "15"),
    Genre("BBW", "16"),
    Genre("BDSM", "17"),
    Genre("Bestiality", "18"),
    Genre("Big Ass", "19"),
    Genre("Big Boobs", "20"),
    Genre("Big Penis", "21"),
    Genre("Bikini", "174"),
    Genre("Bisexual", "175"),
    Genre("Black skin", "176"),
    Genre("Blackmail", "22"),
    Genre("Blindfold", "177"),
    Genre("Bloomers", "23"),
    Genre("BlowJobs", "24"),
    Genre("Body Swap", "25"),
    Genre("Body Writing", "178"),
    Genre("Bodysuit", "26"),
    Genre("Bodyswap", "179"),
    Genre("Bondage", "27"),
    Genre("Breast Sucking", "28"),
    Genre("BreastJobs", "29"),
    Genre("Brocon", "30"),
    Genre("Brother", "31"),
    Genre("Bukkake", "180"),
    Genre("Bunny Girl", "181"),
    Genre("Business Suit", "32"),
    Genre("Catgirls", "33"),
    Genre("Chastity belt", "182"),
    Genre("Che ít", "34"),
    Genre("Che nhiều", "35"),
    Genre("Cheating", "36"),
    Genre("Cheerleader", "183"),
    Genre("Chikan", "37"),
    Genre("Chinese Dress", "38"),
    Genre("Có che", "39"),
    Genre("Collar", "184"),
    Genre("Comedy", "40"),
    Genre("Comic", "41"),
    Genre("Condom", "42"),
    Genre("Cosplay", "43"),
    Genre("Cousin", "44"),
    Genre("Creampie", "171"),
    Genre("Crossdressing", "185"),
    Genre("Crotch Tattoo", "45"),
    Genre("Cum swap", "186"),
    Genre("Cunnilingus", "46"),
    Genre("Dark Skin", "47"),
    Genre("Daughter", "48"),
    Genre("Deepthroat", "49"),
    Genre("Demon", "50"),
    Genre("DemonGirl", "51"),
    Genre("Devil", "52"),
    Genre("DevilGirl", "53"),
    Genre("Dickgirl on dickgirl", "187"),
    Genre("Dickgirl on female", "188"),
    Genre("Dickgirl on male", "189"),
    Genre("Dirty", "54"),
    Genre("Dirty Old Man", "55"),
    Genre("DogGirl", "56"),
    Genre("Double Penetration", "57"),
    Genre("Doujinshi", "58"),
    Genre("Dragon", "215"),
    Genre("Drama", "59"),
    Genre("Drug", "60"),
    Genre("Drunk", "190"),
    Genre("Ecchi", "61"),
    Genre("Elder Sister", "62"),
    Genre("Elf", "63"),
    Genre("Exhibitionism", "64"),
    Genre("Exhibitionist", "191"),
    Genre("Facesitting", "192"),
    Genre("Fantasy", "65"),
    Genre("Father", "66"),
    Genre("Females only", "193"),
    Genre("Femdom", "67"),
    Genre("Feminization", "194"),
    Genre("Fingering", "68"),
    Genre("Footjob", "69"),
    Genre("Foxgirls", "70"),
    Genre("Full Color", "71"),
    Genre("Furry", "72"),
    Genre("Futanari", "73"),
    Genre("Gag", "195"),
    Genre("GangBang", "74"),
    Genre("Garter Belts", "75"),
    Genre("Gender Bender", "76"),
    Genre("Ghost", "77"),
    Genre("Glasses", "78"),
    Genre("Glory hole", "196"),
    Genre("Gothic Lolita", "79"),
    Genre("Group", "80"),
    Genre("Guro", "81"),
    Genre("Hairjob", "197"),
    Genre("Hairy", "82"),
    Genre("Handjob", "83"),
    Genre("Harem", "84"),
    Genre("Hell No", "214"),
    Genre("HentaiVN", "85"),
    Genre("Hidden sex", "198"),
    Genre("Historical", "86"),
    Genre("Horror", "87"),
    Genre("Housewife", "88"),
    Genre("Humiliation", "89"),
    Genre("Idol", "90"),
    Genre("Imouto", "91"),
    Genre("Incest", "92"),
    Genre("Insect (Côn Trùng)", "93"),
    Genre("Isekai", "94"),
    Genre("Kemonomimi", "216"),
    Genre("Không che", "95"),
    Genre("Kimono", "96"),
    Genre("Kissing", "173"),
    Genre("Kuudere", "97"),
    Genre("Lolicon", "98"),
    Genre("Maids", "99"),
    Genre("Male on dickgirl", "199"),
    Genre("Males only", "200"),
    Genre("Manhua", "100"),
    Genre("Manhwa", "101"),
    Genre("Masturbation", "102"),
    Genre("Mature", "103"),
    Genre("Mermaid", "201"),
    Genre("Miko", "104"),
    Genre("Milf", "105"),
    Genre("Mind Break", "106"),
    Genre("Mind Control", "107"),
    Genre("Mizugi", "108"),
    Genre("Monster", "109"),
    Genre("Monstergirl", "110"),
    Genre("Mother", "111"),
    Genre("Nakadashi", "112"),
    Genre("Netori", "113"),
    Genre("Non-hen", "114"),
    Genre("NTR", "115"),
    Genre("Nun", "116"),
    Genre("Nurse", "117"),
    Genre("Old Man", "118"),
    Genre("Oneshot", "119"),
    Genre("Oral", "120"),
    Genre("Osananajimi", "121"),
    Genre("Paizuri", "122"),
    Genre("Pantyhose", "123"),
    Genre("Pegging", "203"),
    Genre("Piercing", "202"),
    Genre("Ponytail", "124"),
    Genre("Pregnant", "125"),
    Genre("Princess", "204"),
    Genre("Rape", "126"),
    Genre("Rimjob", "127"),
    Genre("Romance", "128"),
    Genre("Ryona", "129"),
    Genre("Scat", "130"),
    Genre("School Uniform", "131"),
    Genre("SchoolGirl", "132"),
    Genre("Series", "133"),
    Genre("Sex Toys", "134"),
    Genre("Shimapan", "135"),
    Genre("Short Hentai", "136"),
    Genre("Shota", "137"),
    Genre("Shoujo", "138"),
    Genre("Siscon", "139"),
    Genre("Sister", "140"),
    Genre("Sixty-Nine", "205"),
    Genre("Slave", "141"),
    Genre("Sleeping", "142"),
    Genre("Small Boobs", "143"),
    Genre("Solo action", "206"),
    Genre("Son", "144"),
    Genre("Spanking", "207"),
    Genre("Sports", "145"),
    Genre("Squirting", "172"),
    Genre("Stockings", "146"),
    Genre("Strap-on", "208"),
    Genre("Supernatural", "147"),
    Genre("Sweating", "148"),
    Genre("Swimsuit", "149"),
    Genre("Tail plug", "209"),
    Genre("Tall Girl", "150"),
    Genre("Teacher", "151"),
    Genre("Tentacles", "152"),
    Genre("Time Stop", "153"),
    Genre("Tomboy", "154"),
    Genre("Tracksuit", "155"),
    Genre("Transformation", "156"),
    Genre("Trap", "157"),
    Genre("Truyện Việt", "158"),
    Genre("Tsundere", "159"),
    Genre("Twins", "160"),
    Genre("Twintails", "161"),
    Genre("Underwater", "210"),
    Genre("Vampire", "162"),
    Genre("Vanilla", "163"),
    Genre("Virgin", "164"),
    Genre("Vtuber", "211"),
    Genre("Webtoon", "165"),
    Genre("Wormhole", "212"),
    Genre("X-ray", "166"),
    Genre("Yandere", "167"),
    Genre("Yaoi", "168"),
    Genre("Yuri", "169"),
    Genre("Zombie", "170"),
)
