package eu.kanade.tachiyomi.extension.vi.cuutruyenmoe

import eu.kanade.tachiyomi.source.model.Filter
import eu.kanade.tachiyomi.source.model.FilterList

fun getFilters(): FilterList = FilterList(
    SortFilter(),
    StatusFilter(),
    GenreFilter(getGenreList()),
)

class SortFilter :
    UriPartFilter(
        "Sắp xếp",
        arrayOf(
            Pair("Mới cập nhật", "-updated_at"),
            Pair("Mới nhất", "-created_at"),
            Pair("Cũ nhất", "created_at"),
            Pair("Xem nhiều", "-views"),
            Pair("A-Z", "name"),
            Pair("Z-A", "-name"),
        ),
    )

class StatusFilter :
    UriPartFilter(
        "Trạng thái",
        arrayOf(
            Pair("Tất cả", "2,1"),
            Pair("Đang tiến hành", "2"),
            Pair("Đã hoàn thành", "1"),
        ),
    )

class Genre(name: String, val id: String) : Filter.CheckBox(name)

class GenreFilter(genres: List<Genre>) : Filter.Group<Genre>("Thể loại", genres)

open class UriPartFilter(
    displayName: String,
    private val vals: Array<Pair<String, String>>,
) : Filter.Select<String>(displayName, vals.map { it.first }.toTypedArray()) {
    fun toUriPart() = vals[state].second
}

private fun getGenreList(): List<Genre> = listOf(
    Genre("4 koma", "116"),
    Genre("action", "33"),
    Genre("adaption", "48"),
    Genre("adventure", "91"),
    Genre("age gap", "161"),
    Genre("ai translate", "154"),
    Genre("aliens", "94"),
    Genre("ẩm thực", "53"),
    Genre("animals", "107"),
    Genre("anime", "111"),
    Genre("anthology", "140"),
    Genre("atlus", "85"),
    Genre("awa", "126"),
    Genre("award winning", "40"),
    Genre("bạo lực", "26"),
    Genre("bí ẩn", "21"),
    Genre("bi kịch", "8"),
    Genre("cảnh sát", "25"),
    Genre("chất lượng cao", "119"),
    Genre("chính trị", "136"),
    Genre("chuyển sinh", "106"),
    Genre("chuyển thể", "88"),
    Genre("có màu", "32"),
    Genre("comedy", "34"),
    Genre("comic", "143"),
    Genre("công sở", "55"),
    Genre("cooking", "54"),
    Genre("crime", "130"),
    Genre("crossdressing", "141"),
    Genre("dark fantasy", "46"),
    Genre("databook", "77"),
    Genre("delinquents", "137"),
    Genre("demon", "170"),
    Genre("demons", "131"),
    Genre("doujinshi", "74"),
    Genre("drama", "20"),
    Genre("drop", "90"),
    Genre("du hành thời gian", "109"),
    Genre("đã có dấu răng của assmin cứu truyện", "163"),
    Genre("đã hoàn thành", "2"),
    Genre("đang tiến hành", "28"),
    Genre("đời thường", "14"),
    Genre("động vật", "6"),
    Genre("ecchi", "65"),
    Genre("family", "155"),
    Genre("fantasy", "38"),
    Genre("food", "165"),
    Genre("full color", "127"),
    Genre("game", "103"),
    Genre("gender bender", "148"),
    Genre("genderswap", "146"),
    Genre("ghosts", "95"),
    Genre("giật gân", "36"),
    Genre("girl love", "152"),
    Genre("gl", "138"),
    Genre("gore", "70"),
    Genre("gyaru", "123"),
    Genre("hài hước", "11"),
    Genre("hành động", "10"),
    Genre("harem", "45"),
    Genre("hậu tận thế", "37"),
    Genre("hệ", "160"),
    Genre("hệ thống", "51"),
    Genre("historical", "97"),
    Genre("học đường", "49"),
    Genre("horror", "69"),
    Genre("idol", "93"),
    Genre("incest", "120"),
    Genre("isekai", "30"),
    Genre("josei", "59"),
    Genre("khoa học", "83"),
    Genre("khoa học viễn tưởng", "41"),
    Genre("khỏa thân", "24"),
    Genre("kinh dị", "42"),
    Genre("lãng mạn", "13"),
    Genre("lgbt", "1"),
    Genre("lịch sử", "81"),
    Genre("loạn luân", "132"),
    Genre("loli", "133"),
    Genre("long strip", "142"),
    Genre("magic", "121"),
    Genre("magical girls", "139"),
    Genre("manga", "5"),
    Genre("manhua", "44"),
    Genre("manhwa", "16"),
    Genre("martial arts", "50"),
    Genre("máu me", "117"),
    Genre("mecha", "104"),
    Genre("medical", "98"),
    Genre("miễn bản quyền", "79"),
    Genre("military", "113"),
    Genre("monster girls", "110"),
    Genre("monsters", "80"),
    Genre("music", "128"),
    Genre("mystery", "75"),
    Genre("nam biến nữ", "158"),
    Genre("nam giả nữ", "52"),
    Genre("nam x nam", "23"),
    Genre("ninja", "68"),
    Genre("nsfw", "3"),
    Genre("ntr", "101"),
    Genre("nữ giả nam", "57"),
    Genre("office workers", "124"),
    Genre("official colored", "153"),
    Genre("oneshot", "9"),
    Genre("phép thuật", "60"),
    Genre("phiêu lưu", "39"),
    Genre("philosophical", "102"),
    Genre("police", "149"),
    Genre("pseudo incest", "169"),
    Genre("psychological", "72"),
    Genre("quái vật", "99"),
    Genre("quân đội", "82"),
    Genre("reincarnation", "147"),
    Genre("romance", "17"),
    Genre("romcom", "43"),
    Genre("rpg", "87"),
    Genre("samurai", "157"),
    Genre("sát thủ", "135"),
    Genre("school life", "76"),
    Genre("sci fi", "63"),
    Genre("sega", "86"),
    Genre("seinen", "7"),
    Genre("shoujo", "56"),
    Genre("shoujo ai", "129"),
    Genre("shounen", "12"),
    Genre("siêu nhiên", "31"),
    Genre("sinh tồn", "105"),
    Genre("slice of lìe", "151"),
    Genre("slice of life", "18"),
    Genre("smut", "64"),
    Genre("sport", "66"),
    Genre("sports", "125"),
    Genre("supernatural", "35"),
    Genre("survival", "134"),
    Genre("tâm lý", "19"),
    Genre("tạm ngưng", "29"),
    Genre("thể thao", "89"),
    Genre("thriller", "118"),
    Genre("time travel", "150"),
    Genre("tình dục", "22"),
    Genre("tình yêu", "100"),
    Genre("tình yêu thuần khiết", "167"),
    Genre("toán học", "71"),
    Genre("tội phạm", "27"),
    Genre("tragedy", "73"),
    Genre("trap", "115"),
    Genre("trinh thám", "47"),
    Genre("trung cổ", "144"),
    Genre("truyện việt", "84"),
    Genre("tuyển tập", "168"),
    Genre("uma musume", "166"),
    Genre("vampires", "122"),
    Genre("video games", "114"),
    Genre("việt nam", "58"),
    Genre("virtual reality", "162"),
    Genre("võ thuật", "92"),
    Genre("web comic", "61"),
    Genre("web novel", "156"),
    Genre("webtoon", "15"),
    Genre("wholesome", "62"),
    Genre("xuyên", "159"),
    Genre("xuyên không", "164"),
    Genre("y học", "78"),
    Genre("yakuza", "145"),
    Genre("yandere", "112"),
    Genre("yaoi", "4"),
    Genre("yonkoma", "108"),
    Genre("yuri", "67"),
    Genre("zombie", "96"),
)
