package eu.kanade.tachiyomi.extension.pt.pizzariascan

object PizzariascanFilters {
    val orderFilterOptions = arrayOf(
        "A-Z" to "title",
        "Z-A" to "titlereverse",
        "Latest Update" to "update",
        "Latest Added" to "latest",
        "Popular" to "popular",
    )

    val statusFilterOptions = arrayOf(
        "All" to "",
        "Publishing" to "Publishing",
        "Finished" to "Finished",
    )

    val typeFilterOptions = arrayOf(
        "All" to "",
        "Manga" to "Manga",
        "Manhwa" to "Manhwa",
        "Manhua" to "Manhua",
    )

    val genreFilterOptions = arrayOf(
        "Ação" to "acao",
        "Action" to "action",
        "Adaptação" to "adaptacao",
        "Adaptation" to "adaptation",
        "Adulto" to "adulto",
        "Adventure" to "adventure",
        "Animals" to "animals",
        "Artes marciais" to "artes-marciais",
        "ave" to "ave",
        "Aventura" to "aventura",
        "Aventura Magia Fantasia Adaptação" to "aventura-magia-fantasia-adaptacao",
        "Award Winning" to "award-winning",
        "Boquete" to "boquete",
        "Comédia" to "comedia",
        "Comedy" to "comedy",
        "Cooking" to "cooking",
        "Crossdressing" to "crossdressing",
        "Delinquentes" to "delinquentes",
        "Delinquents" to "delinquents",
        "Demônios" to "demonios",
        "Demons" to "demons",
        "Drama" to "drama",
        "Ecchi" to "ecchi",
        "Erótica" to "erotica",
        "Erótico" to "erotico",
        "Esportes" to "esportes",
        "Fantasia" to "fantasia",
        "Fantasy" to "fantasy",
        "Full Color" to "full-color",
        "Garotas Monstro" to "garotas-monstro",
        "Genderswap" to "genderswap",
        "Gore" to "gore",
        "Gyaru" to "gyaru",
        "Harem" to "harem",
        "Incest" to "incest",
        "Incesto" to "incesto",
        "Isekai" to "isekai",
        "Loli" to "loli",
        "Long Strip" to "long-strip",
        "Magia" to "magia",
        "Magic" to "magic",
        "Manhwa" to "manhwa",
        "Martial Arts" to "martial-arts",
        "Masturbação" to "masturbacao",
        "Mature" to "mature",
        "Mecha" to "mecha",
        "Militares" to "militares",
        "Monster Girls" to "monster-girls",
        "Monsters" to "monsters",
        "Monstros" to "monstros",
        "Ninja" to "ninja",
        "Office Workers" to "office-workers",
        "Psychological" to "psychological",
        "Realidade Virtual" to "realidade-virtual",
        "Reencarnação" to "reencarnacao",
        "Reincarnation" to "reincarnation",
        "Romance" to "romance",
        "School Life" to "school-life",
        "Sci-Fi" to "sci-fi",
        "Seinen" to "seinen",
        "Sex Toys" to "sex-toys",
        "Sexual Violence" to "sexual-violence",
        "Shota" to "shota",
        "Slice of Life" to "slice-of-life",
        "Sobrenatural" to "sobrenatural",
        "Sobrevivência" to "sobrevivencia",
        "Sugestivo" to "sugestivo",
        "Supernatural" to "supernatural",
        "Survival" to "survival",
        "Thriller" to "thriller",
        "Time Travel" to "time-travel",
        "Vida escolar" to "vida-escolar",
        "Video Games" to "video-games",
        "Vilã" to "vila",
        "Villainess" to "villainess",
        "Violência" to "violencia",
        "Violência sexual" to "violencia-sexual",
        "Web Comic" to "web-comic",
        "Webcomic" to "webcomic",
        "Webtoon" to "webtoon",
        "Yuri" to "yuri",
        "Zombies" to "zombies",
    )

    val yearFilterOptions = arrayOf(
        "2008" to "2008",
        "2011" to "2011",
        "2014" to "2014",
        "2015" to "2015",
        "2017" to "2017",
        "2018" to "2018",
        "2019" to "2019",
        "2020" to "2020",
        "2021" to "2021",
        "2022" to "2022",
        "2023" to "2023",
        "2024" to "2024",
        "2025" to "2025",
        "2026" to "2026",
    )
}
