package eu.kanade.tachiyomi.extension.es.lectorjpg

import eu.kanade.tachiyomi.source.model.Filter

class Genre(title: String, val key: String) : Filter.CheckBox(title)
class GenreFilter(title: String, genres: List<Genre>) : Filter.Group<Genre>(title, genres)

internal fun getGenreList() = listOf(
    Genre("BDSM", "bdsm"),
    Genre("Bebes", "bebes"),
    Genre("Bestias", "bestias"),
    Genre("BL Sin Censura", "bl-sin-censura"),
    Genre("Boys Love", "boys-love"),
    Genre("Che Tenete Un Poco De Amor Propio", "che-tenete-un-poco-de-amor-propio"),
    Genre("Ciencia Ficción", "ciencia-ficcion"),
    Genre("Comedia", "comedia"),
    Genre("Crimen", "crimen"),
    Genre("Del Campo", "del-campo"),
    Genre("Demonios", "demonios"),
    Genre("Deportes", "deportes"),
    Genre("Drama", "drama"),
    Genre("Escolar", "escolar"),
    Genre("Espacial", "espacial"),
    Genre("Fantasía", "fantasia"),
    Genre("Furro", "furro"),
    Genre("Harem", "harem"),
    Genre("Harem Inverso", "harem-inverso"),
    Genre("Historia", "historia"),
    Genre("Josei", "josei"),
    Genre("Juego", "juego"),
    Genre("Mafia", "mafia"),
    Genre("Magia", "magia"),
    Genre("Manhwa +19", "manhwa-19"),
    Genre("Militar", "militar"),
    Genre("Moderno", "moderno"),
    Genre("Morocho Hermoso", "morocho-hermoso"),
    Genre("Mucho Gogogo", "mucho-gogogo"),
    Genre("Música", "musica"),
    Genre("Novela", "novela"),
    Genre("Odio-Amor", "odio-amor"),
    Genre("Omegaverse", "omegaverse"),
    Genre("Psicológico", "psicologico"),
    Genre("Reencarnación", "reencarnacion"),
    Genre("Relación Por Convivencia", "relacion-por-convivencia"),
    Genre("Romance", "romance"),
    Genre("Smut", "smut"),
    Genre("Telenovela", "telenovela"),
    Genre("Tetón", "teton"),
    Genre("Toxicidad", "toxicidad"),
    Genre("Toxicidad Nivel Chernóbil", "toxicidad-nivel-chernobil"),
    Genre("Universitario", "universitario"),
    Genre("Venganza", "venganza"),
    Genre("Shoujo", "Shoujo"),
    Genre("Shounen", "Shounen"),
    Genre("Seinen", "Seinen"),
    Genre("+18 Sin Censura", "+ 18 Sin Censura"),
    Genre("NoBL\uD83D\uDC8C", "nobl"),
    Genre("Girls Love", "gl"),
    Genre("Adulto", "adulto"),
    Genre("+18", "18"),
    Genre("Sistema", "sistema"),
    Genre("Acción", "Acción"),
    Genre("Aventura", "Aventura"),
    Genre("Sobrenatural", "Sobrenatural"),
    Genre("Transmigración", "Transmigración"),
    Genre("Misterio", "misterio"),
    Genre("Tragedia", "tragedia"),
    Genre("Horror", "horror"),
    Genre("BL", "bl"),
    Genre("Thriller", "thriller"),
)
