package eu.kanade.tachiyomi.extension.all.comicklive

import eu.kanade.tachiyomi.source.SourceFactory

class ComickFactory : SourceFactory {
    // as of 2025-10-15, the commented languages have 0 chapters uploaded
    // from: /api/languages
    override fun createSources() = listOf(
        Comick("en"),
        // Comick("pt-br", "pt-BR"),
        // Comick("es-419", "es-la"),
        Comick("ru"),
        Comick("vi"),
        Comick("fr"),
        Comick("pl"),
        Comick("id"),
        Comick("tr"),
        Comick("it"),
        Comick("es"),
        Comick("uk"),
        // Comick("ar"),
        // Comick("zh-hk", "zh-Hant"),
        // Comick("hu"),
        // Comick("zh", "zh-Hans"),
        Comick("de"),
        Comick("ko"),
        Comick("th"),
        // Comick("ca"),
        // Comick("bg"),
        // Comick("fa"),
        Comick("ro"),
        // Comick("cs"),
        // Comick("mn"),
        // Comick("pt"),
        // Comick("he"),
        // Comick("hi"),
        // Comick("tl"),
        Comick("ms"),
        // Comick("fi"),
        // Comick("eu"),
        // Comick("kk"),
        // Comick("sr"),
        // Comick("my"),
        Comick("ja"),
        // Comick("el"),
        // Comick("nl"),
        // Comick("bn"),
        // Comick("uz"),
        // Comick("eo"),
        // Comick("ka"),
        // Comick("lt"),
        // Comick("da"),
        // Comick("ta"),
        Comick("sv"),
        // Comick("be"),
        // Comick("gl"),
        // Comick("cv"),
        // Comick("hr"),
        // Comick("la"),
        // Comick("ur"),
        // Comick("ne"),
        Comick("no"),
        // Comick("sq"),
        // Comick("ga"),
        // Comick("jv"),
        // Comick("te"),
        // Comick("sl"),
        // Comick("et"),
        // Comick("az"),
        // Comick("sk"),
        // Comick("af"),
        // Comick("lv"),
    )
}
