package eu.kanade.tachiyomi.extension.pt.hipertoon

import eu.kanade.tachiyomi.multisrc.hiper.Hiper
import keiyoushi.annotation.Source

@Source
abstract class Hipertoon : Hiper() {

    override val genresList = listOf(
        "4-Koma",
        "Ação",
        "Adaptation",
        "Adulto",
        "Aliens",
        "Animais",
        "Antologia",
        "Artes Marciais",
        "Aventura",
        "Boy's Love",
        "Colorido Oficial",
        "Comédia",
        "Crime",
        "Crossdressing",
        "Culinária",
        "Delinquentes",
        "Demônios",
        "Doujinshi",
        "Drama",
        "Ecchi",
        "Escolar",
        "Escritório",
        "Esporte",
        "Fan Colored",
        "Fantasia",
        "Fantasma",
        "Ficção",
        "Ficção Científica",
        "Filosófico",
        "Full Color",
        "Gender Bender",
        "Genderswap",
        "Gore",
        "Gyaru",
        "Harém",
        "Histórico",
        "Horror",
        "Incest",
        "Isekai",
        "Josei",
        "Loli",
        "Longstrip",
        "Maduro",
        "Máfia",
        "Magia",
        "Mecha",
        "Médico",
        "Militar",
        "Mistério",
        "Mitologia",
        "Monster Girl",
        "Monstros",
        "Música",
        "Ninja",
        "One-Shot",
        "Polícia",
        "Pós-Apocalíptico",
        "Premiado",
        "Psicológico",
        "Reencarnação",
        "Regressão",
        "Reverse Harem",
        "Romance",
        "Samurai",
        "Seinen",
        "Self-Published",
        "Sexual Violence",
        "Shota",
        "Shotacon",
        "Shoujo",
        "Shoujo Ai",
        "Shounen",
        "Shounen Ai",
        "Slice of Life",
        "Smut",
        "Sobrenatural",
        "Sobrevivência",
        "Super-Herói",
        "Suspense",
        "Terror",
        "Traditional Games",
        "Tragédia",
        "Vampiros",
        "Viagem no Tempo",
        "Video Games",
        "Vilã",
        "Vingança",
        "Web Comic",
        "Wuxia",
        "Yaoi",
        "Yuri",
        "Zumbi",
    )
}
