package eu.kanade.tachiyomi.extension.all.mangaball

import eu.kanade.tachiyomi.source.SourceFactory

class MangaBallFactory : SourceFactory {
    override fun createSources() = listOf(
        MangaBall("ar", "ar"),
        MangaBall("bg", "bg"),
        MangaBall("bn", "bn"),
        MangaBall("ca", "ca", "ca-ad", "ca-es", "ca-fr", "ca-it", "ca-pt"),
        MangaBall("cs", "cs"),
        MangaBall("da", "da"),
        MangaBall("de", "de"),
        MangaBall("el", "el"),
        MangaBall("en", "en"),
        MangaBall("es", "es", "es-ar", "es-mx", "es-es", "es-la", "es-419"),
        MangaBall("fa", "fa"),
        MangaBall("fi", "fi"),
        MangaBall("fr", "fr"),
        MangaBall("he", "he"),
        MangaBall("hi", "hi"),
        MangaBall("hu", "hu"),
        MangaBall("id", "id"),
        MangaBall("it", "it", "it-it"),
        MangaBall("is", "ib", "ib-is", "is"),
        MangaBall("ja", "jp"),
        MangaBall("ko", "kr"),
        MangaBall("kn", "kn", "kn-in", "kn-my", "kn-sg", "kn-tw"),
        MangaBall("ml", "ml", "ml-in", "ml-my", "ml-sg", "ml-tw"),
        MangaBall("ms", "ms"),
        MangaBall("ne", "ne"),
        MangaBall("nl", "nl", "nl-be"),
        MangaBall("no", "no"),
        MangaBall("pl", "pl"),
        MangaBall("pt-BR", "pt-br", "pt-pt"),
        MangaBall("ro", "ro"),
        MangaBall("ru", "ru"),
        MangaBall("sk", "sk"),
        MangaBall("sl", "sl"),
        MangaBall("sq", "sq"),
        MangaBall("sr", "sr", "sr-cyrl"),
        MangaBall("sv", "sv"),
        MangaBall("ta", "ta"),
        MangaBall("th", "th", "th-hk", "th-kh", "th-la", "th-my", "th-sg"),
        MangaBall("tr", "tr"),
        MangaBall("uk", "uk"),
        MangaBall("vi", "vi"),
        MangaBall("zh", "zh", "zh-cn", "zh-hk", "zh-mo", "zh-sg", "zh-tw"),
    )
}
