package eu.kanade.tachiyomi.extension.vi.truyentranhlh

import eu.kanade.tachiyomi.multisrc.mymangacms.MyMangaCMS

class TruyenTranhLH : MyMangaCMS("TruyenTranhLH", "https://truyenlh.com", "vi") {
    override val id: Long = 7969606392351831672

    override fun getGenreList() = listOf(
        Genre("Action", 1),
        Genre("Adult", 2),
        Genre("Adventure", 3),
        Genre("Anime", 4),
        Genre("Chuyển Sinh", 5),
        Genre("Cổ Đại", 6),
        Genre("Comedy", 7),
        Genre("Comic", 8),
        Genre("Demons", 9),
        Genre("Detective", 10),
        Genre("Doujinshi", 11),
        Genre("Drama", 12),
        Genre("Đam Mỹ", 13),
        Genre("Ecchi", 14),
        Genre("Fantasy", 15),
        Genre("Gender Bender", 16),
        Genre("Harem", 17),
        Genre("Historical", 18),
        Genre("Horror", 19),
        Genre("Huyền Huyễn", 20),
        Genre("Isekai", 21),
        Genre("Josei", 22),
        Genre("Mafia", 23),
        Genre("Magic", 24),
        Genre("Manhua", 25),
        Genre("Manhwa", 26),
        Genre("Martial Arts", 27),
        Genre("Mature", 28),
        Genre("Military", 29),
        Genre("Mystery", 30),
        Genre("Ngôn Tình", 31),
        Genre("One shot", 32),
        Genre("Psychological", 33),
        Genre("Romance", 34),
        Genre("School Life", 35),
        Genre("Sci-fi", 36),
        Genre("Seinen", 37),
        Genre("Shoujo", 38),
        Genre("Shoujo Ai", 39),
        Genre("Shounen", 40),
        Genre("Shounen Ai", 41),
        Genre("Slice of life", 42),
        Genre("Smut", 43),
        Genre("Sports", 44),
        Genre("Supernatural", 45),
        Genre("Tragedy", 46),
        Genre("Trọng Sinh", 47),
        Genre("Truyện Màu", 48),
        Genre("Webtoon", 49),
        Genre("Xuyên Không", 50),
        Genre("Yaoi", 51),
        Genre("Yuri", 52),
        Genre("Mecha", 53),
        Genre("Cooking", 54),
        Genre("Trùng Sinh", 55),
        Genre("Gourmet", 56),
        Genre("Dark Fantasy", 57),
    )
}
