package eu.kanade.tachiyomi.extension.vi.loppytoon

import eu.kanade.tachiyomi.source.model.Filter
import eu.kanade.tachiyomi.source.model.FilterList

fun getFilters(): FilterList = FilterList(
    GenreFilter(getGenreList()),
    GroupFilter(getGroupList()),
)

class Genre(name: String, val slug: String) : Filter.CheckBox(name)

class GenreFilter(genres: List<Genre>) : Filter.Group<Genre>("Thể loại", genres)

class ScanlationGroup(name: String, val slug: String) : Filter.CheckBox(name)

class GroupFilter(groups: List<ScanlationGroup>) : Filter.Group<ScanlationGroup>("Nhóm dịch", groups)

private fun getGenreList(): List<Genre> = listOf(
    Genre("18+", "18"),
    Genre("19+", "19"),
    Genre("21+", "21"),
    Genre("Học Đường", "hoc-duong"),
    Genre("Manhwa", "manhwa"),
    Genre("Manga", "manga"),
    Genre("Manhua", "manhua"),
    Genre("Oneshot", "oneshot"),
    Genre("1x1", "1x1"),
    Genre("3P", "3p"),
    Genre("Action", "action"),
    Genre("Âu Cổ", "au-co"),
    Genre("Bad Boy", "bad-boy"),
    Genre("Bạn Thời Thơ Ấu", "ban-thoi-tho-au"),
    Genre("Bạo Lực Học Đường", "bao-luc-hoc-duong"),
    Genre("BDSM", "bdsm"),
    Genre("Bi Kịch", "bi-kich"),
    Genre("Chaebol", "chaebol"),
    Genre("Chữa Lành", "chua-lanh"),
    Genre("Chuyển Sinh", "chuyen-sinh"),
    Genre("Chuyển Thể", "chuyen-the"),
    Genre("Cổ Đại", "co-dai"),
    Genre("Cổ Trang", "co-trang"),
    Genre("Comedy", "comedy"),
    Genre("Công Sở", "cong-so"),
    Genre("Cưới Trước Yêu Sau", "cuoi-truoc-yeu-sau"),
    Genre("Đô Thị", "do-thi"),
    Genre("Động Vật", "dong-vat"),
    Genre("Drama", "drama"),
    Genre("Fantasy", "fantasy"),
    Genre("Giả Tưởng", "gia-tuong"),
    Genre("Giam Cầm", "giam-cam"),
    Genre("Giật Gân", "giat-gan"),
    Genre("Giết Người", "giet-nguoi"),
    Genre("Giới Giải Trí", "gioi-giai-tri"),
    Genre("Good Boy", "good-boy"),
    Genre("Gương Vỡ Lại Lành", "guong-vo-lai-lanh"),
    Genre("Hài Hước", "hai-huoc"),
    Genre("Harem", "harem"),
    Genre("Hệ Thống", "he-thong"),
    Genre("Hiện Đại", "hien-dai"),
    Genre("Hoàng Gia", "hoang-gia"),
    Genre("Hôn Nhân Hợp Đồng", "hon-nhan-hop-dong"),
    Genre("Horror", "horror"),
    Genre("Huyền Bí", "huyen-bi"),
    Genre("Idol", "idol"),
    Genre("Isekai", "isekai"),
    Genre("Kinh Dị", "kinh-di"),
    Genre("Lãng Mạn", "lang-man"),
    Genre("Light Novel", "light-novel"),
    Genre("Magic", "magic"),
    Genre("Ngôn Tình", "ngon-tinh"),
    Genre("Ngọt", "ngot"),
    Genre("Người Thú", "nguoi-thu"),
    Genre("Nhân Thú", "nhan-thu"),
    Genre("Novel", "novel"),
    Genre("NTR", "ntr"),
    Genre("Nữ Cường", "nu-cuong"),
    Genre("Phép Thuật", "phep-thuat"),
    Genre("Phù Thủy", "phu-thuy"),
    Genre("Quân Nhân", "quan-nhan"),
    Genre("Romance", "romance"),
    Genre("Romcom", "romcom"),
    Genre("Shoujo", "shoujo"),
    Genre("Showbiz", "showbiz"),
    Genre("Slice Of Life", "slice-of-life"),
    Genre("Sủng", "sung"),
    Genre("Tài Phiệt", "tai-phiet"),
    Genre("Tái Sinh", "tai-sinh"),
    Genre("Tâm Lý", "tam-ly"),
    Genre("Thanh Mai Trúc Mã", "thanh-mai-truc-ma"),
    Genre("Thanh Xuân Vườn Trường", "thanh-xuan-vuon-truong"),
    Genre("Tiên Cá", "tien-ca"),
    Genre("Tình Cảm", "tinh-cam"),
    Genre("Tội Phạm", "toi-pham"),
    Genre("Trinh Thám", "trinh-tham"),
    Genre("Trọng Sinh", "trong-sinh"),
    Genre("Trưởng Thành", "truong-thanh"),
    Genre("Truy Thê", "truy-the"),
    Genre("Truyện Ngắn", "truyen-ngan"),
    Genre("Văn Phòng", "van-phong"),
    Genre("Viễn Tưởng", "vien-tuong"),
    Genre("Webtoon", "webtoon"),
    Genre("Xuyên Không", "xuyen-khong"),
    Genre("Yandere", "yandere"),
    Genre("Chuyển Thể Từ Novel", "chuyen-the-tu-novel"),
    Genre("Không Che", "khong-che"),
    Genre("Chiếm Hữu", "chiem-huu"),
    Genre("Mối Tình Tay Ba", "moi-tinh-tay-ba"),
    Genre("Mối Tình Đầu", "moi-tinh-dau"),
    Genre("Bạn Bè > Người Yêu", "ban-be-nguoi-yeu"),
    Genre("Dirty Talk", "dirty-talk"),
    Genre("Trinh Nữ", "trinh-nu"),
    Genre("Báo Thù", "bao-thu"),
    Genre("Thế Giới Ngầm", "the-gioi-ngam"),
    Genre("Mafia", "mafia"),
    Genre("Kịch Tính", "kich-tinh"),
    Genre("Sâu Lắng", "sau-lang"),
    Genre("Yêu Hận Tình Thù", "yeu-han-tinh-thu"),
    Genre("Chính Kịch", "chinh-kich"),
    Genre("Cảm Xúc", "cam-xuc"),
    Genre("Dark Romance", "dark-romance"),
    Genre("Trai Ngoan", "trai-ngoan"),
    Genre("Hài Lãng Mạn", "hai-lang-man"),
    Genre("Hợp Đồng Hẹn Hò", "hop-dong-hen-ho"),
    Genre("Phi Công Trẻ Lái Máy Bay Bà Già", "phi-cong-tre-lai-may-bay-ba-gia"),
    Genre("Gây Sốc", "gay-soc"),
    Genre("Nặng Đô", "nang-do"),
    Genre("Ghét Trước Yêu Sau", "ghet-truoc-yeu-sau"),
    Genre("Vibe", "vibe"),
    Genre("Bối Cảnh Phương Tây", "boi-canh-phuong-tay"),
    Genre("Trả Thù", "tra-thu"),
    Genre("Hiểu Lầm", "hieu-lam"),
    Genre("Mối Quan Hệ Hợp Đồng", "moi-quan-he-hop-dong"),
    Genre("Yêu Đơn Phương", "yeu-don-phuong"),
    Genre("15+", "15"),
    Genre("Cứu Rỗi", "cuu-roi"),
    Genre("Zombie", "zombie"),
    Genre("Ma Cà Rồng", "ma-ca-rong"),
    Genre("Vampire", "vampire"),
    Genre("Hàng Xóm", "hang-xom"),
    Genre("Khoảng Cách Tuổi Tác", "khoang-cach-tuoi-tac"),
    Genre("Ghét Của Nào Trời Trao Của Nấy", "ghet-cua-nao-troi-trao-cua-nay"),
    Genre("Cơ Thể > Tim", "co-the-tim"),
    Genre("Sống Chung", "song-chung"),
    Genre("Siêu Năng Lực", "sieu-nang-luc"),
    Genre("Mất Trí Nhớ", "mat-tri-nho"),
    Genre("Yêu Hận Đan Xen", "yeu-han-dan-xen"),
    Genre("Mối Quan Hệ Tình Cảm Phức Tạp", "moi-quan-he-tinh-cam-phuc-tap"),
    Genre("Thể Thao", "the-thao"),
    Genre("Lọ Lem", "lo-lem"),
)

private fun getGroupList(): List<ScanlationGroup> = listOf(
    ScanlationGroup("LoppyToon", "loppytoon"),
    ScanlationGroup("LoppyToon Novel", "loppytoon-novel"),
    ScanlationGroup("ComicCat-mèo cày truyện", "comiccat"),
    ScanlationGroup("Da Churros", "da-churros"),
    ScanlationGroup("Tiểu Hồ Điệp", "tieu-ho-diep"),
    ScanlationGroup("Mồn Lèo Biết Bay", "mon-leo-biet-bay"),
    ScanlationGroup("Phiêu Nguyệt Team", "phieu-nguyet-team"),
    ScanlationGroup("Tự Kỷ Cùng É", "tu-ky-cung-e"),
    ScanlationGroup("Cái Mồm Xinh", "cai-mom-xinh"),
    ScanlationGroup("Team Vilnius", "team-vilnius"),
    ScanlationGroup("Solar Eclipse Team", "solar-eclipse-team"),
    ScanlationGroup("Động Tâm", "dong-tam"),
    ScanlationGroup("Mồn Lèo Biết Bay x Phiêu Nguyệt Team", "mon-leo-biet-bayphieu-nguyet-team"),
    ScanlationGroup("Da Churros x LoppyToon", "da-churros-x-loppy-toon"),
    ScanlationGroup("Đang Cập Nhật", "navy-team"),
    ScanlationGroup("Dũng Sĩ Diệt Cáo", "dung-si-diet-cao"),
    ScanlationGroup("Dũng Sĩ Diệt Cáo x LoppyToon", "loppytoon-x-dung-si-diet-cao"),
    ScanlationGroup("LoppyToon & Chill", "loppytoon-chill"),
    ScanlationGroup("Closed Heart", "closed-heart"),
    ScanlationGroup("LoppyToon x Mồn Lèo Biết Bay", "loppytoon-x-mon-leo-biet-bay"),
    ScanlationGroup("Amyrae Pinkverse", "amyrae-pinkverse"),
    ScanlationGroup("Bún Đậu Comics", "bun-dau-comics"),
    ScanlationGroup("Capy Comics", "capycomics"),
    ScanlationGroup("Quillpetal", "quillpetal"),
)
