package eu.kanade.tachiyomi.extension.all.xbatcat

import eu.kanade.tachiyomi.source.SourceFactory

class XBatCatFactory : SourceFactory {
    override fun createSources() = listOf(
        XBatCat("all", ""),
        XBatCat("en"),
        XBatCat("ar"),
        XBatCat("bg"),
        XBatCat("zh"),
        XBatCat("cs"),
        XBatCat("da"),
        XBatCat("nl"),
        XBatCat("fil"),
        XBatCat("fi"),
        XBatCat("fr"),
        XBatCat("de"),
        XBatCat("el"),
        XBatCat("he"),
        XBatCat("hi"),
        XBatCat("hu"),
        XBatCat("id"),
        XBatCat("it"),
        XBatCat("ja"),
        XBatCat("ko"),
        XBatCat("ms"),
        XBatCat("pl"),
        XBatCat("pt"),
        XBatCat("pt-BR", "pt_br"),
        XBatCat("ro"),
        XBatCat("ru"),
        XBatCat("es"),
        XBatCat("es-419", "es_419"),
        XBatCat("sv"),
        XBatCat("tr"),
        XBatCat("uk"),
        XBatCat("vi"),
        XBatCat("af"),
        XBatCat("sq"),
        XBatCat("am"),
        XBatCat("hy"),
        XBatCat("az"),
        XBatCat("be"),
        XBatCat("bn"),
        XBatCat("bs"),
        XBatCat("my"),
        XBatCat("km"),
        XBatCat("ca"),
        XBatCat("ceb"),
        XBatCat("zh-Hans", "zh_hk"),
        XBatCat("zh-Hant", "zh_tw"),
        XBatCat("hr"),
        XBatCat("et"),
        XBatCat("fo"),
        XBatCat("ka"),
        XBatCat("gn"),
        XBatCat("gu"),
        XBatCat("ht"),
        XBatCat("ha"),
        XBatCat("is"),
        XBatCat("ig"),
        XBatCat("ga"),
        XBatCat("jv"),
        XBatCat("kn"),
        XBatCat("kk"),
        XBatCat("ku"),
        XBatCat("ky"),
        XBatCat("lo"),
        XBatCat("lv"),
        XBatCat("lt"),
        XBatCat("lb"),
        XBatCat("mk"),
        XBatCat("mg"),
        XBatCat("ml"),
        XBatCat("mt"),
        XBatCat("mi"),
        XBatCat("mr"),
        XBatCat("mo"),
        XBatCat("mn"),
        XBatCat("ne"),
        XBatCat("no"),
        XBatCat("ny"),
        XBatCat("ps"),
        XBatCat("fa"),
        XBatCat("rm"),
        XBatCat("sm"),
        XBatCat("sr"),
        XBatCat("sh"),
        XBatCat("st"),
        XBatCat("sn"),
        XBatCat("sd"),
        XBatCat("si"),
        XBatCat("sk"),
        XBatCat("sl"),
        XBatCat("so"),
        XBatCat("sw"),
        XBatCat("tg"),
        XBatCat("ta"),
        XBatCat("te"),
        XBatCat("th"),
        XBatCat("ti"),
        XBatCat("to"),
        XBatCat("tk"),
        XBatCat("ur"),
        XBatCat("uz"),
        XBatCat("yo"),
        XBatCat("zu"),
        XBatCat("other", "_t"),
    )
}
