package eu.kanade.tachiyomi.extension.ar.mangapro

import eu.kanade.tachiyomi.source.model.Filter
import java.util.Calendar

abstract class SelectFilter<T>(
    name: String,
    private val options: List<Pair<String, T>>,
) : Filter.Select<String?>(
    name,
    options.map { it.first }.toTypedArray(),
) {
    val selected get() = options[state].second
}

class TriStateFilter(name: String, val value: String) : Filter.TriState(name)

abstract class TriStateGroupFilter(
    name: String,
    options: List<Pair<String, String>>,
) : Filter.Group<TriStateFilter>(
    name,
    options.map { TriStateFilter(it.first, it.second) },
) {
    val included get() = state.filter { it.isIncluded() }.map { it.value }
    val excluded get() = state.filter { it.isExcluded() }.map { it.value }
}

class TypeFilter :
    SelectFilter<String?>(
        name = "النوع",
        options = listOf(
            "الكل" to null,
            "مانجا" to "manga",
            "مانها" to "manhua",
            "مانهوا" to "manhwa",
        ),
    )

class SortFilter :
    SelectFilter<String>(
        name = "الفرز",
        options = listOf(
            "أحدث السلاسل" to "latest",
            "أحدث الفصول" to "latest_chapter",
            "الأكثر شهرة" to "popular",
            "الشعبية الإجمالية" to "total_popularity",
            "الأقدم" to "oldest",
            "أبجدي (أ-ي)" to "az",
            "أبجدي (ي-أ)" to "za",
        ),
    )

class StatusFilter :
    SelectFilter<String?>(
        name = "الحالة",
        options = listOf(
            "جميع الحالات" to null,
            "مستمر" to "مستمر",
            "مكتمل" to "مكتمل",
            "متوقف" to "متوقف",
        ),
    )

private val currentYear = Calendar.getInstance()[Calendar.YEAR]

class YearFilter :
    SelectFilter<String?>(
        name = "السنة",
        options = buildList {
            add("جميع السنوات" to null)
            (currentYear downTo 1970).mapTo(this) { it.toString() to it.toString() }
        },
    )

class GenreFilter :
    TriStateGroupFilter(
        name = "التصنيفات",
        options = genres,
    )

class TagFilter :
    TriStateGroupFilter(
        name = "التصنيفات الفرعية",
        options = tags,
    )

val genres = listOf(
    "أكشن" to "Action",
    "للكبار" to "Adult",
    "مغامرة" to "Adventure",
    "كوميديا" to "Comedy",
    "الدوجينشي" to "Doujinshi",
    "دراما" to "Drama",
    "إتشي" to "Ecchi",
    "خيال" to "Fantasy",
    "تحوّل الجنس" to "Gender Bender",
    "حريم" to "Harem",
    "هنتاي" to "Hentai",
    "تاريخي" to "Historical",
    "رعب" to "Horror",
    "جوسي" to "Josei",
    "لوليكون" to "Lolicon",
    "فنون القتال" to "Martial Arts",
    "الناضج" to "Mature",
    "الميكا" to "Mecha",
    "الميلف" to "Milf",
    "نفسي" to "Psychological",
    "رومانسي" to "Romance",
    "حياة المدرسة" to "School Life",
    "الخيال العلمي" to "Sci-fi",
    "السينين" to "Seinen",
    "شوتاكون" to "Shotacon",
    "الشوجو" to "Shoujo",
    "الشوجو آي" to "Shoujo Ai",
    "الشونين" to "Shounen",
    "الشونين آي" to "Shounen Ai",
    "شريحة من الحياة" to "Slice of Life",
    "فاحش" to "Smut",
    "الرياضة" to "Sports",
    "خارق للطبيعة" to "Supernatural",
    "المأساة" to "Tragedy",
    "ياوي" to "Yaoi",
    "يوري" to "Yuri",
)

val tags = listOf(
    "أطفال متروكون" to "Abandoned Children",
    "سرقة القدرات" to "Ability Steal",
    "آباء غائبون" to "Absent Parents",
    "شخصيات مسيئة" to "Abusive Characters",
    "أكاديمية" to "Academy",
    "نمو متسارع" to "Accelerated Growth",
    "التمثيل" to "Acting",
    "مقتبس من مانغا" to "Adapted from Manga",
    "مقتبس من مانهوا (صينية)" to "Adapted from Manhua",
    "مقتبس إلى أنمي" to "Adapted to Anime",
    "مقتبس إلى دراما تلفزيونية" to "Adapted to Drama",
    "مقتبس إلى دراما صوتية" to "Adapted to Drama CD",
    "مقتبس إلى لعبة" to "Adapted to Game",
    "مقتبس إلى مانغا" to "Adapted to Manga",
    "مقتبس إلى مانهوا (صينية)" to "Adapted to Manhua",
    "مقتبس إلى مانهوا (كورية)" to "Adapted to Manhwa",
    "مقتبس إلى فيلم" to "Adapted to Movie",
    "مقتبس إلى رواية بصرية" to "Adapted to Visual Novel",
    "أطفال بالتبنّي" to "Adopted Children",
    "بطل متبنّى" to "Adopted Protagonist",
    "خيانة زوجية" to "Adultery",
    "مغامرون" to "Adventurers",
    "علاقة سرية" to "Affair",
    "تقدّم في العمر" to "Age Progression",
    "ارتداد عمري" to "Age Regression",
    "شخصيات عدوانية" to "Aggressive Characters",
    "الخيمياء" to "Alchemy",
    "كائنات فضائية" to "Aliens",
    "مدرسة فتيات فقط" to "All-Girls School",
    "عالم بديل" to "Alternate World",
    "فقدان الذاكرة" to "Amnesia",
    "مدينة ملاهٍ" to "Amusement Park",
    "جنس شرجي" to "Anal",
    "الصين القديمة" to "Ancient China",
    "العصور القديمة" to "Ancient Times",
    "شخصيات أندروجينية" to "Androgynous Characters",
    "أندرويدات" to "Androids",
    "ملائكة" to "Angels",
    "صفات حيوانية" to "Animal Characteristics",
    "تربية الحيوانات" to "Animal Rearing",
    "مضاد للسحر" to "Anti-Magic",
    "بطل غير اجتماعي" to "Anti-social Protagonist",
    "بطل لا أخلاقي / بطل مضاد" to "Antihero Protagonist",
    "محل تحف" to "Antique Shop",
    "الحياة في الشقة" to "Apartment Life",
    "بطل غير مبالٍ" to "Apathetic Protagonist",
    "نهاية العالم" to "Apocalypse",
    "تغيّر المظهر" to "Appearance Changes",
    "مظهر لا يطابق العمر الحقيقي" to "Appearance Different from Actual Age",
    "الرماية بالقوس" to "Archery",
    "طبقة النبلاء" to "Aristocracy",
    "تجّار أسلحة" to "Arms Dealers",
    "جيش" to "Army",
    "بناء جيش" to "Army Building",
    "زواج مرتب" to "Arranged Marriage",
    "شخصيات متكبّرة" to "Arrogant Characters",
    "صناعة الآثار/القطع السحرية" to "Artifact Crafting",
    "قطع أثرية / قطع سحرية" to "Artifacts",
    "ذكاء اصطناعي" to "Artificial Intelligence",
    "فنانون" to "Artists",
    "قتلة مأجورون" to "Assassins",
    "منجّمون" to "Astrologers",
    "التوحّد" to "Autism",
    "آليّون ذاتيون" to "Automatons",
    "بطل بمظهر عادي" to "Average-looking Protagonist",
    "عمل حائز على جوائز" to "Award-winning Work",
    "بطل محرج اجتماعيًا" to "Awkward Protagonist",
    "فرق موسيقية" to "Bands",
    "مبني على فيلم" to "Based on a Movie",
    "مبني على أغنية" to "Based on a Song",
    "مبني على مسلسل تلفزيوني" to "Based on a TV Show",
    "مبني على لعبة فيديو" to "Based on a Video Game",
    "مبني على رواية بصرية" to "Based on a Visual Novel",
    "مبني على أنمي" to "Based on an Anime",
    "أكاديمية قتالية" to "Battle Academy",
    "مسابقة قتال" to "Battle Competition",
    "بي دي إس إم (سيطرة / خضوع)" to "BDSM",
    "رفاق وحوش" to "Beast Companions",
    "أنصاف وحوش / كائنات وحشية بشرية" to "Beastkin",
    "وحوش" to "Beasts",
    "بطلة جميلة جدًا" to "Beautiful Female Lead",
    "ممارسة جنسية مع الحيوانات" to "Bestiality",
    "خيانة" to "Betrayal",
    "ثنائي كثير الشجار" to "Bickering Couple",
    "شريحة حيوية" to "Biochip",
    "بطل مزدوج الميول" to "Bisexual Protagonist",
    "دهاء مظلم / شخصية خبيثة" to "Black Belly",
    "ابتزاز" to "Blackmail",
    "حدّاد" to "Blacksmith",
    "مواعدات عمياء" to "Blind Dates",
    "بطل أعمى" to "Blind Protagonist",
    "التحكم بالدم" to "Blood Manipulation",
    "سلالات دم قوية" to "Bloodlines",
    "تبادل الأجساد" to "Body Swap",
    "تقسية الجسد / صقل الجسد" to "Body Tempering",
    "بديل جسدي / شبيه" to "Body-double",
    "حراس شخصيون" to "Bodyguards",
    "كتب" to "Books",
    "محبّ للقراءة" to "Bookworm",
    "علاقة رئيس/مرؤوس" to "Boss-Subordinate Relationship",
    "غسل دماغ" to "Brainwashing",
    "هوس بالصدر" to "Breast Fetish",
    "فسخ خطوبة" to "Broken Engagement",
    "هوس بالأخ / تعلق مفرط بالأخ" to "Brother Complex",
    "أخوّة" to "Brotherhood",
    "البوذية" to "Buddhism",
    "تنمّر" to "Bullying",
    "إدارة أعمال" to "Business Management",
    "رجال أعمال" to "Businessmen",
    "خدم/خادم خاص (باتلر)" to "Butlers",
    "بطل هادئ" to "Calm Protagonist",
    "أكل لحوم البشر" to "Cannibalism",
    "ألعاب بطاقات" to "Card Games",
    "بطل لا مبالٍ / مسترخي" to "Carefree Protagonist",
    "بطل عطوف" to "Caring Protagonist",
    "بطل حذر" to "Cautious Protagonist",
    "مشاهير" to "Celebrities",
    "تطوّر الشخصية" to "Character Growth",
    "بطل ذو كاريزما" to "Charismatic Protagonist",
    "بطل ساحر" to "Charming Protagonist",
    "غرف محادثة" to "Chat Rooms",
    "قدرات غش/أوفر باور" to "Cheats",
    "طهاة" to "Chefs",
    "إساءة معاملة الأطفال" to "Child Abuse",
    "بطل طفل" to "Child Protagonist",
    "رعاية الأطفال" to "Childcare",
    "أصدقاء الطفولة" to "Childhood Friends",
    "حب الطفولة" to "Childhood Love",
    "وعد الطفولة" to "Childhood Promise",
    "بطل طفولي" to "Childish Protagonist",
    "متلازمة التشونيبـيو (وهم العظمة)" to "Chuunibyou",
    "بناء عشيرة / عائلة قوية" to "Clan Building",
    "كلاسيكي" to "Classic",
    "بطل ذكي" to "Clever Protagonist",
    "حبيب متشبث" to "Clingy Lover",
    "استنساخ / نسخ بشرية" to "Clones",
    "أندية مدرسية" to "Clubs",
    "حبيب/حبيبة أخرق(ة)" to "Clumsy Love Interests",
    "زملاء عمل" to "Co-Workers",
    "السكن المشترك" to "Cohabitation",
    "حبيب/حبيبة بارد(ة)" to "Cold Love Interests",
    "بطل بارد" to "Cold Protagonist",
    "مجموعة قصص قصيرة" to "Collection of Short Stories",
    "جامعة / كلية" to "College/University",
    "غيبوبة" to "Coma",
    "نبرة كوميدية" to "Comedic Undertone",
    "بلوغ / نضج نفسي" to "Coming of Age",
    "علاقات عائلية معقدة" to "Complex Family Relationships",
    "قوة مشروطة" to "Conditional Power",
    "بطل واثق" to "Confident Protagonist",
    "احتجاز / سجن" to "Confinement",
    "ولاءات متعارضة" to "Conflicting Loyalties",
    "عقود" to "Contracts",
    "الطبخ" to "Cooking",
    "فساد" to "Corruption",
    "حروب كونية" to "Cosmic Wars",
    "كوسبلاي / تنكّر شخصيات" to "Cosplay",
    "نمو العلاقة العاطفية" to "Couple Growth",
    "مسؤول في البلاط / موظف حكومي رفيع" to "Court Official",
    "أبناء العم/الخال" to "Cousins",
    "بطل جبان" to "Cowardly Protagonist",
    "صناعة / حرفية" to "Crafting",
    "جريمة" to "Crime",
    "مجرمون" to "Criminals",
    "تنكّر بملابس الجنس الآخر" to "Cross-dressing",
    "عالم مشترك / تلاقي عوالم" to "Crossover",
    "شخصيات قاسية" to "Cruel Characters",
    "تجميد حيوي" to "Cryostasis",
    "الزراعة الروحية / الزراعة القتالية" to "Cultivation",
    "جنس فموي للأنثى" to "Cunnilingus",
    "بطل ماكر" to "Cunning Protagonist",
    "بطل فضولي" to "Curious Protagonist",
    "لعنات" to "Curses",
    "أطفال لطيفون" to "Cute Children",
    "بطل لطيف" to "Cute Protagonist",
    "قصة لطيفة" to "Cute Story",
    "راقصون / راقصات" to "Dancers",
    "رفيق طريق الداو" to "Dao Companion",
    "استيعاب الداو" to "Dao Comprehension",
    "الطاوية / الداووية" to "Daoism",
    "داكن / مظلم" to "Dark",
    "بطل ميت" to "Dead Protagonist",
    "الموت" to "Death",
    "موت شخص عزيز" to "Death of Loved Ones",
    "ديون" to "Debts",
    "متمردون / منحرفون شبان" to "Delinquents",
    "أوهام" to "Delusions",
    "أنصاف بشر" to "Demi-Humans",
    "سيد الشياطين" to "Demon Lord",
    "تقنية زراعة شيطانية" to "Demonic Cultivation Technique",
    "شياطين / كائنات شيطانية" to "Demons",
    "بطل بليد عاطفيًا" to "Dense Protagonist",
    "تصوير القسوة" to "Depictions of Cruelty",
    "اكتئاب" to "Depression",
    "القدر" to "Destiny",
    "محققون" to "Detectives",
    "بطل مُصمِّم" to "Determined Protagonist",
    "شريك/شريكة مخلص(ة)" to "Devoted Love Interests",
    "فرق في المكانة الاجتماعية" to "Different Social Status",
    "إعاقات" to "Disabilities",
    "تمييز" to "Discrimination",
    "تشوّه" to "Disfigurement",
    "بطل مخادع" to "Dishonest Protagonist",
    "بطل لا يثق بالآخرين" to "Distrustful Protagonist",
    "العرافة / التنبؤ" to "Divination",
    "حماية إلهية" to "Divine Protection",
    "طلاق" to "Divorce",
)
