package eu.kanade.tachiyomi.extension.vi.luvevaland

import eu.kanade.tachiyomi.source.model.Filter
import eu.kanade.tachiyomi.source.model.FilterList

internal class TagFilter :
    Filter.Select<String>(
        "Thể loại",
        TAG_OPTIONS.map { it.first }.toTypedArray(),
    ) {
    fun toSlug(): String? = TAG_OPTIONS[state].second
}

internal fun getFilters(): FilterList = FilterList(
    TagFilter(),
)

private val TAG_OPTIONS = listOf(
    Pair("Tất cả", null),
    Pair("\"Đặc Sắc\"", "18"),
    Pair("1Vs1", "1vs1"),
    Pair("419", "419"),
    Pair("Bách hợp", "bach-hop"),
    Pair("Bàn tay vàng", "ban-tay-vang"),
    Pair("Báo thù rửa hận", "bao-thu-rua-han"),
    Pair("BE", "be"),
    Pair("BP", "bp"),
    Pair("Cán bộ cao cấp", "can-bo-cao-cap"),
    Pair("Cao H", "cao-h"),
    Pair("Cận đại", "can-dai"),
    Pair("Cẩu huyết", "cau-huyet"),
    Pair("Chuyển thể", "chuyen-the"),
    Pair("Chữa lành - cứu rỗi", "chua-lanh-cuu-roi"),
    Pair("Có baby", "co-baby"),
    Pair("Con cưng của trời", "thien-chi-kieu-tu-thien-chi-kieu-nu"),
    Pair("Cổ đại", "co-dai"),
    Pair("Cổ xuyên kim", "co-xuyen-kim"),
    Pair("Cung đấu", "cung-dau"),
    Pair("Cung đình hầu tước", "cung-dinh-hau-tuoc"),
    Pair("Cưng chiều", "sung"),
    Pair("Cưới trước yêu sau", "cuoi-truoc-yeu-sau"),
    Pair("Cưỡng ép - chiếm đoạt", "cuong-thu-hao-doat"),
    Pair("Dân quốc", "dan-quoc"),
    Pair("DC", "dc"),
    Pair("Dị giới", "di-gioi"),
    Pair("Dị năng", "di-nang"),
    Pair("Dirty talk", "dirty-talk"),
    Pair("Duyên trời tác hợp", "duyen-troi-tac-hop"),
    Pair("Dưỡng thê - Nuôi vợ từ bé", "duong-thanh"),
    Pair("Đại thúc vs loli - Chênh lệch tuổi tác", "dai-thuc-vs-loli-trau-gia-gam-co-non"),
    Pair("Đam mỹ", "dam-my"),
    Pair("Điên cuồng - độc chiếm - biến thái", "dien-cuong-doc-chiem-bien-thai"),
    Pair("Điền văn", "dien-van"),
    Pair("Đoản văn", "doan-van"),
    Pair("Đô thị tình duyên", "do-thi-tinh-duyen"),
    Pair("eSport - Thể thao điện tử", "esport-the-thao-dien-tu"),
    Pair("Fake Inc", "gia-incest"),
    Pair("Fanfic", "fanfic"),
    Pair("Fragonard", "nl"),
    Pair("Gangbang", "gangbang"),
    Pair("GE", "ge"),
    Pair("Gia đấu - Trạch đấu", "gia-dau-trach-dau"),
    Pair("Giang hồ", "giang-ho"),
    Pair("Gương vỡ không lành", "guong-vo-khong-lanh"),
    Pair("Gương vỡ lại lành", "guong-vo-lai-lanh"),
    Pair("H văn - Thịt văn", "h-van-thit-van"),
    Pair("Hài hước", "hai-huoc"),
    Pair("Hào môn thế gia", "hao-mon-the-gia"),
    Pair("HE", "he"),
    Pair("Hệ liệt", "he-liet"),
    Pair("Hệ thống", "he-thong"),
    Pair("Hiện đại", "hien-dai"),
    Pair("Hóa thú", "hoa-thu"),
    Pair("Hoán đổi linh hồn", "hoan-doi-linh-hon"),
    Pair("Huyền Huyễn", "huyen-huyen"),
    Pair("Inc", "incest"),
    Pair("Khẩu vị nặng", "khau-vi-nang"),
    Pair("Khống", "khong"),
    Pair("Không CP", "khong-cp"),
    Pair("Không Tam Quan", "khong-tam-quan"),
    Pair("Kiếp trước kiếp này", "kiep-truoc-kiep-nay"),
    Pair("Kinh dị", "kinh-di"),
    Pair("Lạc Miêu Team", "lac-mieu-team"),
    Pair("Lâu ngày gặp lại", "lau-ngay-gap-lai"),
    Pair("Lâu ngày sinh tình", "lau-ngay-sinh-tinh"),
    Pair("Lịch sử", "lich-su"),
    Pair("Linh dị thần quái", "linh-di-than-quai"),
    Pair("Manga", "manga"),
    Pair("Mạt thế", "mat-the"),
    Pair("Mất trí nhớ", "mat-tri-nho"),
    Pair("Mỹ nhân ngư (Nam/Nữ)", "my-nhan-ngu-namnu"),
    Pair("Mỹ nhân sườn xám", "my-nhan-suon-xam"),
    Pair("Mỹ Thực", "my-thuc"),
    Pair("Nam cường", "nam-cuong"),
    Pair("Nam phụ thượng vị - Đập chậu cướp hoa", "nam-phu-thuong-vi"),
    Pair("Nam trọng sinh", "nam-trong-sinh"),
    Pair("Nam/nữ có bệnh", "namnu-co-benh"),
    Pair("Nam/nữ khiếm khuyết", "namnu-khiem-khuyet"),
    Pair("Ngây thơ", "tieu-bach"),
    Pair("Nghiệp giới tinh anh", "nghiep-gioi-tinh-anh"),
    Pair("Ngọt", "ngot"),
    Pair("Ngôn Tình", "ngon-tinh"),
    Pair("Ngược", "nguoc"),
    Pair("Ngược luyến tàn tâm", "nguoc-luyen-tan-tam"),
    Pair("Ngược luyến tình thâm", "nguoc-luyen-tinh-tham"),
    Pair("Ngược nam", "nguoc-nam"),
    Pair("Ngược nữ", "nguoc-nu"),
    Pair("Ngược thân", "nguoc-than"),
    Pair("Ngược tra", "nguoc-tra"),
    Pair("Nham hiểm", "phuc-hac"),
    Pair("Nhân thú", "nhan-thu"),
    Pair("Nhất kiến chung tình", "nhat-kien-chung-tinh"),
    Pair("Nhẹ nhàng", "nhe-nhang"),
    Pair("Novel Kr", "novel-kr"),
    Pair("NP", "np"),
    Pair("NTR", "ntr"),
    Pair("Nữ cường", "nu-cuong"),
    Pair("Nữ giả nam", "nu-phan-nam-trang"),
    Pair("Nữ phụ văn", "nu-phu-van"),
    Pair("Nữ tôn", "nu-ton"),
    Pair("Nữ truy", "nu-truy"),
    Pair("Oan gia", "oan-gia"),
    Pair("OE", "oe"),
    Pair("On Going", "on-going"),
    Pair("Phản xuyên", "phan-xuyen"),
    Pair("Quân nhân/Cảnh sát/Đặc công", "quan-nhan"),
    Pair("Sạch", "sach"),
    Pair("Sắc", "sac"),
    Pair("SE", "se"),
    Pair("Shoujo", "shoujo"),
    Pair("Showbiz", "showbiz"),
    Pair("SM", "sm"),
    Pair("Song trùng sinh", "song-trong-sinh"),
    Pair("Song xuyên", "song-xuyen"),
    Pair("Song xử", "song-xu"),
    Pair("Tản văn", "tan-van"),
    Pair("Tâm lý", "tam-ly"),
    Pair("Thanh mai trúc mã", "thanh-mai-truc-ma"),
    Pair("Thanh thuỷ văn", "thanh-thuy-van"),
    Pair("Thanh xuân vườn trường", "thanh-xuan-vuon-truong"),
    Pair("Thanh xuyên", "thanh-xuyen"),
    Pair("Thâm tình", "tham-tinh"),
    Pair("Thể thao", "the-thao"),
    Pair("Thiên kim thật - giả", "thien-kim-that-gia"),
    Pair("Thực tế", "thuc-te"),
    Pair("Thương trường", "thuong-truong"),
    Pair("Tiên hiệp/ Tu tiên", "tien-hiep-tu-tien"),
    Pair("Tiểu thuyết Hàn Quốc", "tieu-thuyet-han-quoc"),
    Pair("Tình chị em - Hồng hài nhi", "ty-de-luyen"),
    Pair("Tinh tế/ABO", "tinh-teabo"),
    Pair("Tình yêu thầy trò", "su-do-luyen"),
    Pair("Tình yêu văn phòng", "tinh-yeu-van-phong"),
    Pair("Tổng hợp", "tong-hop"),
    Pair("TQ", "tq"),
    Pair("Tranh quyền đoạt vị", "tranh-quyen-doat-vi"),
    Pair("Trap", "trap"),
    Pair("Trinh thám - phá án", "trinh-tham-pha-an"),
    Pair("Trùng sinh", "trong-sinh"),
    Pair("Truyện ⚡", "21"),
    Pair("Truyện Hát - có nội dung", "cao-h-co-cot-truyen"),
    Pair("Truyện ngắn", "truyen-ngan"),
    Pair("Truyện nước ngoài", "truyen-nuoc-ngoai"),
    Pair("Trước ngược nữ sau ngược nam", "truoc-nguoc-nu-sau-nguoc-nam"),
    Pair("Tuỳ bút", "tuy-but"),
    Pair("Tuỳ thân không gian", "tuy-than-khong-gian"),
    Pair("Từ thanh xuân đến trưởng thành", "tu-thanh-xuan-den-truong-thanh"),
    Pair("Tự truyện", "tu-truyen"),
    Pair("Tương lai", "tuong-lai"),
    Pair("Vả mặt", "va-mat"),
    Pair("Viễn tưởng", "vien-tuong"),
    Pair("Võng du", "vong-du"),
    Pair("Võng phối", "vong-phoi"),
    Pair("Vô hạn lưu", "vo-han-luu"),
    Pair("Xã hội đen", "hac-bang"),
    Pair("Xúc tu", "xuc-tu"),
    Pair("Xuyên không", "xuyen-khong"),
    Pair("Xuyên nhanh", "xuyen-nhanh"),
    Pair("Xuyên sách", "xuyen-sach"),
    Pair("Y thuật - Bác sĩ", "y-thuat-bac-si"),
    Pair("Yêu thầm", "tham-men"),
    Pair("📖Xuất bản", "xuat-ban"),
    Pair("📚 Tập truyện", "tap-truyen-click-vao-ten-tac-gia-de-xem-cac-phan-khac"),
    Pair("🏅Kim bài đề cử", "kim-bai-de-cu"),
    Pair("🏏Dụng cụ/Play đủ kiểu", "dung-cuplay-du-kieu"),
    Pair("💣Mìn", "min"),
    Pair("🔞Smut", "smut"),
)
