package eu.kanade.tachiyomi.extension.id.wurmz

import eu.kanade.tachiyomi.source.model.Filter

open class TypeFilter :
    UriPartFilter(
        "Type",
        arrayOf(
            "Semua Type" to "",
            "Manga" to "manga",
            "Manhwa" to "manhwa",
            "Manhua" to "manhua",
        ),
    )

open class StatusFilter :
    UriPartFilter(
        "Status",
        arrayOf(
            "Semua Status" to "",
            "Ongoing" to "ongoing",
            "Tamat" to "tamat",
            "Hiatus" to "hiatus",
            "Drop" to "drop",
        ),
    )

class GenreFilter : UriPartFilter("Genre", GENRES)

abstract class UriPartFilter(name: String, private val vals: Array<Pair<String, String>>) : Filter.Select<String>(name, vals.map { it.first }.toTypedArray()) {
    fun toUriPart() = vals[state].second
}

private val GENRES = arrayOf(
    "Semua Genre" to "",
    "Fantasy" to "Fantasy",
    "Romance" to "Romance",
    "Drama" to "Drama",
    "Action" to "Action",
    "Comedy" to "Comedy",
    "Shounen" to "Shounen",
    "Adventure" to "Adventure",
    "Shoujo" to "Shoujo",
    "School" to "School",
    "Slice of Life" to "Slice of Life",
    "Seinen" to "Seinen",
    "Supernatural" to "Supernatural",
    "Historical" to "Historical",
    "Josei" to "Josei",
    "Webtoons" to "Webtoons",
    "Isekai" to "Isekai",
    "Martial Art" to "Martial Art",
    "Harem" to "Harem",
    "Ecchi" to "Ecchi",
    "Reincarnation" to "Reincarnation",
    "Magic" to "Magic",
    "Mystery" to "Mystery",
    "Psychological" to "Psychological",
    "Yaoi" to "Yaoi",
    "Mature" to "Mature",
    "Horror" to "Horror",
    "Tragedy" to "Tragedy",
    "Sci-fi" to "Sci-fi",
    "Shounen Ai" to "Shounen Ai",
    "Adaptation" to "Adaptation",
    "Demons" to "Demons",
    "Gender Bender" to "Gender Bender",
    "Game" to "Game",
    "Yuri" to "Yuri",
    "Shoujo Ai" to "Shoujo Ai",
    "Thriller" to "Thriller",
    "Sport" to "Sport",
    "Cooking" to "Cooking",
    "Crime" to "Crime",
    "Gore" to "Gore",
    "Royal Family" to "Royal Family",
    "Super Power" to "Super Power",
    "Regression" to "Regression",
    "Military" to "Military",
    "Royalty" to "Royalty",
    "Vampire" to "Vampire",
    "Transmigration" to "Transmigration",
    "Medical" to "Medical",
    "Office Workers" to "Office Workers",
    "Time Travel" to "Time Travel",
    "Childhood Friends" to "Childhood Friends",
    "Music" to "Music",
    "Monsters" to "Monsters",
    "Revenge" to "Revenge",
    "College Life" to "College Life",
    "Villainess" to "Villainess",
    "Kids" to "Kids",
    "Mecha" to "Mecha",
    "Police" to "Police",
    "Omegaverse" to "Omegaverse",
    "One Shot" to "One Shot",
    "Animals" to "Animals",
    "Girls" to "Girls",
    "Reverse Harem" to "Reverse Harem",
    "Ghosts" to "Ghosts",
    "Project" to "Project",
    "Age Gap" to "Age Gap",
    "Showbiz" to "Showbiz",
    "Violence" to "Violence",
    "Boys" to "Boys",
    "Shotacon" to "Shotacon",
    "Survival" to "Survival",
    "Beasts" to "Beasts",
    "Bloody" to "Bloody",
    "Crossdressing" to "Crossdressing",
    "Delinguents" to "Delinguents",
    "Dungeons" to "Dungeons",
    "Non-human" to "Non-human",
    "Post-Apocalyptic" to "Post-Apocalyptic",
    "Zombies" to "Zombies",
    "Doujinshi" to "Doujinshi",
    "Gyaru" to "Gyaru",
    "18+" to "18+",
    "Bodyswap" to "Bodyswap",
    "Yakuzas" to "Yakuzas",
    "Philosophical" to "Philosophical",
    "System" to "System",
    "Lolicon" to "Lolicon",
    "NTR" to "NTR",
    "Aliens" to "Aliens",
    "BDSM" to "BDSM",
    "Hentai" to "Hentai",
    "Fetish" to "Fetish",
    "Incest" to "Incest",
    "Virtual Reality" to "Virtual Reality",
    "Anthology" to "Anthology",
    "Dementia" to "Dementia",
    "Samurai" to "Samurai",
    "4-Koma" to "4-Koma",
    "Cheating" to "Cheating",
    "Milf" to "Milf",
    "Ninja" to "Ninja",
    "Guideverse" to "Guideverse",
    "Infidelity" to "Infidelity",
    "Mafia" to "Mafia",
    "Nakadashi" to "Nakadashi",
    "Parodi" to "Parodi",
    "Reverse Isekai" to "Reverse Isekai",
    "Villain" to "Villain",
)
