package eu.kanade.tachiyomi.extension.id.wurmz

import eu.kanade.tachiyomi.source.model.Filter

open class TypeFilter :
    UriPartFilter(
        "Tipe",
        arrayOf(
            "Semua Tipe" to "",
            "Manga" to "manga",
            "Manhwa" to "manhwa",
            "Manhua" to "manhua",
        ),
    )

open class StatusFilter :
    UriPartFilter(
        "Status",
        arrayOf(
            "Semua Status" to "",
            "Ongoing" to "ongoing",
            "Tamat" to "tamat",
            "Hiatus" to "hiatus",
            "Drop" to "drop",
        ),
    )

class GenreFilter : UriPartFilter("Genre", GENRES)

abstract class UriPartFilter(name: String, private val vals: Array<Pair<String, String>>) : Filter.Select<String>(name, vals.map { it.first }.toTypedArray()) {
    fun toUriPart() = vals[state].second
}

private val GENRES = arrayOf(
    "Semua Genre" to "",
    "18+" to "18+",
    "4-Koma" to "4-Koma",
    "Action" to "Action",
    "Adaptation" to "Adaptation",
    "Adult" to "Adult",
    "Adventure" to "Adventure",
    "Age Gap" to "Age Gap",
    "Aliens" to "Aliens",
    "Animals" to "Animals",
    "Anthology" to "Anthology",
    "BDSM" to "BDSM",
    "Beasts" to "Beasts",
    "Bloody" to "Bloody",
    "Bodyswap" to "Bodyswap",
    "Boys" to "Boys",
    "Cheating" to "Cheating",
    "Childhood Friends" to "Childhood Friends",
    "College Life" to "College Life",
    "Comedy" to "Comedy",
    "Cooking" to "Cooking",
    "Crime" to "Crime",
    "Crossdressing" to "Crossdressing",
    "Delinguents" to "Delinguents",
    "Dementia" to "Dementia",
    "Demons" to "Demons",
    "Doujinshi" to "Doujinshi",
    "Drama" to "Drama",
    "Dungeons" to "Dungeons",
    "Ecchi" to "Ecchi",
    "Fantasy" to "Fantasy",
    "Fetish" to "Fetish",
    "Game" to "Game",
    "Gender Bender" to "Gender Bender",
    "Ghosts" to "Ghosts",
    "Girls" to "Girls",
    "Gore" to "Gore",
    "Guideverse" to "Guideverse",
    "Gyaru" to "Gyaru",
    "Harem" to "Harem",
    "Hentai" to "Hentai",
    "Historical" to "Historical",
    "Horror" to "Horror",
    "Incest" to "Incest",
    "Infidelity" to "Infidelity",
    "Isekai" to "Isekai",
    "Josei" to "Josei",
    "Kids" to "Kids",
    "Lolicon" to "Lolicon",
    "Mafia" to "Mafia",
    "Magic" to "Magic",
    "Martial Art" to "Martial Art",
    "Mature" to "Mature",
    "Mecha" to "Mecha",
    "Medical" to "Medical",
    "Milf" to "Milf",
    "Military" to "Military",
    "Monsters" to "Monsters",
    "Music" to "Music",
    "Mystery" to "Mystery",
    "NTR" to "NTR",
    "Nakadashi" to "Nakadashi",
    "Ninja" to "Ninja",
    "Non-human" to "Non-human",
    "Office Workers" to "Office Workers",
    "Omegaverse" to "Omegaverse",
    "One Shot" to "One Shot",
    "Parodi" to "Parodi",
    "Philosophical" to "Philosophical",
    "Police" to "Police",
    "Post-Apocalyptic" to "Post-Apocalyptic",
    "Project" to "Project",
    "Psychological" to "Psychological",
    "Regression" to "Regression",
    "Reincarnation" to "Reincarnation",
    "Reverse Harem" to "Reverse Harem",
    "Reverse Isekai" to "Reverse Isekai",
    "Revenge" to "Revenge",
    "Romance" to "Romance",
    "Royal Family" to "Royal Family",
    "Royalty" to "Royalty",
    "Samurai" to "Samurai",
    "School" to "School",
    "Sci-fi" to "Sci-fi",
    "Seinen" to "Seinen",
    "Shotacon" to "Shotacon",
    "Shoujo" to "Shoujo",
    "Shoujo Ai" to "Shoujo Ai",
    "Shounen" to "Shounen",
    "Shounen Ai" to "Shounen Ai",
    "Showbiz" to "Showbiz",
    "Slice of Life" to "Slice of Life",
    "Smut" to "Smut",
    "Sport" to "Sport",
    "Super Power" to "Super Power",
    "Supernatural" to "Supernatural",
    "Survival" to "Survival",
    "System" to "System",
    "Thriller" to "Thriller",
    "Time Travel" to "Time Travel",
    "Tragedy" to "Tragedy",
    "Transmigration" to "Transmigration",
    "Vampire" to "Vampire",
    "Villain" to "Villain",
    "Villainess" to "Villainess",
    "Virtual Reality" to "Virtual Reality",
    "Webtoons" to "Webtoons",
    "Yakuzas" to "Yakuzas",
    "Yaoi" to "Yaoi",
    "Yuri" to "Yuri",
    "Zombies" to "Zombies",
)
