package eu.kanade.tachiyomi.extension.ja.flowercomics

import eu.kanade.tachiyomi.source.model.Filter

class CategoryFilter :
    SelectFilter(
        "Category",
        arrayOf(
            Triple("月", "day", "mon"),
            Triple("火", "day", "tue"),
            Triple("水", "day", "wed"),
            Triple("木", "day", "thu"),
            Triple("金", "day", "fri"),
            Triple("土", "day", "sat"),
            Triple("日", "day", "sun"),
            Triple("完結", "rensai", "completed"),
            Triple("よみきり", "rensai", "one-shot"),
            Triple("Ｓｈｏ－Ｃｏｍｉ", "label", "3"),
            Triple("Sho-ComiX", "label", "6"),
            Triple("＆フラワー[1]", "label", "9"),
            Triple("Ｃｈｅｅｓｅ！", "label", "12"),
            Triple("プレミアCheese！", "label", "15"),
            Triple("＆フラワー[2]", "label", "18"),
            Triple("ベツコミ", "label", "21"),
            Triple("ベツフラ[1]", "label", "24"),
            Triple("＆フラワー[3]", "label", "27"),
            Triple("プチコミック", "label", "30"),
            Triple("姉プチ", "label", "33"),
            Triple("デジプチ", "label", "36"),
            Triple("月刊ｆｌｏｗｅｒｓ", "label", "39"),
            Triple("flowers増刊", "label", "42"),
            Triple("ベツフラ[2]", "label", "45"),
            Triple("妻プチ", "label", "48"),
            Triple("モバフラ", "label", "51"),
            Triple("その他", "label", "54"),
            Triple("オリジナル", "label", "57"),
            Triple("＆フラワー[4]", "label", "58"),
            Triple("プチコミック増刊", "label", "59"),
            Triple("プチプチ", "label", "62"),
            Triple("デラックスベツコミ", "label", "65"),
            Triple("恋愛/学園", "tag", "1"),
            Triple("リアルな恋、理想の恋…あなたはどのタイプ？ 大人の恋愛特集", "tag", "4"),
            Triple("恋愛/コメディ", "tag", "7"),
            Triple("恋愛/オフィス", "tag", "10"),
            Triple("恋愛", "tag", "13"),
            Triple("青春・友情", "tag", "16"),
            Triple("ＢＬ・ブロマンス", "tag", "19"),
            Triple("ＧＬ", "tag", "22"),
            Triple("ミステリー・推理", "tag", "25"),
            Triple("ファンタジー", "tag", "28"),
            Triple("歴史・時代モノ", "tag", "31"),
            Triple("転生", "tag", "34"),
            Triple("どうぶつ", "tag", "37"),
            Triple("人外・異種族", "tag", "40"),
            Triple("バース系・特殊設定", "tag", "43"),
            Triple("同居", "tag", "44"),
            Triple("溺愛", "tag", "47"),
            Triple("クール男子", "tag", "50"),
            Triple("メディア化", "tag", "53"),
            Triple("家族・結婚", "tag", "56"),
            Triple("キュン", "tag", "59"),
            Triple("かわいい男子", "tag", "62"),
            Triple("よみきり", "tag", "65"),
            Triple("転落", "tag", "68"),
            Triple("刺激的", "tag", "71"),
            Triple("包容力男子", "tag", "74"),
            Triple("短編集", "tag", "77"),
            Triple("エモ", "tag", "83"),
            Triple("メガネ男子", "tag", "86"),
            Triple("イッキ読み可能♡完結作品", "tag", "89"),
            Triple("禁断・背徳", "tag", "92"),
            Triple("わちゃわちゃ", "tag", "95"),
            Triple("いじわる男子", "tag", "98"),
            Triple("エッセイ・ショート", "tag", "101"),
            Triple("年の差", "tag", "104"),
            Triple("ハラハラ", "tag", "107"),
            Triple("クズ男子", "tag", "110"),
            Triple("嫌われ", "tag", "116"),
            Triple("ちょっとＨ", "tag", "119"),
            Triple("ヤンデレ男子", "tag", "122"),
            Triple("ざまぁ展開", "tag", "152"),
            Triple("俺様・ドS", "tag", "155"),
            Triple("勘違い・すれ違い", "tag", "158"),
            Triple("ほんわか", "tag", "161"),
            Triple("社長", "tag", "164"),
            Triple("SNS", "tag", "167"),
            Triple("切ない", "tag", "170"),
            Triple("ハイスペ・スパダリ", "tag", "173"),
            Triple("三角関係", "tag", "176"),
            Triple("イケおじ", "tag", "179"),
            Triple("癒し系", "tag", "182"),
            Triple("アイドル・芸能人", "tag", "185"),
            Triple("サスペンス", "tag", "188"),
            Triple("ダーク", "tag", "191"),
            Triple("日常", "tag", "194"),
            Triple("ヒューマンドラマ", "tag", "197"),
            Triple("アクション・格闘", "tag", "200"),
            Triple("お仕事", "tag", "203"),
            Triple("特殊能力", "tag", "206"),
            Triple("医療・救護", "tag", "209"),
            Triple("ギャグ・コメディー", "tag", "212"),
            Triple("ホラー", "tag", "215"),
            Triple("スポーツ", "tag", "218"),
            Triple("サクセスストーリー", "tag", "221"),
            Triple("政治・社会派", "tag", "224"),
            Triple("グルメ", "tag", "227"),
            Triple("芸術", "tag", "230"),
            Triple("音楽", "tag", "233"),
            Triple("身分差", "tag", "235"),
            Triple("【４／５まで！】１巻分完全無料", "tag", "238"),
            Triple("愛されまくり！溺愛男子", "tag", "242"),
            Triple("こんな恋がしたい！憧れ学園LOVＥ", "tag", "245"),
            Triple("溢れるロマン！ファンタジー作品", "tag", "248"),
            Triple("この恋にはヒミツがある…禁断の愛", "tag", "251"),
            Triple("予測不能？ミステリー＆サスペンス", "tag", "254"),
            Triple("イッキ読み可能♡　完結作品", "tag", "257"),
            Triple("沼！クズ男子", "tag", "260"),
            Triple("フラコミ限定！オリジナル作品", "tag", "263"),
            Triple("SNSでバズり中！話題の作品！", "tag", "266"),
            Triple("現在無料キャンペーン中の作品！[1]", "tag", "269"),
            Triple("現在無料キャンペーン中の作品！[2]", "tag", "272"),
            Triple("現在無料キャンペーン中の作品！[3]", "tag", "275"),
            Triple("現在無料キャンペーン中の作品！[4]", "tag", "278"),
            Triple("現在無料キャンペーン中の作品！[5]", "tag", "281"),
            Triple("現在無料キャンペーン中の作品！[6]", "tag", "284"),
            Triple("期間限定無料！エッセイ・ショート", "tag", "287"),
            Triple("現在無料キャンペーン中の作品！[7]", "tag", "290"),
            Triple("現在無料キャンペーン中の作品！[8]", "tag", "293"),
            Triple("現在無料キャンペーン中の作品！[9]", "tag", "296"),
            Triple("現在無料キャンペーン中の作品！[10]", "tag", "299"),
            Triple("第94回 小学館 新人コミック大賞受賞作品", "tag", "302"),
            Triple("新人賞", "tag", "305"),
            Triple("キミだから好き。BL特集！", "tag", "311"),
            Triple("プチコミ　ショート作品 一挙新連載特集！", "tag", "314"),
            Triple("間もなく無料期間終了！エッセイ・ショート", "tag", "320"),
            Triple("月１作家企画・吉田秋生先生特集！", "tag", "323"),
            Triple("SF", "tag", "347"),
            Triple("読むなら今！萩尾望都作品無料増量中", "tag", "350"),
            Triple("月１作家企画・和泉かねよし先生特集！", "tag", "356"),
            Triple("食欲の秋！　飲んで食べて恋をして♡[1]", "tag", "359"),
            Triple("ホラー読切特集開催中！", "tag", "362"),
            Triple("超大型無料キャンペーン！漫祭２０２４[1]", "tag", "365"),
            Triple("食欲の秋！　飲んで食べて恋をして♡[2]", "tag", "368"),
            Triple("次のヒット作はこれ！！　１か月以内に開始した新連載作品", "tag", "371"),
            Triple("超大型無料キャンペーン！漫祭２０２４[2]", "tag", "374"),
            Triple("月１作家企画・朱神宝先生特集！", "tag", "377"),
            Triple("超大型無料キャンペーン！漫祭２０２４[3]", "tag", "380"),
            Triple("超大型無料キャンペーン！漫祭２０２４[4]", "tag", "383"),
            Triple("ハロウィン全連載作品1巻無料", "tag", "386"),
            Triple("溺愛＆スパダリの名手！甘宮ちか＆七海月作品特集", "tag", "389"),
            Triple("月１作家企画・みつきかこ先生特集！", "tag", "392"),
            Triple("連載権争奪新人よみきり選手権", "tag", "395"),
            Triple("月１作家企画・北川みゆき先生特集！", "tag", "398"),
            Triple("第95回 小学館 新人コミック大賞受賞作品", "tag", "401"),
            Triple("人生観変わる!?長編漫画特集", "tag", "404"),
            Triple("月１作家企画・くまがい杏子先生特集！", "tag", "407"),
            Triple("美！和装漫画フェア", "tag", "410"),
            Triple("新人賞受賞読切作品", "tag", "413"),
            Triple("月１作家企画・田村由美先生特集！", "tag", "416"),
            Triple("ハッピーバレンタイン！　チョコとお菓子にまつわる恋", "tag", "419"),
            Triple("まずはこれ！　読者数TOP１０", "tag", "422"),
            Triple("【25冬のBL特集】", "tag", "425"),
            Triple("月１作家企画・藤間麗先生特集！", "tag", "428"),
            Triple("特別な恋を君と。ＢＬ特集開催中！", "tag", "431"),
            Triple("『BANANA FISH』４０周年！吉田秋生先生特集[1]", "tag", "432"),
            Triple("月１作家企画・桜小路かのこ先生特集！", "tag", "435"),
            Triple("ベツコミ５５周年記念無料キャンペーン！", "tag", "438"),
            Triple("知性宿る魅力！　メガネ男子特集", "tag", "441"),
            Triple("月１作家企画・小玉ユキ先生特集！", "tag", "444"),
            Triple("５月限定！特選人気作無料キャンペーン", "tag", "447"),
            Triple("GWたっぷり!無料!!で読める作品はコチラ!!!", "tag", "450"),
            Triple("『次にくるマンガ大賞2025』　フラコミがオススメするエントリー候補作品！", "tag", "453"),
            Triple("クイーンズ・クオリティ完結記念！最富キョウスケ特集", "tag", "459"),
            Triple("月１作家企画・吉永ゆう先生特集！", "tag", "462"),
            Triple("６月限定！特選人気作無料キャンペーン", "tag", "465"),
            Triple("第96回 小学館 新人コミック大賞受賞作品", "tag", "468"),
            Triple("７月限定！特選人気作無料キャンペーン", "tag", "473"),
            Triple("月１作家企画・七尾美緒先生特集！", "tag", "476"),
            Triple("月１作家企画・七尾美緒先生特集！読み切り作品", "tag", "479"),
            Triple("創刊５５周年記念　夏恋ベツコミ", "tag", "482"),
            Triple("月１作家企画・宮園いづみ先生特集！", "tag", "485"),
            Triple("8/1～8/9まで毎日1話ずつ無料", "tag", "488"),
            Triple("8/9～8/18まで毎日1話ずつ無料", "tag", "491"),
            Triple("『BANANA FISH』４０周年！吉田秋生先生特集[2]", "tag", "494"),
            Triple("ベツコミ55th　レジェンド作品大集合！", "tag", "497"),
            Triple("祝画業30周年！和泉かねよし傑作無料キャンペーン", "tag", "500"),
            Triple("月１作家企画・梅沢麻里奈先生特集！", "tag", "503"),
            Triple("9月限定！特選人気作無料キャンペーン", "tag", "506"),
            Triple("8チャプター無料！ 3/5まで！", "tag", "509"),
            Triple("漫祭2025　第2弾　甘くて苦くて愛おしい…ときめきが止まらない！ラブストーリーフェア！", "tag", "515"),
            Triple("漫祭2025　第4弾　男女共通！次世代の名作が勢揃い　ネクストブレイク作品フェア！！", "tag", "518"),
            Triple("月１作家企画・織田綺先生特集！", "tag", "521"),
            Triple("10月限定！特選人気作無料キャンペーン", "tag", "524"),
            Triple("漫祭2025　第6弾　恋…だけじゃない　多彩な人間模様を描いた少女・女性漫画フェア！", "tag", "527"),
            Triple("漫祭2025　第7弾 転生も令嬢も盛りだくさん！ 異世界系漫画特集!!", "tag", "530"),
            Triple("漫祭2025　第8弾　イッキ読み必至！読み始めたら止まらない完結済み少女・女性漫画セレクション！", "tag", "533"),
            Triple("11月限定！特選人気作無料キャンペーン", "tag", "538"),
            Triple("月１作家企画・波津彬子先生特集！", "tag", "541"),
            Triple("今週末スタートした無料キャンペーン作品", "tag", "544"),
            Triple("もうすぐ終了！無料キャンペーン", "tag", "547"),
            Triple("月１作家企画・宇佐美真紀先生特集！", "tag", "550"),
            Triple("月１作家企画・水瀬 藍先生特集！", "tag", "553"),
            Triple("第97回 小学館 新人コミック大賞受賞作品", "tag", "554"),
            Triple("闇男子に沼りまくり♡FCフェア2025", "tag", "557"),
            Triple("年始スタートした無料キャンペーン作品", "tag", "560"),
            Triple("水瀬藍＆くまがい杏子画業20周年記念フェア！", "tag", "563"),
            Triple("2026年マンガ初め！小学館オールジャンル漫画フェア！第三弾", "tag", "566"),
            Triple("月１作家企画・畑亜希美先生特集！", "tag", "569"),
            Triple("月１作家企画・藤沢志月先生特集！", "tag", "572"),
            Triple("2/22は猫の日！フラコミで猫まみれ", "tag", "575"),
            Triple("「ラブファントム」「その男、沼につき」合同PV公開中！", "tag", "578"),
            Triple("萩尾望都作品無料増量中！", "tag", "581"),
        ),
    )

open class SelectFilter(displayName: String, private val vals: Array<Triple<String, String, String>>) : Filter.Select<String>(displayName, vals.map { it.first }.toTypedArray()) {
    val type: String
        get() = vals[state].second

    val value: String
        get() = vals[state].third
}
