package eu.kanade.tachiyomi.extension.id.kumopoi

import eu.kanade.tachiyomi.source.model.Filter

class SortFilter(default: String = "latest") :
    Filter.Select<String>(
        "Urutan",
        options.map { it.first }.toTypedArray(),
        options.indexOfFirst { it.second == default }.coerceAtLeast(0),
    ) {
    val selected get() = options[state].second

    companion object {
        private val options = arrayOf(
            "Terbaru" to "latest",
            "Terpopuler" to "popular",
            "A - Z" to "az",
            "Z - A" to "za",
        )
    }
}

class TypeFilter :
    Filter.Select<String>(
        "Tipe",
        options.map { it.first }.toTypedArray(),
    ) {
    val selected get() = options[state].second

    companion object {
        private val options = arrayOf(
            "Semua" to "",
            "Manhwa (Korea)" to "MANHWA",
            "Manga (Jepang)" to "MANGA",
            "Manhua (China)" to "MANHUA",
        )
    }
}

class StatusFilter :
    Filter.Select<String>(
        "Status",
        options.map { it.first }.toTypedArray(),
    ) {
    val selected get() = options[state].second

    companion object {
        private val options = arrayOf(
            "Semua" to "",
            "Ongoing" to "ONGOING",
            "Completed" to "END",
        )
    }
}

class Genre(name: String, val slug: String) : Filter.CheckBox(name)

class GenreFilter(genres: List<Genre> = getGenres()) :
    Filter.Group<Genre>(
        "Genre",
        genres,
    )

fun getGenres(): List<Genre> = listOf(
    Genre("Action", "action"),
    Genre("Adult", "adult"),
    Genre("Adventure", "adventure"),
    Genre("Age Regression", "age-regression"),
    Genre("Ahegao", "ahegao"),
    Genre("Amputee", "amputee"),
    Genre("Anal", "anal"),
    Genre("Apron", "apron"),
    Genre("Artist CG", "artist-cg"),
    Genre("Aunt", "aunt"),
    Genre("Bald", "bald"),
    Genre("BDSM", "bdsm"),
    Genre("Beauty Mark", "beauty-mark"),
    Genre("Bestiality", "bestiality"),
    Genre("Big Areolae", "big-areolae"),
    Genre("Big Ass", "big-ass"),
    Genre("Big Breast", "big-breast"),
    Genre("Big Nipples", "big-nipples"),
    Genre("Big Penis", "big-penis"),
    Genre("Bike Shorts", "bike-shorts"),
    Genre("Bikini", "bikini"),
    Genre("Birth", "birth"),
    Genre("Bisexual", "bisexual"),
    Genre("Biting", "biting"),
    Genre("Blackmail", "blackmail"),
    Genre("Blindfold", "blindfold"),
    Genre("Bloomers", "bloomers"),
    Genre("Blowjob", "blowjob"),
    Genre("Body Swap", "body-swap"),
    Genre("Bodysuit", "bodysuit"),
    Genre("Bondage", "bondage"),
    Genre("Booty", "booty"),
    Genre("Bride", "bride"),
    Genre("Bukkake", "bukkake"),
    Genre("Bullying", "bullying"),
    Genre("Bunny Girl", "bunny-girl"),
    Genre("Business Suit", "business-suit"),
    Genre("Busty", "busty"),
    Genre("Censored", "censored"),
    Genre("Cheating", "cheating"),
    Genre("Cohabitation", "cohabitation"),
    Genre("Collar", "collar"),
    Genre("Comedy", "comedy"),
    Genre("Condom", "condom"),
    Genre("Cosplay", "cosplay"),
    Genre("Cousin", "cousin"),
    Genre("Cowgirl", "cowgirl"),
    Genre("Creampie", "creampie"),
    Genre("Crossdressing", "crossdressing"),
    Genre("Cunnilingus", "cunnilingus"),
    Genre("Dark Skin", "dark-skin"),
    Genre("Daughter", "daughter"),
    Genre("Deepthroat", "deepthroat"),
    Genre("Defloration", "defloration"),
    Genre("Demon", "demon"),
    Genre("Demon Girl", "demon-girl"),
    Genre("Dick Growth", "dick-growth"),
    Genre("Digital", "digital"),
    Genre("DILF", "dilf"),
    Genre("Double Penetration", "double-penetration"),
    Genre("Doujin", "doujin"),
    Genre("Drama", "drama"),
    Genre("Drugs", "drugs"),
    Genre("Drunk", "drunk"),
    Genre("Ecchi", "ecchi"),
    Genre("Elf", "elf"),
    Genre("Emotionless Sex", "emotionless-sex"),
    Genre("Exhibitionism", "exhibitionism"),
    Genre("Eyepatch", "eyepatch"),
    Genre("Fantasy", "fantasy"),
    Genre("Females Only", "females-only"),
    Genre("Femdom", "femdom"),
    Genre("Filming", "filming"),
    Genre("Fingering", "fingering"),
    Genre("Footjob", "footjob"),
    Genre("Fuck Piercing", "fuck-piercing"),
    Genre("Full Color", "full-color"),
    Genre("Furry", "furry"),
    Genre("Futanari", "futanari"),
    Genre("Garter Belt", "garter-belt"),
    Genre("Gender Bender", "gender-bender"),
    Genre("Ghost", "ghost"),
    Genre("Glasses", "glasses"),
    Genre("Gloves", "gloves"),
    Genre("Gokkun", "gokkun"),
    Genre("Group", "group"),
    Genre("Growth", "growth"),
    Genre("Guro", "guro"),
    Genre("Gyaru", "gyaru"),
    Genre("Hairy", "hairy"),
    Genre("Handjob", "handjob"),
    Genre("Harem", "harem"),
    Genre("Hidden Sex", "hidden-sex"),
    Genre("Historical", "historical"),
    Genre("Horns", "horns"),
    Genre("Horror", "horror"),
    Genre("Huge Breast", "huge-breast"),
    Genre("Humiliation", "humiliation"),
    Genre("Impregnation", "impregnation"),
    Genre("Incest", "incest"),
    Genre("Inflation", "inflation"),
    Genre("Insect", "insect"),
    Genre("Inseki", "inseki"),
    Genre("Inverted Nipples", "inverted-nipples"),
    Genre("Invisible", "invisible"),
    Genre("Isekai", "isekai"),
    Genre("Josei", "josei"),
    Genre("Kemomimi", "kemomimi"),
    Genre("Kimono", "kimono"),
    Genre("Kissing", "kissing"),
    Genre("Kuudere", "kuudere"),
    Genre("Lactation", "lactation"),
    Genre("Leotard", "leotard"),
    Genre("Lingerie", "lingerie"),
    Genre("Loli", "loli"),
    Genre("Lolipai", "lolipai"),
    Genre("Long Strip", "long-strip"),
    Genre("Maid", "maid"),
    Genre("Males Only", "males-only"),
    Genre("Martial Arts", "martial-arts"),
    Genre("Massage", "massage"),
    Genre("Masturbation", "masturbation"),
    Genre("Mating Press", "mating-press"),
    Genre("Mature", "mature"),
    Genre("Miko", "miko"),
    Genre("MILF", "milf"),
    Genre("Mind Break", "mind-break"),
    Genre("Mind Control", "mind-control"),
    Genre("Monster", "monster"),
    Genre("Monster Girl", "monster-girl"),
    Genre("Monsters", "monsters"),
    Genre("Mother", "mother"),
    Genre("Multi-work Series", "multi-work-series"),
    Genre("Muscle", "muscle"),
    Genre("Mystery", "mystery"),
    Genre("Nakadashi", "nakadashi"),
    Genre("Netorare", "netorare"),
    Genre("Netorase", "netorase"),
    Genre("Netori", "netori"),
    Genre("Niece", "niece"),
    Genre("Nipple", "nipple"),
    Genre("Nipple Fuck", "nipple-fuck"),
    Genre("Nipples", "nipples"),
    Genre("No Penetration", "no-penetration"),
    Genre("Nurse", "nurse"),
    Genre("Old Man", "old-man"),
    Genre("Original", "original"),
    Genre("Osananajimi", "osananajimi"),
    Genre("Oyakodon", "oyakodon"),
    Genre("Paizuri", "paizuri"),
    Genre("Pantyhose", "pantyhose"),
    Genre("Piercing", "piercing"),
    Genre("Ponytail", "ponytail"),
    Genre("Possession", "possession"),
    Genre("Pregnant", "pregnant"),
    Genre("Prostitution", "prostitution"),
    Genre("Psychological", "psychological"),
    Genre("Pupils", "pupils"),
    Genre("Rape", "rape"),
    Genre("Regression", "regression"),
    Genre("Rimjob", "rimjob"),
    Genre("Romance", "romance"),
    Genre("Scat", "scat"),
    Genre("School Life", "school-life"),
    Genre("School Uniform", "school-uniform"),
    Genre("Sci-Fi", "sci-fi"),
    Genre("Seinen", "seinen"),
    Genre("Sex toys", "sex-toys"),
    Genre("Shemale", "shemale"),
    Genre("Shibari", "shibari"),
    Genre("Shota", "shota"),
    Genre("Shoujo", "shoujo"),
    Genre("Shounen", "shounen"),
    Genre("Sister", "sister"),
    Genre("Sleeping", "sleeping"),
    Genre("Slice of Life", "slice-of-life"),
    Genre("Slime", "slime"),
    Genre("Small Breast", "small-breast"),
    Genre("Small Penis", "small-penis"),
    Genre("Smell", "smell"),
    Genre("Smut", "smut"),
    Genre("Snuff", "snuff"),
    Genre("Sole Female", "sole-female"),
    Genre("Sole Male", "sole-male"),
    Genre("Sports", "sports"),
    Genre("Squirting", "squirting"),
    Genre("Stocking", "stocking"),
    Genre("Story Arc", "story-arc"),
    Genre("Sumata", "sumata"),
    Genre("Supernatural", "supernatural"),
    Genre("Sweating", "sweating"),
    Genre("Swimsuit", "swimsuit"),
    Genre("Swinging", "swinging"),
    Genre("Tail", "tail"),
    Genre("Tall girl", "tall-girl"),
    Genre("Tankoubon", "tankoubon"),
    Genre("Tanlines", "tanlines"),
    Genre("Teacher", "teacher"),
    Genre("Tentacles", "tentacles"),
    Genre("Threesome", "threesome"),
    Genre("Tomboy", "tomboy"),
    Genre("Tomgirl", "tomgirl"),
    Genre("Torture", "torture"),
    Genre("Tragedy", "tragedy"),
    Genre("Tsundere", "tsundere"),
    Genre("Twins", "twins"),
    Genre("Twintails", "twintails"),
    Genre("Ugly Bastard", "ugly-bastard"),
    Genre("Uncensored", "uncensored"),
    Genre("Unusual Pupils", "unusual-pupils"),
    Genre("Vanilla", "vanilla"),
    Genre("Virginity", "virginity"),
    Genre("Voyeurism", "voyeurism"),
    Genre("Widow", "widow"),
    Genre("Wings", "wings"),
    Genre("X-Ray", "x-ray"),
    Genre("Yandere", "yandere"),
    Genre("Yaoi", "yaoi"),
    Genre("Yuri", "yuri"),
)
