package eu.kanade.tachiyomi.extension.ko.agitoon

val platformsMap = mapOf(
    Pair(1, "네이버"),
    Pair(2, "다음"),
    Pair(3, "카카오"),
    Pair(4, "레진"),
    Pair(5, "투믹스"),
    Pair(6, "탑툰"),
    Pair(7, "코미카"),
    Pair(8, "배틀코믹"),
    Pair(9, "코믹GT"),
    Pair(10, "케이툰"),
    Pair(11, "애니툰"),
    Pair(12, "폭스툰"),
    Pair(13, "피너툰"),
    Pair(14, "봄툰"),
    Pair(15, "코미코"),
    Pair(16, "무툰"),
    Pair(17, "지존신마"),
    Pair(99, "기타"),
)

val tagsMap = mapOf(
    Pair(1, "학원"),
    Pair(2, "액션"),
    Pair(3, "SF"),
    Pair(4, "스토리"),
    Pair(5, "판타지"),
    Pair(6, "BL/백합"),
    Pair(7, "개그/코미디"),
    Pair(8, "연애/순정"),
    Pair(9, "드라마"),
    Pair(10, "로맨스"),
    Pair(11, "시대극"),
    Pair(12, "스포츠"),
    Pair(13, "일상"),
    Pair(14, "추리/미스터리"),
    Pair(15, "공포/스릴러"),
    Pair(16, "성인"),
    Pair(17, "옴니버스"),
    Pair(18, "에피소드"),
    Pair(19, "무협"),
    Pair(20, "소년"),
    Pair(99, "기타"),
)

val publishDayMap = mapOf(
    Pair(1, "월"),
    Pair(2, "화"),
    Pair(3, "수"),
    Pair(4, "목"),
    Pair(5, "금"),
    Pair(6, "토"),
    Pair(7, "일"),
    Pair(10, "열흘"),
)
