package eu.kanade.tachiyomi.extension.all.batoto

import eu.kanade.tachiyomi.source.SourceFactory

class BatoToFactory : SourceFactory {
    override fun createSources() = listOf(
        BatoTo("all", ""),
        BatoTo("en"),
        BatoTo("ar"),
        BatoTo("bg"),
        BatoTo("zh"),
        BatoTo("cs"),
        BatoTo("da"),
        BatoTo("nl"),
        BatoTo("fil"),
        BatoTo("fi"),
        BatoTo("fr"),
        BatoTo("de"),
        BatoTo("el"),
        BatoTo("he"),
        BatoTo("hi"),
        BatoTo("hu"),
        BatoTo("id"),
        BatoTo("it"),
        BatoTo("ja"),
        BatoTo("ko"),
        BatoTo("ms"),
        BatoTo("pl"),
        BatoTo("pt"),
        BatoTo("pt-BR", "pt_br"),
        BatoTo("ro"),
        BatoTo("ru"),
        BatoTo("es"),
        BatoTo("es-419", "es_419"),
        BatoTo("sv"),
        BatoTo("tr"),
        BatoTo("uk"),
        BatoTo("vi"),
        BatoTo("af"),
        BatoTo("sq"),
        BatoTo("am"),
        BatoTo("hy"),
        BatoTo("az"),
        BatoTo("be"),
        BatoTo("bn"),
        BatoTo("bs"),
        BatoTo("my"),
        BatoTo("km"),
        BatoTo("ca"),
        BatoTo("ceb"),
        BatoTo("zh-Hans", "zh_hk"),
        BatoTo("zh-Hant", "zh_tw"),
        BatoTo("hr"),
        BatoTo("et"),
        BatoTo("fo"),
        BatoTo("ka"),
        BatoTo("gn"),
        BatoTo("gu"),
        BatoTo("ht"),
        BatoTo("ha"),
        BatoTo("is"),
        BatoTo("ig"),
        BatoTo("ga"),
        BatoTo("jv"),
        BatoTo("kn"),
        BatoTo("kk"),
        BatoTo("ku"),
        BatoTo("ky"),
        BatoTo("lo"),
        BatoTo("lv"),
        BatoTo("lt"),
        BatoTo("lb"),
        BatoTo("mk"),
        BatoTo("mg"),
        BatoTo("ml"),
        BatoTo("mt"),
        BatoTo("mi"),
        BatoTo("mr"),
        BatoTo("mo"),
        BatoTo("mn"),
        BatoTo("ne"),
        BatoTo("no"),
        BatoTo("ny"),
        BatoTo("ps"),
        BatoTo("fa"),
        BatoTo("rm"),
        BatoTo("sm"),
        BatoTo("sr"),
        BatoTo("sh"),
        BatoTo("st"),
        BatoTo("sn"),
        BatoTo("sd"),
        BatoTo("si"),
        BatoTo("sk"),
        BatoTo("sl"),
        BatoTo("so"),
        BatoTo("sw"),
        BatoTo("tg"),
        BatoTo("ta"),
        BatoTo("te"),
        BatoTo("th"),
        BatoTo("ti"),
        BatoTo("to"),
        BatoTo("tk"),
        BatoTo("ur"),
        BatoTo("uz"),
        BatoTo("yo"),
        BatoTo("zu"),
        BatoTo("other", "_t"),
    )
}
