package keiyoushi.gradle.tasks

import keiyoushi.gradle.extensions.DeeplinkFilter
import org.gradle.api.DefaultTask
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.ListProperty
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction

@CacheableTask
abstract class GenerateExtensionManifestTask : DefaultTask() {
    @get:Input
    abstract val filters: ListProperty<DeeplinkFilter>

    @get:OutputFile
    abstract val outputFile: RegularFileProperty

    @TaskAction
    fun generate() {
        val filterList = filters.get()
        val out = outputFile.get().asFile
        out.parentFile.mkdirs()

        if (filterList.isEmpty()) {
            out.writeText(
                """<?xml version="1.0" encoding="utf-8"?>
                |<manifest xmlns:android="http://schemas.android.com/apk/res/android" />
                |
                """.trimMargin(),
            )
            return
        }

        val intentFilters = filterList.joinToString("\n") { f ->
            buildString {
                appendLine("            <intent-filter>")
                appendLine("                <action android:name=\"android.intent.action.VIEW\" />")
                appendLine("                <category android:name=\"android.intent.category.DEFAULT\" />")
                appendLine("                <category android:name=\"android.intent.category.BROWSABLE\" />")
                appendLine("                <data android:scheme=\"https\" />")
                appendLine("                <data android:scheme=\"http\" />")
                f.hosts.forEach {
                    appendLine("                <data android:host=\"$it\" />")
                }
                f.pathPatterns.forEach {
                    appendLine("                <data android:pathPattern=\"$it\" />")
                }
                append("            </intent-filter>")
            }
        }

        out.writeText(
            """
            |<?xml version="1.0" encoding="utf-8"?>
            |<!-- Generated by kei.plugins.extension — do not edit by hand. -->
            |<manifest xmlns:android="http://schemas.android.com/apk/res/android">
            |    <application>
            |        <activity
            |            android:name="keiyoushi.source.UrlActivity"
            |            android:excludeFromRecents="true"
            |            android:exported="true"
            |            android:theme="@android:style/Theme.NoDisplay">
            |$intentFilters
            |        </activity>
            |    </application>
            |</manifest>
            |
            """.trimMargin(),
        )
    }
}
