package keiyoushi.gradle.tasks

import ContentWarning
import keiyoushi.gradle.extensions.DeeplinkFilter
import org.gradle.api.DefaultTask
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.ListProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction

@CacheableTask
abstract class GenerateExtensionManifestTask : DefaultTask() {
    @get:Input
    abstract val filters: ListProperty<DeeplinkFilter>

    @get:Input
    abstract val extensionName: Property<String>

    @get:Input
    abstract val contentWarning: Property<ContentWarning>

    @get:Input
    abstract val extensionLib: Property<String>

    @get:OutputFile
    abstract val outputFile: RegularFileProperty

    @TaskAction
    fun generate() {
        val filterList = filters.get()
        val name = extensionName.get().escapeXml()
        val cls = "ExtensionGenerated"
        val lib = extensionLib.get()
        val cw = contentWarning.get()
        val nsfw = if (cw == ContentWarning.SAFE) "0" else "1"
        val cwValue = when (cw) {
            ContentWarning.SAFE -> "0"
            ContentWarning.MIXED -> "1"
            ContentWarning.NSFW -> "2"
        }
        val out = outputFile.get().asFile
        out.parentFile.mkdirs()

        val intentFilters = filterList.joinToString("\n") { f ->
            buildString {
                appendLine("            <intent-filter>")
                appendLine("                <action android:name=\"android.intent.action.VIEW\" />")
                appendLine("                <category android:name=\"android.intent.category.DEFAULT\" />")
                appendLine("                <category android:name=\"android.intent.category.BROWSABLE\" />")
                appendLine("                <data android:scheme=\"https\" />")
                appendLine("                <data android:scheme=\"http\" />")
                f.hosts.forEach { appendLine("                <data android:host=\"$it\" />") }
                f.pathPatterns.forEach { appendLine("                <data android:pathPattern=\"$it\" />") }
                append("            </intent-filter>")
            }
        }

        val activitySection = if (filterList.isEmpty()) {
            ""
        } else {
            buildString {
                appendLine()
                appendLine("        <activity")
                appendLine("            android:name=\"keiyoushi.source.UrlActivity\"")
                appendLine("            android:excludeFromRecents=\"true\"")
                appendLine("            android:exported=\"true\"")
                appendLine("            android:theme=\"@android:style/Theme.NoDisplay\">")
                appendLine(intentFilters)
                append("        </activity>")
            }
        }

        out.writeText(
            """
            |<?xml version="1.0" encoding="utf-8"?>
            |<!-- Generated by kei.plugins.extension — do not edit by hand. -->
            |<manifest xmlns:android="http://schemas.android.com/apk/res/android">
            |    <uses-feature android:name="tachiyomi.extension" />
            |    <application
            |        android:allowBackup="false"
            |        android:icon="@mipmap/ic_launcher"
            |        android:label="Tachiyomi: $name">
            |        <meta-data android:name="tachiyomix.name" android:value="$name" />
            |        <meta-data android:name="tachiyomi.extension.class" android:value=".$cls" />
            |        <meta-data android:name="tachiyomi.extension.nsfw" android:value="$nsfw" />
            |        <meta-data android:name="tachiyomix.contentWarning" android:value="$cwValue" />
            |        <meta-data android:name="tachiyomix.extensionLib" android:value="$lib" />$activitySection
            |    </application>
            |</manifest>
            |
            """.trimMargin(),
        )
    }
}

private fun String.escapeXml() = replace("&", "&amp;").replace("<", "&lt;").replace("\"", "&quot;")
