package eu.kanade.tachiyomi.extension.all.mangapark

import eu.kanade.tachiyomi.source.SourceFactory

class MangaParkFactory : SourceFactory {
    override fun createSources() = listOf(
        MangaPark("af"),
        MangaPark("sq"),
        MangaPark("am"),
        MangaPark("ar"),
        MangaPark("hy"),
        MangaPark("az"),
        MangaPark("be"),
        MangaPark("bn"),
        MangaPark("bs"),
        MangaPark("bg"),
        MangaPark("my"),
        MangaPark("km"),
        MangaPark("ca"),
        MangaPark("ceb"),
        MangaPark("zh"),
        MangaPark("zh-Hans", "zh_hk"),
        MangaPark("zh-Hant", "zh_tw"),
        MangaPark("hr"),
        MangaPark("cs"),
        MangaPark("da"),
        MangaPark("nl"),
        MangaPark("en"),
        MangaPark("eo"),
        MangaPark("et"),
        MangaPark("fo"),
        MangaPark("fil"),
        MangaPark("fi"),
        MangaPark("fr"),
        MangaPark("ka"),
        MangaPark("de"),
        MangaPark("el"),
        MangaPark("gn"),
        MangaPark("ht"),
        MangaPark("ha"),
        MangaPark("he"),
        MangaPark("hi"),
        MangaPark("hu"),
        MangaPark("is"),
        MangaPark("ig"),
        MangaPark("id"),
        MangaPark("ga"),
        MangaPark("it"),
        MangaPark("ja"),
        MangaPark("jv"),
        MangaPark("kk"),
        MangaPark("ko"),
        MangaPark("ku"),
        MangaPark("ky"),
        MangaPark("lo"),
        MangaPark("lv"),
        MangaPark("lt"),
        MangaPark("lb"),
        MangaPark("mk"),
        MangaPark("mg"),
        MangaPark("ms"),
        MangaPark("ml"),
        MangaPark("mt"),
        MangaPark("mi"),
        MangaPark("mo"),
        MangaPark("mn"),
        MangaPark("ne"),
        MangaPark("no"),
        MangaPark("ny"),
        MangaPark("ps"),
        MangaPark("fa"),
        MangaPark("pl"),
        MangaPark("pt"),
        MangaPark("pt-BR", "pt_br"),
        MangaPark("ro"),
        MangaPark("rm"),
        MangaPark("ru"),
        MangaPark("sm"),
        MangaPark("sr"),
        MangaPark("sh"),
        MangaPark("st"),
        MangaPark("sn"),
        MangaPark("sd"),
        MangaPark("si"),
        MangaPark("sk"),
        MangaPark("sl"),
        MangaPark("so"),
        MangaPark("es"),
        MangaPark("es-419", "es_419"),
        MangaPark("sw"),
        MangaPark("sv"),
        MangaPark("tg"),
        MangaPark("ta"),
        MangaPark("th"),
        MangaPark("ti"),
        MangaPark("to"),
        MangaPark("tr"),
        MangaPark("tk"),
        MangaPark("uk"),
        MangaPark("ur"),
        MangaPark("uz"),
        MangaPark("vi"),
        MangaPark("yo"),
        MangaPark("zu"),
        MangaPark("other", "_t"),
    )
}
