package eu.kanade.tachiyomi.extension.en.divascans

import eu.kanade.tachiyomi.source.model.Filter

// --- Single Select Filters ---

abstract class SelectFilter(
    name: String,
    private val options: Array<Pair<String, String>>,
    defaultValue: String = "",
) : Filter.Select<String>(
    name,
    options.map { it.first }.toTypedArray(),
    options.indexOfFirst { it.second == defaultValue }.takeIf { it != -1 } ?: 0,
) {
    val selected: String
        get() = options[state].second
}

class SortFilter :
    SelectFilter(
        "Sort By",
        arrayOf(
            Pair("Latest", ""),
            Pair("Popular", "popular"),
            Pair("Most Viewed", "views"),
            Pair("Longest", "longest"),
            Pair("Trending", "trending"),
            Pair("Top Rated", "rating"),
            Pair("Newest", "newest"),
        ),
        "",
    )

class StatusFilter :
    SelectFilter(
        "Status",
        arrayOf(
            Pair("All", ""),
            Pair("Ongoing", "Ongoing"),
            Pair("Completed", "Completed"),
            Pair("Hiatus", "Hiatus"),
            Pair("Dropped", "Dropped"),
            Pair("Discontinued", "Discontinued"),
            Pair("Upcoming", "Upcoming"),
        ),
    )

class OriginFilter :
    SelectFilter(
        "Language / Origin",
        arrayOf(
            Pair("All", ""),
            Pair("Korean", "KOREAN"),
            Pair("Japanese", "JAPANESE"),
            Pair("Chinese", "CHINESE"),
            Pair("Other", "OTHER"),
        ),
    )

// --- Multi-Select Filters ---

open class CheckBoxFilter(name: String, val value: String) : Filter.CheckBox(name)

class GenreCheckBox(name: String, value: String) : CheckBoxFilter(name, value)
class GenreFilter :
    Filter.Group<GenreCheckBox>(
        "Genres",
        listOf(
            GenreCheckBox("Action", "action"),
            GenreCheckBox("Adult", "adult"),
            GenreCheckBox("Adventure", "adventure"),
            GenreCheckBox("Campus", "campus"),
            GenreCheckBox("Comedy", "comedy"),
            GenreCheckBox("Drama", "drama"),
            GenreCheckBox("Ecchi", "ecchi"),
            GenreCheckBox("Fantasy", "fantasy"),
            GenreCheckBox("GameLit", "gamelit"),
            GenreCheckBox("Gender Bender", "gender-bender"),
            GenreCheckBox("Harem", "harem"),
            GenreCheckBox("Historical", "historical"),
            GenreCheckBox("Horror", "horror"),
            GenreCheckBox("Isekai", "isekai"),
            GenreCheckBox("Josei", "josei"),
            GenreCheckBox("LitRPG", "litrpg"),
            GenreCheckBox("Martial Arts", "martial-arts"),
            GenreCheckBox("Mature", "mature"),
            GenreCheckBox("Mecha", "mecha"),
            GenreCheckBox("Melodrama", "melodrama"),
            GenreCheckBox("Military", "military"),
            GenreCheckBox("Mystery", "mystery"),
            GenreCheckBox("Political Intrigue", "political-intrigue"),
            GenreCheckBox("Psychological", "psychological"),
            GenreCheckBox("Romance", "romance"),
            GenreCheckBox("Romance Fantasy", "romance-fantasy"),
            GenreCheckBox("School Life", "school-life"),
            GenreCheckBox("Sci-Fi", "sci-fi"),
            GenreCheckBox("Seinen", "seinen"),
            GenreCheckBox("Shoujo", "shoujo"),
            GenreCheckBox("Shoujo Ai", "shoujo-ai"),
            GenreCheckBox("Shounen", "shounen"),
            GenreCheckBox("Shounen Ai", "shounen-ai"),
            GenreCheckBox("Slice of Life", "slice-of-life"),
            GenreCheckBox("Smut", "smut"),
            GenreCheckBox("Sports", "sports"),
            GenreCheckBox("Supernatural", "supernatural"),
            GenreCheckBox("Thriller", "thriller"),
            GenreCheckBox("Tragedy", "tragedy"),
            GenreCheckBox("Virtual Reality", "virtual-reality"),
            GenreCheckBox("Wuxia", "wuxia"),
            GenreCheckBox("Xianxia", "xianxia"),
            GenreCheckBox("Xuanhuan", "xuanhuan"),
            GenreCheckBox("Yaoi", "yaoi"),
            GenreCheckBox("Yuri", "yuri"),
        ),
    )

class TagCheckBox(name: String, value: String) : CheckBoxFilter(name, value)
class TagFilter :
    Filter.Group<TagCheckBox>(
        "Tags",
        listOf(
            TagCheckBox("Abandoned Children", "abandoned-children"),
            TagCheckBox("Ability Steal", "ability-steal"),
            TagCheckBox("Absent Parents", "absent-parents"),
            TagCheckBox("Abusive Characters", "abusive-characters"),
            TagCheckBox("Academy", "academy"),
            TagCheckBox("Accelerated Growth", "accelerated-growth"),
            TagCheckBox("Acting", "acting"),
            TagCheckBox("Action", "action"),
            TagCheckBox("Adapted from Manga", "adapted-from-manga"),
            TagCheckBox("Adapted from Manhua", "adapted-from-manhua"),
            TagCheckBox("Adapted to Anime", "adapted-to-anime"),
            TagCheckBox("Adopted Children", "adopted-children"),
            TagCheckBox("Adopted Protagonist", "adopted-protagonist"),
            TagCheckBox("Adult", "adult"),
            TagCheckBox("Adventure", "adventure"),
            TagCheckBox("Age Gap", "age-gap"),
            TagCheckBox("Age Progression", "age-progression"),
            TagCheckBox("Age Regression", "age-regression"),
            TagCheckBox("Aggressive Characters", "aggressive-characters"),
            TagCheckBox("Alchemy", "alchemy"),
            TagCheckBox("Aliens", "aliens"),
            TagCheckBox("All-Girls School", "all-girls-school"),
            TagCheckBox("Alternate World", "alternate-world"),
            TagCheckBox("Amnesia", "amnesia"),
            TagCheckBox("Ancient China", "ancient-china"),
            TagCheckBox("Angels", "angels"),
            TagCheckBox("Animal Characteristics", "animal-characteristics"),
            TagCheckBox("Antagonist Protagonist", "antagonist-protagonist"),
            TagCheckBox("Antihero Protagonist", "antihero-protagonist"),
            TagCheckBox("Apocalypse", "apocalypse"),
            TagCheckBox("Appearance Changes", "appearance-changes"),
            TagCheckBox("Aristocracy", "aristocracy"),
            TagCheckBox("Army", "army"),
            TagCheckBox("Arranged Marriage", "arranged-marriage"),
            TagCheckBox("Arrogant Characters", "arrogant-characters"),
            TagCheckBox("Artifact", "artifact"),
            TagCheckBox("Artificial Intelligence", "artificial-intelligence"),
            TagCheckBox("Assassins", "assassins"),
            TagCheckBox("Beast Companions", "beast-companions"),
            TagCheckBox("Beast Taming", "beast-taming"),
            TagCheckBox("Beastkin", "beastkin"),
            TagCheckBox("Beautiful Female Lead", "beautiful-female-lead"),
            TagCheckBox("Betrayal", "betrayal"),
            TagCheckBox("Black Belly", "black-belly"),
            TagCheckBox("Body Swap", "body-swap"),
            TagCheckBox("Bodyguards", "bodyguards"),
            TagCheckBox("Brainwashing", "brainwashing"),
            TagCheckBox("Brother Complex", "brother-complex"),
            TagCheckBox("Bullying", "bullying"),
            TagCheckBox("Business Management", "business-management"),
            TagCheckBox("Calm Protagonist", "calm-protagonist"),
            TagCheckBox("Cannibalism", "cannibalism"),
            TagCheckBox("Celebrities", "celebrities"),
            TagCheckBox("Character Growth", "character-growth"),
            TagCheckBox("Cheat", "cheat"),
            TagCheckBox("Child Protagonist", "child-protagonist"),
            TagCheckBox("Childhood Friends", "childhood-friends"),
            TagCheckBox("Cold Protagonist", "cold-protagonist"),
            TagCheckBox("Comedy", "comedy"),
            TagCheckBox("Coming of Age", "coming-of-age"),
            TagCheckBox("Contract Relationship", "contract-relationship"),
            TagCheckBox("Cooking", "cooking"),
            TagCheckBox("Corruption", "corruption"),
            TagCheckBox("Cunning Protagonist", "cunning-protagonist"),
            TagCheckBox("Cute Story", "cute-story"),
            TagCheckBox("Death", "death"),
            TagCheckBox("Demi-Humans", "demi-humans"),
            TagCheckBox("Demon King", "demon-king"),
            TagCheckBox("Demons", "demons"),
            TagCheckBox("Detective", "detective"),
            TagCheckBox("Devil", "devil"),
            TagCheckBox("Different Social Status", "different-social-status"),
            TagCheckBox("Disabilities", "disabilities"),
            TagCheckBox("Doctors", "doctors"),
            TagCheckBox("Doting Love Interests", "doting-love-interests"),
            TagCheckBox("Dragons", "dragons"),
            TagCheckBox("Dungeon", "dungeon"),
            TagCheckBox("Dungeons", "dungeons"),
            TagCheckBox("Elf", "elf"),
            TagCheckBox("Emotionally Weak", "emotionally-weak"),
            TagCheckBox("Empire", "empire"),
            TagCheckBox("European Ambience", "european-ambience"),
            TagCheckBox("Evil Gods", "evil-gods"),
            TagCheckBox("Evil Organizations", "evil-organizations"),
            TagCheckBox("Evil Religions", "evil-religions"),
            TagCheckBox("Exorcism", "exorcism"),
            TagCheckBox("Familiars", "familiars"),
            TagCheckBox("Family Business", "family-business"),
            TagCheckBox("Famous Parents", "famous-parents"),
            TagCheckBox("Famous Protagonist", "famous-protagonist"),
            TagCheckBox("Fanaticism", "fanaticism"),
            TagCheckBox("Fantasy", "fantasy"),
            TagCheckBox("Farmers", "farmers"),
            TagCheckBox("Fast Cultivation", "fast-cultivation"),
            TagCheckBox("Fast Learner", "fast-learner"),
            TagCheckBox("Female Protagonist", "female-protagonist"),
            TagCheckBox("Fetish", "fetish"),
            TagCheckBox("First Love", "first-love"),
            TagCheckBox("Fish out of Water", "fish-out-of-water"),
            TagCheckBox("Forced Living Arrangements", "forced-living-arrangements"),
            TagCheckBox("Forced Marriage", "forced-marriage"),
            TagCheckBox("Fox Spirits", "fox-spirits"),
            TagCheckBox("Friends Become Enemies", "friends-become-enemies"),
            TagCheckBox("Friendship", "friendship"),
            TagCheckBox("Futuristic", "futuristic"),
            TagCheckBox("Game Elements", "game-elements"),
            TagCheckBox("Gamers", "gamers"),
            TagCheckBox("Gangsters", "gangsters"),
            TagCheckBox("Gender Bender", "gender-bender"),
            TagCheckBox("Ghosts", "ghosts"),
            TagCheckBox("Gods", "gods"),
            TagCheckBox("Gore", "gore"),
            TagCheckBox("Harem", "harem"),
            TagCheckBox("Handsome Male Lead", "handsome-male-lead"),
            TagCheckBox("Hard-Working Protagonist", "hard-working-protagonist"),
            TagCheckBox("Harsh Training", "harsh-training"),
            TagCheckBox("Heavenly Tribulation", "heavenly-tribulation"),
            TagCheckBox("Hiding True Abilities", "hiding-true-abilities"),
            TagCheckBox("Historical", "historical"),
            TagCheckBox("Horror", "horror"),
            TagCheckBox("Hospitals", "hospitals"),
            TagCheckBox("Human Experimentation", "human-experimentation"),
            TagCheckBox("Humanoid Protagonist", "humanoid-protagonist"),
            TagCheckBox("Hunters", "hunters"),
            TagCheckBox("Idol", "idol"),
            TagCheckBox("Immortals", "immortals"),
            TagCheckBox("Incest", "incest"),
            TagCheckBox("Insects", "insects"),
            TagCheckBox("Isekai", "isekai"),
            TagCheckBox("Japanese Foreigner", "japanese-foreigner"),
            TagCheckBox("Josei", "josei"),
            TagCheckBox("Kidnapping", "kidnapping"),
            TagCheckBox("Knights", "knights"),
            TagCheckBox("Leadership", "leadership"),
            TagCheckBox("LGBT", "lgbt"),
            TagCheckBox("Litrpg", "litrpg"),
            TagCheckBox("Live-in Lover", "live-in-lover"),
            TagCheckBox("Love Triangle", "love-triangle"),
            TagCheckBox("Lovers", "lovers"),
            TagCheckBox("Magic", "magic"),
            TagCheckBox("Magical Space", "magical-space"),
            TagCheckBox("Male Protagonist", "male-protagonist"),
            TagCheckBox("Management", "management"),
            TagCheckBox("Manhua", "manhua"),
            TagCheckBox("Manhwa", "manhwa"),
            TagCheckBox("Martial Arts", "martial-arts"),
            TagCheckBox("Mature", "mature"),
            TagCheckBox("Mecha", "mecha"),
            TagCheckBox("Medical Knowledge", "medical-knowledge"),
            TagCheckBox("Military", "military"),
            TagCheckBox("Misunderstandings", "misunderstandings"),
            TagCheckBox("Modern", "modern"),
            TagCheckBox("Modern Knowledge", "modern-knowledge"),
            TagCheckBox("Monsters", "monsters"),
            TagCheckBox("Multiple Identities", "multiple-identities"),
            TagCheckBox("Multiple Transported Individuals", "multiple-transported-individuals"),
            TagCheckBox("Murder", "murder"),
            TagCheckBox("Music", "music"),
            TagCheckBox("Mystery", "mystery"),
            TagCheckBox("Ninjas", "ninjas"),
            TagCheckBox("Nudity", "nudity"),
            TagCheckBox("Office Workers", "office-workers"),
            TagCheckBox("Older Love Interests", "older-love-interests"),
            TagCheckBox("Omegaverse", "omegaverse"),
            TagCheckBox("One Piece", "one-piece"),
            TagCheckBox("Opposites Attract", "opposites-attract"),
            TagCheckBox("Oracles", "oracles"),
            TagCheckBox("Otaku", "otaku"),
            TagCheckBox("Overpowered Protagonist", "overpowered-protagonist"),
            TagCheckBox("Ownership", "ownership"),
            TagCheckBox("Panty Fetish", "panty-fetish"),
            TagCheckBox("Parallel Universe", "parallel-universe"),
            TagCheckBox("Parody", "parody"),
            TagCheckBox("Past Trauma", "past-trauma"),
            TagCheckBox("Persistent Love Interests", "persistent-love-interests"),
            TagCheckBox("Pets", "pets"),
            TagCheckBox("Philosophical", "philosophical"),
            TagCheckBox("Photography", "photography"),
            TagCheckBox("Pill Concocting", "pill-concocting"),
            TagCheckBox("Pill Refining", "pill-refining"),
            TagCheckBox("Pirates", "pirates"),
            TagCheckBox("Playful Love Interests", "playful-love-interests"),
            TagCheckBox("Police", "police"),
            TagCheckBox("Political Intrigue", "political-intrigue"),
            TagCheckBox("Polygamy", "polygamy"),
            TagCheckBox("Possession", "possession"),
            TagCheckBox("Post-Apocalyptic", "post-apocalyptic"),
            TagCheckBox("Pregnancy", "pregnancy"),
            TagCheckBox("Priestesses", "priestesses"),
            TagCheckBox("Prison", "prison"),
            TagCheckBox("Prostitutes", "prostitutes"),
            TagCheckBox("Psychic Powers", "psychic-powers"),
            TagCheckBox("Psychological", "psychological"),
            TagCheckBox("Qi Cultivation", "qi-cultivation"),
            TagCheckBox("Quiet Characters", "quiet-characters"),
            TagCheckBox("R-18", "r-18"),
            TagCheckBox("R-15", "r-15"),
            TagCheckBox("Race Change", "race-change"),
            TagCheckBox("Racism", "racism"),
            TagCheckBox("Rape", "rape"),
            TagCheckBox("Rebellion", "rebellion"),
            TagCheckBox("Rebirth", "rebirth"),
            TagCheckBox("Reincarnated as a Monster", "reincarnated-as-a-monster"),
            TagCheckBox("Reincarnation", "reincarnation"),
            TagCheckBox("Revenge", "revenge"),
            TagCheckBox("Reverse Harem", "reverse-harem"),
            TagCheckBox("Rich to Poor", "rich-to-poor"),
            TagCheckBox("Royalty", "royalty"),
            TagCheckBox("Ruthless Protagonist", "ruthless-protagonist"),
            TagCheckBox("Sadistic Characters", "sadistic-characters"),
            TagCheckBox("Saints", "saints"),
            TagCheckBox("Samurai", "samurai"),
            TagCheckBox("School Life", "school-life"),
            TagCheckBox("Sci-Fi", "sci-fi"),
            TagCheckBox("Seinen", "seinen"),
            TagCheckBox("Shoujo", "shoujo"),
            TagCheckBox("Shounen", "shounen"),
            TagCheckBox("Showbiz", "showbiz"),
            TagCheckBox("Sibling Rivalry", "sibling-rivalry"),
            TagCheckBox("Siblings", "siblings"),
            TagCheckBox("Slave Harem", "slave-harem"),
            TagCheckBox("Slaves", "slaves"),
            TagCheckBox("Slice of Life", "slice-of-life"),
            TagCheckBox("Slow Romance", "slow-romance"),
            TagCheckBox("Smart Couple", "smart-couple"),
            TagCheckBox("Smut", "smut"),
            TagCheckBox("Soldiers", "soldiers"),
            TagCheckBox("Spirit Advisor", "spirit-advisor"),
            TagCheckBox("Sports", "sports"),
            TagCheckBox("Succubus", "succubus"),
            TagCheckBox("Sudden Strength Gain", "sudden-strength-gain"),
            TagCheckBox("Supernatural", "supernatural"),
            TagCheckBox("Sword Wielder", "sword-wielder"),
            TagCheckBox("System", "system"),
            TagCheckBox("Teachers", "teachers"),
            TagCheckBox("Time Travel", "time-travel"),
            TagCheckBox("Transmigration", "transmigration"),
            TagCheckBox("Tsundere", "tsundere"),
            TagCheckBox("Twins", "twins"),
            TagCheckBox("Unique Cultivation Technique", "unique-cultivation-technique"),
            TagCheckBox("Vampires", "vampires"),
            TagCheckBox("Villainess", "villainess"),
            TagCheckBox("Virtual Reality", "virtual-reality"),
            TagCheckBox("War", "war"),
            TagCheckBox("Weak to Strong", "weak-to-strong"),
            TagCheckBox("Werebeasts", "werebeasts"),
            TagCheckBox("Witches", "witches"),
            TagCheckBox("World Hopping", "world-hopping"),
            TagCheckBox("Wuxia", "wuxia"),
            TagCheckBox("Xianxia", "xianxia"),
            TagCheckBox("Xuanhuan", "xuanhuan"),
            TagCheckBox("Yandere", "yandere"),
            TagCheckBox("Yaoi", "yaoi"),
            TagCheckBox("Yuri", "yuri"),
            TagCheckBox("Zombies", "zombies"),
        ),
    )
