package eu.kanade.tachiyomi.extension.vi.damconuong

import eu.kanade.tachiyomi.source.model.Filter
import eu.kanade.tachiyomi.source.model.FilterList

fun getFilters(): FilterList = FilterList(
    SortFilter(),
    StatusFilter(),
    SearchTypeFilter(),
    GenreFilter(getGenreList()),
)

class SortFilter :
    UriPartFilter(
        "Sắp xếp",
        arrayOf(
            Pair("Mới cập nhật", "-updated_at"),
            Pair("Mới nhất", "-created_at"),
            Pair("Cũ nhất", "created_at"),
            Pair("Xem nhiều", "-views"),
            Pair("Top ngày", "-views_day"),
            Pair("Top tuần", "-views_week"),
            Pair("A-Z", "name"),
            Pair("Z-A", "-name"),
        ),
    )

class StatusFilter :
    UriPartFilter(
        "Trạng thái",
        arrayOf(
            Pair("Đang tiến hành + Hoàn thành", "2,1"),
            Pair("Đang tiến hành", "2"),
            Pair("Hoàn thành", "1"),
        ),
    )

class SearchTypeFilter :
    UriPartFilter(
        "Tìm theo",
        arrayOf(
            Pair("Tên truyện", "name"),
            Pair("Tác giả", "artist"),
            Pair("Doujinshi", "doujinshi"),
        ),
    )

class Genre(name: String, val id: String) : Filter.CheckBox(name)

class GenreFilter(genres: List<Genre>) : Filter.Group<Genre>("Thể loại", genres)

open class UriPartFilter(
    displayName: String,
    private val vals: Array<Pair<String, String>>,
) : Filter.Select<String>(displayName, vals.map { it.first }.toTypedArray()) {
    fun toUriPart() = vals[state].second
}

private fun getGenreList(): List<Genre> = listOf(
    Genre("3D Hentai", "1"),
    Genre("Animal girl", "10"),
    Genre("Manhua", "100"),
    Genre("Manhwa", "101"),
    Genre("Masturbation", "102"),
    Genre("Mature", "103"),
    Genre("Miko", "104"),
    Genre("Milf", "105"),
    Genre("Mind Break", "106"),
    Genre("Mind Control", "107"),
    Genre("Mizugi", "108"),
    Genre("Monster", "109"),
    Genre("Áo Dài", "11"),
    Genre("Monstergirl", "110"),
    Genre("Mother", "111"),
    Genre("Nakadashi", "112"),
    Genre("Netori", "113"),
    Genre("Non-hen", "114"),
    Genre("NTR", "115"),
    Genre("Nun", "116"),
    Genre("Nurse", "117"),
    Genre("Old Man", "118"),
    Genre("Oneshot", "119"),
    Genre("Apron", "12"),
    Genre("Oral", "120"),
    Genre("Osananajimi", "121"),
    Genre("Paizuri", "122"),
    Genre("Pantyhose", "123"),
    Genre("Ponytail", "124"),
    Genre("Armpit", "1241"),
    Genre("Invisible", "1242"),
    Genre("18+", "1249"),
    Genre("Pregnant", "125"),
    Genre("Echi", "1250"),
    Genre("Hài hước", "1251"),
    Genre("Hentai", "1252"),
    Genre("Hiện đại", "1253"),
    Genre("Lãng Mạn", "1254"),
    Genre("Romanc", "1255"),
    Genre("Con gái", "1256"),
    Genre("19+", "1257"),
    Genre("3P", "1258"),
    Genre("Công Sở", "1259"),
    Genre("Rape", "126"),
    Genre("SM/BDSM/SUB-DOM", "1260"),
    Genre("Ngôn Tình", "1261"),
    Genre("Tình Cảm", "1262"),
    Genre("Đã full", "1263"),
    Genre("Riêng tư", "1264"),
    Genre("Truyện chữ", "1265"),
    Genre("không NTR", "1266"),
    Genre("MANGA", "1267"),
    Genre("One shot", "1268"),
    Genre("Truyện tranh 18+", "1269"),
    Genre("Rimjob", "127"),
    Genre("Truyện Màu", "1270"),
    Genre("16+", "1271"),
    Genre("Smut", "1272"),
    Genre("Vếu to", "1273"),
    Genre("Romance", "128"),
    Genre("Ryona", "129"),
    Genre("Artist CG", "13"),
    Genre("Scat", "130"),
    Genre("School Uniform", "131"),
    Genre("SchoolGirl", "132"),
    Genre("Series", "133"),
    Genre("Sex Toys", "134"),
    Genre("Shimapan", "135"),
    Genre("Short Hentai", "136"),
    Genre("Shota", "137"),
    Genre("Shoujo", "138"),
    Genre("Siscon", "139"),
    Genre("Based Game", "14"),
    Genre("Sister", "140"),
    Genre("Slave", "141"),
    Genre("Sleeping", "142"),
    Genre("Small Boobs", "143"),
    Genre("Son", "144"),
    Genre("Sports", "145"),
    Genre("Stockings", "146"),
    Genre("Supernatural", "147"),
    Genre("Sweating", "148"),
    Genre("Swimsuit", "149"),
    Genre("BBM", "15"),
    Genre("Tall Girl", "150"),
    Genre("Teacher", "151"),
    Genre("Tentacles", "152"),
    Genre("Time Stop", "153"),
    Genre("Tomboy", "154"),
    Genre("Tracksuit", "155"),
    Genre("Transformation", "156"),
    Genre("Trap", "157"),
    Genre("Truyện Việt", "158"),
    Genre("Tsundere", "159"),
    Genre("BBW", "16"),
    Genre("Twins", "160"),
    Genre("Twintails", "161"),
    Genre("Vampire", "162"),
    Genre("Vanilla", "163"),
    Genre("Virgin", "164"),
    Genre("Webtoon", "165"),
    Genre("X-ray", "166"),
    Genre("Yandere", "167"),
    Genre("Yaoi", "168"),
    Genre("Yuri", "169"),
    Genre("BDSM", "17"),
    Genre("Zombie", "170"),
    Genre("Bestiality", "18"),
    Genre("Big Ass", "19"),
    Genre("Action", "2"),
    Genre("Big Boobs", "20"),
    Genre("Big Penis", "21"),
    Genre("Blackmail", "22"),
    Genre("Bloomers", "23"),
    Genre("BlowJobs", "24"),
    Genre("Body Swap", "25"),
    Genre("Bodysuit", "26"),
    Genre("Bondage", "27"),
    Genre("Breast Sucking", "28"),
    Genre("BreastJobs", "29"),
    Genre("Adult", "3"),
    Genre("Brocon", "30"),
    Genre("Brother", "31"),
    Genre("Business Suit", "32"),
    Genre("Catgirls", "33"),
    Genre("Che ít", "34"),
    Genre("Che nhiều", "35"),
    Genre("Cheating", "36"),
    Genre("Chikan", "37"),
    Genre("Chinese Dress", "38"),
    Genre("Có che", "39"),
    Genre("Adventure", "4"),
    Genre("Comedy", "40"),
    Genre("Prostitution", "405"),
    Genre("Kissing", "406"),
    Genre("Comic", "41"),
    Genre("Condom", "42"),
    Genre("Cosplay", "43"),
    Genre("Cousin", "44"),
    Genre("Crotch Tattoo", "45"),
    Genre("Cunnilingus", "46"),
    Genre("Dark Skin", "47"),
    Genre("Daughter", "48"),
    Genre("Deepthroat", "49"),
    Genre("Ahegao", "5"),
    Genre("Demon", "50"),
    Genre("DemonGirl", "51"),
    Genre("Devil", "52"),
    Genre("DevilGirl", "53"),
    Genre("Dirty", "54"),
    Genre("Dirty Old Man", "55"),
    Genre("DogGirl", "56"),
    Genre("Double Penetration", "57"),
    Genre("Doujinshi", "58"),
    Genre("Drama", "59"),
    Genre("Anal", "6"),
    Genre("Drug", "60"),
    Genre("Ecchi", "61"),
    Genre("Elder Sister", "62"),
    Genre("Elf", "63"),
    Genre("Exhibitionism", "64"),
    Genre("Fantasy", "65"),
    Genre("Father", "66"),
    Genre("Femdom", "67"),
    Genre("Fingering", "68"),
    Genre("Footjob", "69"),
    Genre("Angel", "7"),
    Genre("Foxgirls", "70"),
    Genre("Full Color", "71"),
    Genre("Furry", "72"),
    Genre("Futanari", "73"),
    Genre("GangBang", "74"),
    Genre("Garter Belts", "75"),
    Genre("Gender Bender", "76"),
    Genre("Ghost", "77"),
    Genre("Glasses", "78"),
    Genre("Gothic Lolita", "79"),
    Genre("Ảnh động", "8"),
    Genre("Group", "80"),
    Genre("Guro", "81"),
    Genre("Hairy", "82"),
    Genre("Handjob", "83"),
    Genre("Harem", "84"),
    Genre("HentaiVN", "85"),
    Genre("Historical", "86"),
    Genre("Horror", "87"),
    Genre("Housewife", "88"),
    Genre("Humiliation", "89"),
    Genre("Animal", "9"),
    Genre("Idol", "90"),
    Genre("Imouto", "91"),
    Genre("Incest", "92"),
    Genre("Insect (Côn Trùng)", "93"),
    Genre("Isekai", "94"),
    Genre("Không che", "95"),
    Genre("Kimono", "96"),
    Genre("Kuudere", "97"),
    Genre("Lolicon", "98"),
    Genre("Maids", "99"),
)
