package eu.kanade.tachiyomi.extension.tr.ruyamanganet

import eu.kanade.tachiyomi.multisrc.madara.Madara
import java.text.SimpleDateFormat
import java.util.Locale

class RuyaMangaNet : Madara(
    "Rüya Manga.net",
    "https://ruyamanga.net",
    "tr",
    dateFormat = SimpleDateFormat("d MMMM yyyy", Locale("tr")),
) {
    override val useLoadMoreRequest = LoadMoreStrategy.Never
    override val useNewChapterEndpoint = false

    override val fetchGenres = false
    override var genresList = listOf(
        Genre("Action", "action"),
        Genre("Adaptasyon", "adaptasyon"),
        Genre("Adventure", "adventure"),
        Genre("Aile", "aile"),
        Genre("Akademi", "akademi"),
        Genre("Aksiyon", "aksiyon"),
        Genre("Baba&Çocuk", "babacocuk"),
        Genre("Bilim Kurgu", "bilim-kurgu"),
        Genre("Büyü", "buyu"),
        Genre("Canavar", "canavar"),
        Genre("Çok Güçlü", "cok-guclu"),
        Genre("Comedy", "comedy"),
        Genre("Dahi", "dahi"),
        Genre("Deha", "deha"),
        Genre("Doğa Üstü", "doga-ustu"),
        Genre("Doğaüstü", "dogaustu"),
        Genre("Dövüş", "dovus"),
        Genre("Dövüş Sanatları", "dovus-sanatlari"),
        Genre("Dram", "dram"),
        Genre("Drama", "drama"),
        Genre("Ecchi", "ecchi"),
        Genre("Eğlence", "eglence"),
        Genre("Fantastik", "fantastik"),
        Genre("Fantasy", "fantasy"),
        Genre("Fantazi", "fantazi"),
        Genre("Fantezi", "fantezi"),
        Genre("Final", "final"),
        Genre("Genç", "genc"),
        Genre("Geri Dönen", "geri-donen"),
        Genre("Gerileme", "gerileme"),
        Genre("Gerilim", "gerilim"),
        Genre("Gizem", "gizem"),
        Genre("Günlük Hayat", "gunluk-hayat"),
        Genre("Harem", "harem"),
        Genre("Hayatta Kalma", "hayatta-kalma"),
        Genre("Hayattan bir parça", "hayattan-bir-parca"),
        Genre("Hayattan kesitler", "hayattan-kesitler"),
        Genre("Hayvanlar", "hayvanlar"),
        Genre("Horror", "horror"),
        Genre("İblisler", "iblisler"),
        Genre("İntikam", "intikam"),
        Genre("Isekai", "isekai"),
        Genre("Josei", "josei"),
        Genre("Karanlık", "karanlik"),
        Genre("Katliam", "katliam"),
        Genre("Kesitler", "kesitler"),
        Genre("Kıyamet", "kiyamet"),
        Genre("Komedi", "komedi"),
        Genre("Korku", "korku"),
        Genre("Korsan", "korsan"),
        Genre("Kule", "kule"),
        Genre("Macera", "macera"),
        Genre("Magic", "magic"),
        Genre("Manga", "manga"),
        Genre("Manhua", "manhua"),
        Genre("Manhwa", "manhwa"),
        Genre("Martial Arts", "martial-arts"),
        Genre("Meka", "meka"),
        Genre("Modern", "modern"),
        Genre("Modern Hayat", "modern-hayat"),
        Genre("Murim", "murim"),
        Genre("Müzik", "muzik"),
        Genre("Mystery", "mystery"),
        Genre("Okul", "okul"),
        Genre("Okul Hayatı", "okul-hayati"),
        Genre("Ölü Çağıran", "olu-cagiran"),
        Genre("Öneri", "oneri"),
        Genre("Oyun", "oyun"),
        Genre("Pişirme", "pisirme"),
        Genre("Polisiye", "polisiye"),
        Genre("Psikoloji", "psikoloji"),
        Genre("Psikolojik", "psikolojik"),
        Genre("Reenkarnasyon", "reenkarnasyon"),
        Genre("Reenkarne", "reenkarne"),
        Genre("Roma", "roma"),
        Genre("Romance", "romance"),
        Genre("Romantik", "romantik"),
        Genre("Romantizm", "romantizm"),
        Genre("Sahte İlişki", "sahte-iliski"),
        Genre("Sanal Gerçeklik", "sanal-gerceklik"),
        Genre("School Life", "school-life"),
        Genre("Sci-fi", "sci-fi"),
        Genre("Seinen", "seinen"),
        Genre("Şeytan", "seytan"),
        Genre("Shoujo", "shoujo"),
        Genre("Shounen", "shounen"),
        Genre("Şiddet", "siddet"),
        Genre("Sihir", "sihir"),
        Genre("Sistem", "sistem"),
        Genre("Slice of Life", "slice-of-life"),
        Genre("Spor", "spor"),
        Genre("Suç", "suc"),
        Genre("Süperkahraman", "superkahraman"),
        Genre("Supernatural", "supernatural"),
        Genre("Tarih", "tarih"),
        Genre("Tarihi", "tarihi"),
        Genre("Trajedi", "trajedi"),
        Genre("Vampir", "vampir"),
        Genre("Video Oyunları", "video-oyunlari"),
        Genre("Villain", "villain"),
        Genre("Villainess", "villainess"),
        Genre("Webtoon", "webtoon"),
        Genre("Yandere", "yandere"),
        Genre("Yaşamdan Kesitler", "yasamdan-kesitler"),
        Genre("Yeti", "yeti"),
        Genre("Zamanda Yolculuk", "zamanda-yolculuk"),
        Genre("Zindan", "zindan"),
        Genre("Zombi", "zombi"),
    )
}
