package eu.kanade.tachiyomi.extension.vi.yurineko

import eu.kanade.tachiyomi.source.model.Filter
import eu.kanade.tachiyomi.source.model.FilterList

fun getFilters(): FilterList = FilterList(
    TagFilter(),
    GroupFilter(),
    SortFilter(),
)

class UriPart(
    val displayName: String,
    val value: String?,
)

open class UriPartFilter(
    name: String,
    values: Array<UriPart>,
) : Filter.Select<String>(name, values.map(UriPart::displayName).toTypedArray()) {
    private val entries = values

    val selected: String?
        get() = entries[state].value
}

class TagFilter :
    UriPartFilter(
        "Tags",
        arrayOf(
            UriPart("All", null),
            UriPart("4-koma", "4-koma"),
            UriPart("Abuse", "abuse"),
            UriPart("Action", "action"),
            UriPart("Adult Life", "adult-life"),
            UriPart("Adventure", "adventure"),
            UriPart("Age Gap", "age-gap"),
            UriPart("Alien", "alien"),
            UriPart("Alternate World", "alternate-world"),
            UriPart("Amnesia", "amnesia"),
            UriPart("Amputee", "amputee"),
            UriPart("Angel", "angel"),
            UriPart("Animal Ears", "animal-ears"),
            UriPart("Anime", "anime"),
            UriPart("Anthology", "anthology"),
            UriPart("Assassin", "assassin"),
            UriPart("Autobiographical", "autobiographical"),
            UriPart("Bath", "bath"),
            UriPart("BDSM", "bdsm"),
            UriPart("Beach", "beach"),
            UriPart("Big Breasts", "big-breasts"),
            UriPart("Biographical", "biographical"),
            UriPart("Birthday", "birthday"),
            UriPart("Bisexual", "bisexual"),
            UriPart("Biting", "biting"),
            UriPart("Blackmail", "blackmail"),
            UriPart("Blushing", "blushing"),
            UriPart("Body Swap", "body-swap"),
            UriPart("Bullying", "bullying"),
            UriPart("Car", "car"),
            UriPart("Cheating", "cheating"),
            UriPart("Chibi", "chibi"),
            UriPart("Childhood Friends", "childhood-friends"),
            UriPart("Childification", "childification"),
            UriPart("Christmas", "christmas"),
            UriPart("Clones", "clones"),
            UriPart("Co-worker", "co-worker"),
            UriPart("College", "college"),
            UriPart("Comedy", "comedy"),
            UriPart("Cosplay", "cosplay"),
            UriPart("Couple life", "couple-life"),
            UriPart("Creepy", "creepy"),
            UriPart("Cross-dressing", "cross-dressing"),
            UriPart("Dark Skin", "dark-skin"),
            UriPart("Deity", "deity"),
            UriPart("Delinquent", "delinquent"),
            UriPart("Demon", "demon"),
            UriPart("Depressing as fvck", "depressing-as-fvck"),
            UriPart("Disability", "disability"),
            UriPart("Drama", "drama"),
            UriPart("Drunk", "drunk"),
            UriPart("Ecchi", "ecchi"),
            UriPart("Elf", "elf"),
            UriPart("Espionage", "espionage"),
            UriPart("Excuse me WTF?", "excuse-me-wtf"),
            UriPart("Fantasy", "fantasy"),
            UriPart("Feet", "feet"),
            UriPart("Food", "food"),
            UriPart("Full Color", "full-color"),
            UriPart("Furry", "furry"),
            UriPart("Game", "game"),
            UriPart("Gender Bender", "gender-bender"),
            UriPart("Ghost", "ghost"),
            UriPart("Glasses", "glasses"),
            UriPart("Gyaru", "gyaru"),
            UriPart("Halloween", "halloween"),
            UriPart("Harem", "harem"),
            UriPart("Height Gap", "height-gap"),
            UriPart("Het", "het"),
            UriPart("Hints", "hints"),
            UriPart("Historical", "historical"),
            UriPart("Horror", "horror"),
            UriPart("Hypnosis", "hypnosis"),
            UriPart("Idiot Couple", "idiot-couple"),
            UriPart("Idol", "idol"),
            UriPart("Introspective", "introspective"),
            UriPart("Isekai", "isekai"),
            UriPart("Kuudere", "kuudere"),
            UriPart("Loli", "loli"),
            UriPart("Love Triangle", "love-triangle"),
            UriPart("Lỗi: không tìm thấy trai", "loi-khong-tim-thay-trai"),
            UriPart("Mahou Shoujo", "mahou-shoujo"),
            UriPart("Maid", "maid"),
            UriPart("Mangaka", "mangaka"),
            UriPart("Manhua", "manhua"),
            UriPart("Manhwa", "manhwa"),
            UriPart("Marriage", "marriage"),
            UriPart("Martial Arts", "martial-arts"),
            UriPart("Mecha", "mecha"),
            UriPart("Mermaid", "mermaid"),
            UriPart("Miko", "miko"),
            UriPart("Miko", "miko-n49a9"),
            UriPart("Military", "military"),
            UriPart("Moe Paradise", "moe-paradise"),
            UriPart("Molestation", "molestation"),
            UriPart("Monster Girl", "monster-girl"),
            UriPart("Music", "music"),
            UriPart("Mystery", "mystery"),
            UriPart("New Year's", "new-years"),
            UriPart("Ninja", "ninja"),
            UriPart("No Text", "no-text"),
            UriPart("Nun", "nun"),
            UriPart("Office Lady", "office-lady"),
            UriPart("Official", "official"),
            UriPart("Omegaverse", "omegaverse"),
            UriPart("Oneshot", "oneshot"),
            UriPart("Parody", "parody"),
            UriPart("Pay for Gay", "pay-for-gay"),
            UriPart("Philosophical", "philosophical"),
            UriPart("Player", "player"),
            UriPart("Pocky Game", "pocky-game"),
            UriPart("Polyamory", "polyamory"),
            UriPart("Post-Apocalyptic", "post-apocalyptic"),
            UriPart("Prequel", "prequel"),
            UriPart("Psychological", "psychological"),
            UriPart("Reversal", "reversal"),
            UriPart("Rivals", "rivals"),
            UriPart("Robot", "robot"),
            UriPart("Roleplay", "roleplay"),
            UriPart("Romance", "romance"),
            UriPart("Roommates", "roommates"),
            UriPart("School Girl", "school-girl"),
            UriPart("School Life", "school-life"),
            UriPart("Sci-Fi", "sci-fi"),
            UriPart("Science Babies", "science-babies"),
            UriPart("Selfcest", "selfcest"),
            UriPart("Sequel", "sequel"),
            UriPart("Siscon", "siscon"),
            UriPart("Sleeping", "sleeping"),
            UriPart("Slice of Life", "slice-of-life"),
            UriPart("Smoking", "smoking"),
            UriPart("Space", "space"),
            UriPart("Spin-off", "spin-off"),
            UriPart("Sports", "sports"),
            UriPart("Stalking", "stalking"),
            UriPart("Student x Teacher", "student-x-teacher"),
            UriPart("Subtext", "subtext"),
            UriPart("Superhero", "superhero"),
            UriPart("Supernatural", "supernatural"),
            UriPart("Swimsuits", "swimsuits"),
            UriPart("Tentacles", "tentacles"),
            UriPart("Thất Tịch", "that-tich"),
            UriPart("Time Travel", "time-travel"),
            UriPart("Tomboy", "tomboy"),
            UriPart("Tragedy", "tragedy"),
            UriPart("Transgender", "transgender"),
            UriPart("Tsundere", "tsundere"),
            UriPart("Twins", "twins"),
            UriPart("Valentine", "valentine"),
            UriPart("Vampire", "vampire"),
            UriPart("Villainess", "villainess"),
            UriPart("Violence", "violence"),
            UriPart("Web Comic", "web-comic"),
            UriPart("Wholesome", "wholesome"),
            UriPart("Witch", "witch"),
            UriPart("Yandere", "yandere"),
            UriPart("Yaoi", "yaoi"),
            UriPart("Yuri", "yuri"),
            UriPart("Yuri Crush", "yuri-crush"),
            UriPart("Zombies", "zombies"),
        ),
    )

class GroupFilter :
    UriPartFilter(
        "Nhóm dịch",
        arrayOf(
            UriPart("All", null),
            UriPart("45000 năm đu GL", "92ca8843-2c0a-451a-a0e2-0a8942b79305"),
            UriPart("B7", "806a4170-83dd-4622-860f-8f33f040f745"),
            UriPart("BAH - 精神的er", "cc1b89aa-864a-4752-91b7-7aab0b243fc6"),
            UriPart("BanDrea Translation", "d16ace1c-4c98-4645-adc3-7fb907d180a2"),
            UriPart("Con mèo này bị lười", "3c507ef2-6763-4d75-ae74-efbd3f241623"),
            UriPart("DangTN", "f69b7f32-5aca-43d0-a5d0-307e2c5a2c5f"),
            UriPart("Dõi theo sự trưởng thành của Haruyama Hana", "f0a3b28f-7253-4872-b7ca-0755886d4f99"),
            UriPart("Đế Chế Yuri", "216e94ea-fd7e-4939-ad7c-a6aad5f199c3"),
            UriPart("Es_ternal", "a3a22a35-f216-445a-8ef0-6345e0982f7e"),
            UriPart("Gà Con", "ed253c31-5760-41c1-b7c6-7340f8b3b830"),
            UriPart("GekkaHima Team", "132e581c-69a8-437d-a75e-9331bc66c0f5"),
            UriPart("Girl band & dễ thương", "52bd7e7c-5862-4b8e-826e-655ba85ce850"),
            UriPart("Goemul Team", "e932e886-4f28-4ae9-b562-e6d528fd61ef"),
            UriPart("Hirasawa Clan", "c30daea4-5bb3-4561-ba40-af02fc8c4e4f"),
            UriPart("Hotarin", "f0ac9b2d-5d12-4ae6-99b1-9a4d5f17310d"),
            UriPart("Hửm?", "674cfb3a-1c20-4fee-9aa7-287f0794d9bf"),
            UriPart("Ivy Comic", "8eb16e16-9426-42ff-b366-a0cabb1f3dc7"),
            UriPart("Kenko Group", "7ef43e2c-7303-4368-9e4f-73cb85259c8e"),
            UriPart("Knights of Yuri", "8229fab9-434b-467b-8058-fd8f63e7d96b"),
            UriPart("KVF Group", "47a36ed8-b2de-40a0-8657-beec37c725f9"),
            UriPart("Lazy Majo", "cfaa3445-2066-4956-aea5-0141d0bce939"),
            UriPart("Lily Bouquet Team", "26b0e0d4-b65b-41c1-87db-9d30fac19600"),
            UriPart("Lily no himitsu", "65e64c54-0b81-4916-b811-a5fe689738f0"),
            UriPart("Lưu Tinh Team", "5c3fa6be-e326-42ba-9fef-2cd11acaa043"),
            UriPart("Mồm-lèo cầu tài", "4faf8a2e-9aa2-4e43-a07e-9b4724b83c54"),
            UriPart("nen", "76508648-a8cd-46eb-a624-49b75eecf95d"),
            UriPart("Nhà Bếp của Yukino", "a658b8cb-7af0-40e0-98c1-75773fb4a72b"),
            UriPart("Nỏi", "53635678-7e57-45cf-a446-04c901f0ca43"),
            UriPart("Nothing", "9a8f3d9e-bc88-45a8-8407-35830545543f"),
            UriPart("Rảnh đời dịch manga", "043d6ef5-69a4-4177-b8a0-4d8d9c1115be"),
            UriPart("Rin group", "b439ff84-0b64-48b6-918a-e9fd1cbde867"),
            UriPart("Rusano", "4cdb9f3e-13e6-40a6-b2b8-2cdd695ab8ed"),
            UriPart("S•N Winter", "bcb61f49-f911-48ec-a0c3-112d88e6ae1b"),
            UriPart("Sa La Trans", "9eb90194-de1c-4085-83e7-a14f746f905d"),
            UriPart("Shirayuri no Hana", "d01c17f4-de2d-4441-99ca-4a1a1a04f0dd"),
            UriPart("Shiriaki Team", "0fcec919-74c6-4d8d-ae91-d86e164d9d2e"),
            UriPart("Sora no Iro", "67009299-4976-4e78-98f5-241f1383729d"),
            UriPart("Sora Sub", "1cdf248a-6203-4489-840a-ae361fa043b9"),
            UriPart("Sổ viết của Mashiro", "a37728b4-f864-4d1f-bb55-5a3d985b000f"),
            UriPart("Tandoku Translation", "53056222-b304-4c02-8bb7-e3b8d286b1aa"),
            UriPart("Thích Thì Dịch", "a5277d48-cb75-4ef6-9c00-3b8dbd99f65b"),
            UriPart("Tiệm Bánh Bao", "b9514f47-cf7d-4660-b9a8-a495a22992a1"),
            UriPart("TOF", "e14d4124-7234-4e33-8971-633dd500c602"),
            UriPart("Trạm Tinh Đào MiComet", "57ff557f-2a3c-4bff-a36d-a17d0dbbc8bf"),
            UriPart("Truyện tranh Comedy", "4eda4a74-f79c-4d13-a51c-d1aad8e61020"),
            UriPart("Umasaki - Cố Đạ Ngựa Gay Số 1 Tracen", "228142c6-7cc0-4154-81c0-7dcb39c86aea"),
            UriPart("Vườn Mèo", "8d5244f2-ee66-4ecf-ad04-33d1560b5d9f"),
            UriPart("W the Whale", "62c4cb31-dba6-4be7-bfe3-0eb7c9f36554"),
            UriPart("WaddleUp", "d98be063-3745-47c3-ae7d-d5156c0d7c83"),
            UriPart("Yume", "2bc420ee-82f7-487c-8c16-cb5d4460f74c"),
            UriPart("Yune Projekt", "ca5e7679-3c91-4ab9-b330-6c028c5ce354"),
            UriPart("Yuri House", "58a5fd0d-f2c4-4fac-a1ec-b598e9960859"),
            UriPart("Yuri Mädchen", "d0261fc9-bf79-44bb-803e-2e86725998aa"),
            UriPart("百合スキ", "ea4d1bc5-dbf3-41a2-af20-5c8b010472d0"),
        ),
    )

class SortFilter :
    UriPartFilter(
        "Sắp xếp",
        arrayOf(
            UriPart("Mới cập nhật", "latest"),
            UriPart("Lượt xem (Tất cả)", "views"),
            UriPart("Lượt xem (Ngày)", "views_day"),
            UriPart("Lượt xem (Tuần)", "views_week"),
            UriPart("Lượt xem (Tháng)", "views_month"),
            UriPart("Yêu thích (Tất cả)", "bookmarks"),
            UriPart("Yêu thích (Ngày)", "bookmarks_day"),
            UriPart("Yêu thích (Tuần)", "bookmarks_week"),
            UriPart("Yêu thích (Tháng)", "bookmarks_month"),
        ),
    )
