package eu.kanade.tachiyomi.extension.ja.drecomics

import eu.kanade.tachiyomi.source.model.Filter

class Label(name: String, val value: String) : Filter.CheckBox(name)
class LabelFilter :
    Filter.Group<Label>(
        "Label",
        listOf(
            Label("DREコミックス（コミック）", "3"),
            Label("DRE STUDIOS（webtoon）", "1"),
        ),
    )

class Genre(name: String, val value: String) : Filter.CheckBox(name)
class GenreFilter :
    Filter.Group<Genre>(
        "Genre",
        listOf(
            Genre("ファンタジー", "1"),
            Genre("バトル", "2"),
            Genre("恋愛", "3"),
            Genre("ラブコメ", "4"),
            Genre("SF", "5"),
            Genre("ミステリー", "6"),
            Genre("ホラー", "7"),
            Genre("シリアス", "34"),
            Genre("コメディ", "35"),
            Genre("業界", "57"),
            Genre("歴史", "53"),
            Genre("オカルト", "36"),
            Genre("アクション", "37"),
            Genre("もふもふ", "38"),
            Genre("サスペンス", "39"),
            Genre("異世界", "8"),
            Genre("異能", "9"),
            Genre("チート能力", "10"),
            Genre("タイムリープ", "40"),
            Genre("ゲーム世界", "12"),
            Genre("政治", "55"),
            Genre("経営", "56"),
            Genre("思想", "58"),
            Genre("ハーレム", "13"),
            Genre("聖女", "33"),
            Genre("追放", "15"),
            Genre("転生", "16"),
            Genre("転移", "17"),
            Genre("復讐", "18"),
            Genre("溺愛", "41"),
            Genre("悪役令嬢", "14"),
            Genre("王侯・貴族", "19"),
            Genre("婚約破棄", "42"),
            Genre("逆ハーレム", "43"),
            Genre("結婚", "44"),
            Genre("本格", "54"),
            Genre("日常", "21"),
            Genre("戦争", "45"),
            Genre("ドラマ", "30"),
            Genre("成り上がり", "47"),
            Genre("現代", "20"),
            Genre("学園", "22"),
            Genre("青春", "23"),
            Genre("お仕事", "24"),
            Genre("スローライフ", "25"),
            Genre("旅", "26"),
            Genre("子供", "27"),
            Genre("医療", "31"),
            Genre("グルメ", "28"),
            Genre("不良・ヤンキー", "29"),
            Genre("イケメン", "46"),
            Genre("メカ", "32"),
            Genre("魔王", "48"),
            Genre("人外", "49"),
            Genre("書き下ろし", "50"),
            Genre("エッセイ", "52"),
            Genre("コミカライズ", "51"),
            Genre("アニメ化", "62"),
            Genre("webtoon", "61"),
            Genre("受賞作", "63"),
            Genre("DREコミックス", "59"),
            Genre("DREコミックスF", "67"),
            Genre("完結", "65"),
        ),
    )
