package eu.kanade.tachiyomi.extension.en.yaoitoon

import eu.kanade.tachiyomi.source.model.Filter
import eu.kanade.tachiyomi.source.model.FilterList

open class UriPartFilter(
    displayName: String,
    private val vals: Array<Pair<String, String>>,
) : Filter.Select<String>(displayName, vals.map { it.first }.toTypedArray()) {
    fun selectedValue() = vals[state].second
}

class SortFilter :
    UriPartFilter(
        "Sort",
        arrayOf(
            Pair("Default", "default"),
            Pair("Latest Updated", "latest-updated"),
            Pair("Most Viewed", "most-viewd"),
            Pair("Score", "score"),
            Pair("Name A-Z", "az"),
            Pair("Name Z-A", "za"),
            Pair("Newest", "new"),
            Pair("Oldest", "old"),
        ),
    )

class Genre(name: String, val id: String) : Filter.CheckBox(name)

class GenreList(genres: List<Genre>) : Filter.Group<Genre>("Genres", genres)

fun getFilters() = FilterList(
    SortFilter(),
    Filter.Separator(),
    GenreList(getGenreList()),
)

private fun getGenreList() = listOf(
    Genre("4 koma", "30"),
    Genre("Action", "38"),
    Genre("Adaptation", "1"),
    Genre("Adult", "24"),
    Genre("Adventure", "54"),
    Genre("Age Gap", "39"),
    Genre("Aliens", "104"),
    Genre("Animals", "43"),
    Genre("Anthology", "106"),
    Genre("Artbook", "86"),
    Genre("Bara(ML)", "92"),
    Genre("Beasts", "17"),
    Genre("Bloody", "101"),
    Genre("Boys", "119"),
    Genre("Cartoon", "110"),
    Genre("Cheating/Infidelity", "52"),
    Genre("Childhood Friends", "44"),
    Genre("Chinese", "84"),
    Genre("College life", "26"),
    Genre("Comedy", "13"),
    Genre("Comic", "67"),
    Genre("Cooking", "74"),
    Genre("Crime", "69"),
    Genre("Crossdressing", "97"),
    Genre("Delinquents", "68"),
    Genre("Dementia", "120"),
    Genre("Demons", "31"),
    Genre("Doujinshi", "122"),
    Genre("Drama", "2"),
    Genre("Dungeons", "32"),
    Genre("Ecchi", "76"),
    Genre("Fan colored", "115"),
    Genre("Fantasy", "16"),
    Genre("Fetish", "102"),
    Genre("Full color", "3"),
    Genre("Game", "33"),
    Genre("Gender Bender", "51"),
    Genre("Ghosts", "108"),
    Genre("Gore", "71"),
    Genre("Harem", "25"),
    Genre("Hentai", "123"),
    Genre("Historical", "18"),
    Genre("Horror", "72"),
    Genre("Incest", "124"),
    Genre("Isekai", "19"),
    Genre("Japanese", "90"),
    Genre("Josei", "53"),
    Genre("Josei(W)", "93"),
    Genre("Korean", "49"),
    Genre("Long strip", "55"),
    Genre("Mafia", "73"),
    Genre("Magic", "34"),
    Genre("Manga", "45"),
    Genre("Manhua", "20"),
    Genre("Manhwa", "4"),
    Genre("Martial Arts", "65"),
    Genre("Mature", "5"),
    Genre("Mecha", "112"),
    Genre("Medical", "70"),
    Genre("Military", "80"),
    Genre("Monster girls", "100"),
    Genre("Monsters", "35"),
    Genre("Music", "61"),
    Genre("Mystery", "75"),
    Genre("Netorare/NTR", "126"),
    Genre("Non-human", "121"),
    Genre("NTR", "116"),
    Genre("Office workers", "28"),
    Genre("Official colored", "57"),
    Genre("Omegaverse", "60"),
    Genre("One shot", "87"),
    Genre("Oneshot", "105"),
    Genre("Parody", "83"),
    Genre("Police", "89"),
    Genre("Post-Apocalyptic", "22"),
    Genre("Psychological", "47"),
    Genre("Regression", "118"),
    Genre("Reincarnation", "46"),
    Genre("Reverse harem", "99"),
    Genre("Romance", "6"),
    Genre("Royal family", "81"),
    Genre("Royalty", "64"),
    Genre("Samurai", "113"),
    Genre("School life", "14"),
    Genre("Sci-fi", "40"),
    Genre("Science fiction", "56"),
    Genre("Seinen", "77"),
    Genre("Seinen(M)", "94"),
    Genre("Sexual violence", "58"),
    Genre("Shoujo", "27"),
    Genre("Shoujo Ai", "98"),
    Genre("Shounen", "50"),
    Genre("Shounen Ai", "21"),
    Genre("Shounen(B)", "107"),
    Genre("Showbiz", "7"),
    Genre("Slice of Life", "8"),
    Genre("SM/BDSM/SUB-DOM", "63"),
    Genre("Smut", "9"),
    Genre("Sports", "66"),
    Genre("Super Power", "41"),
    Genre("Superhero", "117"),
    Genre("Supernatural", "42"),
    Genre("Survival", "91"),
    Genre("The elderly", "95"),
    Genre("Thriller", "48"),
    Genre("Time travel", "10"),
    Genre("Tragedy", "79"),
    Genre("Transmigration", "125"),
    Genre("Uncategorized", "103"),
    Genre("Vampires", "36"),
    Genre("Video games", "62"),
    Genre("Villainess", "82"),
    Genre("Violence", "37"),
    Genre("Virtual reality", "114"),
    Genre("Web comic", "59"),
    Genre("Webtoon", "11"),
    Genre("Webtoons", "15"),
    Genre("Wuxia", "111"),
    Genre("Yakuzas", "29"),
    Genre("Yaoi", "12"),
    Genre("Yaoi(BL)", "23"),
    Genre("Yuri", "78"),
    Genre("Yuri(GL)", "96"),
    Genre("Zombies", "85"),
)
