package eu.kanade.tachiyomi.extension.id.narasininja

import eu.kanade.tachiyomi.source.model.Filter

internal class StatusFilter :
    Filter.Select<String>(
        "Status",
        arrayOf("All", "Ongoing", "Completed", "Hiatus"),
    ) {
    private val options = arrayOf("", "ongoing", "completed", "hiatus")
    fun selectedValue() = options[state]
}

internal class TypeFilter :
    Filter.Select<String>(
        "Type",
        arrayOf("All", "Manga", "Manhwa", "Manhua", "Comic", "Novel"),
    ) {
    private val options = arrayOf("", "manga", "manhwa", "manhua", "comic", "novel")
    fun selectedValue() = options[state]
}

internal class OrderFilter :
    Filter.Select<String>(
        "Order",
        arrayOf("Update", "Added", "A-Z", "Z-A"),
    ) {
    private val options = arrayOf("update", "added", "title", "titlereverse")
    fun selectedValue() = options[state]
}

internal class GenreCheckBox(name: String, val value: String) : Filter.CheckBox(name)

internal class GenreFilter : Filter.Group<GenreCheckBox>("Genre", GENRES)

private val GENRES = listOf(
    GenreCheckBox("4-Koma", "92"),
    GenreCheckBox("Action", "2"),
    GenreCheckBox("Adaptation", "74"),
    GenreCheckBox("Adult", "67"),
    GenreCheckBox("Adventure", "3"),
    GenreCheckBox("Animals", "117"),
    GenreCheckBox("Anthology", "158"),
    GenreCheckBox("Antihero", "125"),
    GenreCheckBox("apocalypse", "87"),
    GenreCheckBox("Award Winning", "149"),
    GenreCheckBox("Beasts", "97"),
    GenreCheckBox("Bodyswap", "132"),
    GenreCheckBox("Boys' Love", "94"),
    GenreCheckBox("Bully", "114"),
    GenreCheckBox("Cartoon", "133"),
    GenreCheckBox("Childhood Friends", "113"),
    GenreCheckBox("Comedy", "4"),
    GenreCheckBox("Comic", "78"),
    GenreCheckBox("Cooking", "5"),
    GenreCheckBox("Crime", "6"),
    GenreCheckBox("Crossdressing", "62"),
    GenreCheckBox("Dance", "146"),
    GenreCheckBox("Dark Fantasy", "105"),
    GenreCheckBox("Delinquent", "115"),
    GenreCheckBox("Delinquents", "91"),
    GenreCheckBox("Dementia", "134"),
    GenreCheckBox("Demon", "64"),
    GenreCheckBox("Demons", "8"),
    GenreCheckBox("Doujinshi", "119"),
    GenreCheckBox("Drama", "9"),
    GenreCheckBox("Dungeons", "135"),
    GenreCheckBox("Ecchi", "12"),
    GenreCheckBox("Emperor's daughter", "127"),
    GenreCheckBox("Entertainment", "89"),
    GenreCheckBox("Fan-Colored", "128"),
    GenreCheckBox("Fantas", "80"),
    GenreCheckBox("Fantasy", "13"),
    GenreCheckBox("Fetish", "136"),
    GenreCheckBox("Full Color", "75"),
    GenreCheckBox("Game", "14"),
    GenreCheckBox("Games", "163"),
    GenreCheckBox("Gang", "122"),
    GenreCheckBox("Gender Bender", "15"),
    GenreCheckBox("Genderswap", "106"),
    GenreCheckBox("Ghosts", "129"),
    GenreCheckBox("Girls", "82"),
    GenreCheckBox("Girls' Love", "69"),
    GenreCheckBox("gore", "68"),
    GenreCheckBox("gorre", "154"),
    GenreCheckBox("Gyaru", "111"),
    GenreCheckBox("Harem", "17"),
    GenreCheckBox("Hentai", "112"),
    GenreCheckBox("Hero", "99"),
    GenreCheckBox("Historical", "18"),
    GenreCheckBox("Horror", "19"),
    GenreCheckBox("Imageset", "137"),
    GenreCheckBox("Incest", "126"),
    GenreCheckBox("Isekai", "20"),
    GenreCheckBox("Josei", "21"),
    GenreCheckBox("Josei(W)", "118"),
    GenreCheckBox("Kids", "130"),
    GenreCheckBox("Leveling", "164"),
    GenreCheckBox("Loli", "150"),
    GenreCheckBox("Lolicon", "73"),
    GenreCheckBox("Long Strip", "76"),
    GenreCheckBox("Mafia", "151"),
    GenreCheckBox("Magi", "152"),
    GenreCheckBox("Magic", "23"),
    GenreCheckBox("Magical Girls", "116"),
    GenreCheckBox("Martial Art", "101"),
    GenreCheckBox("Martial Arts", "26"),
    GenreCheckBox("Mature", "27"),
    GenreCheckBox("Mecha", "28"),
    GenreCheckBox("Medical", "29"),
    GenreCheckBox("Military", "30"),
    GenreCheckBox("Mirror", "110"),
    GenreCheckBox("Modern", "159"),
    GenreCheckBox("Monster Girls", "153"),
    GenreCheckBox("Monsters", "96"),
    GenreCheckBox("Murim", "79"),
    GenreCheckBox("Music", "31"),
    GenreCheckBox("Mystery", "32"),
    GenreCheckBox("Necromancer", "160"),
    GenreCheckBox("Ninja", "138"),
    GenreCheckBox("Non-human", "139"),
    GenreCheckBox("Office Workers", "103"),
    GenreCheckBox("Official Colored", "156"),
    GenreCheckBox("One-Shot", "84"),
    GenreCheckBox("Oneshot", "147"),
    GenreCheckBox("Overpowered", "161"),
    GenreCheckBox("Parody", "140"),
    GenreCheckBox("Pets", "162"),
    GenreCheckBox("Philosophical", "102"),
    GenreCheckBox("Police", "36"),
    GenreCheckBox("Post-Apocalyptic", "104"),
    GenreCheckBox("Project", "66"),
    GenreCheckBox("Psychological", "37"),
    GenreCheckBox("Regression", "70"),
    GenreCheckBox("Reincarnation", "39"),
    GenreCheckBox("Revenge", "65"),
    GenreCheckBox("Reverse Harem", "71"),
    GenreCheckBox("Reverse Isekai", "141"),
    GenreCheckBox("Romance", "40"),
    GenreCheckBox("Royalty", "142"),
    GenreCheckBox("School", "41"),
    GenreCheckBox("School life", "42"),
    GenreCheckBox("Sci-fi", "44"),
    GenreCheckBox("Seinen", "45"),
    GenreCheckBox("Seinen(M)", "148"),
    GenreCheckBox("Seinin", "123"),
    GenreCheckBox("Sexual Violence", "85"),
    GenreCheckBox("Shotacon", "46"),
    GenreCheckBox("Shoujo", "47"),
    GenreCheckBox("Shoujo Ai", "48"),
    GenreCheckBox("Shoujo(G)", "121"),
    GenreCheckBox("Shounen", "49"),
    GenreCheckBox("Shounen Ai", "50"),
    GenreCheckBox("Shounen(B)", "98"),
    GenreCheckBox("Shounn", "165"),
    GenreCheckBox("Showbiz", "143"),
    GenreCheckBox("Slice of Life", "51"),
    GenreCheckBox("Smut", "72"),
    GenreCheckBox("Space", "144"),
    GenreCheckBox("Sport", "52"),
    GenreCheckBox("Sports", "53"),
    GenreCheckBox("Super Power", "54"),
    GenreCheckBox("Superhero", "93"),
    GenreCheckBox("Supernatural", "55"),
    GenreCheckBox("Supranatural", "95"),
    GenreCheckBox("Survival", "63"),
    GenreCheckBox("System", "88"),
    GenreCheckBox("Thriller", "56"),
    GenreCheckBox("Time Travel", "83"),
    GenreCheckBox("Traditional Games", "145"),
    GenreCheckBox("Tragedy", "57"),
    GenreCheckBox("Transmigration", "131"),
    GenreCheckBox("Vampire", "59"),
    GenreCheckBox("Vampires", "107"),
    GenreCheckBox("Video Games", "108"),
    GenreCheckBox("Villainess", "100"),
    GenreCheckBox("Violence", "157"),
    GenreCheckBox("Virtual Reality", "109"),
    GenreCheckBox("Web Comic", "77"),
    GenreCheckBox("Webtoon", "90"),
    GenreCheckBox("Webtoons", "60"),
    GenreCheckBox("Wuxia", "81"),
    GenreCheckBox("Xianxia", "124"),
    GenreCheckBox("Xuanhuan", "120"),
    GenreCheckBox("Yaoi", "155"),
    GenreCheckBox("Yuri", "61"),
    GenreCheckBox("Zombies", "86"),
)
