package eu.kanade.tachiyomi.extension.ja.magazinepocket

import eu.kanade.tachiyomi.source.model.Filter

class CategoryFilter :
    SelectFilter(
        "Category",
        arrayOf(
            Triple("(ランキング) すべて", "ranking", "30"),
            Triple("(ランキング) まずはコレ！", "ranking", "2"),
            Triple("(ランキング) オリジナル", "ranking", "1"),
            Triple("(ランキング) 新作", "ranking", "31"),
            Triple("(ランキング) アクション", "ranking", "21"),
            Triple("(ランキング) スポーツ", "ranking", "22"),
            Triple("(ランキング) 恋愛", "ranking", "23"),
            Triple("(ランキング) 異世界", "ranking", "24"),
            Triple("(ランキング) サスペンス", "ranking", "25"),
            Triple("(ランキング) 裏社会・ヤンキー", "ranking", "26"),
            Triple("(ランキング) ドラマ", "ranking", "27"),
            Triple("(ランキング) ファンタジー", "ranking", "28"),
            Triple("(ランキング) 日常", "ranking", "29"),
            Triple("恋愛・ラブコメ", "genre", "1"),
            Triple("ホラー・ミステリー・サスペンス", "genre", "2"),
            Triple("ギャグ・コメディー・日常", "genre", "3"),
            Triple("SF・ファンタジー", "genre", "4"),
            Triple("スポーツ", "genre", "5"),
            Triple("ヒューマンドラマ", "genre", "6"),
            Triple("裏社会・アングラ・ヤンキー", "genre", "7"),
            Triple("アクション・バトル", "genre", "8"),
            Triple("異世界・異能力", "genre", "9"),
            Triple("読切", "genre", "10"),
            Triple("MGP", "genre", "11"),
            Triple("第98回新人漫画賞", "genre", "12"),
            Triple("第99回新人漫画賞", "genre", "13"),
            Triple("第100回新人漫画賞", "genre", "14"),
            Triple("第101回新人漫画賞", "genre", "15"),
            Triple("第102回新人漫画賞", "genre", "16"),
            Triple("第103回新人漫画賞", "genre", "17"),
            Triple("第104回新人漫画賞", "genre", "18"),
            Triple("第105回新人漫画賞", "genre", "19"),
            Triple("第106回新人漫画賞", "genre", "20"),
            Triple("第107回新人漫画賞", "genre", "21"),
            Triple("第108回新人漫画賞", "genre", "22"),
            Triple("第109回新人漫画賞", "genre", "23"),
            Triple("第110回新人漫画賞", "genre", "24"),
            Triple("2023真夏の読み切り15連弾", "genre", "25"),
            Triple("マガジンライズ", "genre", "26"),
            Triple("第111回新人漫画賞", "genre", "27"),
            Triple("少女／女性", "genre", "28"),
            Triple("新人漫画大賞", "genre", "29"),
            Triple("第75回新人漫画賞", "genre", "30"),
            Triple("第79回新人漫画賞", "genre", "31"),
            Triple("第85回新人漫画賞", "genre", "32"),
            Triple("第88回新人漫画賞", "genre", "33"),
            Triple("第89回新人漫画賞", "genre", "34"),
            Triple("第91回新人漫画賞", "genre", "35"),
            Triple("第92回新人漫画賞", "genre", "36"),
            Triple("第94回新人漫画賞", "genre", "37"),
            Triple("第95回新人漫画賞", "genre", "38"),
            Triple("第96回新人漫画賞", "genre", "39"),
            Triple("第97回新人漫画賞", "genre", "40"),
            Triple("第112回新人漫画賞", "genre", "41"),
            Triple("第113回新人漫画大賞", "genre", "42"),
            Triple("サッカー", "genre", "43"),
            Triple("テニス", "genre", "44"),
            Triple("バスケ", "genre", "45"),
            Triple("格闘技", "genre", "46"),
            Triple("野球", "genre", "47"),
            Triple("女性向け異世界", "genre", "48"),
            Triple("アニメ化", "genre", "49"),
            Triple("実写化", "genre", "50"),
            Triple("車・バイク", "genre", "51"),
            Triple("グルメ・料理", "genre", "52"),
            Triple("医療", "genre", "53"),
            Triple("頭脳戦", "genre", "54"),
            Triple("サバイバル", "genre", "55"),
            Triple("復讐劇", "genre", "56"),
            Triple("70～80年代", "genre", "57"),
            Triple("90年代", "genre", "58"),
            Triple("金田一シリーズ", "genre", "59"),
            Triple("第114回新人漫画大賞", "genre", "60"),
            Triple("連載獲得ダービー", "genre", "61"),
            Triple("有名漫画賞", "genre", "62"),
            Triple("探偵・警察", "genre", "63"),
            Triple("歴史・時代", "genre", "64"),
            Triple("不倫・浮気", "genre", "65"),
            Triple("犬・猫", "genre", "66"),
        ),
    )

open class SelectFilter(displayName: String, private val vals: Array<Triple<String, String, String>>) : Filter.Select<String>(displayName, vals.map { it.first }.toTypedArray()) {
    val type: String
        get() = vals[state].second

    val value: String
        get() = vals[state].third
}
