package keiyoushi.gradle.extension.codegen

import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction

@CacheableTask
abstract class GenerateUrlActivityTask : DefaultTask() {
    @get:Input
    abstract val pkg: Property<String>

    @get:Input
    abstract val logTag: Property<String>

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generate() {
        val outDir = outputDir.get().asFile
        outDir.deleteRecursively()
        outDir.mkdirs()

        val pkgValue = pkg.get()
        val tag = logTag.get()
        val pkgDir = outDir.resolve(pkgValue.replace('.', '/'))
        pkgDir.mkdirs()

        pkgDir.resolve("GeneratedUrlActivity.kt").writeText(
            """
            |// Generated by kei.plugins.extension — do not edit by hand.
            |package $pkgValue
            |
            |import android.app.Activity
            |import android.content.ActivityNotFoundException
            |import android.content.Intent
            |import android.os.Bundle
            |import android.util.Log
            |
            |class GeneratedUrlActivity : Activity() {
            |    override fun onCreate(savedInstanceState: Bundle?) {
            |        super.onCreate(savedInstanceState)
            |
            |        val data = intent.data
            |        if (data != null) {
            |            val intent = Intent().apply {
            |                setAction("eu.kanade.tachiyomi.SEARCH")
            |                putExtra("query", data.toString())
            |                putExtra("filter", packageName)
            |            }
            |            try {
            |                startActivity(intent)
            |            } catch (e: ActivityNotFoundException) {
            |                Log.e(${'"'}$tag${'"'}, "Unable to launch activity", e)
            |            }
            |        }
            |
            |        finish()
            |        System.exit(0)
            |    }
            |}
            |
            """.trimMargin(),
        )
    }
}
