package keiyoushi.gradle.extension.codegen

import org.gradle.api.DefaultTask
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.ListProperty
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction
import java.io.Serializable

data class DeeplinkFilter(
    val scheme: String,
    val host: String,
    val pathPatterns: List<String>,
) : Serializable

private fun String.xmlAttr(): String = this
    .replace("&", "&amp;")
    .replace("<", "&lt;")
    .replace(">", "&gt;")
    .replace("\"", "&quot;")

@CacheableTask
abstract class GenerateExtensionManifestTask : DefaultTask() {
    @get:Input
    abstract val filters: ListProperty<DeeplinkFilter>

    @get:OutputFile
    abstract val outputFile: RegularFileProperty

    @TaskAction
    fun generate() {
        val filterList = filters.get()
        val out = outputFile.get().asFile
        out.parentFile.mkdirs()

        val intentFilters = filterList.joinToString("\n") { f ->
            buildString {
                appendLine("            <intent-filter>")
                appendLine("                <action android:name=\"android.intent.action.VIEW\" />")
                appendLine("                <category android:name=\"android.intent.category.DEFAULT\" />")
                appendLine("                <category android:name=\"android.intent.category.BROWSABLE\" />")
                appendLine("                <data android:scheme=\"${f.scheme.xmlAttr()}\" />")
                appendLine("                <data android:host=\"${f.host.xmlAttr()}\" />")
                f.pathPatterns.forEach {
                    appendLine("                <data android:pathPattern=\"${it.xmlAttr()}\" />")
                }
                append("            </intent-filter>")
            }
        }

        out.writeText(
            """
            |<?xml version="1.0" encoding="utf-8"?>
            |<!-- Generated by kei.plugins.extension — do not edit by hand. -->
            |<manifest xmlns:android="http://schemas.android.com/apk/res/android">
            |    <application>
            |        <activity
            |            android:name="keiyoushi.core.UrlDispatchActivity"
            |            android:excludeFromRecents="true"
            |            android:exported="true"
            |            android:theme="@android:style/Theme.NoDisplay">
            |$intentFilters
            |        </activity>
            |    </application>
            |</manifest>
            |
            """.trimMargin(),
        )
    }
}
