package keiyoushi.gradle.extension.codegen

import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.TypeSpec
import keiyoushi.gradle.extension.dsl.BaseUrlSpec
import keiyoushi.gradle.extension.dsl.OverrideValue
import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction

@CacheableTask
abstract class GenerateExtensionSourceTask : DefaultTask() {
    @get:Input
    abstract val spec: Property<ResolvedExtension>

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generate() {
        val resolved = spec.get()
        val outDir = outputDir.get().asFile
        outDir.deleteRecursively()
        outDir.mkdirs()

        val file = if (resolved.sources.size == 1) {
            buildSingleSource(resolved, resolved.sources.single())
        } else {
            buildFactorySource(resolved)
        }

        file.toBuilder()
            .addFileComment("Generated by kei.plugins.extension — do not edit by hand.")
            .build()
            .writeTo(outDir)
    }

    private fun buildSingleSource(ext: ResolvedExtension, source: ResolvedSource): FileSpec {
        val userClass = ClassName(ext.pkg, ext.extensionClass)
        val generatedName = "${ext.extensionClass}Generated"
        val typeBuilder = TypeSpec.classBuilder(generatedName)
            .superclass(userClass)

        val configurable = source.baseUrl is BaseUrlSpec.Mirrors || source.baseUrl is BaseUrlSpec.Custom
        // Skip adding ConfigurableSource if super already has it (would be a duplicate supertype).
        if (configurable && !ext.superIsConfigurable) {
            typeBuilder.addSuperinterface(CONFIGURABLE_SOURCE)
        }

        addCoreOverrides(typeBuilder, source, suffix = null)
        addBaseUrlMembers(typeBuilder, source, suffix = null, superIsConfigurable = ext.superIsConfigurable)
        addOverrideProperties(typeBuilder, source.overrides)

        return FileSpec.builder(ext.pkg, generatedName)
            .addAnnotation(suppressUnused())
            .addType(typeBuilder.build())
            .build()
    }

    private fun buildFactorySource(ext: ResolvedExtension): FileSpec {
        val suffixes = sourceSuffixes(ext.sources)
        val generatedName = "${ext.extensionClass}Generated"
        val factoryType = TypeSpec.classBuilder(generatedName)
            .addSuperinterface(SOURCE_FACTORY)
            .addFunction(
                FunSpec.builder("createSources")
                    .addModifiers(KModifier.OVERRIDE)
                    .returns(LIST.parameterizedBy(SOURCE))
                    .addCode(
                        buildCodeBlock {
                            add("return listOf(\n⇥")
                            suffixes.forEach { suffix ->
                                add("%N(),\n", generatedSourceName(ext.extensionClass, suffix))
                            }
                            add("⇤)")
                        },
                    )
                    .build(),
            )
            .build()

        val fileBuilder = FileSpec.builder(ext.pkg, generatedName)
            .addAnnotation(suppressUnused())
            .addType(factoryType)

        val userClass = ClassName(ext.pkg, ext.extensionClass)
        ext.sources.forEachIndexed { index, source ->
            val suffix = suffixes[index]
            val subType = TypeSpec.classBuilder(generatedSourceName(ext.extensionClass, suffix))
                .addModifiers(KModifier.PRIVATE)
                .superclass(userClass)

            val configurable = source.baseUrl is BaseUrlSpec.Mirrors || source.baseUrl is BaseUrlSpec.Custom
            if (configurable && !ext.superIsConfigurable) {
                subType.addSuperinterface(CONFIGURABLE_SOURCE)
            }

            addCoreOverrides(subType, source, suffix = suffix)
            addBaseUrlMembers(subType, source, suffix = suffix, superIsConfigurable = ext.superIsConfigurable)
            addOverrideProperties(subType, source.overrides)

            fileBuilder.addType(subType.build())
        }

        return fileBuilder.build()
    }

    // Lang suffix for stable pref keys; collisions get `_en_2`, `_en_3` etc.
    private fun sourceSuffixes(sources: List<ResolvedSource>): List<String> {
        val seen = mutableMapOf<String, Int>()
        return sources.map { src ->
            val base = src.lang.replace('-', '_').replace('.', '_')
            val count = seen.merge(base, 1) { existing, _ -> existing + 1 }!!
            if (count == 1) base else "${base}_$count"
        }
    }

    private fun addCoreOverrides(builder: TypeSpec.Builder, source: ResolvedSource, suffix: String?) {
        builder.addProperty(
            PropertySpec.builder("name", STRING)
                .addModifiers(KModifier.OVERRIDE)
                .initializer("%S", source.name)
                .build(),
        )
        builder.addProperty(
            PropertySpec.builder("lang", STRING)
                .addModifiers(KModifier.OVERRIDE)
                .initializer("%S", source.lang)
                .build(),
        )
        builder.addProperty(
            PropertySpec.builder("versionId", INT)
                .addModifiers(KModifier.OVERRIDE)
                .initializer("%L", source.versionId)
                .build(),
        )
        builder.addProperty(
            PropertySpec.builder("id", LONG)
                .addModifiers(KModifier.OVERRIDE)
                .initializer("%LL", source.id)
                .build(),
        )
    }

    private fun addBaseUrlMembers(
        builder: TypeSpec.Builder,
        source: ResolvedSource,
        suffix: String?,
        superIsConfigurable: Boolean,
    ) {
        when (val baseUrl = source.baseUrl) {
            is BaseUrlSpec.Static -> {
                builder.addProperty(
                    PropertySpec.builder("baseUrl", STRING)
                        .addModifiers(KModifier.OVERRIDE)
                        .initializer("%S", baseUrl.url)
                        .build(),
                )
            }
            is BaseUrlSpec.Mirrors -> {
                val prefMirrorName = prefName("PREF_MIRROR", suffix)
                val mirrorsName = prefName("MIRRORS", suffix)
                val prefMirrorKey = prefKey("preferred_mirror", suffix)

                builder.addProperty(
                    PropertySpec.builder("preferences", SHARED_PREFERENCES, KModifier.PRIVATE)
                        .initializer("%M()", GET_PREFERENCES)
                        .build(),
                )

                builder.addProperty(
                    PropertySpec.builder("baseUrl", STRING)
                        .addModifiers(KModifier.OVERRIDE)
                        .getter(
                            FunSpec.getterBuilder()
                                .addCode(
                                    buildCodeBlock {
                                        add("val index = preferences.getString(%N, %S)!!.toInt()\n", prefMirrorName, "0")
                                        add(".coerceAtMost(%N.size - 1)\n", mirrorsName)
                                        add("return %N[index]\n", mirrorsName)
                                    },
                                )
                                .build(),
                        )
                        .build(),
                )

                builder.addFunction(
                    FunSpec.builder("setupPreferenceScreen")
                        .addModifiers(KModifier.OVERRIDE)
                        .addParameter("screen", PREFERENCE_SCREEN)
                        .addCode(
                            buildCodeBlock {
                                if (superIsConfigurable) add("super.setupPreferenceScreen(screen)\n")
                                add("%T(screen.context).apply {\n⇥", LIST_PREFERENCE)
                                add("key = %N\n", prefMirrorName)
                                add("title = %S\n", "Preferred mirror")
                                add("entries = %N\n", mirrorsName)
                                add("entryValues = Array(%N.size) { it.toString() }\n", mirrorsName)
                                add("summary = %S\n", "%s")
                                add("setDefaultValue(%S)\n", "0")
                                add("⇤}.also(screen::addPreference)\n")
                            },
                        )
                        .build(),
                )

                val companion = TypeSpec.companionObjectBuilder()
                    .addProperty(
                        PropertySpec.builder(prefMirrorName, STRING, KModifier.PRIVATE, KModifier.CONST)
                            .initializer("%S", prefMirrorKey)
                            .build(),
                    )
                    .addProperty(
                        PropertySpec.builder(mirrorsName, ARRAY.parameterizedBy(STRING), KModifier.PRIVATE)
                            .initializer(
                                CodeBlock.builder().apply {
                                    add("arrayOf(\n⇥")
                                    baseUrl.urls.forEach { add("%S,\n", it) }
                                    add("⇤)")
                                }.build(),
                            )
                            .build(),
                    )
                    .build()
                builder.addType(companion)
            }
            is BaseUrlSpec.Custom -> {
                val prefBaseName = prefName("PREF_BASE_URL", suffix)
                val prefDefaultName = prefName("PREF_DEFAULT_BASE_URL", suffix)
                val defaultName = prefName("DEFAULT_BASE_URL", suffix)
                val prefBaseKey = prefKey("overrideBaseUrl", suffix)
                val prefDefaultKey = prefKey("defaultBaseUrl", suffix)

                builder.addProperty(
                    PropertySpec.builder("preferences", SHARED_PREFERENCES, KModifier.PRIVATE)
                        .initializer(
                            CodeBlock.builder()
                                .add("%M {\n⇥", GET_PREFERENCES)
                                .add("val storedDefault = getString(%N, null)\n", prefDefaultName)
                                .add("if (storedDefault != %N) {\n⇥", defaultName)
                                .add("edit()\n⇥")
                                .add(".putString(%N, %N)\n", prefBaseName, defaultName)
                                .add(".putString(%N, %N)\n", prefDefaultName, defaultName)
                                .add(".apply()\n⇤")
                                .add("⇤}\n")
                                .add("⇤}")
                                .build(),
                        )
                        .build(),
                )

                builder.addProperty(
                    PropertySpec.builder("baseUrl", STRING)
                        .addModifiers(KModifier.OVERRIDE)
                        .getter(
                            FunSpec.getterBuilder()
                                .addStatement("return preferences.getString(%N, %N)!!", prefBaseName, defaultName)
                                .build(),
                        )
                        .build(),
                )

                builder.addFunction(
                    FunSpec.builder("setupPreferenceScreen")
                        .addModifiers(KModifier.OVERRIDE)
                        .addParameter("screen", PREFERENCE_SCREEN)
                        .addCode(
                            buildCodeBlock {
                                if (superIsConfigurable) add("super.setupPreferenceScreen(screen)\n")
                                add("%T(screen.context).apply {\n⇥", EDIT_TEXT_PREFERENCE)
                                add("key = %N\n", prefBaseName)
                                add("title = %S\n", "Custom base URL")
                                add("summary = %S + %N\n", "Leave blank to use default: ", defaultName)
                                add("setDefaultValue(%N)\n", defaultName)
                                add("dialogTitle = %S\n", "Custom base URL")
                                add("dialogMessage = %S + %N\n", "Default: ", defaultName)
                                add("⇤}.also(screen::addPreference)\n")
                            },
                        )
                        .build(),
                )

                val companion = TypeSpec.companionObjectBuilder()
                    .addProperty(
                        PropertySpec.builder(defaultName, STRING, KModifier.PRIVATE, KModifier.CONST)
                            .initializer("%S", baseUrl.defaultUrl)
                            .build(),
                    )
                    .addProperty(
                        PropertySpec.builder(prefBaseName, STRING, KModifier.PRIVATE, KModifier.CONST)
                            .initializer("%S", prefBaseKey)
                            .build(),
                    )
                    .addProperty(
                        PropertySpec.builder(prefDefaultName, STRING, KModifier.PRIVATE, KModifier.CONST)
                            .initializer("%S", prefDefaultKey)
                            .build(),
                    )
                    .build()
                builder.addType(companion)
            }
        }
    }

    private fun addOverrideProperties(builder: TypeSpec.Builder, overrides: Map<String, OverrideValue>) {
        overrides.forEach { (name, value) ->
            val (type, initializer) = when (value) {
                is OverrideValue.Str -> STRING to CodeBlock.of("%S", value.v)
                is OverrideValue.IntV -> INT to CodeBlock.of("%L", value.v)
                is OverrideValue.LongV -> LONG to CodeBlock.of("%LL", value.v)
                is OverrideValue.BoolV -> BOOLEAN to CodeBlock.of("%L", value.v)
            }
            builder.addProperty(
                PropertySpec.builder(name, type)
                    .addModifiers(KModifier.OVERRIDE)
                    .initializer(initializer)
                    .build(),
            )
        }
    }

    private fun generatedSourceName(extensionClass: String, suffix: String): String =
        "${extensionClass}Source_$suffix"

    private fun prefName(base: String, suffix: String?): String =
        if (suffix == null) base else "${base}_${suffix.uppercase()}"

    private fun prefKey(base: String, suffix: String?): String =
        if (suffix == null) base else "${base}_${suffix.lowercase()}"

    private fun suppressUnused() =
        com.squareup.kotlinpoet.AnnotationSpec.builder(ClassName("kotlin", "Suppress"))
            .useSiteTarget(com.squareup.kotlinpoet.AnnotationSpec.UseSiteTarget.FILE)
            .addMember("%S, %S", "unused", "RedundantSuppression")
            .build()

    private fun buildCodeBlock(block: CodeBlock.Builder.() -> Unit): CodeBlock =
        CodeBlock.builder().apply(block).build()
}
