package eu.kanade.tachiyomi.extension.pt.revistasequadrinhos

import eu.kanade.tachiyomi.source.model.Filter

open class UriPartFilter(
    displayName: String,
    private val vals: Array<Pair<String, String>>,
) : Filter.Select<String>(displayName, vals.map { it.first }.toTypedArray()) {
    fun toUriPart() = vals[state].second
}

class CategoryFilter : UriPartFilter("Categorias", categories)
class TagFilter : UriPartFilter("Tags", tags)

private val categories = arrayOf(
    Pair("Selecione uma categoria", ""),
    Pair("Ben 10", "ben-10"),
    Pair("Blacknwhite", "blacknwhite"),
    Pair("Caiu na Net", "caiu-na-net"),
    Pair("Cartoon Comic", "cartoon-comic"),
    Pair("Comics", "comics"),
    Pair("Comics Tube", "comics-tube"),
    Pair("Conto Erótico", "conto-erotico"),
    Pair("CrazyDad3D", "crazydad3d"),
    Pair("Croc", "croc"),
    Pair("Daval3d", "daval3d"),
    Pair("Dragon Ball", "dragon-ball-super"),
    Pair("English", "english"),
    Pair("Erotic Comic", "erotic-comic"),
    Pair("Espanhol", "espanhol"),
    Pair("Famosas Nuas", "famosas-nuas"),
    Pair("Felsala", "felsala"),
    Pair("Fred Perry", "fred-perry"),
    Pair("Furry", "furry"),
    Pair("Futanari", "futanari"),
    Pair("Gay Comics", "gay-comics"),
    Pair("Gilftoon", "gilftoon"),
    Pair("Gravity Falls", "gravity-falls"),
    Pair("Hentai", "hentai"),
    Pair("Hora de Aventura", "hora-de-aventura"),
    Pair("HQ 3D", "hq-3d"),
    Pair("HQ ADULTO", "hq-adulto"),
    Pair("HQ COMICS", "hq-comics"),
    Pair("HQ Furry", "hq-furry"),
    Pair("INCESTO", "incesto"),
    Pair("Inter-Racial", "inter-racial"),
    Pair("Jay-Marvel", "jay-marvel"),
    Pair("John Persons", "john-persons"),
    Pair("Kaos Comics", "kaos-comics"),
    Pair("League of Legends", "league-of-legends"),
    Pair("MelkorMancin", "melkormancin"),
    Pair("Milftoon", "milftoon"),
    Pair("Naruto", "naruto"),
    Pair("Os Simpsons", "os-simpsons"),
    Pair("Palcomix", "palcomix"),
    Pair("Paródias", "parodias"),
    Pair("Pegasus Smith", "pegasus-smith"),
    Pair("Peitos grandes", "peitos-grandes"),
    Pair("PigKing", "pigking"),
    Pair("Pokemon", "pokemon"),
    Pair("Popular Comics", "popular-comics"),
    Pair("Quadrinhos Eróticos", "quadrinhos-eroticos"),
    Pair("Revista Playboy", "revista-playboy"),
    Pair("Revista Sexy", "revista-sexy"),
    Pair("Revistas", "revistas"),
    Pair("Seiren", "seiren"),
    Pair("Sexy Clube", "sexy-clube"),
    Pair("Shemale", "shemale"),
    Pair("Spanish", "spanish"),
    Pair("Super-Heroínas", "super-heroinas"),
    Pair("Tracy Scops", "tracy-scops"),
    Pair("Tradução Exclusiva", "traducao-exclussiva"),
    Pair("VCP", "vcp"),
    Pair("Y3DF", "y3df"),
)

private val tags = arrayOf(
    Pair("Selecione uma tag", ""),
    Pair("3D", "3d"),
    Pair("3D Comix", "3d-comix"),
    Pair("3d incest", "3d-incest"),
    Pair("3D Porn Comic", "3d-porn-comic"),
    Pair("3D Porn Comicy3df", "3d-porn-comicy3df"),
    Pair("A Casa Errada", "a-casa-errada"),
    Pair("academia", "academia"),
    Pair("Accel Art", "accel-art"),
    Pair("adventure", "adventure"),
    Pair("Adventures", "adventures"),
    Pair("After Party 02", "after-party-02"),
    Pair("ahegao", "ahegao"),
    Pair("Ai Papai", "ai-papai"),
    Pair("alien", "alien"),
    Pair("alien girl", "alien-girl"),
    Pair("alongamento", "alongamento"),
    Pair("Amanda", "amanda"),
    Pair("anal", "anal"),
    Pair("anal sex", "anal-sex"),
    Pair("android 18", "android-18"),
    Pair("Animal", "animal"),
    Pair("anime", "anime"),
    Pair("armadilha", "armadilha"),
    Pair("aroma sensei", "aroma-sensei"),
    Pair("As aventuras de Lia", "as-aventuras-de-lia"),
    Pair("As Blogueirinhas", "as-blogueirinhas"),
    Pair("ass expansion", "ass-expansion"),
    Pair("aventura", "aventura"),
    Pair("Aventuras", "aventuras"),
    Pair("avó", "avo"),
    Pair("bart simpson", "bart-simpson"),
    Pair("Batman", "batman"),
    Pair("Bbm", "bbm"),
    Pair("bbw", "bbw"),
    Pair("bdsm", "bdsm"),
    Pair("bdsm-bondage", "bdsm-bondage"),
    Pair("beauty mark", "beauty-mark"),
    Pair("bella da semana", "bella-da-semana"),
    Pair("Ben 10", "ben-10"),
    Pair("Big Ass", "big-ass"),
    Pair("big balls", "big-balls"),
    Pair("big black dick", "big-black-dick"),
    Pair("Big Boobs", "big-boobs"),
    Pair("big breast", "big-breast"),
    Pair("big breasts", "big-breasts"),
    Pair("Big Cock", "big-cock"),
    Pair("big dick", "big-dick"),
    Pair("big lips", "big-lips"),
    Pair("big penis", "big-penis"),
    Pair("big tits", "big-tits"),
    Pair("bigass", "bigass"),
    Pair("bikini", "bikini"),
    Pair("biquíni", "biquini"),
    Pair("bisexual", "bisexual"),
    Pair("black cock", "black-cock"),
    Pair("blackmail", "blackmail"),
    Pair("blacknwhite", "blacknwhite"),
    Pair("BlackNWhitecomics", "blacknwhitecomics"),
    Pair("blonde", "blonde"),
    Pair("blowjob", "blowjob"),
    Pair("Boceta", "boceta"),
    Pair("boceta novinha", "boceta-novinha"),
    Pair("bodysuit", "bodysuit"),
    Pair("bondage", "bondage"),
    Pair("boquete", "boquete"),
    Pair("boruto", "boruto"),
    Pair("brasilbukkake", "brasilbukkake"),
    Pair("breast expansion", "breast-expansion"),
    Pair("brinquedos sexuais", "brinquedos-sexuais"),
    Pair("bro-sis", "bro-sis"),
    Pair("buceta", "buceta"),
    Pair("buceta da novinha", "buceta-da-novinha"),
    Pair("buceta novinha", "buceta-novinha"),
    Pair("bukkake", "bukkake"),
    Pair("bunda", "bunda"),
    Pair("bunda da novinha", "bunda-da-novinha"),
    Pair("bunda grande", "bunda-grande"),
    Pair("bunny girl", "bunny-girl"),
    Pair("busty", "busty"),
    Pair("Caiu na Net", "caiu-na-net"),
    Pair("camshot", "camshot"),
    Pair("caricaturas", "caricaturas"),
    Pair("Cartoon", "cartoon"),
    Pair("Cartoon Comics", "cartoon-comics"),
    Pair("Cartoon Porno", "cartoon-porno"),
    Pair("Cartoon Reality", "cartoon-reality"),
    Pair("Casa Bonita 6", "casa-bonita-6"),
    Pair("Casa da Mãe Joana", "casa-da-mae-joana"),
    Pair("casada", "casada"),
    Pair("casadas", "casadas"),
    Pair("catboy", "catboy"),
    Pair("catgirl", "catgirl"),
    Pair("celebridades", "celebridades"),
    Pair("Celebridades nuas", "celebridades-nuas"),
    Pair("Chaves", "chaves"),
    Pair("cheating", "cheating"),
    Pair("chesare", "chesare"),
    Pair("chichi", "chichi"),
    Pair("Chloe", "chloe"),
    Pair("Coelhinha", "coelhinha"),
    Pair("collar", "collar"),
    Pair("Colorido", "colorido"),
    Pair("comic", "comic"),
    Pair("Comiccrazydad3d", "comiccrazydad3d"),
    Pair("Comics", "comics"),
    Pair("Comics Porno", "comics-porno"),
    Pair("Comix", "comix"),
    Pair("condom", "condom"),
    Pair("Conto Erótico", "conto-erotico"),
    Pair("Contos Eróticos", "contos-eroticos"),
    Pair("controle mental", "controle-mental"),
    Pair("corno", "corno"),
    Pair("corruption", "corruption"),
    Pair("Cousin", "cousin"),
    Pair("cowgirl", "cowgirl"),
    Pair("crazydad3d", "crazydad3d"),
    Pair("Creampie", "creampie"),
    Pair("crempie", "crempie"),
    Pair("Croc", "croc"),
    Pair("crossdressing", "crossdressing"),
    Pair("cuckold", "cuckold"),
    Pair("cum shot", "cum-shot"),
    Pair("Cum shots", "cum-shots"),
    Pair("Cum swallow", "cum-swallow"),
    Pair("cumshot", "cumshot"),
    Pair("cunilíngua", "cunilingua"),
    Pair("Cunnilingus", "cunnilingus"),
    Pair("Dad-Daughter", "dad-daughter"),
    Pair("Danny Phantom", "danny-phantom"),
    Pair("dark skin", "dark-skin"),
    Pair("daughter", "daughter"),
    Pair("daval3d", "daval3d"),
    Pair("deepthroat", "deepthroat"),
    Pair("Defloração", "defloracao"),
    Pair("Deformed", "deformed"),
    Pair("demon girl", "demon-girl"),
    Pair("Detenção", "detencao"),
    Pair("dickgirl", "dickgirl"),
    Pair("dickgirl on male", "dickgirl-on-male"),
    Pair("dilf", "dilf"),
    Pair("dirtycomics", "dirtycomics"),
    Pair("dog boy", "dog-boy"),
    Pair("dog girl", "dog-girl"),
    Pair("doggystyle", "doggystyle"),
    Pair("Domination", "domination"),
    Pair("dominação", "dominacao"),
    Pair("dona de casa", "dona-de-casa"),
    Pair("Dona Mama", "dona-mama"),
    Pair("donas de casa voluptuosas", "donas-de-casa-voluptuosas"),
    Pair("dotado", "dotado"),
    Pair("Dotados", "dotados"),
    Pair("double anal", "double-anal"),
    Pair("double penetration", "double-penetration"),
    Pair("Dragon Ball", "dragon-ball"),
    Pair("dragon ball super", "dragon-ball-super"),
    Pair("dragon ball x", "dragon-ball-x"),
    Pair("dragon ball z", "dragon-ball-z"),
    Pair("Drah Navlag", "drah-navlag"),
    Pair("Drawn Sex", "drawn-sex"),
    Pair("Drunk", "drunk"),
    Pair("Dsan", "dsan"),
    Pair("Dupla penetração", "dupla-penetracao"),
    Pair("elf", "elf"),
    Pair("elfo", "elfo"),
    Pair("emmabrave", "emmabrave"),
    Pair("empregada doméstica", "empregada-domestica"),
    Pair("Erotic", "erotic"),
    Pair("Erotic Comics", "erotic-comics"),
    Pair("Eróticos", "eroticos"),
    Pair("Espanhol", "espanhol"),
    Pair("estilo cachorrinho", "estilo-cachorrinho"),
    Pair("Euro", "euro"),
    Pair("Exhibitionism", "exhibitionism"),
    Pair("expansão de seios", "expansao-de-seios"),
    Pair("eyemask", "eyemask"),
    Pair("Familia Guy", "familia-guy"),
    Pair("family", "family"),
    Pair("Family Guy", "family-guy"),
    Pair("Family Sex", "family-sex"),
    Pair("family-incest", "family-incest"),
    Pair("Famosas Gostosas", "famosas-gostosas"),
    Pair("famosas nuas", "famosas-nuas-2"),
    Pair("Família", "familia"),
    Pair("fantasia", "fantasia"),
    Pair("Fantasy", "fantasy"),
    Pair("father-daughter", "father-daughter"),
    Pair("felsala", "felsala"),
    Pair("females only", "females-only"),
    Pair("femdom", "femdom"),
    Pair("feminization", "feminization"),
    Pair("feminização", "feminizacao"),
    Pair("ffm threesome", "ffm-threesome"),
    Pair("filha", "filha"),
    Pair("filming", "filming"),
    Pair("Fingering", "fingering"),
    Pair("fisting", "fisting"),
    Pair("foda de peitos", "foda-de-peitos"),
    Pair("foda de tetas", "foda-de-tetas"),
    Pair("Footjob", "footjob"),
    Pair("forced", "forced"),
    Pair("fotos amadoras", "fotos-amadoras"),
    Pair("Fotos de Bundas", "fotos-de-bundas"),
    Pair("Fotos Digitais", "fotos-digitais"),
    Pair("freckles", "freckles"),
    Pair("fred perry", "fred-perry"),
    Pair("freira", "freira"),
    Pair("Fright Night", "fright-night"),
    Pair("Frozen", "frozen"),
    Pair("Full Color", "full-color"),
    Pair("Furry", "furry"),
    Pair("Futanari", "futanari"),
    Pair("futanaria", "futanaria"),
    Pair("Gangbang", "gangbang"),
    Pair("Garganta Profunda", "garganta-profunda"),
    Pair("gay", "gay"),
    Pair("Gender Bender", "gender-bender"),
    Pair("gilftoon", "gilftoon"),
    Pair("glasses", "glasses"),
    Pair("gostosa", "gostosa"),
    Pair("gozada", "gozada"),
    Pair("Gozando a Vida Adoidado", "gozando-a-vida-adoidado"),
    Pair("gozar na boca", "gozar-na-boca"),
    Pair("grandes paus", "grandes-paus"),
    Pair("grandmother", "grandmother"),
    Pair("Gravity falls", "gravity-falls"),
    Pair("group", "group"),
    Pair("Group Sex", "group-sex"),
    Pair("grupo", "grupo"),
    Pair("H-Mangá", "h-manga"),
    Pair("hairy", "hairy"),
    Pair("handjob", "handjob"),
    Pair("Hardcore", "hardcore"),
    Pair("harem", "harem"),
    Pair("Harley Quinn", "harley-quinn"),
    Pair("Harry Potter", "harry-potter"),
    Pair("Hentai", "hentai"),
    Pair("Hentai Comics", "hentai-comics"),
    Pair("Hentai Incesto", "hentai-incesto"),
    Pair("hermit moth", "hermit-moth"),
    Pair("Heróis Porno", "herois-porno"),
    Pair("high heels", "high-heels"),
    Pair("Hinata", "hinata"),
    Pair("hinata hyuga", "hinata-hyuga"),
    Pair("Homem Aranha", "homem-aranha"),
    Pair("Hora de aventura", "hora-de-aventura"),
    Pair("housewife", "housewife"),
    Pair("HQ", "hq"),
    Pair("HQ Adulto", "hq-adulto"),
    Pair("HQ Comics", "hq-comics"),
    Pair("HQ de Sexo", "hq-de-sexo"),
    Pair("HQ Erótico", "hq-erotico"),
    Pair("HQ Eróticos Comics", "hq-eroticos-comics"),
    Pair("HQPorno", "hqporno"),
    Pair("huge breasts", "huge-breasts"),
    Pair("huge penis", "huge-penis"),
    Pair("human on furry", "human-on-furry"),
    Pair("impregnation", "impregnation"),
    Pair("impregnação", "impregnacao"),
    Pair("incest", "incest"),
    Pair("incesto", "incesto"),
    Pair("inflation", "inflation"),
    Pair("Inter-racial", "inter-racial"),
    Pair("Interracial", "interracial"),
    Pair("jab-comix", "jab-comix"),
    Pair("jabcomix", "jabcomix"),
    Pair("jay-marvel", "jay-marvel"),
    Pair("jmoz", "jmoz"),
    Pair("jmoz comix", "jmoz-comix"),
    Pair("John Persons", "john-persons"),
    Pair("Kaos", "kaos"),
    Pair("karmagik", "karmagik"),
    Pair("kennycomix", "kennycomix"),
    Pair("Kim Possible", "kim-possible"),
    Pair("kissing", "kissing"),
    Pair("Kogeikun", "kogeikun"),
    Pair("lactation", "lactation"),
    Pair("lambendo buceta", "lambendo-buceta"),
    Pair("Lara Croft", "lara-croft"),
    Pair("Latex", "latex"),
    Pair("leite", "leite"),
    Pair("lesbian", "lesbian"),
    Pair("Lesbians", "lesbians"),
    Pair("Lia", "lia"),
    Pair("Lingerie", "lingerie"),
    Pair("Locofuria", "locofuria"),
    Pair("loiras", "loiras"),
    Pair("lésbica", "lesbica"),
    Pair("Lésbicas", "lesbicas"),
    Pair("madura", "madura"),
    Pair("maduro", "maduro"),
    Pair("Maid", "maid"),
    Pair("males only", "males-only"),
    Pair("Manga", "manga"),
    Pair("Manga Hentai", "manga-hentai"),
    Pair("Mangas", "mangas"),
    Pair("mano", "mano"),
    Pair("mano-irmã", "mano-irma"),
    Pair("Marge simpson", "marge-simpson"),
    Pair("maricas", "maricas"),
    Pair("masturbation", "masturbation"),
    Pair("masturbação", "masturbacao"),
    Pair("mature", "mature"),
    Pair("meias", "meias"),
    Pair("melkor mancin", "melkor-mancin"),
    Pair("Melkormancin", "melkormancin"),
    Pair("Mexican", "mexican"),
    Pair("MILF", "milf"),
    Pair("Milftoon", "milftoon"),
    Pair("mind control", "mind-control"),
    Pair("mom-n-son", "mom-n-son"),
    Pair("mom-son", "mom-son"),
    Pair("Moms help", "moms-help"),
    Pair("mon-n-filho", "mon-n-filho"),
    Pair("mon-n-son", "mon-n-son"),
    Pair("monster", "monster"),
    Pair("monster girl", "monster-girl"),
    Pair("Monster Girls", "monster-girls"),
    Pair("monsters", "monsters"),
    Pair("monstros", "monstros"),
    Pair("moose", "moose"),
    Pair("MORENA", "morena"),
    Pair("mostrando a boceta", "mostrando-a-boceta"),
    Pair("mother", "mother"),
    Pair("mother and son", "mother-and-son"),
    Pair("Multishow", "multishow"),
    Pair("muscle", "muscle"),
    Pair("my bad bunny", "my-bad-bunny"),
    Pair("my dear old sister", "my-dear-old-sister"),
    Pair("Mãe", "mae"),
    Pair("mãe e filha", "mae-e-filha"),
    Pair("Mãe e Filho", "mae-e-filho"),
    Pair("músculo", "musculo"),
    Pair("nakadashi", "nakadashi"),
    Pair("Naruto", "naruto"),
    Pair("Netorare", "netorare"),
    Pair("NLT Comics", "nlt-comics"),
    Pair("NLT Media", "nlt-media"),
    Pair("novinha", "novinha"),
    Pair("novinha nua", "novinha-nua"),
    Pair("Novinhas", "novinhas"),
    Pair("novinhas nuas", "novinhas-nuas"),
    Pair("nua", "nua"),
    Pair("Nun Isabella", "nun-isabella"),
    Pair("o Sogro Tarado", "o-sogro-tarado"),
    Pair("O Sogro Tarado 2", "o-sogro-tarado-2"),
    Pair("O Som do Prazer", "o-som-do-prazer"),
    Pair("Office", "office"),
    Pair("old man", "old-man"),
    Pair("oral", "oral"),
    Pair("oral sex", "oral-sex"),
    Pair("Orc", "orc"),
    Pair("orgia", "orgia"),
    Pair("orgy", "orgy"),
    Pair("Os Flintstones", "os-flintstones"),
    Pair("Os Incríveis", "os-incriveis"),
    Pair("Os Padrinhos Mágicos", "os-padrinhos-magicos"),
    Pair("Os sacanas petisco", "os-sacanas-petisco"),
    Pair("Os Simpsons", "os-simpsons"),
    Pair("Os Simptoons", "os-simptoons"),
    Pair("Padrinhos Mágicos", "padrinhos-magicos"),
    Pair("Pai e Filha", "pai-e-filha"),
    Pair("pai louco", "pai-louco"),
    Pair("pai-filha", "pai-filha"),
    Pair("paizuri", "paizuri"),
    Pair("Palcomix", "palcomix"),
    Pair("Papito", "papito"),
    Pair("Parodia", "parodia"),
    Pair("parodies", "parodies"),
    Pair("parody", "parody"),
    Pair("Party Time", "party-time"),
    Pair("paródias", "parodias"),
    Pair("pau grande", "pau-grande"),
    Pair("pau no cu", "pau-no-cu"),
    Pair("pau preto grande", "pau-preto-grande"),
    Pair("pegasus smith", "pegasus-smith"),
    Pair("peito grande", "peito-grande"),
    Pair("peitos", "peitos"),
    Pair("peitos enormes", "peitos-enormes"),
    Pair("peitos foda", "peitos-foda"),
    Pair("peitos grandes", "peitos-grandes"),
    Pair("Peituda", "peituda"),
    Pair("peitudas", "peitudas"),
    Pair("Peitões", "peitoes"),
    Pair("pelada", "pelada"),
    Pair("pele escura", "pele-escura"),
    Pair("peludo", "peludo"),
    Pair("personal trainer", "personal-trainer"),
    Pair("piercing", "piercing"),
    Pair("pig king", "pig-king"),
    Pair("PigKing", "pigking"),
    Pair("pink pawg", "pink-pawg"),
    Pair("Pokemon", "pokemon"),
    Pair("ponytail", "ponytail"),
    Pair("porcaria", "porcaria"),
    Pair("porquinho", "porquinho"),
    Pair("Porra", "porra"),
    Pair("Portuguese", "portuguese"),
    Pair("pregnant", "pregnant"),
    Pair("Priminha", "priminha"),
    Pair("Priminha Gostosa", "priminha-gostosa"),
    Pair("prostitution", "prostitution"),
    Pair("punheta", "punheta"),
    Pair("pussy licking", "pussy-licking"),
    Pair("putinha nerd", "putinha-nerd"),
    Pair("pênis grande", "penis-grande"),
    Pair("Quadrinhos Eróticos (tag)", "quadrinhos-eroticos"),
    Pair("Quadrinhos", "quadrinhos"),
    Pair("Quadrinhos Eróticos em português", "quadrinhos-eroticos-em-portugues"),
    Pair("rabies", "rabies"),
    Pair("Raio-X", "raio-x"),
    Pair("rape", "rape"),
    Pair("Revista Playboy", "revista-playboy"),
    Pair("Revista Sexy", "revista-sexy"),
    Pair("Revistas e Quadrinhos", "revistas-e-quadrinhos"),
    Pair("robot", "robot"),
    Pair("Ryan", "ryan"),
    Pair("salto alto", "salto-alto"),
    Pair("Schoolgirl", "schoolgirl"),
    Pair("Scooby Doo", "scooby-doo"),
    Pair("Seduced", "seduced"),
    Pair("Sedução", "seducao"),
    Pair("seios enormes", "seios-enormes"),
    Pair("seios grandes", "seios-grandes"),
    Pair("Seiren", "seiren"),
    Pair("Sex and Magic", "sex-and-magic"),
    Pair("sex toys", "sex-toys"),
    Pair("sexgazer", "sexgazer"),
    Pair("sexo a três", "sexo-a-tres"),
    Pair("sexo anal", "sexo-anal"),
    Pair("Sexo em Família", "sexo-em-familia"),
    Pair("sexo em grupo", "sexo-em-grupo"),
    Pair("Sexo em Quadrinhos", "sexo-em-quadrinhos"),
    Pair("sexo grupal", "sexo-grupal"),
    Pair("sexo oral", "sexo-oral"),
    Pair("sexo vaginal", "sexo-vaginal"),
    Pair("Sexy", "sexy"),
    Pair("sexy clube", "sexy-clube-2"),
    Pair("Sexy Sleep Walking", "sexy-sleep-walking"),
    Pair("SexyClube", "sexyclube"),
    Pair("Shadbase", "shadbase"),
    Pair("Shemale", "shemale"),
    Pair("shorts de ginástica", "shorts-de-ginastica"),
    Pair("Sidney 3", "sidney-3"),
    Pair("Simpsons", "simpsons"),
    Pair("Sister", "sister"),
    Pair("sleinad flar", "sleinad-flar"),
    Pair("slut", "slut"),
    Pair("small breasts", "small-breasts"),
    Pair("smell", "smell"),
    Pair("Sogro tarado", "sogro-tarado"),
    Pair("sole dickgirl", "sole-dickgirl"),
    Pair("sole female", "sole-female"),
    Pair("sole male", "sole-male"),
    Pair("solo", "solo"),
    Pair("son-mom", "son-mom"),
    Pair("Sonic", "sonic"),
    Pair("spanking", "spanking"),
    Pair("Spider Man", "spider-man"),
    Pair("Spiderman", "spiderman"),
    Pair("spy", "spy"),
    Pair("star vs. the forces of evil", "star-vs-the-forces-of-evil"),
    Pair("Star Wars", "star-wars"),
    Pair("Steven Universe", "steven-universe"),
    Pair("stockings", "stockings"),
    Pair("stomach deformation", "stomach-deformation"),
    Pair("Straight", "straight"),
    Pair("Straight Shota", "straight-shota"),
    Pair("Suky-Tu", "suky-tu"),
    Pair("sunglasses", "sunglasses"),
    Pair("super heroina", "super-heroina"),
    Pair("super-heroi", "super-heroi"),
    Pair("Super-herois", "super-herois"),
    Pair("Supergirl", "supergirl"),
    Pair("Supergreen", "supergreen"),
    Pair("Superheroine", "superheroine"),
    Pair("superheros", "superheros"),
    Pair("suruba", "suruba"),
    Pair("swestern", "swestern"),
    Pair("swimsuit", "swimsuit"),
    Pair("taboo", "taboo"),
    Pair("Taboolicious", "taboolicious"),
    Pair("tall girl", "tall-girl"),
    Pair("Tara", "tara"),
    Pair("tatuagem", "tatuagem"),
    Pair("teacher", "teacher"),
    Pair("teacher-student", "teacher-student"),
    Pair("Teen", "teen"),
    Pair("Teen Titans", "teen-titans"),
    Pair("Tentacles", "tentacles"),
    Pair("The Collar", "the-collar"),
    Pair("The House", "the-house"),
    Pair("The Simpsons", "the-simpsons"),
    Pair("threesome", "threesome"),
    Pair("tia", "tia"),
    Pair("Titfuck", "titfuck"),
    Pair("tits fuck", "tits-fuck"),
    Pair("titsjob", "titsjob"),
    Pair("Tomb Raider", "tomb-raider"),
    Pair("tomboy", "tomboy"),
    Pair("tomgirl", "tomgirl"),
    Pair("tracy scops", "tracy-scops"),
    Pair("traduzidas", "traduzidas"),
    Pair("traindo", "traindo"),
    Pair("traição", "traicao"),
    Pair("Transformation", "transformation"),
    Pair("Travesti", "travesti"),
    Pair("trio", "trio"),
    Pair("Tsunade", "tsunade"),
    Pair("tufos", "tufos"),
    Pair("Turma do Chaves", "turma-do-chaves"),
    Pair("Um tesao de priminha", "um-tesao-de-priminha"),
    Pair("Uncensored", "uncensored"),
    Pair("unusual pupils", "unusual-pupils"),
    Pair("vadia", "vadia"),
    Pair("vagabunda", "vagabunda"),
    Pair("vcpvip", "vcpvip"),
    Pair("velha", "velha"),
    Pair("velho", "velho"),
    Pair("videl", "videl"),
    Pair("violencia", "violencia"),
    Pair("virgin", "virgin"),
    Pair("voyeur", "voyeur"),
    Pair("western", "western"),
    Pair("witchking00", "witchking00"),
    Pair("X-Men", "x-men"),
    Pair("x-ray", "x-ray"),
    Pair("Y3DF", "y3df"),
    Pair("yaoi", "yaoi"),
    Pair("young", "young"),
    Pair("Young justice", "young-justice"),
    Pair("yuri", "yuri"),
    Pair("zombie", "zombie"),
    Pair("óculos", "oculos"),
)
