package eu.kanade.tachiyomi.extension.vi.truyentvn

import eu.kanade.tachiyomi.source.model.Filter
import eu.kanade.tachiyomi.source.model.FilterList

fun getFilters(): FilterList = FilterList(
    Filter.Header("Lưu ý: Bộ lọc không dùng chung với tìm kiếm theo từ khóa"),
    Filter.Separator(),
    CountryFilter(),
    TopicFilter(),
    GenreFilter(),
)

class CountryFilter : UriPartFilter("Quốc Gia", COUNTRY_VALUES)

class TopicFilter : UriPartFilter("Chủ đề", TOPIC_VALUES)

class GenreFilter : UriPartFilter("Thể loại", GENRE_VALUES)

open class UriPartFilter(displayName: String, values: Array<Pair<String, String?>>) : Filter.Select<String>(displayName, values.map { it.first }.toTypedArray()) {
    private val options = values
    fun toUriPart(): String? = options[state].second
}

private val COUNTRY_VALUES = arrayOf(
    "Tất cả" to null,
    "Nhật Bản" to "/country/nhat-ban",
    "Trung Quốc" to "/country/trung-quoc",
    "Hàn Quốc" to "/country/han-quoc",
    "Việt Nam" to "/country/viet-nam",
)

private val TOPIC_VALUES = arrayOf(
    "Tất cả" to null,
    "Có Che" to "/danh-muc/co-che",
    "Truyện Con Trai" to "/danh-muc/truyen-con-trai",
    "Truyện Tranh 18+" to "/danh-muc/truyen-tranh-18",
    "Manga" to "/danh-muc/manga",
    "One Shot" to "/danh-muc/one-shot",
    "Truyện Màu" to "/danh-muc/truyen-mau",
    "Doujinshi" to "/danh-muc/doujinshi",
    "Manhua" to "/danh-muc/manhua",
    "Truyện Con Gái" to "/danh-muc/truyen-con-gai",
    "Không Che" to "/danh-muc/khong-che",
    "Manhwa" to "/danh-muc/manhwa",
    "Series" to "/danh-muc/series",
    "Webtoon" to "/danh-muc/webtoon",
    "Truyện Việt" to "/danh-muc/truyen-viet",
    "Truyện Thiếu Nhi" to "/danh-muc/truyen-thieu-nhi",
    "Truyện Scan" to "/danh-muc/truyen-scan",
    "Tạp Chí Truyện Tranh" to "/danh-muc/tap-chi-truyen-tranh",
    "Hình Hentai" to "/danh-muc/hinh-hentai",
)

private val GENRE_VALUES = arrayOf(
    "Tất cả" to null,
    "Adult" to "/the-loai/adult",
    "Romance" to "/the-loai/romance",
    "Comedy" to "/the-loai/comedy",
    "Action" to "/the-loai/action",
    "Drama" to "/the-loai/drama",
    "Group" to "/the-loai/group",
    "Nữ Sinh" to "/the-loai/nu-sinh",
    "School Life" to "/the-loai/school-life",
    "Ngôn Tình" to "/the-loai/ngon-tinh",
    "Fantasy" to "/the-loai/fantasy",
    "Shoujo" to "/the-loai/shoujo",
    "Adventure" to "/the-loai/adventure",
    "Ntr" to "/the-loai/ntr",
    "Loli" to "/the-loai/loli",
    "Shounen" to "/the-loai/shounen",
    "Smut" to "/the-loai/smut",
    "Ecchi" to "/the-loai/ecchi",
    "Slice of Life" to "/the-loai/slice-of-life",
    "Ahegao" to "/the-loai/ahegao",
    "Milf" to "/the-loai/milf",
    "Supernatural" to "/the-loai/supernatural",
    "Housewife" to "/the-loai/housewife",
    "Mystery" to "/the-loai/mystery",
    "Harem" to "/the-loai/harem",
    "Mind Break" to "/the-loai/mind-break",
    "Seinen" to "/the-loai/seinen",
    "Comic" to "/the-loai/comic",
    "Horror" to "/the-loai/horror",
    "One shot" to "/the-loai/one-shot",
    "Đồ Bơi" to "/the-loai/do-boi",
    "Hiện Đại" to "/the-loai/hien-dai",
    "Sci-fi" to "/the-loai/sci-fi",
    "Cổ Đại" to "/the-loai/co-dai",
    "Xuyên Không" to "/the-loai/xuyen-khong",
    "Martial Arts" to "/the-loai/martial-arts",
    "Big Breasts" to "/the-loai/big-breasts",
    "Giáo Viên" to "/the-loai/giao-vien",
    "Chuyển Sinh" to "/the-loai/chuyen-sinh",
    "Mind Control" to "/the-loai/mind-control",
    "Historical" to "/the-loai/historical",
    "Psychological" to "/the-loai/psychological",
    "Mature" to "/the-loai/mature",
    "Shoujo Ai" to "/the-loai/shoujo-ai",
    "Đam Mỹ" to "/the-loai/dam-my",
    "Blowjob" to "/the-loai/blowjob",
    "Tragedy" to "/the-loai/tragedy",
    "Big Dick" to "/the-loai/big-dick",
    "Manhwa" to "/the-loai/manhwa",
    "Gender Bender" to "/the-loai/gender-bender",
    "Lxhentai" to "/the-loai/lxhentai",
    "Animal Girl" to "/the-loai/animal-girl",
    "Monster Girl" to "/the-loai/monster-girl",
    "Gangbang" to "/the-loai/gangbang",
    "Hentai 3D" to "/the-loai/hentai-3d",
    "Trinh Thám" to "/the-loai/trinh-tham",
    "Josei" to "/the-loai/josei",
    "Yaoi" to "/the-loai/yaoi",
    "Sports" to "/the-loai/sports",
    "Boylove" to "/the-loai/boylove",
    "Elf" to "/the-loai/elf",
    "Quái Vật" to "/the-loai/quai-vat",
    "Cg" to "/the-loai/cg",
    "Futanari" to "/the-loai/futanari",
    "Kogal" to "/the-loai/kogal",
    "Hầu Gái" to "/the-loai/hau-gai",
    "Full Color" to "/the-loai/full-color",
    "Uncensored" to "/the-loai/uncensored",
    "Anal" to "/the-loai/anal",
    "Sole Male" to "/the-loai/sole-male",
    "Sole Female" to "/the-loai/sole-female",
    "Yuri" to "/the-loai/yuri",
    "Rape" to "/the-loai/rape",
    "Xúc Tua" to "/the-loai/xuc-tua",
    "Con Gái" to "/the-loai/con-gai",
    "Cặc Bự" to "/the-loai/cac-bu",
    "Blow Job" to "/the-loai/blow-job",
    "Soft Yaoi" to "/the-loai/soft-yaoi",
    "Cosplay" to "/the-loai/cosplay",
    "Three Some" to "/the-loai/three-some",
    "Soft Yuri" to "/the-loai/soft-yuri",
    "Breast Sucking" to "/the-loai/breast-sucking",
    "Shounen Ai" to "/the-loai/shounen-ai",
    "Y Tá" to "/the-loai/y-ta",
    "Schoolgirl Outfit" to "/the-loai/schoolgirl-outfit",
    "Boy Love" to "/the-loai/boy-love",
    "Virgin" to "/the-loai/virgin",
    "Schoolgirl Uniform" to "/the-loai/schoolgirl-uniform",
    "Paizuri" to "/the-loai/paizuri",
    "Vếu To" to "/the-loai/veu-to",
    "Mắt Kính" to "/the-loai/mat-kinh",
    "Mother" to "/the-loai/mother",
    "Handjob" to "/the-loai/handjob",
    "Incest" to "/the-loai/incest",
    "Stockings" to "/the-loai/stockings",
    "16+" to "/the-loai/16",
    "Lếu Lều" to "/the-loai/leu-leu",
    "Squirting" to "/the-loai/squirting",
    "Socks" to "/the-loai/socks",
    "First Time" to "/the-loai/first-time",
    "Trap" to "/the-loai/trap",
    "Pregnant" to "/the-loai/pregnant",
    "Dirty Old Man" to "/the-loai/dirty-old-man",
    "Vanilla" to "/the-loai/vanilla",
    "Fingering" to "/the-loai/fingering",
    "Comic 18+" to "/the-loai/comic-18",
    "Toys" to "/the-loai/toys",
    "Hành Động" to "/the-loai/hanh-dong",
    "Mecha" to "/the-loai/mecha",
    "Small Breasts" to "/the-loai/small-breasts",
    "Teacher" to "/the-loai/teacher",
    "Truyện Dài" to "/the-loai/truyen-dai",
    "Anime" to "/the-loai/anime",
    "Glasses" to "/the-loai/glasses",
    "Condom" to "/the-loai/condom",
    "Masturbation" to "/the-loai/masturbation",
    "Scat" to "/the-loai/scat",
    "Blowjobs" to "/the-loai/blowjobs",
    "Slave" to "/the-loai/slave",
    "Webtoon" to "/the-loai/webtoon",
    "Swimsuit" to "/the-loai/swimsuit",
    "Femdom" to "/the-loai/femdom",
    "Defloration" to "/the-loai/defloration",
    "Guro" to "/the-loai/guro",
    "Truyện Tranh" to "/the-loai/truyen-tranh",
    "Tự Sướng" to "/the-loai/tu-suong",
    "Nakadashi" to "/the-loai/nakadashi",
    "Double Penetration" to "/the-loai/double-penetration",
    "Lingerie" to "/the-loai/lingerie",
    "Artist" to "/the-loai/artist",
    "Bbm" to "/the-loai/bbm",
    "Hentai Cube" to "/the-loai/hentai-cube",
    "Bdsm" to "/the-loai/bdsm",
    "Story Arc" to "/the-loai/story-arc",
    "Beast" to "/the-loai/beast",
    "Manga" to "/the-loai/manga",
    "Monster" to "/the-loai/monster",
    "Maid" to "/the-loai/maid",
    "Insect" to "/the-loai/insect",
    "Schoolboy Outfit" to "/the-loai/schoolboy-outfit",
    "Furry" to "/the-loai/furry",
    "Virginity" to "/the-loai/virginity",
    "Office Lady" to "/the-loai/office-lady",
    "Big Ass" to "/the-loai/big-ass",
    "Big Vagina" to "/the-loai/big-vagina",
    "Bukkake" to "/the-loai/bukkake",
    "Hentaivn" to "/the-loai/hentaivn",
    "Abo" to "/the-loai/abo",
    "Cooking" to "/the-loai/cooking",
    "Ugly Bastard" to "/the-loai/ugly-bastard",
    "Big Penis" to "/the-loai/big-penis",
    "Footjob" to "/the-loai/footjob",
    "Cốt Truyện" to "/the-loai/cot-truyen",
    "School Uniform" to "/the-loai/school-uniform",
    "Milfs" to "/the-loai/milfs",
    "Foursome" to "/the-loai/foursome",
    "Live action" to "/the-loai/live-action",
    "1X1" to "/the-loai/1x1",
    "Nhóm" to "/the-loai/nhom",
    "Phiêu Lưu" to "/the-loai/phieu-luu",
    "Short" to "/the-loai/short",
    "Schoolgirl" to "/the-loai/schoolgirl",
    "Cheating" to "/the-loai/cheating",
    "Âu Cổ" to "/the-loai/au-co",
    "Loạn Luân Chị Em" to "/the-loai/loan-luan-chi-em",
    "Gia Đình" to "/the-loai/gia-dinh",
    "Nun" to "/the-loai/nun",
    "Che Ít" to "/the-loai/che-it",
    "Truyện Tranh 18+" to "/the-loai/truyen-tranh-18",
    "Mông To" to "/the-loai/mong-to",
    "Hiện Thực" to "/the-loai/hien-thuc",
    "Sex Toys" to "/the-loai/sex-toys",
    "Girl Love" to "/the-loai/girl-love",
    "Kissing" to "/the-loai/kissing",
    "Hệ Thống" to "/the-loai/he-thong",
    "Nam Sinh" to "/the-loai/nam-sinh",
    "X-Ray" to "/the-loai/x-ray",
    "Cổ Trang" to "/the-loai/co-trang",
    "Lolicon" to "/the-loai/lolicon",
    "Truyện Ngọt" to "/the-loai/truyen-ngot",
    "Đeo Kính" to "/the-loai/deo-kinh",
    "Kimono" to "/the-loai/kimono",
    "Dark Skin" to "/the-loai/dark-skin",
    "Cunnilingus" to "/the-loai/cunnilingus",
    "Girllove" to "/the-loai/girllove",
    "Bạn Bè Thành Người Yêu" to "/the-loai/ban-be-thanh-nguoi-yeu",
    "Nurse" to "/the-loai/nurse",
    "Art Book" to "/the-loai/art-book",
    "3P" to "/the-loai/3p",
    "Mối Quan Hệ Tình Cảm Phức Tạp" to "/the-loai/moi-quan-he-tinh-cam-phuc-tap",
    "Hentaicb" to "/the-loai/hentaicb",
    "Hentai Không Che" to "/the-loai/hentai-khong-che",
    "Lỗ Nhị" to "/the-loai/lo-nhi",
    "Ngược" to "/the-loai/nguoc",
    "Chiếm Hữu" to "/the-loai/chiem-huu",
    "Succubus" to "/the-loai/succubus",
    "Vét Máng" to "/the-loai/vet-mang",
    "Body Writting" to "/the-loai/body-writting",
    "Hentaiz" to "/the-loai/hentaiz",
    "Virgins" to "/the-loai/virgins",
    "Manhua" to "/the-loai/manhua",
    "Small Boobs" to "/the-loai/small-boobs",
    "19+" to "/the-loai/19",
    "Hentaivnx" to "/the-loai/hentaivnx",
    "Công Sở" to "/the-loai/cong-so",
    "Old Man" to "/the-loai/old-man",
    "Thủ Dâm" to "/the-loai/thu-dam",
    "Fendom" to "/the-loai/fendom",
    "Shotacon" to "/the-loai/shotacon",
    "Chị / Em" to "/the-loai/chi-em",
    "Funny" to "/the-loai/funny",
    "Hentaivl" to "/the-loai/hentaivl",
    "Body Modifications" to "/the-loai/body-modifications",
    "Exhibitionism" to "/the-loai/exhibitionism",
    "Huge Boobs" to "/the-loai/huge-boobs",
    "Maids" to "/the-loai/maids",
    "Blackmail" to "/the-loai/blackmail",
    "Mẹ Con" to "/the-loai/me-con",
    "Hentai Lxmanga" to "/the-loai/hentai-lxmanga",
    "Hài Romance" to "/the-loai/hai-romance",
    "Beach" to "/the-loai/beach",
    "Incomplete" to "/the-loai/incomplete",
    "Bondage" to "/the-loai/bondage",
    "Oral" to "/the-loai/oral",
    "Sport" to "/the-loai/sport",
    "Netori" to "/the-loai/netori",
    "Inseki" to "/the-loai/inseki",
    "Chikan" to "/the-loai/chikan",
    "Từ Bạn Thành Yêu" to "/the-loai/tu-ban-thanh-yeu",
    "Bạn Thời Thơ Ấu" to "/the-loai/ban-thoi-tho-au",
    "Pantyhose" to "/the-loai/pantyhose",
    "Breastjobs" to "/the-loai/breastjobs",
    "Dirty Talk" to "/the-loai/dirty-talk",
    "Mối Tình Tay Ba" to "/the-loai/moi-tinh-tay-ba",
    "Twintails" to "/the-loai/twintails",
    "Rphang" to "/the-loai/rphang",
    "Nam Hối Hận" to "/the-loai/nam-hoi-han",
    "Hentaihvn" to "/the-loai/hentaihvn",
    "Hấp Diêm" to "/the-loai/hap-diem",
    "Rimjob" to "/the-loai/rimjob",
    "3D Hentai" to "/the-loai/3d-hentai",
    "Body Modification" to "/the-loai/body-modification",
    "Humiliation" to "/the-loai/humiliation",
    "Hairy" to "/the-loai/hairy",
    "Truyện Tranh 16+" to "/the-loai/truyen-tranh-16",
    "Bị Thuốc" to "/the-loai/bi-thuoc",
    "Bách Hợp" to "/the-loai/bach-hop",
    "Dickgirl" to "/the-loai/dickgirl",
    "Kinh Dị" to "/the-loai/kinh-di",
    "Swinging" to "/the-loai/swinging",
    "Tài Phiệt" to "/the-loai/tai-phiet",
    "Tentacle" to "/the-loai/tentacle",
    "Artist Cg" to "/the-loai/artist-cg",
    "Mối Tình Đầu" to "/the-loai/moi-tinh-dau",
    "Huge Ass" to "/the-loai/huge-ass",
    "Net Truyen Hentai" to "/the-loai/net-truyen-hentai",
    "Demongirl" to "/the-loai/demongirl",
    "Tình Yêu Công Sở" to "/the-loai/tinh-yeu-cong-so",
    "No Sex" to "/the-loai/no-sex",
    "Sweating" to "/the-loai/sweating",
    "Niên Hạ" to "/the-loai/nien-ha",
    "Mimihentai" to "/the-loai/mimihentai",
    "Ihentai" to "/the-loai/ihentai",
    "Ngoài Trời/Công Cộng" to "/the-loai/ngoai-troi-cong-cong",
    "Twins" to "/the-loai/twins",
    "Dirty" to "/the-loai/dirty",
    "Tổng Tài" to "/the-loai/tong-tai",
    "Art" to "/the-loai/art",
    "Raw" to "/the-loai/raw",
    "Tsundere" to "/the-loai/tsundere",
    "Brother" to "/the-loai/brother",
    "Sayhentai" to "/the-loai/sayhentai",
    "Sleeping" to "/the-loai/sleeping",
    "Phong Cách Phương Đông" to "/the-loai/phong-cach-phuong-dong",
    "Tì" to "/the-loai/ti",
    "Romanc" to "/the-loai/romanc",
    "Huyền Huyễn" to "/the-loai/huyen-huyen",
    "Based Game" to "/the-loai/based-game",
    "Catgirls" to "/the-loai/catgirls",
    "Magic" to "/the-loai/magic",
    "Tall Girl" to "/the-loai/tall-girl",
    "Không Ntr" to "/the-loai/khong-ntr",
    "Đã Full" to "/the-loai/da-full",
    "Cô / Dì" to "/the-loai/co-di",
    "Hàng Xóm" to "/the-loai/hang-xom",
    "Cô Gái Yêu Đơn Phương" to "/the-loai/co-gai-yeu-don-phuong",
    "Body Swap" to "/the-loai/body-swap",
    "Chàng Trai Mưu Mô" to "/the-loai/chang-trai-muu-mo",
    "Mối Quan Hệ Hợp Đồng" to "/the-loai/moi-quan-he-hop-dong",
    "Trả Thù" to "/the-loai/tra-thu",
    "Business Suit" to "/the-loai/business-suit",
    "Họ Hàng" to "/the-loai/ho-hang",
    "Hentaiayame" to "/the-loai/hentaiayame",
    "Family" to "/the-loai/family",
    "Tình Tay Ba" to "/the-loai/tinh-tay-ba",
    "Tomboy" to "/the-loai/tomboy",
    "Animal" to "/the-loai/animal",
    "Bestiality" to "/the-loai/bestiality",
    "Stocking" to "/the-loai/stocking",
    "Bối Cảnh Phương Tây" to "/the-loai/boi-canh-phuong-tay",
    "Hoàng Gia" to "/the-loai/hoang-gia",
    "Hồng Hài Nhi" to "/the-loai/hong-hai-nhi",
    "Say Xỉn" to "/the-loai/say-xin",
    "Tình Yêu Hợp Đồng" to "/the-loai/tinh-yeu-hop-dong",
    "Devilgirl" to "/the-loai/devilgirl",
    "Monstergirl" to "/the-loai/monstergirl",
    "Garter Belts" to "/the-loai/garter-belts",
    "Thú Nhân" to "/the-loai/thu-nhan",
    "Ngọt" to "/the-loai/ngot",
    "Joseon" to "/the-loai/joseon",
    "Osananajimi" to "/the-loai/osananajimi",
    "Ponytail" to "/the-loai/ponytail",
    "Truy" to "/the-loai/truy",
    "Chinese Dress" to "/the-loai/chinese-dress",
    "Demon" to "/the-loai/demon",
    "Cô Gái Ngây Thơ" to "/the-loai/co-gai-ngay-tho",
    "Orgasm Denial" to "/the-loai/orgasm-denial",
    "Đô Thị" to "/the-loai/do-thi",
    "Nặng Đô" to "/the-loai/nang-do",
    "Sister" to "/the-loai/sister",
    "Sếch Tàn Bạo" to "/the-loai/sech-tan-bao",
    "Ám Ảnh" to "/the-loai/am-anh",
    "Harem Ngược" to "/the-loai/harem-nguoc",
    "Khoa Học Viễn Tưởng" to "/the-loai/khoa-hoc-vien-tuong",
    "Người Nổi Tiếng" to "/the-loai/nguoi-noi-tieng",
    "Imouto" to "/the-loai/imouto",
    "Kuudere" to "/the-loai/kuudere",
    "Black Skin" to "/the-loai/black-skin",
    "Siscon" to "/the-loai/siscon",
    "21+" to "/the-loai/21",
    "Hôn Nhân Hợp Đồng" to "/the-loai/hon-nhan-hop-dong",
    "Thanh Xuân Vườn Trường" to "/the-loai/thanh-xuan-vuon-truong",
    "Gyaru" to "/the-loai/gyaru",
    "Giả Tưởng" to "/the-loai/gia-tuong",
    "Drug" to "/the-loai/drug",
    "Romanceg" to "/the-loai/romanceg",
    "Tam Giác Tình Yêu" to "/the-loai/tam-giac-tinh-yeu",
    "Demon Girl" to "/the-loai/demon-girl",
    "Hardcode" to "/the-loai/hardcode",
    "Truyện Dà" to "/the-loai/truyen-da",
    "Cứu Rỗi Lẫn Nhau" to "/the-loai/cuu-roi-lan-nhau",
    "Anh Chàng Mưu Mô/ Ranh Mãnh" to "/the-loai/anh-chang-muu-mo-ranh-manh",
    "Anh Chàng Nhỏ Tuổi" to "/the-loai/anh-chang-nho-tuoi",
    "Cô Nàng Từng Bị Tổn Thương" to "/the-loai/co-nang-tung-bi-ton-thuong",
    "Lxnovel" to "/the-loai/lxnovel",
    "Cứu Rỗi" to "/the-loai/cuu-roi",
    "Đồ Chơi Tình Dục" to "/the-loai/do-choi-tinh-duc",
    "Văn Phòng" to "/the-loai/van-phong",
    "V" to "/the-loai/v",
    "Góa Phụ" to "/the-loai/goa-phu",
    "Bbw" to "/the-loai/bbw",
    "Exhibitionist" to "/the-loai/exhibitionist",
    "Cặp Đôi Thanh Mai Trúc Mã" to "/the-loai/cap-doi-thanh-mai-truc-ma",
    "Truyện" to "/the-loai/truyen",
    "Cô Gái Từng Bị Tổn Thương" to "/the-loai/co-gai-tung-bi-ton-thuong",
    "Ghen Tuông" to "/the-loai/ghen-tuong",
    "Truy Thê" to "/the-loai/truy-the",
    "Người Đàn Ông Ám Ảnh" to "/the-loai/nguoi-dan-ong-am-anh",
    "Người Đàn Ông Nhỏ Tuổi" to "/the-loai/nguoi-dan-ong-nho-tuoi",
    "Người Phụ Nữ Lớn Tuổi" to "/the-loai/nguoi-phu-nu-lon-tuoi",
    "Vợ Của Sư Phụ" to "/the-loai/vo-cua-su-phu",
    "Tình C" to "/the-loai/tinh-c",
    "Chị Gái Hơn Tuổi X Em Trai Kém Tuổi" to "/the-loai/chi-gai-hon-tuoi-x-em-trai-kem-tuoi",
    "Sự Nhỉ Nhục" to "/the-loai/su-nhi-nhuc",
    "Cáo Già X Thỏ Con" to "/the-loai/cao-gia-x-tho-con",
    "Yandere" to "/the-loai/yandere",
    "Chàng Trai Cáu Kỉnh" to "/the-loai/chang-trai-cau-kinh",
    "Cô Nàng Thẳng Thắn" to "/the-loai/co-nang-thang-than",
    "Huyền Bí" to "/the-loai/huyen-bi",
    "Ma Cà Rồng" to "/the-loai/ma-ca-rong",
    "Truyện Tranh 1" to "/the-loai/truyen-tranh-1",
    "Năng Lực Siêu Nhiên" to "/the-loai/nang-luc-sieu-nhien",
    "Trường Học" to "/the-loai/truong-hoc",
    "Truyện M" to "/the-loai/truyen-m",
    "Khổ Dâm" to "/the-loai/kho-dam",
    "Bloomers" to "/the-loai/bloomers",
    "Cousin" to "/the-loai/cousin",
    "Father" to "/the-loai/father",
    "Ngoài Trời" to "/the-loai/ngoai-troi",
    "Yêu Hận Đan Xen" to "/the-loai/yeu-han-dan-xen",
    "Idol" to "/the-loai/idol",
    "Truyện Việt" to "/the-loai/truyen-viet",
    "Time Stop" to "/the-loai/time-stop",
    "Elder Sister" to "/the-loai/elder-sister",
    "Brocon" to "/the-loai/brocon",
    "Tracksuit" to "/the-loai/tracksuit",
    "Color" to "/the-loai/color",
    "Sex Bạo" to "/the-loai/sex-bao",
    "Game" to "/the-loai/game",
    "Siêu Nhiên" to "/the-loai/sieu-nhien",
    "Mối Quan Hệ Bí Mật" to "/the-loai/moi-quan-he-bi-mat",
    "Nữ Cường" to "/the-loai/nu-cuong",
    "Giới Giải Trí" to "/the-loai/gioi-giai-tri",
    "Tentacles" to "/the-loai/tentacles",
    "Ranh Mãnh" to "/the-loai/ranh-manh",
    "Nữ Giả Nam" to "/the-loai/nu-gia-nam",
    "Sixty-Nine" to "/the-loai/sixty-nine",
    "Robot" to "/the-loai/robot",
    "Tù Nhân" to "/the-loai/tu-nhan",
    "Quản Giáo" to "/the-loai/quan-giao",
    "Mori Sinrisk" to "/the-loai/mori-sinrisk",
    "Trọng Sinh" to "/the-loai/trong-sinh",
    "Khoảng Cách Tuổi Tác" to "/the-loai/khoang-cach-tuoi-tac",
    "Deepthroat" to "/the-loai/deepthroat",
    "Small Penis" to "/the-loai/small-penis",
    "Short Hentai" to "/the-loai/short-hentai",
    "Transformation" to "/the-loai/transformation",
    "Ryona" to "/the-loai/ryona",
    "Mất Trí Nhớ" to "/the-loai/mat-tri-nho",
    "Ảo Tưởng" to "/the-loai/ao-tuong",
    "Truyenvn" to "/the-loai/truyenvn",
    "Thế Giới Abo" to "/the-loai/the-gioi-abo",
    "Che Nhiều" to "/the-loai/che-nhieu",
    "Guideverse" to "/the-loai/guideverse",
    "Bí Ẩn" to "/the-loai/bi-an",
    "Bi Kịch" to "/the-loai/bi-kich",
    "Devil" to "/the-loai/devil",
    "Chênh Lệch Thân Phận" to "/the-loai/chenh-lech-than-phan",
    "Chữa Lành" to "/the-loai/chua-lanh",
    "Giật Gân" to "/the-loai/giat-gan",
    "Hiểu Lầm" to "/the-loai/hieu-lam",
    "Phản Bội" to "/the-loai/phan-boi",
    "Tình Yêu Bị Cấm Đoán" to "/the-loai/tinh-yeu-bi-cam-doan",
    "Chàng Trai Yêu Đơn Phương" to "/the-loai/chang-trai-yeu-don-phuong",
    "Oan Gia" to "/the-loai/oan-gia",
    "Nữ Đơn Phương" to "/the-loai/nu-don-phuong",
    "Truyện T" to "/the-loai/truyen-t",
    "T" to "/the-loai/t",
    "Miko" to "/the-loai/miko",
    "Ma Giới" to "/the-loai/ma-gioi",
    "Bodysuit" to "/the-loai/bodysuit",
    "Xã Hội Đen" to "/the-loai/xa-hoi-den",
    "Romcom" to "/the-loai/romcom",
    "Cặp Đôi Chênh Lệch Tuổi Tác" to "/the-loai/cap-doi-chenh-lech-tuoi-tac",
    "Quan Hệ Hôn Nhân Hợp Đồng" to "/the-loai/quan-he-hon-nhan-hop-dong",
    "Mizugi" to "/the-loai/mizugi",
    "Bạn Tình" to "/the-loai/ban-tinh",
    "Vườn Trường" to "/the-loai/vuon-truong",
    "Gothic Lolita" to "/the-loai/gothic-lolita",
)
