package eu.kanade.tachiyomi.extension.vi.hentaivnx

import eu.kanade.tachiyomi.source.model.Filter

class GenreFilter(genres: List<Pair<String, String>>) : Filter.Select<String>(
    "Thể loại",
    genres.map { it.first }.toTypedArray(),
)

fun getGenreList(): List<Pair<String, String>> = listOf(
    Pair("Tất cả", ""),
    Pair("Adult", "adult"),
    Pair("Ahegao", "ahegao"),
    Pair("Anal", "anal"),
    Pair("Big Ass", "big-ass"),
    Pair("Big Boobs", "big-boobs"),
    Pair("Big Breasts", "big-breasts"),
    Pair("Big Penis", "big-penis"),
    Pair("Blowjob", "blowjob"),
    Pair("Blowjobs", "blowjobs"),
    Pair("Cheating", "cheating"),
    Pair("Chơi Hai Lỗ", "choi-hai-lo"),
    Pair("Có Che", "co-che"),
    Pair("Condom", "condom"),
    Pair("Cosplay", "cosplay"),
    Pair("Doujinshi", "doujinshi"),
    Pair("Drama", "drama"),
    Pair("Ecchi", "ecchi"),
    Pair("Elf", "elf"),
    Pair("Fantasy", "fantasy"),
    Pair("Femdom", "femdom"),
    Pair("Fingering", "fingering"),
    Pair("Full Color", "full-color"),
    Pair("Gangbang", "gangbang"),
    Pair("Glasses", "glasses"),
    Pair("Group", "group"),
    Pair("Hãm Hiếp", "ham-hiep"),
    Pair("Handjob", "handjob"),
    Pair("Harem", "harem"),
    Pair("Hậu Môn", "hau-mon"),
    Pair("Housewife", "housewife"),
    Pair("Huge Ass", "huge-ass"),
    Pair("Huge Boobs", "huge-boobs"),
    Pair("Huge Dick", "huge-dick"),
    Pair("Incest", "incest"),
    Pair("Không Che", "khong-che"),
    Pair("Loạn Luân", "loan-luan"),
    Pair("Loli", "loli"),
    Pair("Manga", "manga"),
    Pair("Manhwa", "manhwa"),
    Pair("Masturbation", "masturbation"),
    Pair("Milf", "milf"),
    Pair("Mind Break", "mind-break"),
    Pair("Mind Control", "mind-control"),
    Pair("Mother", "mother"),
    Pair("Nakadashi", "nakadashi"),
    Pair("Ngực Lớn", "nguc-lon"),
    Pair("Ngực Nhỏ", "nguc-nho"),
    Pair("Ntr", "ntr"),
    Pair("Nữ Sinh", "nu-sinh"),
    Pair("Oneshot", "oneshot"),
    Pair("Paizuri", "paizuri"),
    Pair("Rape", "rape"),
    Pair("Romance", "romance"),
    Pair("School Uniform", "school-uniform"),
    Pair("Schoolgirl", "schoolgirl"),
    Pair("Schoolgirl Outfit", "schoolgirl-outfit"),
    Pair("Series", "series"),
    Pair("Sex Toys", "sex-toys"),
    Pair("Shota", "shota"),
    Pair("Small Breasts", "small-breasts"),
    Pair("Smut", "smut"),
    Pair("Stocking", "stocking"),
    Pair("Stockings", "stockings"),
    Pair("Truyện Không Che", "truyen-khong-che"),
    Pair("Truyện Màu", "truyen-mau"),
    Pair("Truyện Ngắn", "truyen-ngan"),
    Pair("Uncensored", "uncensored"),
    Pair("Vanilla", "vanilla"),
    Pair("Vếu To", "veu-to"),
    Pair("Virgin", "virgin"),
    Pair("X-ray", "x-ray"),
    Pair("Yuri", "yuri"),
)
