name: PR check

on:
  pull_request:
    paths:
      - '**'
      - '!**.md'
      - '!.github/**'
      - '.github/workflows/build_pull_request.yml'

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

env:
  CI_CHUNK_SIZE: 80
  IS_PR_CHECK: true

jobs:
  prepare:
    name: Prepare job
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      matrix: ${{ steps.generate-matrices.outputs.matrix }}
      lint_modules: ${{ steps.generate-matrices.outputs.lint_modules }}
      delete: ${{ steps.generate-matrices.outputs.delete }}
    steps:
      - name: Checkout PR
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Audit package names
        run: |
          python ./.github/scripts/audit-packages.py

      - id: generate-matrices
        name: Generate build matrices
        run: |
          python ./.github/scripts/generate-build-matrices.py origin/main

  build:
    name: Build extensions (${{ matrix.chunk.number }})
    needs: prepare
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: ${{ toJson(fromJson(needs.prepare.outputs.matrix).chunk) != '[]' }}
    strategy:
      matrix: ${{ fromJSON(needs.prepare.outputs.matrix) }}
    steps:
      - name: Checkout PR
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up Java
        uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
        with:
          java-version: 17
          distribution: temurin

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0
        with:
          cache-read-only: true

      - name: Build extensions (${{ matrix.chunk.number }})
        env:
          MODULES: ${{ join(matrix.chunk.modules, ' ') }}
        run: |
          TASKS=()
          for module in $MODULES; do
            TASKS+=("${module}:assembleRelease" "${module}:lintRelease")
          done
          ./gradlew "${TASKS[@]}"

      - name: Upload APKs (${{ matrix.chunk.number }})
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: "github.repository == 'keiyoushi/extensions-source'"
        with:
          name: "individual-apks-${{ matrix.chunk.number }}"
          path: |
            **/build/outputs/apk/release/*.apk
            **/build/outputs/jar/release/*.jar
          retention-days: 1

  lint-shared:
    name: Lint shared modules
    needs: prepare
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: ${{ needs.prepare.outputs.lint_modules != '[]' }}
    steps:
      - name: Checkout PR
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up Java
        uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
        with:
          java-version: 17
          distribution: temurin

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0
        with:
          cache-read-only: true

      - name: Lint shared modules
        env:
          MODULES: ${{ join(fromJSON(needs.prepare.outputs.lint_modules), ' ') }}
        run: |
          TASKS=()
          for module in $MODULES; do
            TASKS+=("${module}:lintRelease")
          done
          ./gradlew "${TASKS[@]}"
