name: My Private MangaPro Build

on:
  push:
    branches:
      - main

jobs:
  single_build:
    name: Build My APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'microsoft'

    - name: Setup Android SDK and Accept ALL Licenses
      run: |
        # إنشاء مجلد الـ SDK الخاص بنا
        mkdir -p ./android-sdk/licenses
        
        # استخدام أداة النظام الرسمية في السيرفر للموافقة التلقائية على كل تراخيص جوجل
        # ونقلها مباشرة إلى مجلد المشروع ليتعرف عليها Gradle
        if [ -d "$ANDROID_HOME/tools/bin" ]; then
          yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses
        elif [ -d "$ANDROID_HOME/cmdline-tools/latest/bin" ]; then
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
        fi
        
        # نسخ التراخيص المعتمدة إلى مجلدنا
        cp -r $ANDROID_HOME/licenses/* ./android-sdk/licenses/ || true
        echo "sdk.dir=./android-sdk" > local.properties

    - name: Build APK Only
      run: ./gradlew :src:ar:mangapro:assembleDebug -x spotlessKotlinCheck -x spotlessCheck

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: ProChan-MangaPro-APK
        path: src/ar/mangapro/build/outputs/apk/debug/*.apk
